#!/usr/bin/env bash
name='libsoup3'
release='2'
version='3.4.2'
url='https://gitlab.gnome.org/GNOME/libsoup.git/'
description='HTTP client/server library for GNOME '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/libsoup/-/archive/$version/libsoup-$version.tar.gz")
depends=(smartypants glib-networking)
makedepends=()
md5sums=('d927a69038058f2010c49c12a31c8f1f')
group=(net.libs)
uses=()
arch=('x86_64')

cd libsoup-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dsysprof=disabled
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

