#!/usr/bin/env bash
name='py3-jinja'
release='2'
version='3.1.4'
url='https://github.com/pallets/jinja'
description='A very fast and expressive template engine.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/pallets/jinja/archive/refs/tags/$version.tar.gz")
depends=(python)
makedepends=(py3-markupsafe)
sha256sums=('ed06f67abd2c8b7697dfb714f80715903ab0507e3c5acc11e92477e4ea51033b')
group=(dev.python)
uses=()
arch=('x86_64')

cd jinja-$version

build(){
    python3 -m build --wheel --no-isolation
}

package(){
    python3 -m installer -d "$DESTDIR" dist/*.whl
}

