#!/usr/bin/env bash
name='weston'
release='4'
version='14.0.2'
url='https://gitlab.freedesktop.org/wayland/weston'
description='A lightweight and functional Wayland compositor'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wayland/weston/-/archive/$version/weston-$version.tar.gz")
depends=(pixman libdrm libxkbcommon libinput pango libjpeg-turbo lcms2 seatd pipewire xorg-xwayland xcb-util-cursor)
makedepends=()
sha256sums=('633f4e0f232ad150300c95ffcbc646fedf1349487bf389dbd2045fa69013d6e2')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dsystemd=false \
        -Dbackend-rdp=false \
        -Dbackend-vnc=false \
        -Dremoting=false
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

