#!/usr/bin/env bash
name='weston'
release='3'
version='13.0.0'
url='https://gitlab.freedesktop.org/wayland/weston'
description='A lightweight and functional Wayland compositor'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wayland/weston/-/archive/$version/weston-$version.tar.gz")
depends=(pixman libdrm libxkbcommon libinput pango libjpeg-turbo lcms2 seatd)
makedepends=()
md5sums=('f5d8614664a26211621910d310b42890')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dimage-webp=false \
        -Dbackend-rdp=false \
        -Dbackend-vnc=false \
        -Dxwayland=false \
        -Dsystemd=false \
        -Dremoting=false \
        -Dpipewire=false
}

build(){
    ninja -C build
}
 
package(){
    ninja -C build install
}

