#!/usr/bin/env bash
name='kcrash'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Support for application crash analysis and bug report from apps'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcrash-${version}.tar.xz")
depends=(qt6-base kcoreaddons)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('a66293821b151f575fcfb59848578749e248c5baa2f262ac86725d0f64b324e0')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

