#!/usr/bin/env bash
name='kcrash'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Support for application crash analysis and bug report from apps'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcrash-${version}.tar.xz")
depends=(qt6-base kcoreaddons)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('f56f1ed44e494417b7046e4f94791ad4ddd07c6cb8f0f704f2053717a44296f9')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

