#!/usr/bin/env bash
name='breeze-gtk'
release='3'
version='6.1.5'
url='https://kde.org/plasma-desktop'
description='Artwork, styles and assets for the Breeze visual style for the Plasma Desktop'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/breeze-gtk-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules sassc py3-cairo breeze)
sha256sums=('960c3df047423e85e1f33bdb60b71bdc7486b9941d89d785310debe501bd46d1')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
