#!/usr/bin/env bash
name='khtml'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='The KDE HTML library, ancestor of WebKit'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/portingAids/khtml-${version}.tar.xz")
depends=(giflib kparts kjs)
makedepends=(extra-cmake-modules gperf)
md5sums=('33c96cb6f85043dbde58c33ffa1c6767')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
