#!/usr/bin/env bash
name='fish'
release='2'
version='3.7.0'
url='https://fishshell.com/'
description='Smart and user friendly shell intended mostly for interactive use'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://github.com/fish-shell/fish-shell/releases/download/${version}/fish-${version}.tar.xz")
depends=(ncurses libpcre2 gettext)
makedepends=(cmake python)
md5sums=('22c3fab479b185faf620a3b3f43443c3')
group=(app.shell)
uses=()
arch=('x86_64')

cd $name-$version

#export CXXFLAGS+=" ${CPPFLAGS}" 

setup(){
    cmake -B build -G Ninja\
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc \
        -DFISH_USE_SYSTEM_PCRE2=true \
        -DBUILD_DOCS=false
}

build(){
    cmake --build build --target all fish_tests
}

package(){
    DESTDIR="$DESTDIR" cmake --install build
    rm -fr "$DESTDIR"/usr/share/$name/groff

	mkdir -p "$DESTDIR"/usr/lib
	mv "$DESTDIR"/usr/share/pkgconfig "$DESTDIR"/usr/lib

}

