#!/usr/bin/env bash
name='gvfs'
release='2'
version='1.52.0'
url='https://wiki.gnome.org/Projects/gvfs'
description='Virtual filesystem implementation for GIO'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://gitlab.gnome.org/GNOME/gvfs/-/archive/${version}/gvfs-${version}.tar.gz")
depends=(udisks2 libcdio-paranoia)
makedepends=()
md5sums=('5a3b313b2cf6838c8765a55008b7cc55')
group=(gnome.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
		--buildtype=release \
		-Dfuse=false        \
		-Dgphoto2=false     \
		-Dafc=false         \
		-Dbluray=false      \
		-Dnfs=false         \
		-Dmtp=false         \
		-Dsmb=false         \
		-Dtmpfilesdir=no    \
		-Ddnssd=false       \
		-Dgoa=false         \
		-Dgoogle=false      \
		-Dsystemduserunitdir=no
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

