#!/usr/bin/env bash
name='gvfs'
release='1'
version='1.50.4'
url='https://gitlab.gnome.org/GNOME/gvfs'
description='Gnome Virtual FileSystem'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gvfs/-/archive/$version/gvfs-$version.tar.gz")
depends=(gcr polkit libsoup3 libgphoto2 libmtp libnfs udisks2 fuse)
makedepends=()
md5sums=('9318356ad05f95eee0bc658b137aeb8c')
group=(gnome.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        -Dudisks2=true \
        -Ddnssd=false \
        -Dafc=false \
        -Dgoa=false \
        -Dbluray=false \
        -Dsmb=false \
        -Dcdda=false \
        -Dgoogle=false \
        -Dsystemduserunitdir=no \
        -Dtmpfilesdir=no \
        -Dlogind=false
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

