#!/usr/bin/env bash
name='lcms2'
release='1'
version='14'
url='https://github.com/mm2/Little-CMS'
description='A lightweight, speed optimized color management engine '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/mm2/Little-CMS/archive/refs/tags/lcms2.$version.tar.gz")
depends=()
makedepends=()
md5sums=('7982e4dc874c29bbfef0b7de6783006b')
group=(media.libs)
uses=()
arch=('x86_64')

cd Little-CMS-$name.$version

setup(){
	meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

