#!/usr/bin/env bash
name='sqlite'
release='2'
version='3.42.0'
url='https://www.sqlite.org/download.html'
description='A C library that implements an SQL database engine'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
srcver='3420000'
			  #https://www.sqlite.org/2023/sqlite-autoconf-3420000.tar.gz
source=("https://www.sqlite.org/2023/sqlite-autoconf-$srcver.tar.gz")
depends=(zlib readline)
makedepends=( )
md5sums=('0c5a92bc51cf07cae45b4a1e94653dea')
uses=()
group=(dev.db)
arch=('x86_64')

cd $name-autoconf-$srcver

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --enable-fts3 \
        --enable-fts4 \
        --enable-fts5 \
        --enable-rtree \
        CPPFLAGS="-DSQLITE_ENABLE_FTS3=1            \
                  -DSQLITE_ENABLE_FTS4=1            \
                  -DSQLITE_ENABLE_COLUMN_METADATA=1 \
                  -DSQLITE_ENABLE_UNLOCK_NOTIFY=1   \
                  -DSQLITE_ENABLE_DBSTAT_VTAB=1     \
                  -DSQLITE_SECURE_DELETE=1          \
                  -DSQLITE_ENABLE_FTS3_TOKENIZER=1"
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

