#!/usr/bin/env bash
name='ell'
release='5'
version='0.62'
url='https://01.org/ell'
description='Embedded Linux library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2.1')
source=(https://mirrors.edge.kernel.org/pub/linux/libs/$name/$name-$version.tar.{xz,sign})
depends=()
makedepends=()
md5sums=('720eac90e32a6008ec5408f7930a0415' 'SKIP')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install DESTDIR="$DESTDIR" $jobs
}

