#!/usr/bin/env bash
name='ell'
release='2'
version='0.57'
url='https://01.org/ell'
description='Embedded Linux library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2.1')
source=(https://mirrors.edge.kernel.org/pub/linux/libs/$name/$name-$version.tar.{xz,sign})
depends=()
makedepends=()
md5sums=('7ec5975ae506431b2bec40371931dd31' '44177e69a7044febaadbe545b2e0947b')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install DESTDIR="$DESTDIR" $jobs
}

