#!/usr/bin/env bash
name='hicolor-icon-theme'
release='2'
version='0.17'
url='https://www.freedesktop.org/wiki/Software/icon-theme/'
description='Freedesktop.org Hicolor icon theme'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("http://icon-theme.freedesktop.org/releases/hicolor-icon-theme-$version.tar.xz")
depends=()
makedepends=()
sha256sums=('317484352271d18cbbcfac3868eab798d67fff1b8402e740baa6ff41d588a9d8')
group=(x11.themes)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

