#!/usr/bin/env bash
name='hicolor-icon-theme'
release='1'
version='0.17'
url='https://www.freedesktop.org/wiki/Software/icon-theme/'
description='Freedesktop.org Hicolor icon theme'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("http://icon-theme.freedesktop.org/releases/hicolor-icon-theme-$version.tar.xz")
depends=()
makedepends=()
md5sums=('84eec8d6f810240a069c731f1870b474')
group=(x11.themes)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

