#!/usr/bin/env bash
name='cmake'
release='7'
version='3.31.4'
url='https://github.com/Kitware/CMake'
description='A cross-platform open-source make system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/Kitware/CMake/releases/download/v$version/cmake-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('a6130bfe75f5ba5c73e672e34359f7c0a1931521957e8393a5c2922c8b0f7f25')
uses=()
uses_extra=(qt)
group=(dev.util)
arch=('x86_64')

cd $name-$version

setup(){
    ./bootstrap --prefix=/usr \
        --no-system-libs \
        $(use_opt qt --qt-gui --no-qt-gui) \
        --parallel=`nproc`
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

