#!/usr/bin/env bash
name='cmake'
release='2'
version='3.27.7'
url='https://example.org'
description='A cross-platform open-source make system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/Kitware/CMake/releases/download/v$version/cmake-$version.tar.gz")
depends=()
makedepends=( )
md5sums=('0f11cf15c7f2fa6234b9fc415c78029c')
uses=()
uses_extra=(qt)
group=(dev.util)
arch=('x86_64')

cd $name-$version

setup(){
    ./bootstrap --prefix=/usr \
        --no-system-libs \
        $(use_opt qt --qt-gui --no-qt-gui) \
        --parallel=`nproc`
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

