#!/usr/bin/env bash
name='xfce4-pulseaudio-plugin'
release='4'
version='0.5.1'
url='https://goodies.xfce.org/projects/panel-plugins/xfce4-pulseaudio-plugin'
description='Pulseaudio plugin for the Xfce4 panel'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/panel-plugins/xfce4-pulseaudio-plugin/${version%.*}/xfce4-pulseaudio-plugin-${version}.tar.xz")
depends=(xfce4-panel libpulse libkeybinder3 libnotify libcanberra)
makedepends=(intltool)
sha256sums=('8e1f3a505f37aa3bc2816a58bec5f9555366f1c476f10eab59fd0e6581d08c47')
group=(xfce.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sysconfdir=/etc \
        --localstatedir=/var
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
