#!/usr/bin/env bash
name='lxappearance'
release='1'
version='0.6.3'
url='Feature-rich GTK+ theme switcher of the LXDE Desktop'
description='Feature-rich GTK+ theme switcher of the LXDE Desktop'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL2')
source=("https://downloads.sourceforge.net/lxde/$name-$version.tar.xz")
depends=(gtk3) #dbus-glib
makedepends=(intltool)
md5sums=('f10345313e2c12bad51c1b58bd46b454')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr --enable-gtk3 \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

