#!/usr/bin/env bash
name='pango'
release='2'
version='1.51.0'
url='https://metacpan.org/pod/Pango'
description='Layout and render international text'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.gnome.org/sources/pango/1.51/pango-$version.tar.xz")
depends=(fribidi libthai harfbuzz cairo libXft)
makedepends=(gobject-introspection)
md5sums=('d5968724bee6ff1e327fdf0b491d9719')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version


setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dintrospection=enabled \
        -Dxft=enabled \
        -Dcairo=enabled \
        -Dlibthai=enabled \
        -Dfreetype=enabled \
        -Dgtk_doc=false
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

