#!/usr/bin/env bash
name='pango'
release='1'
version='1.50.12'
url='https://metacpan.org/pod/Pango'
description='Layout and render international text'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.gnome.org/sources/pango/1.50/pango-$version.tar.xz")
depends=(fribidi libthai harfbuzz cairo)
makedepends=()
md5sums=('fd4b0b23915d6a0255317f811bea4215')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version


setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -D gtk_doc=false
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

