#!/usr/bin/env bash
name='systemsettings'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description='KDE system manager for hardware, software, and workspaces'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/systemsettings-$version.tar.xz")
depends=(plasma-workspace)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('561f9013ba07071c0add777858ec85d40a8dddfcc83a10f5f04b2ce1016666bc')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
    # fix symlink
    rm -f $DESTDIR/usr/share/kglobalaccel/systemsettings.desktop
    ln -s ../applications/systemsettings.desktop $DESTDIR/usr/share/kglobalaccel/systemsettings.desktop
    # link kinfocenter
    ln -s systemsettings $DESTDIR/usr/bin/kinfocenter
}

