#!/usr/bin/env bash
name='py3-docutils'
release='2'
version='0.21.2'
url='https://pypi.org/project/docutils'
description='Documentation Utilities for Python3'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=(BSD-2-Clause  GPL-3.0-or-later  Python-2.0)
source=("https://files.pythonhosted.org/packages/source/d/docutils/docutils-${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-flit py3-installer)
sha256sums=('3a6b18732edf182daa3cd12775bbb338cf5691468f91eeeb109deff6ebfa986f')
group=(dev.python)
uses=()
arch=('x86_64')

cd "docutils"-$version

build(){
    python3 -m build --wheel --skip-dependency-check --no-isolation
}

package(){
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
  mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}



