#!/usr/bin/env bash
name='py3-docutils'
release='1'
version='0.20.1'
url='https://pypi.org/project/docutils'
description='Documentation Utilities for Python3'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=(BSD-2-Clause  GPL-3.0-or-later  Python-2.0)
source=("https://files.pythonhosted.org/packages/source/d/docutils/docutils-${version}.tar.gz")
depends=(python)
makedepends=()
md5sums=('93bcfe0065cf1d0b6a0bcabeca7a2335')
group=(dev.python)
uses=()
arch=('x86_64')

cd "docutils"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}


