#!/usr/bin/env bash
name='py3-setuptools'
release='2'
version='67.8.0'
url='https://pypi.org/project/setuptools/'
description='Easily download, build, install, upgrade, and uninstall Python packages'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pypa/setuptools/archive/refs/tags/v${version}.tar.gz")
depends=(python)
makedepends=( )
md5sums=('4036ad7ba388ef0cf2b3a35dba79af62')
uses=()
group=(dev.python)
arch=('x86_64')

cd setuptools-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

