#!/usr/bin/env bash
name='py3-setuptools'
release='1'
version='65.6.3'
url='https://pypi.org/project/setuptools/'
description='Easily download, build, install, upgrade, and uninstall Python packages'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://files.pythonhosted.org/packages/b6/21/cb9a8d0b2c8597c83fce8e9c02884bce3d4951e41e807fc35791c6b23d9a/setuptools-$version.tar.gz")
depends=(python)
makedepends=( )
md5sums=('1fd8bd04b0bed95ad6c81f03b1c080bc')
uses=()
group=(dev.python)
arch=('x86_64')

cd setuptools-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

