#!/usr/bin/env bash
name='openssl'
release='2'
version='3.1.1'
url='https://www.openssl.org/source/'
description='Package description missing'
email=' aliriza.keskin@pardus.org.tr'
maintainer=' aliriza'
license=('GPLv3')
source=("https://www.openssl.org/source/openssl-$version.tar.gz"
        "https://curl.haxx.se/ca/cacert.pem"
        "update-certdata.sh")
depends=()
makedepends=(coreutils)
md5sums=('1864b75e31fb4a6e0a07fd832529add3'
         'SKIP'
         'SKIP')
arch=('x86_64')
group=(dev.libs)
uses=(legacy)
legacy_depends=(openssl-1.1)

cd $name-$version

# for pod2man
export PATH=$PATH:/usr/bin/core_perl

setup(){
    ./Configure --prefix=/usr \
        --openssldir=/etc/ssl \
        --libdir=lib64 \
        shared linux-x86_64
}

build(){
    make depend $jobs
    make $jobs
}

package(){
    mkdir -p "${DESTDIR}/etc/ssl/" "${DESTDIR}/sbin/"
    install ../update-certdata.sh "${DESTDIR}/sbin/update-certdata"
    install ../cacert.pem "${DESTDIR}/etc/ssl/cert.pem"
    make DESTDIR="${DESTDIR}" \
    install_sw \
    install_ssldirs \
    install_man_docs  $jobs
}

