#!/usr/bin/env bash
name='openssl'
release='3'
version='3.3.3'
url='https://www.openssl.org/source/'
description='The Open Source toolkit for Secure Sockets Layer and Transport Layer Security'
email='aliriza.keskin@pardus.org.tr'
maintainer=' aliriza'
license=('GPLv3')
source=("https://www.openssl.org/source/openssl-$version.tar.gz"
        "https://curl.haxx.se/ca/cacert.pem"
        "update-certdata.sh")
depends=()
makedepends=(coreutils)
sha256sums=('712590fd20aaa60ec75d778fe5b810d6b829ca7fb1e530577917a131f9105539'
         'SKIP'
         'SKIP')
arch=('x86_64')
group=(dev.libs)
uses_extra=(legacy)
legacy_depends=(openssl-1.1)

cd $name-$version

# for pod2man
export PATH=$PATH:/usr/bin/core_perl

setup(){
    ./Configure --prefix=/usr \
        --openssldir=/etc/ssl \
        --libdir=lib64 \
        shared linux-x86_64
}

build(){
    make depend $jobs
    make $jobs
}

package(){
    mkdir -p "${DESTDIR}/etc/ssl/" "${DESTDIR}/sbin/"
    install ../update-certdata.sh "${DESTDIR}/sbin/update-certdata"
    install ../cacert.pem "${DESTDIR}/etc/ssl/cert.pem"
    make DESTDIR="${DESTDIR}" \
    install_sw \
    install_ssldirs \
    install_man_docs  $jobs
}

