#!/usr/bin/env bash
name='papirus-icon-theme'
release='3'
version='20231101'
url='https://github.com/PapirusDevelopmentTeam/papirus-icon-theme'
description='papirus icon theme'
email='03teknoloji@gmail.com'
maintainer='mobilturka'
license=('GPLv3')
source=("https://github.com/PapirusDevelopmentTeam/$name/archive/$version/$name-$version.tar.gz")
depends=()
makedepends=()
md5sums=('2c42e8eb7477055ed09e6a700baa4a6f')
group=(x11.themes)
uses=()
arch=('x86_64')

package() {
  cd $name-$version
  make DESTDIR="$DESTDIR" install
}
