#!/usr/bin/env bash
name='papirus-icon-theme'
release='4'
version='20231201'
url='https://github.com/PapirusDevelopmentTeam/papirus-icon-theme'
description='papirus icon theme'
email='03teknoloji@gmail.com'
maintainer='mobilturka'
license=('GPLv3')
source=("https://github.com/PapirusDevelopmentTeam/$name/archive/$version/$name-$version.tar.gz")
depends=()
makedepends=()
md5sums=('5498bc168d422f274cf6232f0131d48f')
group=(x11.themes)
uses=()
arch=('x86_64')

package() {
  cd $name-$version
  make DESTDIR="$DESTDIR" install
}
