#!/usr/bin/env bash
name='vulkan-loader'
release='1'
version='1.3.239'
url='Vulkan Installable Client Driver (ICD) Loader'
description='Vulkan Installable Client Driver (ICD) Loader'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/tags/v$version.tar.gz")
depends=(vulkan-headers libXrandr libXrender libxcb libX11)
makedepends=()
md5sums=('dede7db932a44fa5633ad94d665a62cb')
group=(media.libs)
uses=()
arch=('x86_64')

cd Vulkan-Loader-$version

setup(){
    mkdir build && cd build
    cmake .. \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DVULKAN_HEADERS_INSTALL_DIR=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib64 \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc \
        -DCMAKE_INSTALL_DATADIR=/share \
        -DCMAKE_SKIP_RPATH=True \
        -DBUILD_TESTS=Off \
        -DBUILD_WSI_XCB_SUPPORT=On \
        -DBUILD_WSI_XLIB_SUPPORT=On \
        -DBUILD_WSI_WAYLAND_SUPPORT=On
}

build(){
    make $jobs -C build
}

package(){
    make -C build install $jobs
}

