#!/usr/bin/env bash
name='atk'
release='1'
version='2.38.0'
url='https://gitlab.gnome.org/GNOME/atk'
description='GTK+ & GNOME Accessibility Toolkit'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=('https://gitlab.gnome.org/GNOME/atk/-/archive/2.38.0/atk-2.38.0.tar.gz')
depends=(glib libffi libpcre2)
makedepends=()
md5sums=('252ffadcb89d5f05370e7564ec9fc1be')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -D introspection=false

}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

