#!/usr/bin/env bash
name='hwdata'
release='3'
version='0.387'
url='https://github.com/vcrhonek/hwdata'
description='Hardware identification and configuration data'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/vcrhonek/hwdata/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
sha256sums=('8c6be8f0863a8ff5c83b2c46aa525b503b30d42792ed57891c40849de543e1ee')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}



