#!/usr/bin/env bash
name='hwdata'
release='1'
version='0.366'
url='https://github.com/vcrhonek/hwdata'
description='Hardware identification and configuration data'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://github.com/vcrhonek/hwdata/archive/refs/tags/v0.366.tar.gz')
depends=()
makedepends=()
md5sums=('c80465b4b955177a3409f1f4d39d86ca')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

