#!/usr/bin/env bash
name='hwdata'
release='4'
version='0.394'
url='https://github.com/vcrhonek/hwdata'
description='Hardware identification and configuration data'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/vcrhonek/hwdata/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
sha256sums=('b7c3fd7214a3b7c49d2661db127a712dc11cffd1799f793947aa1cb20aaf3298')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    # configure is a custom script.
    # autoreconf not required.
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}



