#!/usr/bin/env bash
name='plasma-integration'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='Qt Platform Theme integration plugins for the Plasma workspaces'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-integration-${version}.tar.xz")
depends=(libXcursor kio perl)
makedepends=(extra-cmake-modules breeze plasma-wayland-protocols)
md5sums=('b4d2a1401be865fa9a3ba1cde1f7cfd1')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF \
		-DCMAKE_DISABLE_FIND_PACKAGE_FontNotoSans=true \
		-DCMAKE_DISABLE_FIND_PACKAGE_FontHack=true
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


