#!/usr/bin/env bash
name='plasma-integration'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='Qt Platform Theme integration plugins for the Plasma workspaces'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-integration-${version}.tar.xz")
depends=(kcolorscheme kcompletion kconfig kcoreaddons kguiaddons kiconthemes kstatusnotifieritem ki18n kio kwidgetsaddons kwindowsystem
         kxmlgui libxcb libXcursor qt6-base qt6-declarative qt6-wayland wayland)
makedepends=(extra-cmake-modules plasma-wayland-protocols)
sha256sums=('c3e271de1fa26c8833440b69ccac5e8c094a85e4742bf26f97bcb7caa8c17b2c')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QT5=OFF \
		-DBUILD_TESTING=OFF \
		-DCMAKE_DISABLE_FIND_PACKAGE_FontNotoSans=true \
		-DCMAKE_DISABLE_FIND_PACKAGE_FontHack=true
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


