#!/usr/bin/env bash
name='kgamma'
release='3'
version='6.1.5'
url='https://kde.org/plasma-desktop'
description="Adjust your monitor's gamma settings"
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kgamma-${version}.tar.xz")
depends=(kcmutils kconfig kcoreaddons ki18n libX11 libXxf86vm qt6-base)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('2f43ec6b4abac27249b101594f19f222fe7e5947054f5252c11a9d9ec20ab42c')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

