#!/usr/bin/env bash
name='kgamma'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description="Adjust your monitor's gamma settings"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kgamma5-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules kdoctools)
md5sums=('2445a1c0a3d84c2ee96de07492ddce89')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name"5"-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

