#!/usr/bin/env bash
name='autoconf'
release='1'
version='2.71'
url='https://www.gnu.org/software/autoconf/'
description='A GNU tool for automatically configuring source code'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.xz')
depends=( )
makedepends=( )
group=(sys.devel)
md5sums=('12cfa1687ffa2606337efe1a64416106')
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

