#!/usr/bin/env bash
name='autoconf'
release='2'
version='2.72'
url='https://www.gnu.org/software/autoconf/'
description='A GNU tool for automatically configuring source code'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/autoconf/autoconf-${version}.tar.xz")
depends=(perl m4)
makedepends=( )
group=(sys.devel)
md5sums=('1be79f7106ab6767f18391c5e22be701')
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

