#!/usr/bin/env bash
name='kinfocenter'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='A utility that provides information about a computer system'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kinfocenter-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules solid kio plasma-framework kdoctools)
md5sums=('ca83253ccce484f94a4c17a529ba0f82')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build

	rm -f $DESTDIR/usr/bin/kinfocenter
	ln -s ../systemsettings5 $DESTDIR/usr/bin/kinfocenter
}
#usr/bin/kinfocenter => /usr/bin/systemsettings5

 #rm -f $DESTDIR/usr/share/kglobalaccel/org.kde.dolphin.desktop
  #ln -s ../applications/org.kde.dolphin.desktop $DESTDIR/usr/share/kglobalaccel/org.kde.dolphin.desktop