#!/usr/bin/env bash
name='kinfocenter'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='A utility that provides information about a computer system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kinfocenter-${version}.tar.xz")
depends=(kauth kcmutils kconfig kcoreaddons kdeclarative ki18n kio kirigami kservice kwidgetsaddons libusb qt6-base
         qt6-declarative)
makedepends=(extra-cmake-modules solid kdoctools)
sha256sums=('508730f7b44dc85ba4e67caf526199528cefcf3dd603f6280917a930e0fe06cc')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
    # systemsettings5 file is not part of kinfocenter
    rm -f $DESTDIR/usr/bin/kinfocenter
}
