#!/usr/bin/env bash
name='kdbusaddons'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Addons to QtDBus'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdbusaddons-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('dce95cd146e18b400c4df31ea8c9bbba8f919e329a52dc1a19635184ac85e49a')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


