#!/usr/bin/env bash
name='kdbusaddons'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Addons to QtDBus'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdbusaddons-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('afacf9ff5d7a2dd294520718508d33eadf3f63a957091d30a68a45ab1ef0a8fe')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


