#!/usr/bin/env bash
name='kdbusaddons'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Addons to QtDBus'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdbusaddons-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('11e70d0c7239bd818962d91cdb94aeba94748055c77003a4f64ff14dab0ae989')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


