#!/usr/bin/env bash
name='qqc2-desktop-style'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='A style for Qt Quick Controls 2 to make it follow your desktop theme'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/qqc2-desktop-style-${version}.tar.xz")
depends=(kcolorscheme kconfig kirigami kiconthemes qt6-base qt6-declarative sonnet)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=('888638775a4c8bb7f80e10e878fd923880c75f2aa6e3878d52c12a77f3da9321')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}