#!/usr/bin/env bash
name='kpipewire'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description='Components relating to pipewire use in Plasma'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kpipewire-${version}.tar.xz")
depends=(ki18n kcoreaddons libdrm libva mesa pipewire libepoxy ffmpeg qt6-base qt6-declarative)
makedepends=(extra-cmake-modules plasma-wayland-protocols)
sha256sums=('dd585ee4de3b5bcdc10f36fe5df91966447ca716570d6b4ea15160db1f1d73bc')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

