#!/usr/bin/env bash
name='kde-gtk-config'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='GTK2 and GTK3 Configurator for KDE'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kde-gtk-config-${version}.tar.xz")
depends=(qt5-svg kdecoration kconfigwidgets kdbusaddons kwindowsystem)
makedepends=(extra-cmake-modules gtk3 sassc)
md5sums=('2f336708889452f4e841132e9a18258d')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
