#!/usr/bin/env bash
name='kde-gtk-config'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='GTK2 and GTK3 Configurator for KDE'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kde-gtk-config-${version}.tar.xz")
depends=(qt6-svg kdecoration kconfigwidgets kdbusaddons kwindowsystem)
makedepends=(extra-cmake-modules gtk3 sassc)
sha256sums=('9bb622aefea20aa933f85242c11c70758150a86f7961cf37527d14cd6d98f967')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
