#!/usr/bin/env bash
name='kde-gtk-config'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='GTK2 and GTK3 Configurator for KDE'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kde-gtk-config-${version}.tar.xz")
depends=(qt6-svg kdecoration kconfigwidgets kdbusaddons kwindowsystem)
makedepends=(extra-cmake-modules gtk3 sassc)
sha256sums=('f7a81c1efd539b608cc640a999fdb184bbb83cfc9600d407d1a4f332c3880ec2')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
