#!/usr/bin/env bash
name='udisks2'
release='2'
version='2.10.1'
url='https://github.com/storaged-project/udisks'
description='Disk Management Service, version 2'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/storaged-project/udisks/archive/refs/tags/udisks-$version.tar.gz"
        udisks.initd)
depends=(libblockdev libatasmart libgudev polkit)
makedepends=()
sha256sums=('a1c4232ce0f4d6a800269f8e8c6e93afb0e39aa7017383082943e400a0bc8e13'
         'SKIP')
group=(sys.fs)
uses=()
arch=('x86_64')

cd udisks-udisks-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --libdir=/usr/lib64/ \
        --with-systemdsystemunitdir=no \
        --enable-lvm2 \
        --enable-lvmcache \
        --enable-btrfs \
        --disable-zram
}

build(){
    make $jobs
}

package(){
    make install $jobs
    # openrc service
    mkdir -p $DESTDIR/etc/init.d
    install ../udisks.initd $DESTDIR/etc/init.d/udisks
}

