#!/usr/bin/env bash
name='breeze-plymouth'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='Breeze theme for Plymouth'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/breeze-plymouth-${version}.tar.xz")
depends=(plymouth)
makedepends=(extra-cmake-modules)
md5sums=('f1450b508f2390e3537c155e3f8cd53b')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

