#!/usr/bin/env bash
name='xf86-video-dummy'
release='1'
version='0.4.0'
url='https://gitlab.freedesktop.org/xorg/driver/xf86-video-dummy'
description='X.Org driver for dummy cards'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/driver/xf86-video-dummy/-/archive/xf86-video-dummy-$version/xf86-video-dummy-xf86-video-dummy-$version.tar.gz")
depends=()
makedepends=()
md5sums=('810d5794e08e5f225689510dc003f23d')
group=(x11.drivers)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install
}

