#!/usr/bin/env bash
name='libdisplay-info'
release='2'
version='0.3.0'
url='https://gitlab.freedesktop.org/emersion/libdisplay-info'
description='EDID and DisplayID library'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('MIT')
source=("https://gitlab.freedesktop.org/emersion/libdisplay-info/-/archive/${version}/libdisplay-info-${version}.tar.gz")
depends=()
makedepends=(hwdata meson ninja python)
sha256sums=('2b467e3336aec63819d6aca28d7310d3dc7415b2b3a3c3a5aec9d3727053c078')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
        -Ddefault_library=both
}

build () {
    ninja -C build
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install
}

