#!/usr/bin/env bash
name='fuse2'
release='1'
version='2.9.9'
url='https://github.com/libfuse/libfuse'
description='Filesystem in Userspace'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/libfuse/libfuse/releases/download/fuse-$version/fuse-$version.tar.gz")
depends=(fuse)
makedepends=()
md5sums=('8000410aadc9231fd48495f7642f3312')
group=(sys.fs)
uses=()
arch=('x86_64')

cd "fuse"-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --enable-static \
        --enable-shared \
        --disable-example \
        --enable-lib \
        --disable-util
}

build(){
    make $jobs
}

package(){
    make install $jobs
}
