#!/usr/bin/env bash
name='spirv-tools'
release='2'
version='1.3.261.1'
url='https://github.com/KhronosGroup/SPIRV-Tools'
description='Provides an API and commands for processing SPIR-V modules'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/sdk-$version.tar.gz")
depends=(spirv-headers gcc)
makedepends=()
md5sums=('461a76f8d68ef0749a0dacfb38a258c4')
group=(dev.util)
uses=()
arch=('x86_64')

cd SPIRV-Tools-sdk-$version

setup(){
    mkdir build && cd build
    cmake .. \
        -GNinja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib64 \
        -DCMAKE_BUILD_TYPE=None \
        -DSPIRV_WERROR=Off \
        -DBUILD_SHARED_LIBS=ON \
        -DSPIRV_TOOLS_BUILD_STATIC=OFF \
        -DSPIRV-Headers_SOURCE_DIR=/usr
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

