#!/usr/bin/env bash
name='spirv-tools'
release='3'
version='1.4.313.0'
url='https://github.com/KhronosGroup/SPIRV-Tools'
description='Provides an API and commands for processing SPIR-V modules'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/vulkan-sdk-$version.tar.gz")
depends=(spirv-headers gcc)
makedepends=()
sha256sums=('6b60f723345ceed5291cceebbcfacf7fea9361a69332261fa08ae57e2a562005')
group=(dev.util)
uses=()
arch=('x86_64')

cd SPIRV-Tools-vulkan-sdk-$version

setup(){
local cmake_options=(
    -D BUILD_SHARED_LIBS=ON
    -D CMAKE_BUILD_TYPE=Release
    -D CMAKE_INSTALL_PREFIX=/usr
    -D CMAKE_INSTALL_SYSCONFDIR=/etc
    -D CMAKE_SKIP_INSTALL_RPATH=ON
    -D SPIRV-Headers_SOURCE_DIR=/usr
    -D SPIRV_TOOLS_BUILD_STATIC=OFF
    -D SPIRV_WERROR=OFF
  )

  cmake -B build -G Ninja "${cmake_options[@]}"
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

