#!/usr/bin/env bash
name='rust'
release='7'
version='1.84.0'
url='https://www.rust-lang.org'
description='Systems programming language from Mozilla'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://static.rust-lang.org/dist/rustc-$version-src.tar.gz"
        'config.toml')
depends=(curl gcc libssh llvm)
makedepends=(cmake ninja perl python lld)
sha256sums=('722d773bd4eab2d828d7dd35b59f0b017ddf9a97ee2b46c1b7f7fac5c8841c6e'
         'SKIP')
group=(dev.lang)
uses=()
arch=('x86_64')
# disable strip
dontstrip=1

cd rustc-$version-src

setup () {
    install ../config.toml ./config.toml
    sed -i "s/@verison@/"$version"/g" ./config.toml
}

build () {
    python3 ./x.py build -j `nproc`
}

package () {
    python3 ./x.py install -j `nproc`
}

