#!/usr/bin/env bash
name='xcb-util'
release='1'
version='0.4.0'
url='https://xcb.freedesktop.org'
description='X C-language Bindings sample implementations'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/xcb/xcb-util-${version}.tar.gz")
depends=(libxcb)
makedepends=(util-macros xorgproto)
md5sums=('157d82738aa89934b6adaf3ca508a0f5')
uses=()
arch=('x86_64')
group=(x11.libs)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
	--enable-shared \
	--enable-static \
	--disable-devel-docs \
	--without-doxygen
}

build(){
    make $jobs
}

package(){
    make install $jobs
}
