#!/usr/bin/env bash
name='qt5-svg'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='Classes for displaying the contents of SVG files'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtsvg-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=()
sha256sums=('a99e87dbebd2621ea62fb4f8448b978a660d781fd91bb8f02fc636073035f145')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtsvg-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}
