#!/usr/bin/env bash
name='spirv-headers'
release='3'
version='1.3.275.0'
url='https://github.com/KhronosGroup/SPIRV-Headers'
description='Machine-readable files for the SPIR-V Registry'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-$version.tar.gz")
depends=()
makedepends=()
md5sums=('f293886617aa816fdbb2b50d5e909681')
group=(dev.util)
uses=()
arch=('x86_64')

cd SPIRV-Headers-vulkan-sdk-$version

setup(){
    mkdir build && cd build
    cmake .. \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    make -C build
}

package(){
    make -C build install
}

