#!/usr/bin/env bash
name='spirv-headers'
release='2'
version='1.3.261.1'
url='https://github.com/KhronosGroup/SPIRV-Headers'
description='Machine-readable files for the SPIR-V Registry'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/sdk-$version.tar.gz")
depends=()
makedepends=()
md5sums=('ab619ff9081e1d6cb8d87b1baa40f1d9')
group=(dev.util)
uses=()
arch=('x86_64')

cd SPIRV-Headers-sdk-$version

setup(){
    mkdir build && cd build
    cmake .. \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    make -C build
}

package(){
    make -C build install
}

