#!/usr/bin/env bash
name='spirv-headers'
release='1'
version='1.3.236.0'
url='https://github.com/KhronosGroup/SPIRV-Headers'
description='Machine-readable files for the SPIR-V Registry'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/sdk-$version.tar.gz")
depends=()
makedepends=()
md5sums=('da1982a5df290f7a76ff786af4587ffc')
group=()
uses=()
arch=('x86_64')

cd SPIRV-Headers-sdk-$version

setup(){
    mkdir build && cd build
    cmake .. \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    make -C build
}

package(){
    make -C build install
}

