#!/usr/bin/env bash
name='python'
release='1'
version='3.10'
url='https://gitlab.com/sulix'
description='Python meta package'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('pydefault')
depends=(python3.10)
makedepends=()
md5sums=('SKIP')
uses=()
group=(dev.lang)
arch=('x86_64')

package(){
    mkdir -p ${DESTDIR}/usr/bin/
    install pydefault ${DESTDIR}/usr/bin/
}

