#!/usr/bin/env bash
name='kconfigwidgets'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Widgets for KConfig'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kconfigwidgets-${version}.tar.xz")
depends=(qt6-base kcodecs kconfig ki18n kwidgetsaddons kcoreaddons kguiaddons kcolorscheme)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('aa5a7be6278a19733f77e6a435f84c3e71926b28f1ac3766313778890d640813')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
