#!/usr/bin/env bash
name='qt5-multimedia'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='Qt5 - Multimedia support'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtmultimedia-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base alsa-lib gst-plugins-base)
makedepends=(qt5-declarative)
sha256sums=('c5ec6b6eb99444c79b24d32cd0eab813810ab20c9b09bc9c98df7ca3fe09c7a4')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtmultimedia-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}
