#!/usr/bin/env bash
name='libwebp'
release='2'
version='1.5.0'
url='https://developers.google.com/speed/webp/'
description='WebP library and conversion tools'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${version}.tar.gz")
depends=(libpng libjpeg-turbo libtiff)
makedepends=(cmake ninja)
sha256sums=('7d6fab70cf844bf6769077bd5d7a74893f8ffd4dfb42861745750c63c2a5c92c')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --enable-libwebpmux     \
        --enable-libwebpdemux   \
        --enable-libwebpdecoder \
        --enable-libwebpextras  \
        --enable-swap-16bit-csp
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

