#!/usr/bin/env bash
name='libwebp'
release='1'
version='1.3.0'
url='https://developers.google.com/speed/webp/'
description='WebP library and conversion tools'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${version}.tar.gz")
depends=(libpng libjpeg-turbo libtiff)
makedepends=(cmake ninja)
md5sums=('994cf2efb664ef5140fa0b56b83fa721')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --enable-libwebpmux     \
        --enable-libwebpdemux   \
        --enable-libwebpdecoder \
        --enable-libwebpextras  \
        --enable-swap-16bit-csp
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

