#!/usr/bin/env bash
name='pam'
release='2'
version='1.6.0'
url='https://github.com/linux-pam/linux-pam'
description='PAM (Pluggable Authentication Modules) library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/linux-pam/linux-pam/releases/download/v$version/Linux-PAM-$version.tar.xz")
depends=(libtirpc libxcrypt libnsl)
makedepends=( )
md5sums=('41a10af5fc35a7be472ae9864338e64a')
uses=()
arch=('x86_64')
group=(sys.libs)

cd Linux-PAM-$version

setup(){
    ./configure --prefix=/usr \
        --sbindir=/sbin \
        --libdir=/lib64 \
        --enable-securedir=/lib64/security \
        --enable-static \
        --enable-shared \
        --disable-selinux \
        --disable-nls
}

build(){
    make $jobs
}

package(){
    make install $jobs
    # remove systemd stuff
    rm -rf ${DESTDIR}/usr/lib/systemd/
}

