#!/usr/bin/env bash
name='pam'
release='1'
version='1.5.2'
url='https://github.com/linux-pam/linux-pam'
description='PAM (Pluggable Authentication Modules) library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/linux-pam/linux-pam/releases/download/v$version/Linux-PAM-$version.tar.xz")
depends=(libtirpc libxcrypt libnsl)
makedepends=( )
md5sums=('895e8adfa14af334f679bbeb28503f66')
uses=()
arch=('x86_64')
group=(sys.libs)

cd Linux-PAM-$version

setup(){
    ./configure --prefix=/usr \
        --sbindir=/sbin \
        --libdir=/lib64 \
        --enable-securedir=/lib64/security \
        --enable-static \
        --enable-shared \
        --disable-selinux \
        --disable-nls
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
    # remove systemd stuff
    rm -rf ${DESTDIR}/usr/lib/systemd/
    # ld.so.conf
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    mv ${DESTDIR}/lib64/pam/pkgconfig ${DESTDIR}/lib64/pkgconfig
}

