#!/usr/bin/env bash
name='pam'
release='1'
version='1.5.2'
url='https://github.com/linux-pam/linux-pam'
description='PAM (Pluggable Authentication Modules) library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/linux-pam/linux-pam/releases/download/v$version/Linux-PAM-$version.tar.xz")
depends=(libtirpc libxcrypt)
makedepends=( )
md5sums=('895e8adfa14af334f679bbeb28503f66')
uses=()
arch=('x86_64')
group=(sys.libs)

cd Linux-PAM-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

