#!/usr/bin/env bash
name='libcdio'
release='1'
version='2.1.0'
url='https://www.gnu.org/software/libcdio/'
description='GNU Compact Disc Input and Control Library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/libcdio/libcdio-${version}.tar.bz2")
depends=()
makedepends=()
md5sums=('aa7629e8f73662a762f64c444b901055')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

