#!/usr/bin/env bash
name='py3-markupsafe'
release='3'
version='3.0.2'
url='https://pypi.org/project/MarkupSafe'
description='Safely add untrusted strings to HTML/XML markup.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pallets/markupsafe/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer py3-setuptools py3-wheel)
sha256sums=('cd182103704bfafefce25369fd27f14a5f578f078b7f3ddd1ce2cb940b86403a')
group=(dev.python)
uses=()
arch=('x86_64')

cd markupsafe-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}

