#!/usr/bin/env bash
name='py3-markupsafe'
release='2'
version='2.1.5'
url='https://pypi.org/project/MarkupSafe'
description='Safely add untrusted strings to HTML/XML markup.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pallets/markupsafe/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer py3-setuptools py3-wheel)
sha256sums=('307f63295d17f178b7d3af5968fb828e34086d5d66fec505b630a1e5f5b3328b')
group=(dev.python)
uses=()
arch=('x86_64')

cd markupsafe-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

