#!/usr/bin/env bash
name='thunar-volman'
release='1'
version='4.18.0'
_version='4.18'
url='https://docs.xfce.org/xfce/thunar/thunar-volman'
description='Automatic management of removable drives and media for Thunar'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/thunar-volman/${_version}/thunar-volman-${version}.tar.bz2")
depends=( hicolor-icon-theme libxfce4ui thunar)
makedepends=(intltool)
md5sums=('a0965931e78fe662ad134e63b1ab33b9')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug 
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

