#!/usr/bin/env bash
name='thunar-volman'
release='2'
version='4.20.0'
_version='4.20'
url='https://docs.xfce.org/xfce/thunar/thunar-volman'
description='Automatic management of removable drives and media for Thunar'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/thunar-volman/${_version}/thunar-volman-${version}.tar.bz2")
depends=( hicolor-icon-theme libxfce4ui thunar)
makedepends=(intltool)
sha256sums=('b0dad852959b515b8fbfd1ed552e362340347d26d5246e7f1b973027131eb1da')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

