#!/usr/bin/env bash
name='pygobject'
release='1'
version='3.43.1'
url='Python bindings for GObject Introspection'
description='Python bindings for GObject Introspection'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/pygobject/-/archive/$version/pygobject-$version.tar.gz")
depends=(python cairo py3-cairo libX11 libXext)
makedepends=()
md5sums=('644705774d5cd6b668e95ac33ba64de2')
group=(dev.python)
uses=()
arch=('x86_64')

cd $name-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
