#!/usr/bin/env bash
name='kcmutils'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Utilities for interacting with KCModules'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcmutils-${version}.tar.xz")
depends=(kdeclarative)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('f24eed2390eef633913a29252430af45')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
