#!/usr/bin/env bash
name='spectacle'
release='3'
version='6.4.5'
url='https://kde.org/applications/utilities/org.kde.spectacle'
description='Application for capturing desktop screenshots'
email='osman.coskun95@gmail.com'
maintainer='mergin'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/spectacle-$version.tar.xz"
        "remove-opencv.patch"
        "spectacle.desktop")
depends=(qt6-base kwayland kpipewire)
makedepends=(extra-cmake-modules ki18n kdoctools)
sha256sums=('42a56f0593c0c5c7b661088ef6e6e32a0ea248354fbbfdb4a20f3a21ba5540e7'
            'SKIP'
            'SKIP')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version
export PATH=$PATH:/usr/lib64/qt6/libexec/rcc

export LANG=en_US.UTF-8

prepare(){
    patch -Np1 -i ../remove-opencv.patch
}

setup(){
		cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64
}

build(){
		ninja -C build $jobs
}

package(){
     ninja -C build install $jobs
     # fix symlink
     rm -f $DESTDIR/usr/share/kglobalaccel/org.kde.spectacle.desktop
     ln -s ../applications/org.kde.spectacle.desktop \
          $DESTDIR/usr/share/kglobalaccel/org.kde.spectacle.desktop
     # install autostart file
     install -Dm644 ../spectacle.desktop -t "$DESTDIR"/etc/xdg/autostart/
}
