#!/usr/bin/env bash
name='ghostscript'
release='3'
version='10.03.1'
_version='10031'
url='https://example.org'
description='An interpreter for the PostScript language'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=(
    "https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs${_version}/ghostscript-${version}.tar.xz"
    "https://downloads.sourceforge.net/gs-fonts/ghostscript-fonts-std-8.11.tar.gz"
    "https://downloads.sourceforge.net/gs-fonts/gnu-gs-fonts-other-6.0.tar.gz"
)
depends=(libXt cups fontconfig zlib libpng libtiff lcms2 poppler cairo glibc libX11 gdk-pixbuf glib)
makedepends=(gtk3 gnutls)
sha256sums=(
    '157212edc96b8ccc409475dce2e49833fb4427f150c455258ded9632c106abee'
    '0eb6f356119f2e49b2563210852e17f57f9dcc5755f350a69a46a0d641a0c401'
    '8146cccc4699fe9dab841446bdd17039f4769c903eceb54409188b920754aab3'
)
group=(app.text)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
        --disable-compile-inits \
         --enable-dynamic \
         --disable-hidden-visibility
}

build () {
    make so $jobs
}

package () {
    make install $jobs
    make soinstall $jobs
    install -v -m644 base/*.h $DESTDIR/usr/include/ghostscript
    ln -sfvn ghostscript $DESTDIR/usr/include/ps
    install -v -m644 ../fonts/* $DESTDIR/usr/share/ghostscript
}

