#!/usr/bin/env bash
name='libplacebo'
release='4'
version='6.338.2'
url='https://code.videolan.org/videolan/libplacebo/'
description='Reusable library for GPU-accelerated image processing primitives'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://code.videolan.org/videolan/libplacebo/-/archive/v$version/libplacebo-v$version.tar.gz")
depends=(libunwind)
makedepends=(vulkan-headers)
md5sums=('20fbb598f79eb1c6b6ef1130baf6dd6c')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-v$version

setup(){
	meson setup build --prefix=/usr \
      --libdir=/usr/lib64/ \
      -Dopengl=disabled \
      -Dd3d11=disabled \
      -Dshaderc=disabled \
      -Dvulkan=disabled

}

build(){
    ninja -C build
}

package(){
   ninja -C build install
}

