#!/usr/bin/env bash
name='xf86-input-keyboard'
release='1'
version='1.9.0'
url='https://gitlab.freedesktop.org/xorg/driver/xf86-input-keyboard'
description='Xorg keyboard input driver'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/driver/xf86-input-keyboard/-/archive/xf86-input-keyboard-$version/xf86-input-keyboard-xf86-input-keyboard-$version.tar.gz")
depends=()
makedepends=()
md5sums=('9de5e2b54b8fda5c927daf2a8532f2c4')
group=(x11.drivers)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

