#!/usr/bin/env bash
name='dav1d'
release='2'
version='1.2.0'
url='https://code.videolan.org/videolan/dav1d/'
description='dav1d is an AV1 Decoder'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://code.videolan.org/videolan/dav1d/-/archive/$version/dav1d-$version.tar.gz")
depends=()
makedepends=()
md5sums=('87807808ecbed1167399fbffd6be7f7a')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Denable_asm=false
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

