#!/usr/bin/env bash
name='xf86-video-ast'
release='1'
version='1.1.6'
url='https://gitlab.freedesktop.org/xorg/driver/xf86-video-ast'
description='X.Org driver for ASpeedTech cards'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://gitlab.freedesktop.org/xorg/driver/xf86-video-ast/-/archive/xf86-video-ast-1.1.6/xf86-video-ast-xf86-video-ast-1.1.6.tar.gz')
depends=()
makedepends=()
md5sums=('7ad42ca3f7011f0db6ea7f03899be45b')
group=(x11.drivers)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install
}

