#!/usr/bin/env bash
name='libXfont'
release='1'
version='1.5.4'
url='https://gitlab.freedesktop.org/xorg/lib/libXfixes.git/'
description='X.Org Xfixes library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXfont-$version.tar.gz")
depends=(libfontenc freetype)
makedepends=()
md5sums=('562cc729034de3442d860f1c50508c8b')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

