#!/usr/bin/env bash
name='jack2'
release='1'
version='1.9.22'
url='https://github.com/jackaudio/jack2'
description='A frontend for several cd-rippers and mp3 encoders '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/jackaudio/jack2/archive/refs/tags/v$version.tar.gz"
"jack2-1.9.22-db-5.3.patch")
depends=(python)
makedepends=()
md5sums=('e57c8ad3de75f78b6eb7aacea4e25755'
"SKIP")
group=(media.sound)
uses=()
arch=('x86_64')

cd $name-$version

_pick() {
  local p="$1" f d; shift
  for f; do
    d="$srcdir/$p/${f#$pkgdir/}"
    mkdir -p "$(dirname "$d")"
    mv "$f" "$d"
    rmdir -p --ignore-fail-on-non-empty "$(dirname "$f")"
  done
}

prepare() {
  patch -Np1 -i ../jack2-1.9.22-db-5.3.patch

  # remove custom waflib, as we are using system provided waf
  #rm -rv waflib
}

setup() {
  local waf_options=(
    --prefix=/usr
    --libdir=/usr/lib64/
    --htmldir=/usr/share/doc/$name/html
    --autostart=none
    --doxygen=no
    --classic
    --dbus
  )


  waf configure "${waf_options[@]}"
}

build(){
  waf build
}

package() {
  export PYTHONPATH="$PWD:$PYTHONPATH"
  waf install --destdir="$DESTDIR"
}

