#!/usr/bin/env bash
name='py3-markdown'
release='3'
version='3.6'
url='https://github.com/Python-Markdown/markdown'
description='A Python implementation of John Gruber’s Markdown with Extension support.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/Python-Markdown/markdown/archive/refs/tags/$version.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer py3-setuptools py3-wheel)
sha256sums=('f65f3867f967b4b0ea4acd951bb7f0d9cb4d033c6fc28847a7eeb4d9fe242844')
group=(dev.python)
uses=()
arch=('x86_64')

cd markdown-$version

build(){
    python3 -m build --wheel
}

package(){
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
}

