#!/usr/bin/env bash
name='py3-markdown'
release='2'
version='3.5.1'
url='https://github.com/Python-Markdown/markdown'
description='A Python implementation of John Gruber’s Markdown with Extension support.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/Python-Markdown/markdown/archive/refs/tags/$version.tar.gz")
depends=(python)
makedepends=()
md5sums=('cf0cb1e79621a55fd443cfe4497659e2')
group=(dev.python)
uses=()
arch=('x86_64')

cd markdown-$version

build(){
    python3 -m build --wheel
}

package(){
	python3 -m installer --destdir="$DESTDIR" dist/*.whl
}

