#!/usr/bin/env bash
name='gstreamer'
release='2'
version='1.24.7'
url='https://gstreamer.freedesktop.org/'
description='Multimedia graph framework - core'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-${version}.tar.xz")
depends=(glib elfutils libxml2 orc)
makedepends=(gobject-introspection gtk3 libcap python)
sha256sums=('c0e75b124c52bb7a0c3dcdb734b2ad260ea7286a8745cf2ea629d4c849e6a958')
group=(media.libs)
uses=()
arch=('x86_64')


cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
