#!/usr/bin/env bash
name='gstreamer'
release='2'
version='1.24.7'
url='https://gstreamer.freedesktop.org/'
description='Multimedia graph framework - core'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-${version}.tar.xz")
depends=(glib elfutils libxml2 ocr)
makedepends=(gobject-introspection gtk3 libcap python)
sha256sums=('779f5ede3016019eec01d64a025583078d3936e35d4288ec2e8433494d757dd9')
group=(media.libs)
uses=()
arch=('x86_64')


cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
