#!/usr/bin/env bash
name='kmediaplayer'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Media player framework for KDE 5'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/portingAids//kmediaplayer-${version}.tar.xz")
depends=(kparts kxmlgui qt5-base)
makedepends=(extra-cmake-modules)
md5sums=('f74f62b13772e6b79391b29bc4c821e1')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

