#!/usr/bin/env bash
name='kitemviews'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Widget addons for Qt Model/View'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kitemviews-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('f74c03e2ec367238ec395b1f2438878999c2be3e29b41b6bd4a3ccd04440e29a')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DBUILD_TESTING=OFF \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

