#!/usr/bin/env bash
name='kitemviews'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description='Widget addons for Qt Model/View'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kitemviews-${version}.tar.xz")
depends=(qt5-base)
makedepends=(extra-cmake-modules qt5-tools doxygen)
md5sums=('9f4950395dd81d063c45e69a16c24203')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DBUILD_TESTING=OFF \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

