#!/usr/bin/env bash
name='vala'
release='2'
version='0.56.18'
url='https://wiki.gnome.org/Projects/Vala'
description='Compiler for the GObject type system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("http://download.gnome.org/sources/vala/0.56/vala-$version.tar.xz")
depends=(glib gcc)
makedepends=()
sha256sums=('f2affe7d40ab63db8e7b9ecc3f6bdc9c2fc7e3134c84ff2d795f482fe926a382')
uses=()
uses_extra=(doc)
arch=('x86_64')
doc_depends=(graphviz)
group=(dev.lang)

cd $name-$version

# gcc14 build bloken (yet)
export CC=clang

setup(){
    autoreconf -vfi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        $(use_opt doc --enable-valadoc --disable-valadoc)
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

