#!/usr/bin/env bash
name='xfsprogs'
release='4'
version='6.5.0'
url='https://xfs.wiki.kernel.org/'
description='XFS filesystem utilities'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://mirrors.edge.kernel.org/pub/linux/utils/fs/xfs/xfsprogs/xfsprogs-${version}.tar.xz")
depends=(inih liburcu)
makedepends=()
md5sums=('312d4f63c02c63a6b8b8b80a9ada11c6')
group=(sys.fs)
uses=()
arch=('x86_64')

cd $name-$version
setup(){
    make configure
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sbindir=/usr/sbin

}

build(){
    make $jobs
}

package(){
   # make install $jobs
  make DIST_ROOT="${DESTDIR}" PKG_ROOT_SBIN_DIR="/usr/sbin" install install-dev
  # add hack as we cannot set rootlibdir
  mv "${DESTDIR}"/lib64/libhandle.so* "${DESTDIR}/usr/lib64/"
  rm -rf "${DESTDIR}/lib64"

}

