#!/usr/bin/env bash
name='wayland-protocols'
release='2'
version='1.32'
url='https://gitlab.freedesktop.org/wayland/wayland-protocols'
description='Wayland protocol files'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/$version/downloads/wayland-protocols-$version.tar.xz")
depends=(wayland)
makedepends=()
md5sums=('00c2cedb0d2df714a0965a00c19385c6')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr \
        -Ddefault_library=both
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

