#!/usr/bin/env bash
name='wayland-protocols'
release='4'
version='1.36'
url='https://gitlab.freedesktop.org/wayland/wayland-protocols'
description='Wayland protocol files'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/$version/downloads/wayland-protocols-$version.tar.xz")
depends=(wayland)
makedepends=()
sha256sums=('71fd4de05e79f9a1ca559fac30c1f8365fa10346422f9fe795f74d77b9ef7e92')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr \
        -Ddefault_library=both
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

