#!/usr/bin/env bash
name='libgphoto2'
release='1'
version='2.5.30'
url='http://www.gphoto.org/'
description='Digital camera access library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://github.com/gphoto/libgphoto2/archive/refs/tags/v${version}.tar.gz")
depends=(libxml2 libusb curl libjpeg-turbo)
makedepends=()
md5sums=('97ea83b7e4448c49f9184893561446b9')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make DESTDIR="$DESTDIR" install $jobs
}

