#!/usr/bin/env bash
name='firefox-installer'
release='4'
version='1.0.2'
url='https://turkman/devel/sources/firefox-installer'
description='Firefox installer'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/firefox-installer/-/archive/$version/firefox-installer-$version.tar.gz")
depends=(dbus-glib alsa-lib ffmpeg libX11)
makedepends=()
sha256sums=('826d7b3fefcbd4b10fb205a26f0393892e0396bcd362d649cafae7955152e902')
group=(www.client)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr
}

package(){
    ninja -C build install $jobs
}

