#!/usr/bin/env bash
name='firefox-installer'
release='1'
version='20230419'
url='https://github.com/my-garbage-stuff/firefox-installer'
description='Firefox installer'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/my-garbage-stuff/firefox-installer/archive/refs/tags/$version.tar.gz")
depends=(dbus-glib alsa-lib ffmpeg libX11)
makedepends=()
md5sums=('519c74fa28038243cf415660997db48f')
group=(www.client)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    # replace /opt with /usr/libexec
    sed -i "s|/opt|/usr/libexec|g" Makefile firefox firefox-installer.desktop
}

package(){
    make install $jobs
}

