#!/usr/bin/env bash
name='libxkbui'
release='1'
version='1.0.2'
url='https://example.org'
description='Package libxkbui'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libxkbui-$version.tar.gz")
depends=(libX11 libXt libxkbfile)
makedepends=()
md5sums=('a6210171defde64d9e8bcf6a6f6074b0')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

