#!/usr/bin/env bash
name='libXres'
release='1'
version='1.2.2'
url='https://gitlab.freedesktop.org/xorg/lib/libXres.git/'
description='X.Org XRes library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXres-$version.tar.xz")
depends=(libX11 libXext xorgproto)
makedepends=()
md5sums=('66c9e9e01b0b53052bb1d02ebf8d7040')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

