#!/usr/bin/env bash
name='py3-flit'
release='3'
version='3.9.0'
url='https://github.com/pypa/flit'
description='Simplified packaging of Python modules'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pypa/flit/archive/refs/tags/$version.tar.gz")
depends=(python)
makedepends=()
sha256sums=('55e28d0953726c4c744f02779b85f733f65da5bffb6a5d2fe11072d19ca2d148')
group=(dev.python)
uses=()
arch=('x86_64')

cd flit-$version

build(){
    cur=$PWD
    for dir in . flit_core; do
        cd $dir
        python -m build --wheel --skip-dependency-check --no-isolation
        cd $cur
    done
}

package(){
    cur=$PWD
    for dir in . flit_core; do
        cd $dir
        python -m installer --destdir="$DESTDIR" dist/*.whl
        cd $cur
    done
}
