#!/usr/bin/env bash
name='kcodecs'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Provide a collection of methods to manipulate strings using various encodings'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcodecs-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools gperf)
sha256sums=('247eda9ade502699062c7baaca7bb93691a308f202c165954652875ebe777426')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr

}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

