#!/usr/bin/env bash
name='kcodecs'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description='Provide a collection of methods to manipulate strings using various encodings'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcodecs-${version}.tar.xz")
depends=(qt5-base)
makedepends=(extra-cmake-modules doxygen qt5-tools gperf 	graphviz)
md5sums=('11e441ff480648521b91890aa1a4a5e6')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr

}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

