#!/usr/bin/env bash
name='kross'
release='3'
version='5.116.0'
url='https://community.kde.org/Frameworks'
description='Framework for scripting KDE applications'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/portingAids/kross-${version}.tar.xz")
depends=(kcompletion kcoreaddons ki18n kiconthemes kio kparts kwidgetsaddons kxmlgui qt5-base qt5-script)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('96c985837152efdd216a93790703823877fdea43a1b9d3a5197a9b94c264be4f')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


