#!/usr/bin/env bash
name='librsvg'
release='3'
version='2.57.0'
url='https://github.com/oaken-source/librsvg-og'
description='Scalable Vector Graphics (SVG) rendering library '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
#source=("https://github.com/oaken-source/librsvg-og/archive/refs/tags/$version.tar.gz")
source=("https://download.gnome.org/sources/librsvg/${version%.*}/librsvg-${version}.tar.xz")
depends=(libcroco gobject-introspection pango cairo fontconfig libX11 libXext libXrender libxcb gdk-pixbuf)
makedepends=()
md5sums=('8b700dd04c10bf65dbc6824d2780561d')
group=(gnome.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    #autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install DESTDIR="$DESTDIR" $jobs
}

