#!/usr/bin/env bash
name='bdftopcf'
release='1'
version='1.1.1'
url='https://gitlab.freedesktop.org/xorg/util/bdftopcf.git/'
description='X.Org bdftopcf application'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/util/bdftopcf/-/archive/bdftopcf-$version/bdftopcf-bdftopcf-$version.tar.gz")
depends=(font-util)
makedepends=()
md5sums=('bb9ff1d1cb088d97c1dcb28f0d08179c')
group=(x11.apps)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

