#!/usr/bin/env bash
name='libbytesize'
release='2'
version='2.11'
url='https://github.com/storaged-project/libbytesize'
description='A tiny library providing a C "class" for working with arbitrary big sizes in bytes'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/storaged-project/libbytesize/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('794fc1804dd16ff0d5a505dbab2dd84c174d1159f4a58f3764fee1c8e5d949ca')
group=(sys.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

