#!/usr/bin/env bash
name='libbytesize'
release='1'
version='2.8'
url='https://github.com/storaged-project/libbytesize'
description='A tiny library providing a C "class" for working with arbitrary big sizes in bytes'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/storaged-project/libbytesize/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
md5sums=('c64c8f3042f0d172df6970f06cb94b94')
group=(sys.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

