#!/usr/bin/env bash
name='zxing-cpp'
release='1'
version='2.2.1'
url='https://github.com/zxing-cpp/zxing-cpp'
description='C++ Multi-format 1D/2D barcode image processing library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/zxing-cpp/zxing-cpp/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=(cmake ninja)
sha256sums=('02078ae15f19f9d423a441f205b1d1bee32349ddda7467e2c84e8f08876f8635')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -G Ninja \
         -DCMAKE_INSTALL_PREFIX=/usr \
         -DBUILD_EXAMPLES=OFF \
         -DBUILD_UNIT_TESTS=ON
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

