#!/usr/bin/env bash
name='ki18n'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Advanced internationalization framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/ki18n-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(doxygen extra-cmake-modules python)
sha256sums=('d0cbfbf3427c0368daa23f9f68b3cb5b03ad37b6820591491b3ea8a0a28bea61')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QCH=ON
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

