#!/usr/bin/env bash
name='kparts'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Document centric plugin system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kparts-${version}.tar.xz")
depends=(kconfig kcoreaddons ki18n kio kwidgetsaddons kxmlgui qt6-base)
makedepends=(doxygen extra-cmake-modules qt6-tools)
sha256sums=('4eb5417b267f77c16c85482f919adfb5b7714a95239771c4aafbfeb90e4a371f')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

