#!/usr/bin/env bash
name='kemoticons'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description='Support for emoticons and emoticons themes'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kemoticons-${version}.tar.xz")
depends=(karchive kconfig kcoreaddons kservice)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('6eb1424946cca988b61bec4577be39b4')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

