#!/usr/bin/env bash
name='libsfdo'
release='1'
version='0.1.3'
url='https://gitlab.freedesktop.org/vyivel/libsfdo'
description='A collection of libraries which implement some of the freedesktop.org specifications.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/vyivel/libsfdo/-/archive/v$version/libsfdo-v$version.tar.gz")
depends=()
makedepends=()
sha256sums=('d1f2d8b5edec827fd386c22d6f9151377ec7c194dca4d293e3abad9df9974209')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-v$version

setup () {
    meson setup build \
         --prefix=/usr \
         --libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

