#!/usr/bin/env bash
name='glib'
release='2'
version='2.76.3'
url='https://download.gnome.org/sources/glib/'
description='Low-level core library that forms the basis for projects such as GTK+ and GNOME.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://download.gnome.org/sources/glib/2.76/glib-${version}.tar.xz"
        "glib.sysconf")
depends=(libffi util-linux libpcre2 zlib)
makedepends=( )
md5sums=('9e8f5c00f0cdf71c7e47e554bfbf9dcb'
         'SKIP')
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64 \
        --default-library both \
        -D glib_debug=disabled \
        -D selinux=disabled \
        -D sysprof=disabled
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../glib.sysconf ${DESTDIR}/etc/sysconf.d/glib
}

