#!/usr/bin/env bash
name='kdeclarative'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Provides integration of QML and KDE Frameworks'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdeclarative-${version}.tar.xz")
depends=(kio kpackage libepoxy)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('e141465054d4bf65467db3f2e7c4ebed')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

