#!/usr/bin/env bash
name='kdeclarative'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Provides integration of QML and KDE Frameworks'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdeclarative-${version}.tar.xz")
depends=(kio kpackage libepoxy ki18n kconfig kwidgetsaddons kguiaddons kglobalaccel)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('4671ebb7ee9ba2ed7a02d2c71dde90fe681be507e7d7913e79acb15dfce7b6f9')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

