#!/usr/bin/env bash
name='drkonqi'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='The KDE crash handler'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/drkonqi-${version}.tar.xz")
depends=(kidletime syntax-highlighting kirigami2 kitemmodels kuserfeedback kio py3-distro py3-psutil qt5-tools)
makedepends=(extra-cmake-modules)
md5sums=('119a1ef17f748a4a3d64b306f3e651a1')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

