#!/usr/bin/env bash
name='vim'
release='2'
version='9.1.0095'
url='http://ftp.vim.org/pub/vim/unix/'
description='free and open-source, screen-based text editor program'
email='queryvs@example.com'
maintainer='queryvs'
license=('GPLv2')
				#https://github.com/vim/vim/archive/refs/tags/v9.1.0095.tar.gz
source=("https://github.com/vim/vim/archive/refs/tags/v$version.tar.gz")
depends=(ncurses)
makedepends=()
md5sums=('9bcf6aa825dd6955a447e984a87307b3'
         'SKIP')
arch=('x86_64')
group=(app.editor)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --enable-cscope \
        --enable-multibyte \
        --with-ex-name=vim-ex \
        --with-view-name=vim-view \
        --disable-canberra \
        --disable-sodium \
        --disable-acl \
        --disable-perlinterp \
        --disable-pythoninterp \
        --disable-rubyinterp \
        --disable-netbeans \
        --disable-gpm \
        --disable-xim \
        --disable-gui \
        --disable-nls \
        --without-x
}

build(){
    make $jobs
}

package(){
    make DESTDIR="$DESTDIR" install $jobs
}

