#!/usr/bin/env bash
name='qpdf'
release='1'
version='11.6.1'
url='https://github.com/qpdf/qpdf'
description='Command-line tool for structural, content-preserving transformation of PDF files'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/qpdf/qpdf/releases/download/v$version/qpdf-$version.tar.gz")
depends=(libjpeg-turbo gnutls)
makedepends=()
md5sums=('a5cacc48af5c931e62c58c8e4421e940')
group=(app.text)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -G Ninja ..
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

