#!/usr/bin/env bash
name='qt5-virtualkeyboard'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='Virtual keyboard framework'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtvirtualkeyboard-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-svg qt5-declarative)
makedepends=()
md5sums=('5a38e7c6825d71e91cf9980780de8110')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtvirtualkeyboard-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

