#!/usr/bin/env bash
name='qt5-virtualkeyboard'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='Virtual keyboard framework'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtvirtualkeyboard-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-svg qt5-declarative)
makedepends=()
sha256sums=('55caf54fd49ce63dc20e8900ade9bf890d95292404f28eb1e746b21d97cfb6db')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtvirtualkeyboard-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

