#!/usr/bin/env bash
name='font-bh-lucidatypewriter-100dpi'
release='1'
version='1.0.3'
url='https://gitlab.freedesktop.org/xorg/font/bh-lucidatypewriter-100dpi'
description='X.Org Bigelow & Holmes Lucida bitmap fonts'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://gitlab.freedesktop.org/xorg/font/bh-lucidatypewriter-100dpi/-/archive/font-bh-lucidatypewriter-100dpi-1.0.3/bh-lucidatypewriter-100dpi-font-bh-lucidatypewriter-100dpi-1.0.3.tar.gz')
depends=(font-util)
makedepends=()
md5sums=('a6b28dc6baa622ee828a882b94255731')
group=(media.fonts)
uses=()
arch=('x86_64')

cd bh-lucidatypewriter-100dpi-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

