#!/usr/bin/env bash
name='smartypants'
release='2'
version='2.0.2'
url='https://github.com/leohemsted/smartypants.py/'
description='ASCII quote-dot-dash to HTML entity converter'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/leohemsted/smartypants.py/archive/refs/tags/v$version.tar.gz")
depends=(python)
makedepends=()
sha256sums=('560ae7485a27c288f5bd63131f5c3c7b8f0745f50e7c3f85f0bbc65d87799d19')
group=(dev.python)
uses=()
arch=('x86_64')

cd $name.py-$version

build(){
    python3 -m build
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
    mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}
