#!/usr/bin/env bash
name='chrpath'
release='2'
version='0.17'
url='https://directory.fsf.org/wiki/Chrpath'
description='Chrpath can modify the rpath and runpath of ELF executables'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://codeberg.org/pere/chrpath/archive/release-$version.tar.gz")
depends=()
makedepends=()
md5sums=('a76a47c9c82016821808f5726a66e600')
group=(app.admin)
uses=()
arch=('x86_64')

cd $name

setup(){
   autoreconf -vfi
   ./configure --prefix=/usr \
       --mandir=/usr/share/man
}

build(){
    make $jobs
}

package(){
    make docdir=/usr/share/doc/chrpath install

}

