#!/usr/bin/env bash
name='xfce4-screenshooter'
release='2'
version='1.11.2'
url='https://docs.xfce.org/apps/xfce4-screenshooter/start'
description='An application to take screenshots for Xfce'
email='03teknoloji@gmail.com'
maintainer='mobilturka'
license=('GPLv2')
source=("https://archive.xfce.org/src/apps/$name/${version%.*}/$name-$version.tar.xz")
depends=(xfce4-panel hicolor-icon-theme)
makedepends=()
sha256sums=('6ae5bc4823d43e770b3a11700d048d56bdcaafdef37de7deacb8970b55fc1565')
group=(xfce.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup() {
    meson setup build \
      --prefix=/usr \
      --sysconfdir=/etc \
      --localstatedir=/var
}

build(){
    ninja -C build $jobs
}

package() {
    ninja -C build install $jobs
}

