#!/usr/bin/env bash
name='gtk3'
release='1'
version='3.24.37'
url='https://example.org'
description='Package description missing'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.gnome.org/sources/gtk+/${version:0:4}/gtk+-${version}.tar.xz"
        "gtk3.sysconf"
        "gtk3-filechooser-icon-view.patch"
        "nocsd-support.patch")
depends=(cairo libXi libXext libXfixes libXcursor libXdamage librsvg at-spi2-core
         shared-mime-info gdk-pixbuf libxkbcommon libepoxy colord libcloudproviders
         dconf cantarell-fonts libpng libXcomposite)
makedepends=()
md5sums=('3649dd48556ead2d909467c1f0751956'
         'SKIP'
         'SKIP'
         'SKIP')
group=()
uses=()
arch=('x86_64')

unset CFLAGS
unset CXXFLAGS

cd gtk+-$version
export XDG_DATA_DIRS=/usr/share

prepare(){
    patch -Np1 -i ../nocsd-support.patch
    patch -Np1 -i ../gtk3-filechooser-icon-view.patch
}

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dman=false \
        -D installed_tests=false \
        -D tests=false \
        -D broadway_backend=true \
        -D cloudproviders=true \
        -D colord=yes \
        -D introspection=true \
        -D tracker3=false
}

build(){
   ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/etc/sysconf.d
    install ../gtk3.sysconf ${DESTDIR}/etc/sysconf.d/gtk3
}

