#!/usr/bin/env bash
name='gtk3'
release='2'
version='3.24.39'
url='https://download.gnome.org/sources'
description='Gimp Toolkit'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.gnome.org/sources/gtk+/${version:0:4}/gtk+-${version}.tar.xz"
        "gtk3.sysconf"
        "gtk3-filechooser-icon-view.patch"
        "nocsd-support.patch")
depends=(cairo libXi libXext libXfixes libXcursor libXdamage librsvg at-spi2-core
         shared-mime-info gdk-pixbuf libxkbcommon libepoxy colord libcloudproviders
         dconf cantarell-fonts libpng libXcomposite libXinerama glib libXrandr pango
         wayland)
makedepends=()
md5sums=('9364eedb002a8fab7287b578ef02bdd8'
         'SKIP'
         'SKIP'
         'SKIP')
group=(gui.libs)
uses=()
arch=('x86_64')

unset CFLAGS
unset CXXFLAGS

cd gtk+-$version
export XDG_DATA_DIRS=/usr/share

prepare(){
    patch -Np1 -i ../nocsd-support.patch
    patch -Np1 -i ../gtk3-filechooser-icon-view.patch
}

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dman=false \
        -D installed_tests=false \
        -D tests=false \
        -D broadway_backend=true \
        -D cloudproviders=true \
        -D colord=yes \
        -D introspection=true \
        -D tracker3=false
}

build(){
   ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/etc/sysconf.d
    install ../gtk3.sysconf ${DESTDIR}/etc/sysconf.d/gtk3
}

