#!/usr/bin/env bash
name='kactivities-stats'
release='1'
version='5.112.0'
url='https://download.kde.org/stable/frameworks'
description='A library for accessing the usage data collected by the activities system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/5.112/kactivities-stats-$version.tar.xz")
depends=(kactivities)
makedepends=()
md5sums=('e71d3565da690b8deb33f900e7b41e14')
group=(kde.framework)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DBUILD_TESTING=OFF \
        -DBUILD_QCH=ON
}

build () {
    cmake --build build
}

package () {
    cmake --install build
}

