#!/usr/bin/env bash
name='libqaccessibilityclient'
release='1'
version='0.5.0'
url='https://invent.kde.org/libraries/libqaccessibilityclient'
description='Accessibilty tools helper library, used e.g. by screen readers'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.kde.org/stable/libqaccessibilityclient/libqaccessibilityclient-${version}.tar.xz")
depends=(glibc)
makedepends=(extra-cmake-modules qt5-base)
md5sums=('138add284b3f5104e89b98847d6205d3')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DQT_MAJOR_VERSION=5

}

build() {
	cmake --build build
}

package() {
	DESTDIR="$DESTDIR" cmake --install build
}
