#!/usr/bin/env bash
name='libqaccessibilityclient'
release='2'
version='0.6.0'
url='https://invent.kde.org/libraries/libqaccessibilityclient'
description='Accessibilty tools helper library, used e.g. by screen readers'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/libqaccessibilityclient/libqaccessibilityclient-${version}.tar.xz")
depends=(glibc)
makedepends=(extra-cmake-modules qt6-base)
sha256sums=('4c50c448622dc9c5041ed10da7d87b3e4e71ccb49d4831a849211d423c5f5d33')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DQT_MAJOR_VERSION=6

}

build() {
	cmake --build build
}

package() {
	DESTDIR="$DESTDIR" cmake --install build
}
