#!/usr/bin/env bash
name='ktextwidgets'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Advanced text editing widgets'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/ktextwidgets-${version}.tar.xz")
depends=(kcolorscheme kcompletion kconfig kconfigwidgets ki18n kwidgetsaddons qt6-base sonnet qt6-speech)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('a99df1c634831e9d01f704009c951378108334a4258ad5b64f60f55e55770212')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

#HATA :CMake Error at /usr/lib64/cmake/Qt5TextToSpeech/Qt5TextToSpeechConfig.cmake:26 (message):
#  The imported target "Qt5::TextToSpeech" references the file "/usr/lib/qt5/plugins/texttospeech/libqtexttospeech_speechd.so"

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

