#!/usr/bin/env bash
name='ktextwidgets'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Advanced text editing widgets'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/ktextwidgets-${version}.tar.xz")
depends=(kcompletion sonnet qt5-speech)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('ff9d06b644ec42b7cfadb4edda08d5dd')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

#HATA :CMake Error at /usr/lib64/cmake/Qt5TextToSpeech/Qt5TextToSpeechConfig.cmake:26 (message):
#  The imported target "Qt5::TextToSpeech" references the file "/usr/lib/qt5/plugins/texttospeech/libqtexttospeech_speechd.so"

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON \
		-DDocBookXSL_DIR=/usr/share/xml/docbook/xsl-stylesheets-1.79.2-nons
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

