#!/usr/bin/env bash
name='xcb-util-wm'
release='1'
version='0.4.2'
url='https://example.org'
description='Package xcb-util-wm'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/xcb-util-wm-$version.tar.xz")
depends=()
makedepends=()
md5sums=('581b3a092e3c0c1b4de6416d90b969c3')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

