#!/usr/bin/env bash
name='qt5-webview'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='Provides a way to display web content in a QML application'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtwebview-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-svg qt5-declarative)
makedepends=()
md5sums=('26fadf031fba62001631583744d8cf31')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtwebview-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

