#!/usr/bin/env bash
name='qt6-declarative'
release='4'
version='6.9.1'
url='https://www.qt.io/developers/'
description='Qt6 - QtDeclarative component'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtdeclarative-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(python vulkan-headers qt6-languageserver qt6-shadertools)
sha256sums=('ccb94665df0199d7ee387b965b29677c8b89cfb1782bb6f01239b1d1524cec97')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtdeclarative-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH


setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DINSTALL_PUBLICBINDIR=usr/bin \
		-DCMAKE_INSTALL_PREFIX=/usr
}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}


