#!/usr/bin/env bash
name='qt6-declarative'
release='2'
version='6.7.0'
url='https://www.qt.io/developers/'
description='Qt6 - QtDeclarative component'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtdeclarative-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-shadertools)
makedepends=(python vulkan-headers)
md5sums=('788bc607fd0ccbe2b56623c6b017019b')
sha256sums=('5a0c39579a74d7cca581162c866ed0887287d4f8d5abff7ab9492d4a58fa9e2c')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtdeclarative-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH


setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DINSTALL_PUBLICBINDIR=usr/bin \
		-DCMAKE_INSTALL_PREFIX=/usr
}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}


