#!/usr/bin/env bash
name='qt6-declarative'
release='3'
version='6.8.0'
url='https://www.qt.io/developers/'
description='Qt6 - QtDeclarative component'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtdeclarative-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(python vulkan-headers qt6-languageserver qt6-shadertools)
md5sums=('788bc607fd0ccbe2b56623c6b017019b')
sha256sums=('3b41a36b42e919a3aa0da1f71107591504200f41707bee2ad8e8d4f99b5644c2')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtdeclarative-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH


setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DINSTALL_PUBLICBINDIR=usr/bin \
		-DCMAKE_INSTALL_PREFIX=/usr
}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}


