#!/usr/bin/env bash
name='libnma'
release='1'
version='1.10.6'
url='https:///gitlab.gnome.org/GNOME/libnma'
description='Network Manager gtk client library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/libnma/-/archive/$version/libnma-$version.tar.gz")
depends=(gtk3 networkmanager iso-codes)
makedepends=()
md5sums=('1469b18a2f25991b5a2401fd1c990987')
group=(net.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build  --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dmobile_broadband_provider_info=false
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

