#!/usr/bin/env bash
name='boost'
release='2'
version='1.84.0'
_version='1_84_0'
url='https://www.boost.org/'
description='Free peer-reviewed portable C++ source libraries (development headers)'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('custom')
source=("https://boostorg.jfrog.io/artifactory/main/release/${version}/source/boost_${_version}.tar.bz2")
depends=(icu)
makedepends=(which)
md5sums=('9dcd632441e4da04a461082ebbafd337')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name"_"$_version

prepare(){
	sed -i '/#include.*phoenix.*tuple.hpp.*/d' boost/phoenix/stl.hpp
}

build () {
	./bootstrap.sh --prefix=/usr --with-python=python3
	./b2 stage -j4 threading=multi link=shared
}

package () {
	./b2 --includedir="$DESTDIR"/usr/include \
		--libdir="$DESTDIR"/usr/lib \
		install
}
