#!/usr/bin/env bash
name='unzip'
release='1'
version='6.0'
_version='60'
url='http://infozip.sourceforge.net/UnZip.html'
description='For extracting and viewing files in .zip archives'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('custom')
source=("https://downloads.sourceforge.net/infozip/unzip60.tar.gz" "https://www.linuxfromscratch.org/patches/blfs/svn/unzip-6.0-consolidated_fixes-1.patch")
depends=(bzip2)
makedepends=()
md5sums=('62b490407489521db863b523a7f86375' '14c119ef7019f769497363e5cec306e0')
group=(app.arch)
uses=()
arch=('x86_64')

cd $name$_version

setup(){
    patch -Np1 -i ../unzip-6.0-consolidated_fixes-1.patch
}

build(){
    	make -f unix/Makefile prefix=/usr generic
}

package(){
    make -f unix/Makefile prefix=$DESTDIR/usr install
	install -Dm644 LICENSE "${DESTDIR}/usr/share/licenses/${name}/LICENSE"
}

