#!/usr/bin/env bash
name='inih'
release='1'
version='56'
url='https://github.com/benhoyt/inih'
description='inih (INI not invented here) simple .INI file parser'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/benhoyt/inih/archive/refs/tags/r$version.tar.gz")
depends=()
makedepends=()
md5sums=('e27e394554d9f339b728035a5766d8f3')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-r$version
setup(){
	meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    ninja -C build
}

package(){
   ninja -C build install
}

