#!/usr/bin/env bash
name='libjpeg-turbo'
release='2'
version='3.0.0'
url='https://libjpeg-turbo.org/'
description='MMX, SSE, and SSE2 SIMD accelerated JPEG library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
md5sums=('c84d907ace44d351fcce643c2b9d9492')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
        -DWITH_JPEG8=ON ..
}

build(){
    cd build
    make $jobs
}

package(){
    cd build
    make install $jobs
}

