#!/usr/bin/env bash
name='libjpeg-turbo'
release='1'
version='2.1.4'
url='MMX, SSE, and SSE2 SIMD accelerated JPEG library'
description='https://libjpeg-turbo.org/'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
md5sums=('357dc26a802c34387512a42697846d16')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
        -DWITH_JPEG8=ON ..
}

build(){
    cd build
    make $jobs
}

package(){
    cd build
    make install $jobs
}

