#!/usr/bin/env bash
name='libjpeg-turbo'
release='3'
version='3.1.0'
url='https://libjpeg-turbo.org/'
description='MMX, SSE, and SSE2 SIMD accelerated JPEG library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('35fec2e1ddfb05ecf6d93e50bc57c1e54bc81c16d611ddf6eff73fff266d8285')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
        -DWITH_JPEG8=ON ..
}

build(){
    cd build
    make $jobs
}

package(){
    cd build
    make install $jobs
}

