#!/usr/bin/env bash
name='caribou'
release='2'
version='0.4.21'
url='https://wiki.gnome.org/Projects/Caribou'
_commit="9c900f0139af225bb35bf34bb2aee83f47495ba5"
description='A text entry and UI navigation application (on-screen keyboard)'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://gitlab.gnome.org/Archive/caribou/-/archive/${_commit}/caribou-${_commit}.tar.gz"
        "unicode_to_keyval-symbol-check.patch")
depends=(at-spi2-core py3-pygobject gtk3 libxklavier libgee dconf clutter)
makedepends=(intltool docbook-xsl gobject-introspection vala git gnome-common)
sha256sums=('74cee69ebe3b69f54d1eec0235fcc12d84b9a4de964c75d015eb290f9db815fa' SKIP)
group=(app.accessibility)
uses=()
arch=('x86_64')

cd $name-${_commit}


prepare(){
    : #patch -Np1 -i ../unicode_to_keyval-symbol-check.patch
}

setup () {
    autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--build=$CBUILD \
		--host=$CHOST \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-gtk2-module \
    --disable-schemas-compile
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

