#!/usr/bin/env bash
name='qt5-serialbus'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='Qt module for general purpose serial bus access'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtserialbus-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=()
md5sums=('9c73256f47f6f33c281dd28629de62a4')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtserialbus-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

