#!/usr/bin/env bash
name='gyp'
release='2'
version='20230301'
url='https://salsa.debian.org/python-team/packages/gyp'
description='GYP (Generate Your Projects) meta-build system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://salsa.debian.org/python-team/packages/gyp/-/archive/debian/0.1+20220404git9ecf45e-2/gyp-debian-0.1+20220404git9ecf45e-2.tar.gz')
depends=(py3-six)
makedepends=()
sha256sums=('c7d3f3cc351ec7aa68e1e00ef6ecfe0d9d8ab8c8fa4cbef0b84b3fe8d18a7738')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-debian-0.1+20220404git9ecf45e-2

build(){
    python setup.py build
}

package(){
    python setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

