#!/usr/bin/env bash
name='xhost'
release='1'
version='1.0.9'
url='https://gitlab.freedesktop.org/xorg/app/xhost'
description='X server access control program'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/app/xhost/-/archive/xhost-$version/xhost-xhost-$version.tar.gz")
depends=(libX11)
makedepends=()
md5sums=('39fdb4f4aa2b1e816486d986ac0a9521')
group=(x11.apps)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

