#!/usr/bin/env bash
name='hello'
release='1'
version='2.12'
url='https://ftp.gnu.org/gnu/'
description='Hello world Package'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/hello/hello-${version}.tar.gz")
depends=( )
makedepends=( )
md5sums=('SKIP')
arch=(x86_64)
group=(app.misc)
dontstrip="31"

cd $name-$version

prepare(){
    echo "#!/bin/busybox true" > $HOME/makeinfo
    chmod 755 $HOME/makeinfo
}

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64

    # do not generate po files
    echo -e "%:" > po/Makefile
    echo -e "\t:" >> po/Makefile
}

build(){
    make
}

package(){
    make install
}
