#!/usr/bin/env bash
name='hello'
release='1'
version='2.12'
url='https://example.org'
description='Hello world Package'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/hello/hello-${version}.tar.gz")
depends=( )
makedepends=( )
md5sums=('SKIP')
arch=(x86_64)
group=(app.misc)
dontstrip="1"

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/hello
}

build(){
    make
}

package(){
    make install
    echo "/usr/lib64/hello/" > ${DESTDIR}/etc/ld.so.conf.d/hello.conf
}
