#!/usr/bin/env bash
name='qt5-sensors'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='The Qt Sensors API provides access to sensor hardware via QML and C++'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtsensors-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=(qt5-declarative)
sha256sums=('2a60d62997d7cb88be5145e61e460aeebc18983628e5a9217eec3720ef309a1d')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtsensors-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

