#!/usr/bin/env bash
name='foot'
release='3'
version='1.15.1'
url='https://codeberg.org/dnkl/foot'
description='Fast, lightweight and minimalistic Wayland terminal emulator'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://codeberg.org/dnkl/foot/archive/$version.tar.gz")
depends=(wayland fontconfig ncurses pixman)
makedepends=()
md5sums=('a0fc6e3e0fb1f3b10edb2887779aeae7')
group=(gui.apps)
uses=()
arch=('x86_64')

cd $name

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    rm -f $DESTDIR/usr/share/terminfo/f/foot-direct
    rm -f $DESTDIR/usr/share/terminfo/f/foot
}

