#!/usr/bin/env bash
name='foot'
release='4'
version='1.16.2'
url='https://codeberg.org/dnkl/foot'
description='Fast, lightweight and minimalistic Wayland terminal emulator'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://codeberg.org/dnkl/foot/archive/$version.tar.gz")
depends=(wayland fontconfig ncurses pixman)
makedepends=()
md5sums=('5e19001c74469c4951fbf425b84cdd23')
group=(gui.apps)
uses=()
arch=('x86_64')

cd $name

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    rm -f $DESTDIR/usr/share/terminfo/f/foot-direct
    rm -f $DESTDIR/usr/share/terminfo/f/foot
}

