#!/usr/bin/env bash
name='syndication'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='An RSS/Atom parser library'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/syndication-${version}.tar.xz")
depends=(kcodecs qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('c2a485229d8a430858d7f473fe8b133737d93d33a776e46eedfa77bb9e30ba24')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

