#!/usr/bin/env bash
name='syndication'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='An RSS/Atom parser library'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/syndication-${version}.tar.xz")
depends=(kcodecs qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('cdafc51c9271b00150b8d63bf250d6d040f7bc8c56907af61dc59a44c96c674e')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

