#!/usr/bin/env bash
name='libXtst'
release='1'
version='1.2.4'
url='https://gitlab.freedesktop.org/xorg/lib/libXtst.git/'
description='X.Org Xlib-based client API for the XTEST & RECORD extensions library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXtst-$version.tar.xz")
depends=(libX11 libXext xorgproto libXi)
makedepends=()
md5sums=('02f128fbf809aa9c50d6e54c8e57cb2e')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

