#!/usr/bin/env bash
name='libXaw3d'
release='1'
version='1.6.4'
url='https://gitlab.freedesktop.org/xorg/lib/libXaw3d'
description='X.Org Xaw3d library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXaw3d-$version.tar.gz")
depends=(libX11 libXt libXmu libXext)
makedepends=()
md5sums=('e8dc77463cb2e28e7ed4427cc9698c42')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

