#!/usr/bin/env bash
name='taglib'
release='2'
version='2.0'
url='https://taglib.github.io/'
description='A Library for reading and editing the meta-data of several popular audio formats'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL' 'MPL')
				#https://github.com/taglib/taglib/archive/refs/tags/v2.0.tar.gz
source=("https://taglib.github.io/releases/taglib-${version}.tar.gz")
depends=(zlib)
makedepends=(cmake utf8cpp)
md5sums=('1826bf7e8486246a23fd98579f666413')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DWITH_ZLIB=ON \
		-DBUILD_SHARED_LIBS=ON \
		-DBUILD_EXAMPLES=ON \
		-DVISIBILITY_HIDDEN=ON \
		-DCMAKE_CXX_FLAGS="$CXXFLAGS -DNDEBUG"
}

build () {
	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

