#!/usr/bin/env bash
name='libproxy'
release='2'
version='0.5.3'
url='https://libproxy.github.io/libproxy'
description='Automatic proxy configuration management library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
#source=("https://github.com/libproxy/libproxy/releases/download/${version}/libproxy-${version}.tar.xz")
source=("https://github.com/libproxy/libproxy/archive/refs/tags/${version}.tar.gz")
depends=(curl duktape glib)
makedepends=()
md5sums=('bc744f1f6bb0569bcb0e4c7eb9c920f7')
group=(net.libs)
uses=()
arch=('x86_64')

cd $name-$version


setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
