#!/sbin/openrc-run

name="xinit"
description="X11 autologin service"
supervisor="supervise-daemon"
pidfile="/var/run/xinit.pid"
command="/etc/X11/xinit/xserverrc"
command_args=":0"

start_pre(){
    while sleep 0.3 ; do
        if env DISPLAY=:0 xterm -bg "#000000" -e true 2>/dev/null ; then
            su - "$USER" -c "env DISPLAY=:0 /etc/X11/xinit/xinitrc"
        fi
    done &
}

depend()
{
        need dbus
        provide gui display-manager getty
}

