#!/usr/bin/env bash
name='kfind'
release='5'
version='25.08.1'
url='https://www.kde.org/applications/utilities/kfind'
description='Find Files/Folders'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/release-service/${version}/src/kfind-${version}.tar.xz")
depends=(karchive kcompletion kconfig kconfigwidgets kcoreaddons kfilemetadata ki18n kio kwidgetsaddons
         kxmlgui qt6-5compat qt6-base)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('06155b309fba75dcd373a86bd5f89f08425455168470c7f69b62f09f05c5a4e1')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QCH=ON \
		-DBUILD_TESTING=OFF
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}
