#!/usr/bin/env bash
name='kfind'
release='4'
version='24.08.2'
url='https://www.kde.org/applications/utilities/kfind'
description='Find Files/Folders'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/release-service/${version}/src/kfind-${version}.tar.xz")
depends=(karchive kcompletion kconfig kconfigwidgets kcoreaddons kfilemetadata ki18n kio kwidgetsaddons
         kxmlgui qt6-5compat qt6-base)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('9206728400c3edde21a3bc3db04f7f7325588fd6ad3c78de3b105e3fa3f54445')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QCH=ON \
		-DBUILD_TESTING=OFF
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}
