#!/usr/bin/env bash
name='py3-packaging'
release='3'
version='24.0'
url='https://pypi.org/project/packaging'
description='Core utilities for Python3 packages'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('Apache-2.0 AND BSD-2-Clause')
source=("https://github.com/pypa/packaging/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer)
sha256sums=('1bf35cf2c2be982f2ae6c905760ae19cb744fadbf56269f2e54f7bdcef64d291')
group=(dev.python)
uses=()
arch=('x86_64')

cd "packaging"-$version

export PYTHONPATH=src/packaging

build(){
    python -m build -nw
}

package(){
#    mkdir -p $DESTDIR/usr/lib64/python3
#    cp -prfv src/* $DESTDIR/usr/lib64/python3
    python -m installer --destdir="$DESTDIR" dist/*.whl
}

