#!/usr/bin/env bash
name='py3-packaging'
release='2'
version='23.2'
url='https://pypi.org/project/packaging'
description='Core utilities for Python3 packages'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('Apache-2.0 AND BSD-2-Clause')
source=("https://github.com/pypa/packaging/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-parsing)
md5sums=('0f7bc51196160ee850df25ff7f0f603a')
group=(dev.python)
uses=()
arch=('x86_64')

cd "packaging"-$version

export PYTHONPATH=src/packaging

build(){
    python -m build -nw
}

package(){
#    mkdir -p $DESTDIR/usr/lib64/python3
#    cp -prfv src/* $DESTDIR/usr/lib64/python3
    python -m installer --destdir="$DESTDIR" dist/*.whl
}

