#!/usr/bin/env bash
name='py3-packaging'
release='1'
version='23.1'
url='https://pypi.org/project/packaging'
description='Core utilities for Python3 packages'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('Apache-2.0 AND BSD-2-Clause')
source=("https://github.com/pypa/packaging/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-parsing)
md5sums=('c43924bf15188607e7789c0db2955fdc')
group=(dev.python)
uses=()
arch=('x86_64')

cd "packaging"-$version

build(){
    python -m build -nw
}

package(){
    python -m installer --destdir="$DESTDIR" dist/*.whl
}

