#!/usr/bin/env bash
name='libdbusmenu'
release='1'
version='16.04.0'
url='https://launchpad.net/libdbusmenu'
description='Library to pass menu structure across DBus'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://launchpad.net/libdbusmenu/16.04/$version/+download/libdbusmenu-$version.tar.gz")
depends=(gtk3)
makedepends=(intltool)
md5sums=('3c05d53053b3ea69384b5f93d7a4c7c4')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version
export CFLAGS="$CFLAGS -Wno-error"


setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --with-gtk=3 \
        --disable-dumper
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

