#!/usr/bin/env bash
name='libxss'
release='2'
version='1.2.4'
url='https://gitlab.freedesktop.org/xorg/lib/libxscrnsaver'
description='X11 Screen Saver extension library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://salsa.debian.org/xorg-team/lib/libxss/-/archive/libxss-${version}/libxss-#libxss-${version}.tar.gz")
source=("https://xorg.freedesktop.org/releases/individual/lib/libXScrnSaver-${version}.tar.xz")
depends=(libXext util-macros xorgproto)
makedepends=()
md5sums=('e613751d38e13aa0d0fd8e0149cec057')
group=(x11.libs)
uses=()
arch=('x86_64')

cd "libXScrnSaver"-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

