#!/usr/bin/env bash
name='qt6-websockets'
release='2'
version='6.7.0'
url='https://www.qt.io/'
description='Provides WebSocket communication compliant with RFC 6455'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtwebsockets-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(cmake)
sha256sums=('5ffc77da6b36cdf18e04c975a0fbf243968806a93a6291bcd2e9cd0b26139736')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtwebsockets-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}