#!/usr/bin/env bash
name='tar'
release='2'
version='1.35'
url='https://ftp.gnu.org/gnu/tar/'
description='Utility used to store, backup, and transport files'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/tar/tar-$version.tar.xz")
depends=(acl attr)
makedepends=()
md5sums=('a2d8042658cfd8ea939e6d911eaf4152')
uses=()
group=(app.arch)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

