#!/usr/bin/env bash
name='kmenuedit'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description='KDE menu editor'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kmenuedit-${version}.tar.xz")
depends=(kio)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('fa6a09e8fec343680d58d47daedf0d58267f8b990f12e2c50aa72babc963ac5f')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

