#!/usr/bin/env bash
name='kmenuedit'
release='3'
version='6.1.5'
url='https://kde.org/plasma-desktop'
description='KDE menu editor'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kmenuedit-${version}.tar.xz")
depends=(kio)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('fcb27a83a5554fb5654633bed08cb608986572e30f5e4241607a354ec89d6556')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

