#!/usr/bin/env bash
name='kmenuedit'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='KDE menu editor'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kmenuedit-${version}.tar.xz")
depends=(kio)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('2162efd754128fb0674a06506f38b24fe984595bdb928a9fa700e6a06f040ff7')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

