#!/usr/bin/env bash
name='clutter'
release='1'
version='1.26.4'
url='https://blogs.gnome.org/clutter/'
description='A toolkit for creating fast, portable, compelling dynamic UIs'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.gnome.org/sources/clutter/${version%.*}/clutter-${version}.tar.xz")
depends=(gtk3 libinput cogl)
makedepends=(gobject-introspection gtk-doc)
md5sums=('624dd776a5159de0267587b1df6b97b2')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--build=$CBUILD \
		--host=$CHOST \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--localstatedir=/var \
		--with-x \
		--enable-gdk-backend \
		--enable-egl-backend \
		--enable-wayland-backend \
		--enable-x11-backend \
		--enable-evdev-input
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

