#!/usr/bin/env bash
name='thunar-archive-plugin'
release='2'
version='0.5.2'
_version='0.5'
url='https://docs.xfce.org/xfce/thunar/archive'
description='Adds archive operations to the Thunar file context menus'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/thunar-plugins/thunar-archive-plugin/${_version}/thunar-archive-plugin-${version}.tar.bz2")
depends=(thunar)
makedepends=(intltool)
sha256sums=('6379f877bcfc0ea85db9f43723b6fb317893050c712bd03c2ae3232fb9d5ade3')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--libexecdir=/usr/libexec \
		--localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

