#!/usr/bin/env bash
name='thunar-archive-plugin'
release='3'
version='0.5.3'
_version='0.5'
url='https://docs.xfce.org/xfce/thunar/archive'
description='Adds archive operations to the Thunar file context menus'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/thunar-plugins/thunar-archive-plugin/${_version}/thunar-archive-plugin-${version}.tar.bz2")
depends=(thunar)
makedepends=(intltool)
sha256sums=('cc0ffc86dc48e72edc6f6a61ad4345f99018526d5d854360960759ce1ec2ca22')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--libexecdir=/usr/libexec \
		--localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

