#!/usr/bin/env bash
name='gobject-introspection'
release='2'
version='1.76.1'
url='https://gitlab.gnome.org/GNOME/gobject-introspection.git/'
description='Introspection system for GObject-based libraries '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gobject-introspection/-/archive/${version}/gobject-introspection-${version}.tar.gz")
depends=()
makedepends=()
md5sums=('746611b169fb9fe3c05e5f4bf254b0c6')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

