#!/usr/bin/env bash
name='gobject-introspection'
release='3'
version='1.78.0'
url='https://gitlab.gnome.org/GNOME/gobject-introspection.git/'
description='Introspection system for GObject-based libraries '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gobject-introspection/-/archive/${version}/gobject-introspection-${version}.tar.gz")
depends=()
makedepends=()
md5sums=('6d7bff4172389d66637f5b47b37c13f1')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    unset meson
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        --wrap-mode=nodownload
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

