#!/usr/bin/env bash
name='py3-six'
release='1'
version='1.16.0'
url='https://github.com/benjaminp/six'
description='Python 2 and 3 compatibility library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/benjaminp/six/archive/refs/tags/$version.tar.gz")
depends=(python)
makedepends=()
sha256sums=('af6745f78dceb1ad5107dc6c2d3646c8cb57cf4668ba7b5427145a71a690f60e')
group=(dev.python)
uses=()
arch=('x86_64')

cd six-$version

build(){
    python setup.py build
}

package(){
    python setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build

}

