#!/usr/bin/env bash
name='qt5-tools'
release='2'
version='5.15.14'
url='https://download.qt.io/official_releases/qt/'
description='A cross-platform application and UI framework'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.qt.io/official_releases/qt/5.15/$version/submodules/qttools-everywhere-opensource-src-$version.tar.xz")
depends=(qt5-base)
makedepends=(vulkan-headers)
sha256sums=('12061a85baf5f4de8fbc795e1d3872b706f340211b9e70962caeffc6f5e89563')
group=(dev.qt)
uses=()
arch=('x86_64')

cd qttools-everywhere-src-$version

export PATH=/usr/bin/qt5:$PATH

setup () {
    qmake
}

build () {
    make $jobs
}

package () {
    make install INSTALL_ROOT=$DESTDIR $jobs
}

