#!/usr/bin/env bash
name='py3-tomli-w'
release='2'
version='1.2.0'
url='https://github.com/hukkin/tomli-w'
description="Lil' TOML writer"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/hukkin/tomli-w/archive/refs/tags/${version}.zip")
depends=()
makedepends=()
sha256sums=('ea8a98d2f854b193607012c80bec65b490f749a6ae9ed2b105332e67dc8ac6f1')
group=(dev.python)
uses=()
arch=('x86_64')

cd "tomli-w"-$version

build(){
     python -m build --wheel
}

package(){
    python -m installer --destdir="${DESTDIR}" dist/*.whl
  install -Dm 644 LICENSE -t "${DESTDIR}"/usr/share/licenses/python-tomli-w/
  mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}

