#!/usr/bin/env bash
name='gcr'
release='1'
version='3.41.1'
url='https://download.gnome.org/sources/gc'
description='Libraries for cryptographic UIs and accessing PKCS#11 modules'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.gnome.org/sources/gcr/3.41/gcr-$version.tar.xz")
depends=(gnupg openssh p11-kit libsecret gtk3)
makedepends=()
md5sums=('c1e98af977236255006e11e8f8cfbaca')
group=(app.crypt)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
       -Dsystemd=disabled
}

build(){
    ninja -C build  $jobs
}

package(){
    ninja -C build  install $jobs
}

