#!/usr/bin/env bash
name='xfce4-dev-tools'
release='2'
version='4.18.1'
_version='4.18'
url='https://www.xfce.org/'
description='Xfce developer tools'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("http://archive.xfce.org/src/xfce/xfce4-dev-tools/${_version}/xfce4-dev-tools-${version}.tar.bz2")
depends=(glib gtk-doc)
makedepends=(intltool)
sha256sums=('812cabe7048922ebc176564b73c3e427e467c9566365ee3e54c0487d305a7681')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug 
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

