#!/usr/bin/env bash
name='xfce4-dev-tools'
release='3'
version='4.20.0'
_version='4.20'
url='https://www.xfce.org/'
description='Xfce developer tools'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("http://archive.xfce.org/src/xfce/xfce4-dev-tools/${_version}/xfce4-dev-tools-${version}.tar.bz2")
depends=(glib gtk-doc)
makedepends=(intltool)
sha256sums=('1fba39a08a0ecc771eaa3a3b6e4272a4f0b9e7c67d0f66e780cd6090cd4466aa')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

