#!/usr/bin/env bash
name='libpng'
release='1'
version='1.6.39'
url='http://www.libpng.org/'
description='Portable Network Graphics library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://salsa.debian.org/debian/libpng1.6/-/archive/debian/$version-2/libpng1.6-debian-$version-2.tar.gz")
depends=(zlib)
makedepends=()
md5sums=('f57191ff3cc3321b3733d71d00dfeaca')
group=(media.libs)
uses=()
arch=('x86_64')

cd ${name}1.6-debian-$version-2

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

