#!/usr/bin/env bash
name='libpng'
release='1'
version='1.6.39'
url='http://www.libpng.org/'
description='Portable Network Graphics library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://sourceforge.net/projects/libpng/files/latest/download')
depends=()
makedepends=()
md5sums=('aa1ae92e172417039bda072b702f6326')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

