#!/usr/bin/env bash
name='ppp'
release='2'
version='2.5.0'
url='https://download.samba.org/pub/ppp'
description='A daemon which implements the Point-to-Point Protocol for dial-up networking'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.samba.org/pub/ppp/ppp-$version.tar.gz" 
	"pppd.initd")
depends=(libpcap openssl dbus libxcrypt)
makedepends=()
md5sums=('ce5fd7b9f6e1095ae6c0c11365c444eb' 'SKIP')
group=(net.dialup)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--disable-systemd
}

build(){
    make $jobs
}

package(){
    make DESTDIR="$DESTDIR" install $jobs
	install -D -m755 "../pppd.initd" $DESTDIR"/etc/init.d/pppd"
}
