#!/usr/bin/env bash
name='ppp'
release='2'
version='2.5.0'
url='https://download.samba.org/pub/ppp'
description='A daemon which implements the Point-to-Point Protocol for dial-up networking'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.samba.org/pub/ppp/ppp-$version.tar.gz")
depends=(libpcap openssl dbus libxcrypt)
makedepends=()
md5sums=('ce5fd7b9f6e1095ae6c0c11365c444eb')
group=(net.dialup)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install INSTROOT="$DESTDIR" DESTDIR="$DESTDIR/usr" $jobs
}

