#!/usr/bin/env bash
name='dotconf'
release='1'
version='1.3'
url='https://example.org'
description='A C library for parsing configuration files'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://github.com/williamh/dotconf/archive/refs/tags/v${version}.tar.gz")
depends=()
makedepends=()
md5sums=('b3ba921e45b05e89bf69835c0f30bc14')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ 
}

build () {
    make $jobs
}

package () {
    make DESTDIR="${DESTDIR}" install $jobs
}

