#!/usr/bin/env bash
name='psautohint'
release='1'
version='2.4.0'
url='https://github.com/adobe-type-tools/psautohint'
description='ASCII quote-dot-dash to HTML entity converter'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/adobe-type-tools/psautohint/archive/refs/tags/v$version.tar.gz")
depends=(python)
makedepends=()
md5sums=('8cf07baebbc5fc631b01e977209b162e')
group=(dev.python)
uses=()
arch=('x86_64')

cd $name-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
