#!/usr/bin/env bash
name='file'
release='3'
version='5.45'
url='https://www.darwinsys.com/file/'
description="Identify a file's format by scanning binary data for patterns"
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
source=("http://ftp.astron.com/pub/file/file-${version}.tar.gz")
md5sums=('26b2a96d4e3a8938827a1e572afd527a')
group=(sys.apps)

uses=(bzip2 lzma zlib seccomp)

zlib_depends=(zlib)
lzma_depends=(xz-utils)
bzip2_depends=(bzip2)
seccomp_depends=(libseccomp)
arch=(x86_64)

cd $name-$version

setup(){
    opts=(
    	--prefix=/usr
        --libdir=/usr/lib64
        --enable-static
        --enable-elf
        --enable-elf-core
    )
    ./configure ${opts[@]} \
	$(use_opt zlib --enable-zlib --disable-zlib) \
	$(use_opt lzma --enable-xzlib --disable-xzlib) \
	$(use_opt bzip2 --enable-bzlib --disable-bzlib) \
	$(use_opt seccomp --enable-libseccomp --disable-libseccomp)
}

build(){
    make $jobs
}

package(){
    make install $jobs
}
