#!/usr/bin/env bash
name='xdg-desktop-portal-gtk'
release='2'
version='1.15.1'
url='https://github.com/flatpak/xdg-desktop-portal-gtk'
description='A backend implementation for xdg-desktop-portal using GTK'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/flatpak/xdg-desktop-portal-gtk/archive/refs/tags/$version.tar.gz")
depends=(gsettings-desktop-schemas gtk3 xdg-desktop-portal)
makedepends=()
md5sums=('a2a161c5e4e48442b61ee9c7bed18b40')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Db_lto=true \
		-Dappchooser=enabled \
		-Ddatarootdir=/usr/lib/pkgconfig \
		-Ddbus-service-dir=/usr/share/dbus-1/services/ \
		-Dlockdown=enabled \
		-Dsettings=enabled \
		-Dwallpaper=disabled
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
