#!/usr/bin/env bash
name='glib-networking'
release='2'
version='2.76.0'
url='https://gitlab.gnome.org/GNOME/glib-networking.git/'
description='Network-related giomodules for glib '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/glib-networking/-/archive/$version/glib-networking-$version.tar.gz")
depends=(gsettings-desktop-schemas)
makedepends=(gnutls)
md5sums=('5b2fbc674ac207a8810cdd312aa0021d')
group=(net.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
	-Dlibproxy=disabled \
	-Dinstalled_tests=false
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

