#!/usr/bin/env bash
name='libXext'
release='1'
version='1.3.5'
url='https://gitlab.freedesktop.org/xorg/lib/libXext.git/'
description='X.Org Xext library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXext-$version.tar.xz")
depends=(libX11 xorgproto)
makedepends=()
md5sums=('964942427fcc5a9fa0539661421857c8')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

