#!/usr/bin/env bash
name='orc'
release='2'
version='0.4.40'
url='https://gitlab.freedesktop.org/gstreamer/'
description='Optimized Inner Loop Runtime Compiler'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/gstreamer/orc/-/archive/$version/orc-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('272aea9badb58d9b01a5d882405e0832a884a1e9bc7f51fad1e77bd7d5205cce')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
    --libdir=/usr/lib64 \
		-Dgtk_doc=disabled
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}
