#!/usr/bin/env bash
name='ksshaskpass'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='ssh-add helper that uses kwallet and kpassworddialog'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/ksshaskpass-${version}.tar.xz")
depends=(kwallet)
makedepends=(extra-cmake-modules kdoctools)
md5sums=('91d2157906d3b877339bd89bb59c2fe5')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

