#!/usr/bin/env bash
name='qt6-5compat'
release='3'
version='6.8.0'
url='https://www.qt.io'
description='Module that contains unsupported Qt 5 APIs'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qt5compat-everywhere-src-${version}.tar.xz")
depends=(icu qt6-base qt6-shadertools)
makedepends=(ninja qt6-declarative)
sha256sums=('3c9b05fdd70b6bd6ec152e6b43f2a5f4c7b31c9eb342d62fa8450d63f5835e30')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qt5compat-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
