#!/usr/bin/env bash
name='qt6-5compat'
release='1'
version='6.7.0'
url='https://www.qt.io'
description='Module that contains unsupported Qt 5 APIs'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qt5compat-everywhere-src-${version}.tar.xz")
depends=(icu qt6-base qt6-shadertools)
makedepends=(ninja qt6-declarative)
sha256sums=('9d49d4fd8345d8a40b63e0b65cd49c1d8286e33a7f1409bf1316763f654e19f5')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qt5compat-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
