#!/usr/bin/env bash
name='kwayland'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Qt-style Client and Server library wrapper for the Wayland libraries'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kwayland-${version}.tar.xz")
depends=(qt5-wayland wayland)
makedepends=(extra-cmake-modules doxygen qt5-tools wayland-protocols plasma-wayland-protocols)
md5sums=('ee78d5b3a947df75ecb663b5c621b1f4')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
