#!/usr/bin/env bash
name='itstool'
release='1'
version='2.0.7'
url='https://github.com/itstool/itstool'
description=' Translation tool for XML documents that uses gettext files and ITS rules '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/itstool/itstool/archive/refs/tags/$version.tar.gz")
depends=(libxml2)
makedepends=()
md5sums=('e759b258617a912acce630de3fa43957')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

