#!/usr/bin/env bash
name='tumbler'
release='2'
version='4.18.2'
_version='4.18'
url='https://docs.xfce.org/xfce/tumbler/start'
description='Thumbnail service implementing the thumbnail management D-Bus specification'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2' 'LGPL')
source=("https://archive.xfce.org/src/xfce/tumbler/${_version}/tumbler-${version}.tar.bz2")
depends=(glib  gdk-pixbuf libxfce4util)
makedepends=(intltool)
sha256sums=('b530eec635eac7f898c0d8d3a3ff79d76a145d3bed3e786d54b1ec058132be7a')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--disable-debug 
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}
