#!/usr/bin/env bash
name='tumbler'
release='3'
version='4.20.0'
_version='4.20'
url='https://docs.xfce.org/xfce/tumbler/start'
description='Thumbnail service implementing the thumbnail management D-Bus specification'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2' 'LGPL')
source=("https://archive.xfce.org/src/xfce/tumbler/${_version}/tumbler-${version}.tar.bz2")
depends=(glib  gdk-pixbuf libxfce4util)
makedepends=(intltool)
sha256sums=('74b1647d55926547e98bfac70838ff63c5a84299a5e10c81c38d1fab90e25880')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}
