#!/usr/bin/env bash
name='tumbler'
release='1'
version='4.18.1'
_version='4.18'
url='https://docs.xfce.org/xfce/tumbler/start'
description='Thumbnail service implementing the thumbnail management D-Bus specification'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2' 'LGPL')
source=("https://archive.xfce.org/src/xfce/tumbler/${_version}/tumbler-${version}.tar.bz2")
depends=(glib  gdk-pixbuf libxfce4util)
makedepends=(intltool)
md5sums=('e66ff221ea5cd19c84ce80abca033f52')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--disable-debug 
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}
