#!/usr/bin/env bash
name='rustup'
release='1'
version='1.28.2'
url='https://www.rust-lang.org/'
description='Rust compiler downlaoader'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=('https://sh.rustup.rs')
depends=()
makedepends=()
sha256sums=('17247e4bcacf6027ec2e11c79a72c494c9af69ac8d1abcc1b271fa4375a106c2')
group=(dev.lang)
uses=()
arch=('x86_64')

package () {
    mkdir -p $DESTDIR/etc/profile.d/
    mkdir -p $DESTDIR/usr/bin
    install sh.rustup.rs $DESTDIR/usr/bin/rustup-init
    ln -s rustup-init $DESTDIR/usr/bin/rustup
    echo "export RUSTUP_HOME=/usr/lib64/rust" > $DESTDIR/etc/profile.d/rust.sh
    echo "export PATH=\$PATH:/usr/lib64/rust/toolchains/stable-$(uname -m)-unknown-linux-gnu/bin" >> $DESTDIR/etc/profile.d/rust.sh

}

