#!/usr/bin/env bash
name='freetds'
release='1'
version='1.4.2'
url='https://www.freetds.org'
description='Tabular Datastream Library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://www.freetds.org/files/stable/freetds-${version}.tar.bz2")
depends=(openssl linux-headers readline unixodbc)
makedepends=()
md5sums=('285b620219e3ae0e416c2410536f2ecc')
group=(dev.db)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install 
}

