#!/usr/bin/env bash
name='libcap'
release='3'
version='2.73'
url='https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/'
description='POSIX 1003.1e capabilities'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://mirrors.edge.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-$version.tar.xz")
depends=()
makedepends=( )
sha256sums=('6405f6089cf4cdd8c271540cd990654d78dd0b1989b2d9bda20f933a75a795a5')
uses=()
uses_extra=(pam)
pam_depends=(pam)
group=(sys.libs)
arch=('x86_64')

cd $name-$version

cap_opts=(
    SUDO=""
    prefix=/usr
    KERNEL_HEADERS=/usr/include
    lib=lib64
    RAISE_SETFCAP=no
    $(use_opt pam PAM_CAP=yes PAM_CAP=no)
)

build(){
    make ${cap_opts[@]} DYNAMIC=yes
    make ${cap_opts[@]} DYNAMIC=no
}

package(){
    make ${cap_opts[@]} install DYNAMIC=yes
    make ${cap_opts[@]} install DYNAMIC=no

}

