#!/usr/bin/env bash
name='py3-installer'
release='2'
version='0.7.0'
url='https://github.com/pypa/installer/'
description='Easily download, build, install, upgrade, and uninstall Python packages'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pypa/installer/archive/refs/tags/$version.tar.gz")
depends=(python py3-build)
makedepends=( )
sha256sums=('e1589201863a6b6f570ce2f9994febe54a8d9196e0cc54fd331cd7ffd728fb86')
uses=()
group=(dev.python)
arch=('x86_64')

cd installer-$version

package(){
    mkdir -p $DESTDIR/usr/lib64/python3/installer
    cp -prfv src/installer/* $DESTDIR/usr/lib64/python3/installer
}

