#!/usr/bin/env bash
name='dbus'
release='1'
version='1.15.2'
url='https://dbus.freedesktop.org/releases/dbus/'
description='A message bus system, a simple way for applications to talk to each other'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://dbus.freedesktop.org/releases/dbus/dbus-$version.tar.xz"
        "dbus.sysconf"
        "dbus.initd"
        "dbus.confd"
        "dbus.xinit")
depends=(audit expat libcap-ng)
makedepends=()
md5sums=('c56de960ea9031b92ee71aaa0e8e72c2'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP')
group=(sys.apps)
uses=(x11)
x11_depends=(libX11)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --localstatedir=/var \
        --sysconfdir=/etc \
        --with-system-pid-file=/run/dbus/dbus.pid \
        $(use_opt x11 --with-x --without-x)
}

build(){
    make $jobs
}

package(){
    make $jobs install
    mkdir -p "$DESTDIR"/etc/{passwd,group,sysconf,init,conf}.d "$DESTDIR"/etc/X11/xinit/xinitrc.d/
    echo "messagebus:x:109:" > "$DESTDIR"/etc/group.d/dbus
    echo "messagebus:x:103:109::/nonexistent:/usr/sbin/nologin" > "$DESTDIR"/etc/passwd.d/dbus
    install ../dbus.sysconf "$DESTDIR"/etc/sysconf.d/dbus
    install ../dbus.initd "$DESTDIR"/etc/init.d/dbus
    install ../dbus.confd "$DESTDIR"/etc/conf.d/dbus
    install ../dbus.xinit "$DESTDIR"/etc/X11/xinit/xinitrc.d/30-dbus-launch.sh
}

