#!/usr/bin/env bash
name='dbus'
release='2'
version='1.15.10'
url='https://dbus.freedesktop.org/releases/dbus/'
description='A message bus system, a simple way for applications to talk to each other'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://dbus.freedesktop.org/releases/dbus/dbus-$version.tar.xz"
        "dbus.sysconf"
        "dbus.initd"
        "dbus.confd"
        "dbus.xinit")
depends=(audit expat libcap-ng elogind)
makedepends=()
sha256sums=('f700f2f1d0473f11e52f3f3e179f577f31b85419f9ae1972af8c3db0bcfde178'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP')
group=(sys.apps)
uses=(x11)
x11_depends=(libX11)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        --localstatedir=/var \
        --sysconfdir=/etc \
        -Dxml_docs=disabled \
        -Dsystem_pid_file=/run/dbus/dbus.pid \
        -Dx11_autolaunch=$(use_opt x11 enabled disabled)
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
    mkdir -p "$DESTDIR"/etc/{passwd,group,sysconf,init,conf}.d "$DESTDIR"/etc/X11/xinit/xinitrc.d/
    # GID: messagebus 103
    echo "messagebus:x:103:" > "$DESTDIR"/etc/group.d/dbus
    echo "messagebus:x:103:103::/nonexistent:/usr/sbin/nologin" > "$DESTDIR"/etc/passwd.d/dbus
    install ../dbus.sysconf "$DESTDIR"/etc/sysconf.d/dbus
    install ../dbus.initd "$DESTDIR"/etc/init.d/dbus
    install ../dbus.confd "$DESTDIR"/etc/conf.d/dbus
    install ../dbus.xinit "$DESTDIR"/etc/X11/xinit/xinitrc.d/30-dbus-launch.sh
}

