#!/usr/bin/env bash
name='xtrans'
release='1'
version='1.4.0'
url='https://gitlab.freedesktop.org/xorg/lib/libxtrans.git/'
description='X.Org xtrans library'
email='bayramk@gmail.com'
maintainer='bayramkarahan'
license=('GPLv3')
source=("https://www.x.org/archive//individual/lib/xtrans-$version.tar.gz")
depends=(xtrans)
makedepends=()
md5sums=('0d8fe8de9eb7e733711835d139f906dc')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

