#!/usr/bin/env bash
name='vulkan-headers'
release='2'
version='1.3.269'
url='https://github.com/KhronosGroup/Vulkan-Headers'
description='Vulkan Header files and API registry'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
md5sums=('0814001914deccaa65fd42188ab12db2')
group=(dev.util)
uses=()
arch=('x86_64')

cd Vulkan-Headers-$version

setup(){
    mkdir build && cd build
    cmake .. \
      -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    make -C build $jobs
}

package(){
    make -C build install $jobs
}

