#!/usr/bin/env bash
name='vulkan-headers'
release='3'
version='1.3.295'
url='https://github.com/KhronosGroup/Vulkan-Headers'
description='Vulkan Header files and API registry'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
sha256sums=('b4568b984be4b8a317343cc14d854669e258705079a16cabef3fb92302f55561')
group=(dev.util)
uses=()
arch=('x86_64')

cd Vulkan-Headers-$version

setup(){
    mkdir build && cd build
    cmake .. \
      -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    make -C build $jobs
}

package(){
    make -C build install $jobs
}

