#!/usr/bin/env bash
name='vulkan-headers'
release='1'
version='1.3.239'
url='https://github.com/KhronosGroup/Vulkan-Headers'
description='Vulkan Header files and API registry'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
md5sums=('a345e779c8003024314de96a3819877b')
group=(dev.util)
uses=()
arch=('x86_64')

cd Vulkan-Headers-$version

setup(){
    mkdir build && cd build
    cmake .. \
      -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    make -C build -j`nproc`
}

package(){
    make -C build install -j`nproc`
}

