#!/usr/bin/env bash
name='cinnamon-menus'
release='2'
version='6.0.0'
url='https://github.com/linuxmint/cinnamon'
description='Linux desktop which provides advanced innovative features and a traditional user experience'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://github.com/linuxmint/cinnamon-menus/archive/refs/tags/${version}.tar.gz")
depends=(glib)
makedepends=(gobject-introspection meson)
md5sums=('9e10b0e9839e83e3b1264366c565340b')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
 		--libdir=/usr/lib64/ 
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=$DESTDIR ninja -C build install $jobs
}

