#!/usr/bin/env bash
name='cinnamon-menus'
release='4'
version='6.4.0'
url='https://github.com/linuxmint/cinnamon'
description='Linux desktop which provides advanced innovative features and a traditional user experience'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://github.com/linuxmint/cinnamon-menus/archive/refs/tags/${version}.tar.gz")
depends=(glib)
makedepends=(gobject-introspection meson)
sha256sums=('9cad5ac61900492f66c91810fd13bed9dc37b49ec0b9bbc0bbe9ebf48ee45452')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
 		--libdir=/usr/lib64/ 
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=$DESTDIR ninja -C build install $jobs
}

