#!/usr/bin/env bash
name='tmux'
release='2'
version='3.4'
url='https://github.com/tmux/tmux'
description='Teminal multiplexer'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/tmux/tmux/releases/download/$version/tmux-$version.tar.gz")
depends=(ncurses libevent)
makedepends=()
sha256sums=('551ab8dea0bf505c0ad6b7bb35ef567cdde0ccb84357df142c254f35a23e19aa')
group=(app.misc)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./configure --prefix=/usr \
 --libdir=/usr/lib64/
}

build () {
    make $jobs
}

package () {
    make install $jobs
}

