#!/usr/bin/env bash
name='xorg-xwayland'
release='3'
version='24.1.2'
url='https://xorg.freedesktop.org/archive/individual/xserver/'
description='Standalone X server running under Wayland'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://xorg.freedesktop.org/archive/individual/xserver/xwayland-$version.tar.xz")
depends=(wayland libdrm libepoxy libglvnd libXau libxcvt mesa nettle pixman libxkbfile libXfont2 libfontenc)
makedepends=()
sha256sums=('141eb76e7e422a3661c08782c70be40931084755042c04506e0d97dd463ef7d2')
group=(x11.base)
uses=()
arch=('x86_64')

cd xwayland-$version

setup () {
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -D ipv6=true \
        -D xvfb=true \
        -D xdmcp=false \
        -D xcsecurity=true \
        -D dri3=true \
        -D glamor=true \
        -D xkb_dir=/usr/share/X11/xkb \
        -D xkb_output_dir=/var/lib/xkb

}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
    # this files provided by xorg-server
    rm $DESTDIR/usr/lib64/xorg/protocol.txt
    rm $DESTDIR/usr/share/man/man1/Xserver.1
}

