#!/usr/bin/env bash
name='xf86-input-wacom'
release='2'
version='1.2.0'
url='https://github.com/linuxwacom/xf86-input-wacom'
description='Driver for Wacom tablets and drawing devices'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/linuxwacom/xf86-input-wacom/archive/refs/tags/xf86-input-wacom-$version.tar.gz")
depends=(libXi libXinerama)
makedepends=()
md5sums=('c954f33cf1f781943f9cff0fa327354a')
group=(x11.drivers)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install
}

