#!/usr/bin/env bash
name='flatpak'
release='3'
version='1.16.0'
url='https://github.com/flatpak/flatpak'
description='Linux application sandboxing and distribution framework'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://salsa.debian.org/debian/flatpak/-/archive/debian/$version-1/flatpak-debian-$version-1.tar.gz")
depends=(ostree desktop-file-utils shared-mime-info curl libX11 json-glib appstream py3-parsing libseccomp)
makedepends=()
sha256sums=('c5f32fa8d837ec1100cdc55410db4fef6d25ffca085662ce843dbf1f30638676')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-debian-$version-1

unset meson
setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sysconfdir=/etc \
        -Dsystem_helper=disabled \
        -Dsystemd=disabled \
        -Dsystem_install_dir=/data/flatpak \
        -Dmalcontent=disabled \
        -Dlibzstd=disabled \
        -Dtests=false
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

