#!/usr/bin/env bash
name='qt6-shadertools'
release='4'
version='6.9.1'
url='https://www.qt.io/'
description='Package description missing'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtshadertools-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(cmake perl)
sha256sums=('4e1ed24cce0887fb4b6c7be4f150239853a29c330c9717f6bacfb6376f3b4b74')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtshadertools-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr
}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}