#!/usr/bin/env bash
name='qt6-shadertools'
release='3'
version='6.8.0'
url='https://www.qt.io/'
description='Package description missing'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtshadertools-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(cmake perl)
sha256sums=('44692dc93482374bf3b39e96c881fa08275f0bf82958b68a7e3c796b76d4c4cb')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtshadertools-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr
}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}