#!/usr/bin/env bash
name='qt6-imageformats'
release='3'
version='6.8.0'
url='https://www.qt.io/'
description='Plugins for additional image formats: TIFF, MNG, TGA, WBMP'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtimageformats-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(cmake ninja)
sha256sums=('595bf8557b91e1f8ebc726f1e09868a3c7e610ff5045068f2d4ea2428c49a5d4')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtimageformats-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH


setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DINSTALL_PUBLICBINDIR=usr/bin \
		-DCMAKE_INSTALL_PREFIX=/usr
}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}