#!/usr/bin/env bash
name='py3-cairo'
release='4'
version='1.26.0'
url='https://github.com/pygobject/pycairo/'
description='Python bindings for the cairo library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/pygobject/pycairo/archive/refs/tags/v$version.tar.gz")
pyver=$(python -c "import sys; print(str( sys.version_info[0]) +\".\"+ str(sys.version_info[1] ))")
depends=(python"$pyver" cairo)
makedepends=()
md5sums=('1fc8dae1f5d07e401f9ab40cdd234ef3')
group=(dev.python)
uses=()
arch=('x86_64')

cd pycairo-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
