#!/usr/bin/env bash
name='gsettings-desktop-schemas'
release='2'
version='44.0'
url='https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas.git/'
description=' Collection of GSettings schemas for GNOME desktop '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/archive/$version/gsettings-desktop-schemas-$version.tar.gz")
depends=()
makedepends=()
md5sums=('a5ae51de37e6802afd35965b2bc94874')
group=(gnome.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    sed -i -r 's:"(/system):"/org/gnome\1:g' schemas/*.in
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

