#!/usr/bin/env bash
name='gsettings-desktop-schemas'
release='1'
version='43.0'
url='https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas.git/'
description=' Collection of GSettings schemas for GNOME desktop '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/-/archive/$version/gsettings-desktop-schemas-$version.tar.gz")
depends=()
makedepends=()
md5sums=('df5f7cfbf7d285a726cb8a3e7703a832')
group=(gnome.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

