#!/usr/bin/env bash
name='gmp'
release='1'
version='6.2.1'
url='https://gmplib.org'
description='Library for arbitrary-precision arithmetic on different type of numbers'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('GPLv2' 'LGPLv3')
source=('https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz')
md5sums=('0b82665c4a92fd2ade7440c13fcaa42b')
arch=('x86_64')
group=(system.devel)
uses=(cxx)
cxx_depends=(gcc)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
	--libdir=/usr/lib64 \
	$(use_opt cxx --enable-cxx --disable-cxx)
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

