#!/usr/bin/env bash
name='cjs'
release='1'
version='5.8.0'
url='https://github.com/linuxmint/cjs'
description='Javascript Bindings for Cinnamon'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL')
source=("https://github.com/linuxmint/cjs/archive/refs/tags/${version}.tar.gz")
depends=(js102)
makedepends=()
md5sums=('991e1bbf2ebf7cca4e93cfce66c4a876')
group=(gnome.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

