#!/usr/bin/env bash
name='cjs'
release='2'
version='6.0.0'
url='https://github.com/linuxmint/cjs'
description='Javascript Bindings for Cinnamon'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL')
source=("https://github.com/linuxmint/cjs/archive/refs/tags/${version}.tar.gz")
depends=(mozjs102)
makedepends=()
md5sums=('3e4c66fe5643c16b0041959084929ca1')
group=(gnome.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

