#!/usr/bin/env bash
name='icu'
release='2'
version='74.2'
_version='74-2'
url='https://github.com/unicode-org/icu'
description='icu International Components for Unicode'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/unicode-org/icu/archive/refs/tags/release-${_version}.tar.gz")
#source=("https://github.com/unicode-org/icu/releases/download/release-${version}/icu4c-${_version}-src.tgz")
depends=()
makedepends=()
md5sums=('70e681a5d43fe813e98859d53049d150')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-"release-"$_version"/icu4c/source"

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

