#!/usr/bin/env bash
name='icu'
release='2'
version='73.2'
_version='73-2'
url='https://github.com/unicode-org/icu'
description='icu International Components for Unicode'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
				https://github.com/unicode-org/icu/archive/refs/tags/release-73-2.tar.gz
source=("https://github.com/unicode-org/icu/archive/refs/tags/release-${_version}.tar.gz")
depends=()
makedepends=()
md5sums=('2fc030d5f0316be527a46bc0730b8580')
group=(dev.libs)
uses=()
arch=('x86_64')

cd "icu-release"-$version"/icu4c/source"

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

