#!/usr/bin/env bash
name='icu'
release='2'
version='73-2'
_version='73_2'
url='https://github.com/unicode-org/icu'
description='icu International Components for Unicode'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
#source=('https://github.com/unicode-org/icu/archive/refs/tags/icu4x/2023-03-06/72.x.tar.gz')
source=("https://github.com/unicode-org/icu/releases/download/release-${version}/icu4c-${_version}-src.tgz")
depends=()
makedepends=()
md5sums=('b8a4b8cf77f2e2f6e1341eac0aab2fc4')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name"/source"

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

