#!/usr/bin/env bash
name='gdk-pixbuf'
release='1'
version='2.42.10'
url='https://gitlab.gnome.org/GNOME/gdk-pixbuf'
description='gdk-pixbuf Image loading library for GTK+ '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/archive/$version/gdk-pixbuf-$version.tar.gz")
depends=(libjpeg-turbo shared-mime-info gi-docgen)
makedepends=()
md5sums=('d0d5dc2647a3104efe4d61765a792b5b')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
pip3 install docutils
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

