#!/usr/bin/env bash
name='atkmm'
release='1'
version='2.28.3'
url='https://www.gtkmm.org'
description='Atkmm is the official C++ interface for the ATK accessibility toolkit library.'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.gnome.org/sources/atkmm/${version%.*}/atkmm-${version}.tar.xz")
depends=(at-spi2-core glibmm)
makedepends=()
md5sums=('bad12606feaaba28c4d31b8857b7099e')
group=(dev.cpp)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}

