#!/usr/bin/env bash
name='xfce4-xkb-plugin'
release='2'
version='0.9.0'
_version='0.9'
url='https://docs.xfce.org/panel-plugins/xfce4-xkb-plugin'
description='Plugin to switch keyboard layouts for the Xfce4 panel'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('custom')
source=("https://archive.xfce.org/src/panel-plugins/xfce4-xkb-plugin/${_version}/xfce4-xkb-plugin-${version}.tar.xz")
depends=(libnotify librsvg libwnck3 libxklavier xfce4-panel)
makedepends=(intltool)
sha256sums=('7cd7f3626ef39dc4ce142b2f96ab7583cbea84b4c0352fbc9c9667faac0bdd12')
group=(xfce.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
      --prefix=/usr
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

