#!/usr/bin/env bash
name='xfce4-xkb-plugin'
release='1'
version='0.8.3'
_version='0.8'
url='https://docs.xfce.org/panel-plugins/xfce4-xkb-plugin'
description='Plugin to switch keyboard layouts for the Xfce4 panel'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('custom')
source=("https://archive.xfce.org/src/panel-plugins/xfce4-xkb-plugin/${_version}/xfce4-xkb-plugin-${version}.tar.bz2")
#source=("https://mirror.netcologne.de/xfce/src/panel-plugins/xfce4-xkb-plugin/${_version}/xfce4-xkb-plugin-${version}.tar.bz2")
depends=(libnotify librsvg libwnck3 libxklavier xfce4-panel)
makedepends=(intltool)
md5sums=('16ed2f9fdd7107383a209625f616d398')
group=(xfce.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--libexecdir=/usr/lib \
		--localstatedir=/var \
		--disable-debug
}

build(){
    make $jobs
}

package(){
  make DESTDIR="$DESTDIR" install
  install -Dm644 COPYING "$DESTDIR/usr/share/licenses/$name/COPYING"
}

