#!/usr/bin/env bash
name='bubblewrap'
release='3'
version='0.11.0'
url='https://containers/bubblewrap'
description='Unprivileged sandboxing tool, namespaces-powered chroot-like solution'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/containers/bubblewrap/archive/refs/tags/v$version.tar.gz")
depends=(libcap)
makedepends=()
sha256sums=('cfeeb15fcc47d177d195f06fdf0847e93ee3aa6bf46f6ac0a141fa142759e2c3')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja install -C build $jobs
}

