#!/usr/bin/env bash
name='bubblewrap'
release='2'
version='0.10.0'
url='https://containers/bubblewrap'
description='Unprivileged sandboxing tool, namespaces-powered chroot-like solution'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/containers/bubblewrap/archive/refs/tags/v$version.tar.gz")
depends=(libcap)
makedepends=()
sha256sums=('2108fafedeec4df2c451119606c191b0bfbd88328972dbb04fb8eb56081a724f')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja install -C build $jobs
}

