#!/usr/bin/env bash
name='xdg-utils'
release='1'
version='1.1.3'
url='https://www.freedesktop.org/wiki/Software/xdg-utils/'
description='Command line tools that assist applications with a variety of desktop integration tasks'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://portland.freedesktop.org/download/xdg-utils-$version.tar.gz"
"https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/21.patch")
depends=(file xorg-xset xorg-xprop)
makedepends=(docbook-xsl lynx xmlto git)
md5sums=('902042508b626027a3709d105f0b63ff' '31376a25c58f023d1bcbbb79afa9c3da')
group=(x11.misc)
uses=()
arch=('x86_64')

cd $name-$version

patch -Np1 -i ../21.patch

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        #--docdir=
}

build(){
    make $jobs
}

package(){
    make DESTDIR="$DESTDIR" install
    install -D -m644 LICENSE "$DESTDIR/usr/share/licenses/$name/LICENSE"

    # install empty directory to prevent xdg-desktop-menu install *.desktop to fail, see FS#33316
    install -dm755 "$DESTDIR"/usr/share/desktop-directories
}

