#!/usr/bin/env bash
name='xdg-utils'
release='2'
version='1.2.1'
url='https://www.freedesktop.org/wiki/Software/xdg-utils/'
description='Command line tools that assist applications with a variety of desktop integration tasks'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xdg/xdg-utils/-/archive/v${version}/xdg-utils-v${version}.tar.gz")
depends=(file xorg-xset xorg-xprop)
makedepends=(docbook-xsl lynx xmlto)
md5sums=('4c72585a98ba8f775cb9e72b066cc0df')
group=(x11.misc)
uses=()
arch=('x86_64')

cd $name-"v"$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    make $jobs
}

package(){
    make DESTDIR="$DESTDIR" install
    install -D -m644 LICENSE "$DESTDIR/usr/share/licenses/$name/LICENSE"
}


