#!/usr/bin/env bash
name='kwindowsystem'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Access to the windowing system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kwindowsystem-${version}.tar.xz")
depends=(libX11 libxcb qt6-base qt6-wayland wayland xcb-util-keysyms libXfixes)
makedepends=(extra-cmake-modules qt6-tools doxygen qt6-declarative wayland-protocols)
sha256sums=('62c0f0b4a9507939d84aeeda55bbd4300b88c04e37953e5189b139003310a8f4')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


