#!/usr/bin/env bash
name='kwindowsystem'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Access to the windowing system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kwindowsystem-${version}.tar.xz")
depends=(libX11 libxcb qt6-base qt6-wayland wayland xcb-util-keysyms libXfixes)
makedepends=(extra-cmake-modules qt6-tools doxygen qt6-declarative wayland-protocols)
sha256sums=('1906caa53b7d58fc0c4d78a3c8d99f25aa056fc6d09c5fc121ed5e1f80396a94')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


