#!/usr/bin/env bash
name='no-static'
release='1'
version='0.3.1'
url='https://https://gitlab.com/turkman/devel/assets/no-static'
description='Ymp static library remover'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/assets/no-static/-/archive/$version/no-static-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('0b1d4657eab07dd59e5797cd09da9985182087e7fa42ae7f3699082d3a967a30')
group=(app.misc)
uses=()
arch=('x86_64')

cd $name-$version

package () {
    make install $jobs
}

