#!/usr/bin/env bash
name='gst-plugins-bad'
release='1'
version='1.18.6'
url='https://gitlab.freedesktop.org/gstreamer'
description=' GStreamer plugins and helper libraries'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/archive/$version/gst-plugins-bad-$version.tar.gz")
depends=()
makedepends=()
md5sums=('4bd822ca18be8c3d409f091a8f9219ff')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}
