#!/usr/bin/env bash
name='gst-plugins-bad'
release='2'
version='1.22.7'
url='https://gitlab.freedesktop.org/gstreamer'
description=' GStreamer plugins and helper libraries'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-${version}.tar.xz")
#source=("https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/archive/$version/gst-plugins-bad-$version.tar.gz")
depends=(gst-plugins-base)
makedepends=()
md5sums=('63d4e2811069a0a852782a788b494340')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

# Fix undefined symbol 'exp'
export CFLAGS="$CfLAGS -lm"

setup(){
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64 \
    -Dgpl=enabled
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}
