#!/usr/bin/env bash
name='kdesu'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Integration with su for elevated privileges'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdesu-${version}.tar.xz")
depends=(qt6-base kpty kconfig)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('41091ea45c6e22e1411d89d1538b2c8bd98bdc1f38d59df3e9c423aac0224e28')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
