#!/usr/bin/env bash
name='kdesu'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Integration with su for elevated privileges'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdesu-${version}.tar.xz")
depends=(kpty kconfig)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('1bbb4a71e19463364708174837c6c47a')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
