#!/usr/bin/env bash
name='kdesu'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Integration with su for elevated privileges'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdesu-${version}.tar.xz")
depends=(qt6-base kpty kconfig)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('24cca7ab6da9630799e5f0107b546d37ee635b1f9f4b7c12eb53a1b3619b2c0c')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
