#!/usr/bin/env bash
name='xorg-server'
release='2'
version='21.1.13'
url='https://www.x.org/wiki/'
description='X.Org X servers'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/releases/individual/xserver/xorg-server-$version.tar.xz")
depends=(libmd libbsd libepoxy libfontenc libxkbfile xauth xkbcomp setxkbmap freetype
         libXfont2 libxcvt mesa libX11 libdrm pixman font-util xcb-util-renderutil
         xcb-util xcb-util-image xcb-util-wm xcb-util-keysyms)
makedepends=()
sha256sums=('b45a02d5943f72236a360d3cc97e75134aa4f63039ff88c04686b508a3dc740c')
group=(x11.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
   meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -D ipv6=true \
        -D xvfb=true \
        -D xnest=true \
        -D xcsecurity=true \
        -D xorg=true \
        -D xephyr=true \
        -D glamor=true \
        -D udev=true \
        -D dtrace=false \
        -D systemd_logind=false \
        -D suid_wrapper=true \
        -D xkb_dir=/usr/share/X11/xkb \
        -D xkb_output_dir=/var/lib/xkb \
        -D libunwind=false
}

build(){
    ninja -C build
}

package(){
    ninja install -C build
}

