#!/usr/bin/env bash
name='plasma-activities-stats'
release='2'
version='6.0.0'
url='https://download.kde.org/stable/frameworks'
description='A library for accessing the usage data collected by the activities system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/plasma-activities-stats-$version.tar.xz")
depends=(plasma-activities)
makedepends=()
sha256sums=('5e6ab0fe5f3c5db0de2ebe6adcd79c26170b92addc056cf35f0484fb45007d2e')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DBUILD_TESTING=OFF \
        -DBUILD_QCH=ON
}

build () {
    cmake --build build
}

package () {
    cmake --install build
}

