#!/usr/bin/env bash
name='libgcrypt'
release='1'
version='1.10.1'
url='https://www.gnupg.org'
description='General purpose cryptographic library based on the code from GnuPG'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=(https://gnupg.org/ftp/gcrypt/${name}/${name}-${version}.tar.bz2{,.sig})
depends=(libgpg-error)
makedepends=()
md5sums=('8fadbe1fddafa341dce5ef3869f70e25' 'SKIP')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

sed -i "s:t-secmem::" tests/Makefile.am
sed -i "s:t-sexp::" tests/Makefile.am

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --disable-static \
        --disable-padlock-support
}

build(){
    make $jobs
}

package(){
    make DESTDIR=${DESTDIR} install $jobs
}

