#!/bin/bash
name=bash
version=5.2
release=2
url='https://www.gnu.org/software/bash/'
description="Bash is the GNU Project's shell—the Bourne Again SHell."
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
arch=(x86_64)
depends=(readline ncurses)
source=("https://ftp.gnu.org/gnu/$name/$name-$version.tar.gz")
md5sums=(cfb4cf795fc239667f187b3d6b3d396f)
group=(app.shell)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/lib64 \
        --bindir=/bin \
        --with-curses \
        --enable-readline \
        --without-bash-malloc
}
build(){
    make 
}

package(){
    make DESTDIR=${DESTDIR} install
}
