#!/bin/bash
name=bash
version=5.3
release=3
url='https://www.gnu.org/software/bash/'
description="Bash is the GNU Project's shell—the Bourne Again SHell."
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
arch=(x86_64)
depends=(readline ncurses)
source=("https://ftp.gnu.org/gnu/$name/$name-$version.tar.gz")
sha256sums=(0d5cd86965f869a26cf64f4b71be7b96f90a3ba8b3d74e27e8e9d9d5550f31ba)
group=(app.shell)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/lib64 \
        --bindir=/bin \
        --with-curses \
        --enable-readline \
        --without-bash-malloc
}
build(){
    make 
}

package(){
    make DESTDIR=${DESTDIR} install
}
