#!/usr/bin/env bash
name='py3-webencodings'
release='1'
version='0.5.1'
url='https://github.com/gsnedders/python-webencodings'
description='Character encoding for the web'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://github.com/gsnedders/python-webencodings/archive/v${version}.tar.gz")
depends=(python)
makedepends=(py3-setuptools)
md5sums=('7eb67377743cd55eaa356496c439471e')
group=(dev.python)
uses=()
arch=('x86_64')

cd "python-webencodings"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

