#!/usr/bin/env bash
name='qt5-xmlpatterns'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='Virtual keyboard framework'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtxmlpatterns-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=(qt5-declarative)
sha256sums=('c73bec56c5c4fe706496ae8f29bdda7bcb59f9faa2fa11feb700d5e2f38caaba')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtxmlpatterns-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}
