#!/usr/bin/env bash
name='qt5-xmlpatterns'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='Virtual keyboard framework'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtxmlpatterns-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=(qt5-declarative)
md5sums=('1a15066f195183f9aeaa8568135edcb9')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtxmlpatterns-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}
