#!/usr/bin/env bash
name='tllist'
release='1'
version='1.1.0'
url='https://codeberg.org/dnkl/$name'
description='Header-only implementation of a typed linked list in C'
email='tolgaucar44@gmail.com'
maintainer='librecat'
license=('MIT')
source=("https://codeberg.org/dnkl/tllist/archive/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('0e7b7094a02550dd80b7243bcffc3671550b0f1d8ba625e4dff52517827d5d23')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name

setup(){
	meson setup build -Dprefix=/usr
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

