#!/usr/bin/env bash
name='font-xfree86-type1'
release='1'
version='1.0.4'
url='https://gitlab.freedesktop.org/xorg/font/xfree86-type1'
description='X.Org XFree86 Type 1 font'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/font/font-xfree86-type1-$version.tar.gz")
depends=()
makedepends=()
md5sums=('89c33c5176cd580de6636ad50ce7777b')
group=(media.fonts)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

