#!/usr/bin/env bash
name='p7zip'
release='1'
version='17.04'
url='https://github.com/jinfeihan57/p7zip'
description='Command-line file archiver with high compression ratio'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/flyfishzy/p7zip/archive/refs/tags/v$version.zip")
depends=(gcc)
makedepends=()
md5sums=('5f362f28d7f8b75d89f86065b3dba520')
uses=()
arch=('x86_64')
group=(app.arch)

cd $name-$version

build(){
    make 7z 7zr 7za $jobs
}

package(){
    make install \
        DEST_DIR="${DESTDIR}" \
        DEST_HOME=/usr
    mv ${DESTDIR}/usr/lib{,64}
    sed -i "s/lib/lib64/g" ${DESTDIR}/usr/bin/*
}

