#!/usr/bin/env bash
name='libXdmcp'
release='1'
version='1.1.4'
url='X.Org X Display Manager Control Protocol library'
description='X.Org X Display Manager Control Protocol library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXdmcp-$version.tar.xz")
depends=()
makedepends=()
md5sums=('0b4056a282c1e14323d5daef8fb5345d')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

