#!/usr/bin/env bash
name='kdesignerplugin'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Integration of Frameworks widgets in Qt Designer/Creator'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/portingAids/kdesignerplugin-${version}.tar.xz")
depends=(kconfig kcoreaddons)
makedepends=(extra-cmake-modules qt5-tools kdoctools)
md5sums=('f59cd2f11e1f9d7e6fec6dc1586409e1')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
