#!/usr/bin/env bash
name='xfdesktop'
release='1'
version='4.18.1'
_version='4.18'
url='https://docs.xfce.org/xfce/xfdesktop/start'
description="Xfce's desktop manager"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://archive.xfce.org/src/xfce/xfdesktop/${_version}/xfdesktop-${version}.tar.bz2")
depends=(exo garcon libwnck3 libxfce4ui thunar)
makedepends=(intltool)
md5sums=('e675c2989436dc724fef402d1db0125d')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--enable-thunarx \
		--enable-notifications \
		--disable-debug 
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

