#!/usr/bin/env bash
name='xfdesktop'
release='2'
version='4.20.0'
_version='4.20'
url='https://docs.xfce.org/xfce/xfdesktop/start'
description="Xfce's desktop manager"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://archive.xfce.org/src/xfce/xfdesktop/${_version}/xfdesktop-${version}.tar.bz2")
depends=(exo garcon libwnck3 libxfce4ui thunar)
makedepends=(intltool)
sha256sums=('227041ba80c7f3eb9c99dec817f1132b35d8aec7a4335703f61ba1735cd65632')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--enable-thunarx \
		--enable-notifications
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

