#!/usr/bin/env bash
name='xfdesktop'
release='3'
version='4.20.1'
_version='4.20'
url='https://docs.xfce.org/xfce/xfdesktop/start'
description="Xfce's desktop manager"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://archive.xfce.org/src/xfce/xfdesktop/${_version}/xfdesktop-${version}.tar.bz2")
depends=(exo garcon libwnck3 libxfce4ui thunar)
makedepends=(intltool)
sha256sums=('acccde849265bbf4093925ba847977b7abf70bb2977e4f78216570e887c157b8')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
         --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dtests=false
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

