#!/usr/bin/env bash
name='py3-dbus'
_name='dbus-python'
release='1'
version='1.3.2'
url='https://www.freedesktop.org/wiki/Software/DBusBindings'
description='Python3 bindings for DBUS'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://dbus.freedesktop.org/releases/dbus-python/$_name-${version}.tar.gz")
depends=()
makedepends=()
md5sums=('33be8a4a766e1c7c9a377b8f934ce21a')
group=(dev.python)
uses=()
arch=('x86_64')

cd $_name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

