#!/usr/bin/env bash
name='py3-dbus'
_name='dbus-python'
release='1'
version='1.3.2'
url='https://www.freedesktop.org/wiki/Software/DBusBindings'
description='Python3 bindings for DBUS'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('MIT')
source=("https://dbus.freedesktop.org/releases/dbus-python/$_name-${version}.tar.gz")
depends=(python dbus)
makedepends=(py3-sphinx py3-tomli)
sha256sums=('ad67819308618b5069537be237f8e68ca1c7fcc95ee4a121fe6845b1418248f8')
group=(dev.python)
uses=()
arch=('x86_64')

cd $_name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

