#!/usr/bin/env bash
name='libdbusmenu-qt'
release='1'
version='0.9.3'
url='https://launchpad.net/libdbusmenu-qt'
description='library to export QMenu over DBusMenu protocol'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://launchpad.net/ubuntu/+archive/primary/+files/libdbusmenu-qt_${version}+16.04.20160218.orig.tar.gz")
depends=(qt5-base )
makedepends=(cmake)
md5sums=('8b90312bd8654e026d814d4db986ce5e')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version"+16.04.20160218"

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
	    -DCMAKE_INSTALL_LIBDIR=lib \
	    -DCMAKE_BUILD_TYPE=None \
	    -DUSE_QT5=ON
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

