#!/bin/bash
name=dash
version=0.5.11
release=1

url='https://salsa.debian.org/debian/dash'
description="The Debian Almquist Shell (dash) is a POSIX-compliant shell derived from ash. "
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv2')
depends=()
arch=(x86_64)
ver=$version+git20210903+057cd650a4ed-8
source=(https://salsa.debian.org/debian/dash/-/archive/debian/$ver/dash-debian-$ver.zip)
md5sums=(fa7d340bd8968e10f8097667cfdd1c18)
group=(app.shell)

cd $name-debian-$ver

setup(){
    ./autogen.sh
    ./configure --prefix=/usr \
    --libdir=/lib64 \
    --bindir=/bin
}
build(){
    make $jobs
}

package(){
    make install
}
