#!/usr/bin/env bash
name='powerdevil'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='Manages the power consumption settings of a Plasma Shell'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/powerdevil-${version}.tar.xz")
depends=(plasma-activities kauth kcmutils kconfig kcoreaddons kcrash kdbusaddons kglobalaccel ki18n
         kidletime kirigami kitemmodels knotifications ksvg kwindowsystem kxmlgui layer-shell-qt libkscreen
         libplasma libxcb plasma-workspace qt6-base qt6-declarative solid
)
makedepends=(extra-cmake-modules kdoctools kcmutils)
sha256sums=('aa8e9c6f33b8aed4edae9c9c43830966ed4eec2fb437cf21023150bdfbd82e48')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


