#!/usr/bin/env bash
name='qt6-lottie'
release='4'
version='6.9.1'
url='https://www.qt.io/'
description='A family of player software for a certain json-based file format for describing 2d vector graphics animations'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtlottie-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(qt6-declarative cmake ninja)
sha256sums=('8ee88c2e0773c96109c179d7e75a46ba7bc548b5bc8be409a23cbaddafa18ba2')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtlottie-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
