#!/usr/bin/env bash
name='libvdpau'
release='1'
version='1.5'
url='https://gitlab.freedesktop.org/vdpau/libvdpau/'
description='VDPAU wrapper and trace libraries'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/vdpau/libvdpau/-/archive/$version/libvdpau-$version.tar.gz")
depends=(libXext)
makedepends=()
md5sums=('665b9dd49440ed48b08e0ab053ad9ede')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64 \
        -Ddri2=true
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

