#!/usr/bin/env bash
name='py3-distutils-extra'
release='1'
version='2.39'
url='https://launchpad.net/python-distutils-extra'
description='Enhancements to the Python build system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://launchpad.net/python-distutils-extra/trunk/$version/+download/python-distutils-extra-$version.tar.gz")
depends=(python py3-setuptools)
makedepends=(intltool)
sha256sums=('723f24f4d65fc8d99b33a002fbbb3771d4cc9d664c97085bf37f3997ae8063af')
group=(dev.python)
uses=()
arch=('x86_64')

cd python-distutils-extra-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

