#!/usr/bin/env bash
name='pcmanfm'
release='1'
version='1.3.2'
url='https://github.com/lxde/lxinput'
description='LXDE keyboard and mouse configuration tool '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/pcmanfm/archive/refs/tags/$version.tar.gz")
depends=(lxmenu-data libfm menu-cache libkeybinder3)
makedepends=()
sha256sums=('66ee6b1a5907bb519d5b175e379f975acfcdaa68b6cbbc72d168b3ff935e6fea')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

export CC="clang"
export CXX="clang++"

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ --with-gtk=3 
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

