#!/usr/bin/env bash
name='pcmanfm'
release='1'
version='1.3.2'
url='https://github.com/lxde/lxinput'
description='LXDE keyboard and mouse configuration tool '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/pcmanfm/archive/refs/tags/$version.tar.gz")
depends=(lxmenu-data libfm menu-cache libkeybinder3)
makedepends=()
md5sums=('212a3ca12bc38dbd92c4b501b98d8074')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ --with-gtk=3 
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

