#!/usr/bin/env bash
name='pcmanfm'
release='2'
version='1.4.0'
url='https://github.com/lxde/lxinput'
description='LXDE keyboard and mouse configuration tool '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/pcmanfm/archive/refs/tags/$version.tar.gz")
depends=(lxmenu-data libfm menu-cache libkeybinder3)
makedepends=()
sha256sums=('cda4f5ad7e049dcdf3b051b9de4c779adcd55bd720e9c96c45275389aa84264e')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

export CC="clang"
export CXX="clang++"

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ --with-gtk=3 
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

