#!/usr/bin/env bash
name='unrar'
release='2'
version='7.0.9'
url='https://www.rarlab.com/rar_add.htm'
description='The RAR uncompression program'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('custom')
source=("https://www.rarlab.com/rar/unrarsrc-${version}.tar.gz")
depends=()
makedepends=()
sha256sums=('505c13f9e4c54c01546f2e29b2fcc2d7fabc856a060b81e5cdfe6012a9198326')
group=(app.arch)
uses=()
arch=('x86_64')

#cd $name-$version

setup(){
    sed -e '/CXXFLAGS=/d' -e '/LDFLAGS=/d' -i unrar/makefile # Use system build flags
}

build(){
  cp -a unrar libunrar
  export LDFLAGS+=' -pthread'
  make -C libunrar lib $jobs
  make -C unrar $jobs
}

package(){
  cd unrar
  install -Dm755 unrar -t "$DESTDIR"/usr/bin/
  # install license
  install -Dm644 license.txt "$DESTDIR"/usr/share/licenses/$name/LICENSE
}

