#!/usr/bin/env bash
name='xcb-util-keysyms'
release='1'
version='0.4.1'
url='https://gitlab.freedesktop.org/xorg/lib/libxcb-keysyms.git/g'
description='X C-language Bindings sample implementations'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/xcb-util-keysyms-$version.tar.xz")
depends=()
makedepends=()
md5sums=('fbdc05f86f72f287ed71b162f1a9725a')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

