#!/usr/bin/env bash
name='libmd'
release='2'
version='1.1.0'
url='https://www.hadrons.org/software/libmd/'
description='Message Digest functions from BSD systems'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://archive.hadrons.org/software/libmd/libmd-$version.tar.xz")
depends=()
makedepends=()
md5sums=('b2a0650c78d92c7a9632a2a3cdd4f6a6')
group=(app.crypt)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make 
}

package(){
    make install 
}

