#!/usr/bin/env bash
name='libXmu'
release='1'
version='1.1.4'
url='https://gitlab.freedesktop.org/xorg/lib/libXmu.git/'
description='X.Org Xmu library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXmu-$version.tar.xz")
depends=(libXt libXext libX11)
makedepends=()
md5sums=('ed52d396115fbc4d05300762aab79685')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

