#!/usr/bin/env bash
name='libfontenc'
release='1'
version='1.1.7'
url='https://gitlab.freedesktop.org/xorg/lib/libfontenc'
description='PX.Org fontenc library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libfontenc-$version.tar.xz")
depends=()
makedepends=()
md5sums=('6d3f1b15bb5b0bb71ae9f0a5103c1fc4')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

