#!/usr/bin/env bash
name='xorgproto'
release='4'
version='2024.1'
url='https://gitlab.freedesktop.org/xorg/proto/xorgproto'
description='X.Org combined protocol headers'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/proto/xorgproto-${version}.tar.xz")
depends=()
makedepends=(util-macros)
md5sums=('12374d29fb5ae642cfa872035e401640')
uses=()
arch=('x86_64')
group=(x11.base)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
	--without-xmlto \
	--without-xsltproc
}

build(){
    make $jobs
}

package(){
    make install $jobs
}
