#!/usr/bin/env bash
name='kjobwidgets'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Widgets for tracking KJob instances'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kjobwidgets-${version}.tar.xz")
depends=(kcoreaddons kwidgetsaddons knotifications qt6-base)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('5239d0d47af8118c962b59816fceeebbff930a43ab7923438982ac08dbcb84be')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
