#!/usr/bin/env bash
name='kjobwidgets'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Widgets for tracking KJob instances'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kjobwidgets-${version}.tar.xz")
depends=(kcoreaddons kwidgetsaddons knotifications qt6-base)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('16d7e7ab54235d6fa1eb213d3d637182e22fcbdbcb7b4b14032430a02a2f888a')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
