#!/usr/bin/env bash
name='libmpc'
release='1'
version='1.2.1'
url='http://www.multiprecision.org/'
description='Library for the arithmetic of complex numbers with arbitrarily high precision'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('LGPL')
source=("https://ftp.gnu.org/gnu/mpc/mpc-$version.tar.gz")
depends=(mpfr)
makedepends=( )
md5sums=('9f16c976c25bb0f76b50be749cd7a3a8')
group=(dev.libs)
arch=('x86_64')

cd mpc-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/libmpc
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/usr/lib64/libmpc/" > ${DESTDIR}/etc/ld.so.conf.d/libmpc.conf
}

