#!/usr/bin/env bash
name='libmpc'
release='2'
version='1.3.1'
url='http://www.multiprecision.org/'
description='Library for the arithmetic of complex numbers with arbitrarily high precision'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('LGPL')
source=("https://ftp.gnu.org/gnu/mpc/mpc-$version.tar.gz")
depends=(mpfr)
makedepends=()
md5sums=('5c9bc658c9fd0f940e8e3e0f09530c62')
group=(dev.libs)
arch=('x86_64')

cd mpc-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

