#!/usr/bin/env bash
name='libheif'
release='1'
version='1.16.2'
url='https://www.libde265.org/'
description='ISO/IEC 23008-12:2017 HEIF file format decoder and encoder'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/strukturag/libheif/releases/download/v${version}/libheif-${version}.tar.gz")
depends=(aom libpng gdk-pixbuf x265)
makedepends=(cmake libjpeg-turbo)
md5sums=('e6bec8efc317b56d85884197ad874f0a')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 

}

build () {
    	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}


