#!/usr/bin/env bash
name='nemo-terminal'
release='2'
version='6.2.0'
url='https://example.org'
description='Embedded terminal window for Nemo'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://github.com/linuxmint/nemo-extensions/archive/refs/tags/${version}.tar.gz")
depends=(nemo)
makedepends=(intltool gobject-introspection meson ninja)
sha256sums=('b1c7e3d269ed05f472c80c16cf3f12827cbb48cb05406b276be14060225dbbc3')
group=(cinnamon.extra)
uses=()
arch=('x86_64')

cd "nemo-extensions"-$version/"nemo-terminal"

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
