#!/usr/bin/env bash
name='libpulse'
release='2'
version='17.0'
url='https://www.freedesktop.org/wiki/Software/PulseAudio/'
description='Libraries for PulseAudio clients '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.freedesktop.org/software/pulseaudio/releases/pulseaudio-$version.tar.xz")
depends=(dbus libsndfile tdb libICE libxcb libSM libXtst gtk3 sbc jack2 lirc gst-plugins-base gstreamer libasyncns speexdsp libsoxr)
makedepends=(bluez)
md5sums=('c4a3596a26ff4b9dcd0c394dd1d4f8ee')
group=(media.libs)
uses=()
arch=('x86_64')

cd pulseaudio-$version

setup(){
	meson setup build --prefix=/usr \
      --libdir=/usr/lib64/ \
      -Dsystemd=disabled \
      -Dtests=false \
      -Ddoxygen=false \
      -Dman=false
}

build(){
    ninja -C build
}

package(){
   ninja -C build install
}

