#!/usr/bin/env bash
name='wpa_supplicant'
release='2'
version='2.11'
url='https://w1.fi/wpa_supplicant/'
description='IEEE 802.1X/WPA supplicant for secure wireless transfers'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=('https://w1.fi/releases/wpa_supplicant-2.11.tar.gz'
    'wpa_supplicant.initd'
    'wpa_supplicant.confd'
    'wpa_cli.sh'
)
depends=(dbus libnl openssl pcsc-lite readline)
makedepends=()
sha256sums=('912ea06f74e30a8e36fbb68064d6cdff218d8d591db0fc5d75dee6c81ac7fc0a'
    'SKIP'
    'SKIP'
    'SKIP'
)
group=(net.wireless)
uses=()
arch=('x86_64')

cd $name-$version/$name

unset CFLAGS
unset CXXFLAGS

export BINDIR=/usr/sbin
export LIBDIR=/usr/lib64

setup(){
    cp defconfig .config
}

build(){
    make $jobs
    make $jobs eapol_test
}

package(){
    make install $jobs 
    # config
    install -Dm644 ./wpa_supplicant.conf $DESTDIR/etc/wpa_supplicant/wpa_supplicant-example.conf
    echo "" > $DESTDIR/etc/wpa_supplicant/wpa_supplicant.conf
    # openrc
    install -Dm755 ../../wpa_supplicant.initd $DESTDIR/etc/init.d/wpa_supplicant
    install -Dm755 ../../wpa_supplicant.confd $DESTDIR/etc/conf.d/wpa_supplicant
    # stuff
    install -Dm755 ./eapol_test $DESTDIR/$BINDIR/eapol_test
    install -Dm755 ../..//wpa_cli.sh $DESTDIR/etc/wpa_supplicant/wpa_cli.sh

    # dbus
    install -Dm644 ./dbus/dbus-wpa_supplicant.conf $DESTDIR/usr/share/dbus-1/system.d/wpa_supplicant.conf
    install -Dm644 ./dbus/fi.w1.wpa_supplicant1.service -t $DESTDIR/usr/share/dbus-1/system-services
}

