#!/usr/bin/env bash
name='font-bh-ttf'
release='1'
version='1.0.3'
url='https://gitlab.freedesktop.org/xorg/font/bh-ttf'
description='X.Org Bigelow & Holmes TrueType fonts'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/font/bh-ttf/-/archive/font-bh-ttf-$version/bh-ttf-font-bh-ttf-$version.tar.gz")
depends=(font-util)
makedepends=()
md5sums=('bda93c22b4a33d915e41e80bfafd19c0')
group=(media.fonts)
uses=()
arch=('x86_64')

cd bh-ttf-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

