#!/usr/bin/env bash
name='ffmpeg'
release='1'
version='6.0'
url='https://ffmpeg.org/'
description='A complete, cross-platform solution to record, convert and stream audio and video.'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://salsa.debian.org/multimedia-team/ffmpeg/-/archive/upstream/$version/ffmpeg-upstream-$version.tar.gz")
depends=(gnutls libaom libass dav1d)
makedepends=()
md5sums=('333b7ce677e42082c36e08d23e56acbe')
group=()
uses=()
arch=('x86_64')

cd $name-upstream-$version

setup(){
  ./configure --prefix=/usr \
    --disable-x86asm \
    --disable-librtmp \
		--disable-lzma \
		--disable-static \
		--disable-stripping \
		--enable-avfilter \
		--enable-gnutls \
		--enable-gpl \
		--enable-libaom \
		--enable-libass \
		--enable-libdav1d \
		--enable-libdrm \
		--enable-libfontconfig \
		--enable-libfreetype \
		--enable-libfribidi \
		--enable-libjxl \
		--enable-libmp3lame \
		--enable-libopenmpt \
		--enable-libopus \
		--enable-libplacebo \
		--enable-libpulse \
		--enable-librist \
		--enable-libsoxr \
		--enable-libsrt \
		--enable-libssh \
		--enable-libtheora \
		--enable-libv4l2 \
		--enable-libvidstab \
		--enable-libvorbis \
		--enable-libvpx \
		--enable-libwebp \
		--enable-libx264 \
		--enable-libx265 \
		--enable-libxcb \
		--enable-libxvid \
		--enable-libzimg \
		--enable-libzmq \
		--enable-lto \
		--enable-pic \
		--enable-postproc \
		--enable-pthreads \
		--enable-shared \
		--enable-vaapi \
		--enable-vdpau \
		--enable-vulkan \
		--optflags="-O3"
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

