#!/usr/bin/env bash
name='ffmpeg'
release='5'
version='7.1.1'
url='https://ffmpeg.org/'
description='A complete, cross-platform solution to record, convert and stream audio and video.'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://ffmpeg.org/releases/ffmpeg-${version}.tar.xz")
depends=(gnutls libaom libass dav1d libjxl libdrm lcms2 lame opus
         libopenmpt libpulse libunwind vulkan-loader gnutls librist
         libsrt libtheora v4l-utils vidstab libvpx libwebp x264 x265
         xvidcore zimg zeromq)
makedepends=(nasm)
sha256sums=('733984395e0dbbe5c046abda2dc49a5544e7e0e1e2366bba849222ae9e3a03b1')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version


setup(){
  ./configure --prefix=/usr \
    --disable-librtmp \
		--disable-lzma \
		--disable-stripping \
		--enable-avfilter \
		--enable-gnutls \
		--enable-gpl \
		--enable-libaom \
		--enable-libass \
		--enable-libdav1d \
		--enable-libdrm \
		--enable-libfontconfig \
		--enable-libfreetype \
		--enable-libfribidi \
		--enable-libjxl \
		--enable-libmp3lame \
		--enable-libopus \
		--enable-libpulse \
		--enable-librist \
		--enable-libsoxr \
		--enable-libsrt \
		--enable-libssh \
		--enable-libtheora \
		--enable-libv4l2 \
		--enable-libvidstab \
		--enable-libvorbis \
		--enable-libvpx \
		--enable-libwebp \
		--enable-libx264 \
		--enable-libx265 \
		--enable-libopenmpt \
		--enable-libxcb \
		--enable-libxvid \
		--enable-libzimg \
		--enable-libzmq \
		--enable-lto \
		--enable-pic \
		--enable-postproc \
		--enable-pthreads \
		--enable-static \
		--enable-shared \
		--enable-vaapi \
		--enable-vdpau \
		--optflags="-O3"
		#--enable-vulkan \

}

build(){
    make $jobs
}

package(){
    make install -j`nproc`
}

