#!/usr/bin/env bash
name='iso-codes'
release='4'
version='4.17.0'
url='https://salsa.debian.org/iso-codes-team/iso-codes'
description='Lists of the country, language, and currency names'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v${version}/iso-codes-v${version}.tar.gz")
depends=()
makedepends=()
sha256sums=('dd5ca13db77ec6dd1cc25f5c0184290a870ec1fed245d8e39a04ff34f59076c3')
group=(app.text)
uses=()
arch=('x86_64')

cd $name-"v"$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

