#!/usr/bin/env bash
name='iso-codes'
release='2'
version='4.15.0'
url='https://salsa.debian.org/iso-codes-team/iso-codes'
description='Lists of the country, language, and currency names'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v${version}/iso-codes-v${version}.tar.gz")
depends=()
makedepends=()
md5sums=('68d0a549e3086a33a9e35d17a2b1a608')
group=(app.text)
uses=()
arch=('x86_64')

cd $name-"v"$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

