#!/usr/bin/env bash
name='qt6-httpserver'
release='3'
version='6.8.0'
url='https://www.qt.io/'
description='Qt6 HTTP Server'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qthttpserver-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-websockets)
makedepends=(cmake ninja)
sha256sums=('81c308c8d23a5c9062330882008143cfeff88dc783e2d5c7bfaf22c81aae797f')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qthttpserver-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
