#!/usr/bin/env bash
name='qt6-httpserver'
release='2'
version='6.7.0'
url='https://www.qt.io/'
description='Qt6 HTTP Server'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qthttpserver-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-websockets)
makedepends=(cmake ninja)
sha256sums=('c2e2e38b2b21537eeef20d097bb5f216081462c44b78d63045e60d6fd9f89bfa')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qthttpserver-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
