#!/usr/bin/env bash
name='qt6-httpserver'
release='4'
version='6.9.1'
url='https://www.qt.io/'
description='Qt6 HTTP Server'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qthttpserver-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-websockets)
makedepends=(cmake ninja)
sha256sums=('bfc7b511e2bbc365f11027ae8d7d2e33f3ff63591b866df9a880c51363f02b53')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qthttpserver-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
