#!/usr/bin/env bash
name='cups'
release='2'
version='2.4.7'
url='https://github.com/OpenPrinting/cups'
description='The Common Unix Printing System '
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/OpenPrinting/cups/releases/download/v${version}/cups-${version}-source.tar.gz"
        'cups.groups'
        'cups.users'
		'cupsd.initd')
depends=(openssl)
makedepends=()
md5sums=('e0a5ddbf53dfad41da26fc1ef60b2256'
         'SKIP'
         'SKIP'
		 'SKIP')
group=(net.print)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--with-menudir=/usr/share/applications \
		--with-icondir=/usr/share/icons \
		--with-logdir=/var/log/cups \
		--with-docdir=/usr/share/cups \
		--with-rundir=/run/cups \
		--with-cupsd-file-perm=0755 \
		--with-cups-user=lp \
		--with-cups-group=lp \
		--with-system-groups=lpadmin \
		--with-domainsocket=/run/cups/cups.sock \
		--enable-libusb \
		--without-rcdir \
		--without-php \
		--disable-pam \
		--enable-raw-printing \
		--enable-dbus \
		--with-dbusdir=/usr/share/dbus-1 \
		--enable-libpaper \
		--enable-ssl=yes \
		--enable-gnutls \
		--disable-launchd \
		--disable-systemd
}

build(){
    make $jobs
}

package(){
    make install $jobs
    mkdir -p "$DESTDIR"/etc/{passwd,group,init}.d
    install ../cups.groups "$DESTDIR"/etc/group.d/cups
    install ../cups.users "$DESTDIR"/etc/passwd.d/cups
	install ../cupsd.initd "$DESTDIR"/etc/init.d/cupsd
}

