#!/usr/bin/env bash
name='xdo'
release='1'
version='0.5.7'
url='https://github.com/baskerville/xdo'
description='Small X utility to perform elementary actions on windows'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://github.com/baskerville/xdo/archive/refs/tags/${version}.tar.gz")
depends=(libxcb xcb-util-wm xcb-util)
makedepends=()
md5sums=('26a864375c6e703b87a2ff6d6f7a6068')
group=(x11.misc)
uses=()
arch=('x86_64')

cd $name-$version



build () {
    make $jobs
}

package () {
    make install PREFIX=/usr DESTDIR="$DESTDIR" $jobs
}

