#!/usr/bin/env bash
name='kquickcharts'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='A QtQuick plugin providing high-performance charts'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kquickcharts-${version}.tar.xz")
depends=(kirigami qt6-base qt6-declarative)
makedepends=(extra-cmake-modules qt6-shadertools)
sha256sums=('ebd9a8f501b80e72a12f50d984847a698f7283be389644f7e24133484076a6a5')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
