#!/usr/bin/env bash
name='kquickcharts'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='A QtQuick plugin providing high-performance charts'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kquickcharts-${version}.tar.xz")
depends=(qt5-quickcontrols2)
makedepends=(extra-cmake-modules)
md5sums=('5da5d058b64e40beb6692e327cbba109')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
