#!/usr/bin/env bash
name='kquickcharts'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='A QtQuick plugin providing high-performance charts'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kquickcharts-${version}.tar.xz")
depends=(kirigami qt6-base qt6-declarative)
makedepends=(extra-cmake-modules qt6-shadertools)
sha256sums=('c5a9a5cc206fdd2a86854284b081b16575f638bbb28b658065677b447d8c9002')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
