#!/usr/bin/env bash
name='libtiff'
release='2'
version='4.6.0'
url='https://gitlab.com/libtiff/libtiff'
description='Tag Image File Format (TIFF) library '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.com/libtiff/libtiff/-/archive/v$version/libtiff-v$version.tar.gz")
depends=()
makedepends=(cmake)
md5sums=('118a2e5fc9ed71653195b332b9715890')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-v$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --disable-docs
}

build(){
    make $jobs
}

package(){
    make DESTDIR="${DESTDIR}" install $jobs
}

