#!/usr/bin/env bash
name='kdesrc-build'
release='1'
version='22.07'
url='https://invent.kde.org/sdk/kdesrc-build'
description='Script to streamline setting up and maintaining KDE software development environment'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://invent.kde.org/sdk/kdesrc-build/-/archive/v${version}/kdesrc-build-v${version}.tar.gz")
depends=(dialog git)
makedepends=(extra-cmake-modules cmake)
md5sums=('af0f072c6a4c47efb7e64be47829b7e3')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-"v"$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
