#!/usr/bin/env bash
name='xauth'
release='1'
version='1.1.2'
url='https://gitlab.freedesktop.org/xorg/app/xauth'
description='X authority file utility'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/app/xauth/-/archive/xauth-$version/xauth-xauth-$version.tar.gz")
depends=(libXmu libX11)
makedepends=()
md5sums=('1e3086f646c35e7e66e81cb878490baf')
group=(x11.app)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

