#!/usr/bin/env bash
name='kfilemetadata'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='A library for extracting file metadata'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kfilemetadata-${version}.tar.xz")
depends=(attr exiv2 karchive kconfig kcoreaddons ki18n qt6-base taglib)
makedepends=(doxygen extra-cmake-modules ffmpeg qt6-tools)
sha256sums=('a6242a79e672b523ebf1b2554ebf83aca7a9d5065929b6f152731e9851d008d0')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}