#!/usr/bin/env bash
name='knewstuff'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Support for downloading application assets from the network'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/knewstuff-${version}.tar.xz")
depends=(qt6-base karchive kconfig kcoreaddons ki18n kpackage attica kwidgetsaddons syndication)
makedepends=(extra-cmake-modules doxygen qt6-tools qt6-declarative)
sha256sums=('7e721735abf7e2f6f8c0f42324f885bcad1114c317ac79bfabc705fb8018dba5')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


