#!/usr/bin/env bash
name='knewstuff'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Support for downloading application assets from the network'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/knewstuff-${version}.tar.xz")
depends=(qt6-base karchive kconfig kcoreaddons ki18n kpackage attica kwidgetsaddons syndication)
makedepends=(extra-cmake-modules doxygen qt6-tools qt6-declarative)
sha256sums=('a4184622d430b64ec7cc4c77113df67c886f359cc89cc6313fbcc71764d23fa7')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


