#!/usr/bin/env bash
name='xarchiver'
release='1'
version='0.5.4.20'
url='https://github.com/ib/xarchiver'
description='GTK+ frontend to various command line archivers'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/ib/xarchiver/archive/refs/tags/${version}.tar.gz")
depends=(gtk3 unrar p7zip gzip bzip2)
makedepends=(docbook-xsl intltool xmlto)
md5sums=('95c0e8a727faad16122d59889c105210')
group=(app.arch)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

