#!/usr/bin/env bash
name='libXfont2'
release='1'
version='2.0.6'
url='https://gitlab.freedesktop.org/xorg/lib/libXfont.git/'
description='X.Org Xfont library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXfont2-$version.tar.xz")
depends=()
makedepends=()
md5sums=('c179daa707f5f432f1bc13977e5bb329')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

