#!/usr/bin/env bash
name='smartypants'
release='1'
version='2.0.1'
url='https://github.com/leohemsted/smartypants.py/'
description='ASCII quote-dot-dash to HTML entity converter'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/leohemsted/smartypants.py/archive/refs/tags/v$version.tar.gz")
depends=(python)
makedepends=()
md5sums=('27957540f4718e892039b2ed208c78f3')
group=(dev.python)
uses=()
arch=('x86_64')

cd $name.py-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
