#!/usr/bin/env bash
name='yelp-xsl'
release='1'
version='42.1'
url='https://gitlab.gnome.org/GNOME/yelp-xsl'
description='XSL stylesheets for yelp'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/yelp-xsl/-/archive/$version/yelp-xsl-$version.tar.gz")
depends=()
makedepends=()
md5sums=('be9833ea51a6d45a94acf6103c9730d5')
group=(gnome.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
   autoreconf -fvi
	./configure --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

