#!/usr/bin/env bash
name=xz-utils
version=5.6.2
release=1
homepage='https://tukaani.org/xz/'
description='lzma compression utilities'
maintainer='kurth4cker'
email='kurth4cker@tutanota.com'
license=('GPLv2+')
source=("https://tukaani.org/xz/xz-${version}.tar.gz")
sha256sums=('8bfd20c0e1d86f0402f2497cfa71c6ab62d4cd35fd704276e3140bfb71414519')
group=(app.arch)
arch=(x86_64)
uses=(doc nls)

cd xz-$version

setup(){
    ./configure --prefix=/usr \
	--libdir=/usr/lib64 \
	--enable-static \
	--enable-shared \
	$(use_opt doc --enable-doc --disable-doc) \
	$(use_opt nls --enable-nls --disable-nls)
}
build(){
    make $jobs
}
package(){
    make install $jobs
}

