#!/usr/bin/env bash
name=xz-utils
release=3
version=5.8.1
homepage='https://tukaani.org/xz/'
description='lzma compression utilities'
maintainer='kurth4cker'
email='kurth4cker@tutanota.com'
license=('GPLv2+')
source=("https://tukaani.org/xz/xz-${version}.tar.gz")
sha256sums=('507825b599356c10dca1cd720c9d0d0c9d5400b9de300af00e4d1ea150795543')
group=(app.arch)
arch=(x86_64)
uses=(doc nls)

cd xz-$version

setup(){
    ./configure --prefix=/usr \
	--libdir=/usr/lib64 \
	--enable-static \
	--enable-shared \
	$(use_opt doc --enable-doc --disable-doc) \
	$(use_opt nls --enable-nls --disable-nls)
}
build(){
    make $jobs
}
package(){
    make install $jobs
}

