#!/usr/bin/env bash
name='graphviz'
release='3'
version='13.0.1'
url='https://www.graphviz.org/'
description='Graph Visualization Tools'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('EPL-1.0')
source=("https://gitlab.com/graphviz/graphviz/-/archive/$version/graphviz-$version.tar.gz")
depends=(expat gcc gcc gtk3 librsvg libtool libwebp pango zlib)
makedepends=()
sha256sums=('b91a80434f34986c47410b490d15ab1bd87fc7fea4e130161c8f029c548055a3')
group=(dev.python)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    touch redhat/graphviz.spec.rhel.in
    ./autogen.sh
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--disable-python \
		--disable-silent-rules \
		--disable-static \
		--disable-dependency-tracking \
		--disable-ltdl-install \
		--enable-ltdl \
		--enable-sharp=no \
		--enable-go=no \
		--enable-guile=no \
		--enable-java=no \
		--enable-lua=yes \
		--enable-ocaml=no \
		--enable-perl=no \
		--enable-php=no \
		--enable-python3 \
		--enable-r=no \
		--enable-ruby=no \
		--enable-tcl=no \
		--without-included-ltdl \
		--with-gdk-pixbuf=yes \
		--with-ipsepcola=yes \
		--with-jpeg \
		--with-libgd=yes \
		--with-pangocairo=yes \
		--with-rsvg=yes \
		--with-x
}

build () {
    make $jobs
}

package () {
    make DESTDIR=${DESTDIR} install $jobs
}

