#!/usr/bin/env bash
name='wireless-tools'
release='2'
version='30_pre9-17'
url='http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/Tools.html'
description='A collection of tools to configure IEEE 802.11 wireless LAN cards '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://salsa.debian.org/debian/wireless-tools/-/archive/debian/30_pre9-17/wireless-tools-debian-30_pre9-17.tar.gz")
depends=()
makedepends=()
sha256sums=('e0a5a76af530b887fc3846f59eb77be22a93c42289e37b76f0135ca3bf1d85d8')
group=(net.wireless)
uses=()
arch=('x86_64')

cd $name-debian-$version

build(){
    make $jobs
}

package(){
    make install $jobs \
        INSTALL_DIR="${DESTDIR}/usr/bin" \
        INSTALL_LIB="${DESTDIR}/usr/lib64" \
        INSTALL_INC="${DESTDIR}/usr/include" \
        INSTALL_MAN="${DESTDIR}/usr/share/man"
}

