#!/usr/bin/env bash
name='wireless-tools'
release='1'
version='30_pre9-13'
url='http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/Tools.html'
description='A collection of tools to configure IEEE 802.11 wireless LAN cards '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://salsa.debian.org/debian/wireless-tools/-/archive/debian/30_pre9-13/wireless-tools-debian-30_pre9-13.tar.gz")
depends=()
makedepends=()
md5sums=('c962c6c2e2a5e686e9464fcf73eb97b7')
group=(net.wireless)
uses=()
arch=('x86_64')

cd $name-debian-$version

build(){
    make $jobs
}

package(){
    make install $jobs \
        INSTALL_DIR="${DESTDIR}/usr/bin" \
        INSTALL_LIB="${DESTDIR}/usr/lib64" \
        INSTALL_INC="${DESTDIR}/usr/include" \
        INSTALL_MAN="${DESTDIR}/usr/share/man"
}

