#!/usr/bin/env bash
name='libinput'
release='4'
version='1.25.0'
url='https://gitlab.freedesktop.org/libinput/libinput'
description='Input device management and event handling library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/libinput/libinput/-/archive/$version/libinput-$version.tar.gz")
depends=(eudev mtdev libevdev)
makedepends=()
md5sums=('fc582c553e40be99bea49adf6d4aa669')
group=(dev.libs)
uses=()
uses_extra=(wacom)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dudev-dir=/lib64/udev \
        -Dlibwacom=$(use_opt wacom true false) \
        -Ddebug-gui=false \
        -Dtests=false
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

