#!/usr/bin/env bash
name='popt'
release='1'
version='1.19'
url='https://github.com/rpm-software-management/popt'
description='Parse Options - Command line parser'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/rpm-software-management/popt/archive/refs/tags/popt-$version-rc1.tar.gz")
depends=()
makedepends=()
md5sums=('d2e41e1338e1227826d986855344925b')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$name-$version-rc1

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

