#!/usr/bin/env bash
name='gst-plugins-good'
release='3'
version='1.24.7'
url='https://gitlab.freedesktop.org/gstreamer/'
description='GStreamer plugins'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-${version}.tar.xz")
#source=("https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/archive/$version/gst-plugins-good-$version.tar.gz")
depends=(gstreamer gst-plugins-base)
makedepends=()
sha256sums=('759acb11e6de8373ff8cbb5e7ab8eb9a38631be81cf24220267b001eb55593c1')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64 \
    -Dqt6=disabled
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}
