#!/usr/bin/env bash
name='gst-plugins-good'
release='1'
version='1.18.6'
url='https://gitlab.freedesktop.org/gstreamer/'
description='GStreamer plugins'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/-/archive/$version/gst-plugins-good-$version.tar.gz")
depends=()
makedepends=()
md5sums=('fa12514ea3a9d6e83b400a4d29051ab2')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}
