#!/usr/bin/env bash
name='mkinitrd'
release='5'
version='0.2.2'
url='https://gitlab.com/turkman/devel/sources/mkinitrd'
description='Initial ramdisk system from turkman linux'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/mkinitrd/-/archive/$version/mkinitrd-$version.tar.gz"
        "mkinitrd.sysconf")
depends=(eudev findutils coreutils)
makedepends=()
sha256sums=('5a39997b199bd940d417a0dfc62bad319f329623847b4c311dc6d19798204d1c'
            'SKIP')
uses=()
group=(sys.kernel)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr
}

package(){
    ninja -C build install
    # sysconf trigger
    mkdir -p $DESTDIR/etc/sysconf.d
    install ../mkinitrd.sysconf $DESTDIR/etc/sysconf.d/mkinitrd
}
