#!/usr/bin/env bash
name='mkinitrd'
release='9'
version='1.0.0'
url='https://gitlab.com/turkman/devel/sources/mkinitrd'
description='Initial ramdisk system from turkman linux'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/mkinitrd/-/archive/$version/mkinitrd-$version.tar.gz"
        "mkinitrd.sysconf")
depends=(findutils coreutils)
makedepends=()
sha256sums=('06729fefb21551ad3b487ab8922c2b5c95714704ee63caacd188e8a5c85923a0'
            'SKIP')
uses=()
group=(sys.kernel)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr
}

package(){
    ninja -C build install
    # sysconf trigger
    mkdir -p $DESTDIR/etc/sysconf.d
    install ../mkinitrd.sysconf $DESTDIR/etc/sysconf.d/mkinitrd
}
