#!/usr/bin/env bash
name='kconfig'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Configuration system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kconfig-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('e48e5315d3491ddfb878abf124a6e14886a6317857fa63f411ecd720da8a5d13')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

