#!/usr/bin/env bash
name='kconfig'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Configuration system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kconfig-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('517cbf6747df9289d6fce860a73d49e59354685334ae468ecd53f1067d9d618b')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

