#!/usr/bin/env bash
name='automake'
release='1'
version='1.16'
url='https://www.gnu.org/software/automake/'
description='A GNU tool for automatically configuring source code'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://ftp.gnu.org/gnu/automake/automake-1.16.tar.xz')
depends=(autoconf)
makedepends=( )
group=(sys.devel)
md5sums=('bfdf69ac36c327b3a59b83ab01057e30')
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

