#!/usr/bin/env bash
name='automake'
release='1'
version='1.16.5'
url='https://www.gnu.org/software/automake/'
description='A GNU tool for automatically configuring source code'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/automake/automake-${version}.tar.xz")
depends=(autoconf)
makedepends=( )
group=(sys.devel)
md5sums=('4017e96f89fca45ca946f1c5db6be714')
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

