#!/usr/bin/env bash
name='automake'
release='3'
version='1.18.1'
url='https://www.gnu.org/software/automake/'
description='A GNU tool for automatically configuring source code'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/automake/automake-${version}.tar.xz")
depends=(autoconf)
makedepends=( )
group=(sys.devel)
sha256sums=('168aa363278351b89af56684448f525a5bce5079d0b6842bd910fdd3f1646887')
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    # empty makeinfo file
    > $HOME/makeinfo
    chmod 0755 $HOME/makeinfo
    # run bootstrap
    ./bootstrap
}

setup(){
   autoreconf -fvi
   ./configure --prefix=/usr
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

