#!/usr/bin/env bash
name='gnupg'
release='2'
version='2.4.1'
url='https://www.gnupg.org/'
description='Complete and free implementation of the OpenPGP standard'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3' 'BSD' 'custom' 'GPL2' 'LGPL3' 'GPL2.1' 'MIT')
source=("https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-$version.tar.bz2")
depends=(libassuan libgcrypt libksba npth gnutls pinentry)
makedepends=()
md5sums=('b7436fb4a11af229428b52ba15ade8a2')
group=(app.crypt)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

