#!/usr/bin/env bash
name='breeze'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description='Artwork, styles and assets for the Breeze visual style for the Plasma Desktop'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/breeze-${version}.tar.xz")
depends=(breeze-icons frameworkintegration kcmutils kcolorscheme kconfig kcoreaddons kguiaddons ki18n kiconthemes kirigami
         kwidgetsaddons kwindowsystem qt6-base qt6-declarative kdecoration hicolor-icon-theme)
makedepends=(extra-cmake-modules)
sha256sums=('bc72a16b116b7beabf1b4e9a451019f9048e7be6b05ac73a4627f25b2c2059ea')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QT5=OFF \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}