#!/bin/bash
name=zlib
release=1
version=1.2.13
url='https://zlib.net'
description='A compression/decompression library'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('zlib')
source=("https://zlib.net/zlib-$version.tar.gz")
md5sums=('9b8aa094c4e5765dabf4da391f00d15c')
arch=(x86_64)
group=(system.base)

cd $name-$version

setup(){
    ./configure --prefix=/usr --libdir=/lib64/zlib --shared
    cd contrib/minizip
    autoreconf -fvi
	./configure --prefix=/usr --libdir=/lib64/zlib
}
build(){
    make -j$(nproc)
    cd contrib/minizip
    make -j$(nproc)
}
package(){
    make install pkgconfigdir="/usr/lib64/pkgconfig"
    cd contrib/minizip
    make install pkgconfigdir="/usr/lib64/pkgconfig"
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/lib64/zlib/" > ${DESTDIR}/etc/ld.so.conf.d/zlib.conf

}
