#!/usr/bin/env bash
name='xf86-video-vboxvideo'
release='1'
version='1.0.0'
url='https://gitlab.freedesktop.org/xorg/driver/xf86-video-vbox'
description='VirtualBox guest video driver'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://gitlab.freedesktop.org/xorg/driver/xf86-video-vbox/-/archive/xf86-video-vboxvideo-1.0.0/xf86-video-vbox-xf86-video-vboxvideo-1.0.0.tar.gz')
depends=()
makedepends=()
md5sums=('6cada475229a1735505ad62d645ce779')
group=(x11.drivers)
uses=()
arch=('x86_64')

cd xf86-video-vbox-$name-$version

setup(){
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install
}

