#!/usr/bin/env bash
name='gzip'
release='2'
version='1.13'
url='https://ftp.gnu.org/gnu/gzip'
description='Standard GNU compressor'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/gzip/gzip-$version.zip")
depends=()
makedepends=()
md5sums=('fdfa4ccc111f0de54a947fe041f2119a')
uses=()
group=(app.arch)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

