#!/usr/bin/env bash
name='perl'
release='2'
version='5.38.0'
url='https://www.cpan.org/src/'
description='A highly capable, feature-rich programming language'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://www.cpan.org/src/5.0/perl-$version.tar.gz")
depends=(gdbm libxcrypt libnsl)
makedepends=( )
md5sums=('06934f18763474c1e3c9312c158f5d0e')
uses=()
group=(dev.lang)
arch=('x86_64')

cd $name-$version

setup(){
    _baseversion="${version%.*}"
    ./Configure -des -Dusethreads -Duseshrplib -Doptimize="${CFLAGS}" \
        -Dprefix=/usr -Dvendorprefix=/usr \
        -Dprivlib=/usr/share/perl5/core_perl \
        -Darchlib=/usr/lib64/perl5/$_baseversion/core_perl \
        -Dsitelib=/usr/share/perl5/site_perl \
        -Dsitearch=/usr/lib64/perl5/$_baseversion/site_perl \
        -Dvendorlib=/usr/share/perl5/vendor_perl \
        -Dvendorarch=/usr/lib64/perl5/$_baseversion/vendor_perl \
        -Dscriptdir=/usr/bin/core_perl \
        -Dsitescript=/usr/bin/site_perl \
        -Dvendorscript=/usr/bin/vendor_perl \
        -Dinc_version_list=none \
        -Dman1ext=1perl -Dman3ext=3perl $(use_opt x86_86 -Dcccdlflags='-fPIC' "") \
        -Dlddlflags="-shared ${LDFLAGS}" -Dldflags="${LDFLAGS}"
}

build(){
    make $jobs
}

package(){
    make install $jobs
    rm -f ${DESTDIR}/*[0-9]
}

