#!/usr/bin/env bash
name='libxslt'
release='1'
version='1.1.37'
url='https://gitlab.gnome.org/GNOME/libxslt'
description=' XSLT libraries and tools '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/libxslt/-/archive/v$version/libxslt-v$version.tar.gz")
depends=()
makedepends=()
md5sums=('61f62b7efce418fe669825e350792c8a')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-v$version

setup(){
	autoreconf -fvi
  ./configure --prefix=/usr \
      --libdir=/usr/lib64/

}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

