#!/usr/bin/env bash
name='py3-cerberus'
release='3'
version='1.3.7'
url='http://python-cerberus.org/'
description='Lightweight, extensible data validation library for Python'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('ISC')
source=("https://github.com/pyeve/cerberus/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-setuptools py3-build py3-installer py3-wheel)
sha256sums=('2e74ba37eaac72c3a8efb09d61ce5ac80cc6e43df5f7688a67e832f40a4d9d73')
group=(dev.python)
uses=()
arch=('x86_64')

cd "cerberus"-$version

build(){
    python3 -m build --wheel --no-isolation
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
}


