#!/usr/bin/env bash
name='py3-cerberus'
release='1'
version='1.3.4'
url='http://python-cerberus.org/'
description='Lightweight, extensible data validation library for Python'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('ISC')
source=("https://github.com/pyeve/cerberus/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-setuptools)
md5sums=('df1416f38dc34f7db37d2f3026909f0d')
group=(dev.python)
uses=()
arch=('x86_64')

cd "cerberus"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}


