#!/usr/bin/env bash
name='xcb-util-errors'
release='1'
version='1.0.1'
url='https://www.x.org/archive/individual/lib/xcb-util-errors'
description='Package xcb-util-errors'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/xcb-util-errors-$version.tar.xz")
depends=()
makedepends=()
md5sums=('322cf9df283625223933ffcecb4a1cca')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

