#!/usr/bin/env bash
name='mozjs102'
release='1'
version='102.12.0'
url='https://spidermonkey.dev/'
description='JavaScript interpreter and libraries - Version 102'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MPL')
source=("https://salsa.debian.org/gnome-team/mozjs/-/archive/upstream/${version}/mozjs-upstream-${version}.tar.gz")
depends=()
makedepends=()
md5sums=('2c3edd3fa06881c60a4911a369d06ca7')
group=(gnome.extra)
uses=()
arch=('x86_64')

cd "mozjs-upstream"-$version

export MOZCONFIG=./mozconfig.opt
unset CARGO_PROFILE_RELEASE_OPT_LEVEL
unset CARGO_PROFILE_RELEASE_LTO
export CC=clang
export CXX=clang++
export CFLAGS="$CFLAGS -O2"
export CXXFLAGS="$CXXFLAGS -O2"
export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=system
export MOZBUILD_STATE_PATH="$srcdir/mozbuild"
export MOZ_NOSPAM=1
export PYTHON=/usr/bin/python3
export RUST_TARGET="$CTARGET"
export SHELL=/bin/ash
export RUSTFLAGS="$RUSTFLAGS -C debuginfo=1"
	
build(){
    ./mach build --directory $DESTDIR
}

package(){
    cd obj
	make DESTDIR="$DESTDIR" install
	rm -f "$DESTDIR"/usr/lib/*.ajs
}
