#!/usr/bin/env bash
name='granite'
release='1'
version='6.2.0'
url='https://github.com/elementary/granite'
description='Library that extends GTK with common widgets and utilities'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/elementary/granite/archive/refs/tags/$version.tar.gz")
depends=(gtk3 libgee)
makedepends=()
md5sums=('b5cb2159d784020667c87d21f82157c1')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

