#!/usr/bin/env bash
name='xapp'
release='3'
version='2.8.0'
url='https://github.com/linuxmint/xapp'
description='Common library for X-Apps project'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL')
source=("https://github.com/linuxmint/xapp/archive/$version/xapp-${version}.tar.gz")
depends=(libdbusmenu libgnomekbd)
makedepends=(vala py3-pygobject make gobject-introspection)
md5sums=('d987bbe17224a157d1bc1a7b30460c27')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}


build(){
    ninja -C build
}

package(){
    DESTDIR="${DESTDIR}" ninja -C build install
}

