#!/usr/bin/env bash
name='gtkmm3'
release='1'
version='3.24.7'
url='https://www.gtkmm.org/'
description='C++ bindings for GTK+ 3'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.gnome.org/sources/gtkmm/${version%.*}/gtkmm-${version}.tar.xz")
depends=(atkmm cairomm glibmm pangomm)
makedepends=(mm-common)
md5sums=('9576353c26db5e273a074264b68ad6cf')
group=(dev.cpp)
uses=()
arch=('x86_64')

cd "gtkmm"-$version

setup () {
	#autoreconf -fvi
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}

