#!/usr/bin/env bash
name='gtkmm3'
release='2'
version='3.24.9'
url='https://www.gtkmm.org/'
description='C++ bindings for GTK+ 3'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.gnome.org/sources/gtkmm/${version%.*}/gtkmm-${version}.tar.xz")
depends=(atkmm cairomm glibmm pangomm)
makedepends=(mm-common)
sha256sums=('30d5bfe404571ce566a8e938c8bac17576420eb508f1e257837da63f14ad44ce')
group=(dev.cpp)
uses=()
arch=('x86_64')

cd "gtkmm"-$version

setup () {
	#autoreconf -fvi
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}

