#!/usr/bin/env bash
name='xf86-video-ati'
release='2'
version='22.0.0'
url='https://gitlab.freedesktop.org/xorg/driver/xf86-video-ati.git/'
description='ATI video driver'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/driver/xf86-video-ati/-/archive/xf86-video-ati-$version/xf86-video-ati-xf86-video-ati-$version.tar.gz")
depends=()
makedepends=()
md5sums=('76ef17b7e770be446b87078f6ffaa6fe')
group=(x11.drivers)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install
}

