#!/usr/bin/env bash
name='nasm'
release='1'
version='2.16.01'
url='https://www.nasm.us/'
description='80x86 assembler designed for portability and modularity'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://www.nasm.us/pub/nasm/releasebuilds/${version}/nasm-${version}.tar.xz")
depends=(asciidoc xmlto)
makedepends=(diffutils)
md5sums=('d755ba0d16f94616c2907f8cab7c748b')
group=(dev.lang)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
    install -Dm 644 LICENSE -t "${DESTDIR}"/usr/share/licenses/nasm
}

