#!/usr/bin/env bash
name='wireplumber'
release='2'
version='0.5.6'
url='https://gitlab.freedesktop.org/pipewire/'
description='Session / policy manager implementation for PipeWire'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/$version/$name-$version.tar.gz")
depends=(pipewire)
makedepends=()
sha256sums=('ce7b7217d880bed1438e408ea412716a259cb46b09f597bfd652a577dc60185c')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    # force disable docs
    sed -i "s/^subdir('docs')//g" meson.build
}

setup(){
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64 \
    -Dsystem-lua=true \
		-Ddoc=disabled \
		-Dsystemd=disabled \
		-Dtests=false
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}

