#!/usr/bin/env bash
name='qt6-location'
release='3'
version='6.8.0'
url='https://www.qt.io/'
description='Helps you create viable mapping solutions using the data available from some of the popular location services'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtlocation-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative qt6-positioning)
makedepends=(cmake ninja)
sha256sums=('a0c487f4b36965ea921127033cc227acf1f292ba577081842c5b75d2ef9731a0')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtlocation-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}