#!/usr/bin/env bash
name='networkmanager'
release='1'
version='1.40.12'
url='https://gitlab.freedesktop.org/NetworkManager/NetworkManager'
description='network management daemon'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/archive/$version/NetworkManager-$version.tar.gz"
        "conf/30-random-mac.conf"
        "conf/networkmanager.conf"
        "conf/20-wifi-powersave.conf"
        "networkmanager.initd")
depends=(libndp nss newt)
makedepends=(libxslt gobject-introspection)
md5sums=('9495b3b631194bdeb701acfe8240e073'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP')
group=(net.misc)
uses=(ppp ovs)
arch=('x86_64')

ppp_depends=(ppp)
ovs_depends=(jansson)

cd NetworkManager-$version

unset CFLAGS
unset CXXFLAGS

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dsession_tracking=no \
        -Dsession_tracking_consolekit=false \
        -Dselinux=false \
        -Dpolkit=false \
        -Dcrypto=nss \
        -Dsystemd_journal=false \
        -Dsystemdsystemunitdir=no \
        -Dqt=false \
        -Dmodem_manager=false \
        -Dppp=$(use_opt ppp true false) \
        -Dovs=$(use_opt ovs true false) \
        -Dvapi=true \
        -Dtests=no
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    install -D -m644 ../networkmanager.initd "${DESTDIR}"/etc/init.d/networkmanager
    install -D -m644 ../networkmanager.conf "${DESTDIR}"/etc/NetworkManager/NetworkManager.conf
    install -D -m644 ../30-random-mac.conf "${DESTDIR}"/etc/NetworkManager/conf.d/
    install -D -m644 ../20-wifi-powersave.conf "${DESTDIR}"/etc/NetworkManager/conf.d/
    
}

