#!/usr/bin/env bash
name='kjsembed'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='JavaScript bindings for QObject'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/portingAids/kjsembed-${version}.tar.xz")
depends=(ki18n kjs qt5-svg)
makedepends=(extra-cmake-modules qt5-tools kdoctools)
md5sums=('10389619954ea07e8dbad87b989aa7d7')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

