#!/usr/bin/env bash
name='libXt'
release='2'
version='1.3.0'
url='https://gitlab.freedesktop.org/xorg/lib/libXt.git/'
description='X.Org X Toolkit Intrinsics library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXt-$version.tar.gz")
depends=(libSM libX11)
makedepends=()
md5sums=('62dfe73a164697f7b1723447cb26c4fd')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

