#!/usr/bin/env bash
name='libXt'
release='1'
version='1.2.1'
url='https://example.org'
description='Package libXt'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://www.x.org/archive/individual/lib/libXt-1.2.1.tar.gz')
depends=(libSM libX11)
makedepends=()
md5sums=('c98b235835a44fb7ced85a11914af900')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

