#!/usr/bin/env bash
name='kxmlgui'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='User configurable main windows'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kxmlgui-${version}.tar.xz")
depends=(kcolorscheme kconfig kconfigwidgets kcoreaddons kglobalaccel kguiaddons ki18n kiconthemes kitemviews kwidgetsaddons qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('75549dd54ae7b3e0bf01c6d82ebe2dcc797195ade223b6986dde9d688c5cd903')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

