#!/usr/bin/env bash
name='kxmlgui'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description='User configurable main windows'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kxmlgui-${version}.tar.xz")
depends=(kglobalaccel kiconthemes kitemviews)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('0e82d262cb9d08755d8ece168fc31022')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

