#!/usr/bin/env bash
name='kxmlgui'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='User configurable main windows'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kxmlgui-${version}.tar.xz")
depends=(kglobalaccel kiconthemes kitemviews)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('494846db7e48f1d999c7a374eaf9a1ff')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

