#!/usr/bin/env bash
name='xextproto'
release='1'
version='7.3.0'
url='https://example.org'
description='Package description missing'
email='bayramk@gmail.com'
maintainer='bayramkarahan'
license=('GPLv3')
source=("https://www.x.org/archive/individual/proto/xextproto-$version.tar.gz")
depends=()
makedepends=()
md5sums=('37b700baa8c8ea7964702d948dd13821')
group=(x11.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

