#!/usr/bin/env bash
name='exo'
release='2'
version='4.20.0'
_version='4.20'
url='https://docs.xfce.org/xfce/exo/start'
description='Application library for the Xfce desktop environment'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/exo/${_version}/exo-${version}.tar.bz2")
depends=(libxfce4ui libSM libICE)
makedepends=(intltool)
sha256sums=('4277f799245f1efde01cd917fd538ba6b12cf91c9f8a73fe2035fd5456ec078d')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}
