#!/usr/bin/env bash
name='py3-stemmer'
release='1'
version='2.2.0.1'
url='https://github.com/snowballstem/pystemmer'
description='String processing language for creating stemming algorithms'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/snowballstem/pystemmer/archive/refs/tags/v$version.tar.gz")
pyver=$(python -c "import sys; print(str( sys.version_info[0]) +\".\"+ str(sys.version_info[1] ))")
depends=(python"$pyver")
makedepends=()
md5sums=('8e4f6e0373a0571ed34cda2c8bf98d22')
group=(dev.python)
uses=()
arch=('x86_64')

cd pystemmer-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
    pyver=$(python -c "import sys; print(str( sys.version_info[0]) + str(sys.version_info[1] ))")
    for ver in 311 310 ; do
        if [[ ! -e ${DESTDIR}/usr/lib64/python3/Stemmer.cpython-$ver-$(uname -m)-linux-gnu.so ]] ; then
            ln -s Stemmer.cpython-$pyver-$(uname -m)-linux-gnu.so \
                ${DESTDIR}/usr/lib64/python3/Stemmer.cpython-$ver-$(uname -m)-linux-gnu.so
        fi
    done
}
