#!/usr/bin/env bash
name='py3-stemmer'
release='2'
version='3.0.0'
url='https://github.com/snowballstem/pystemmer'
description='String processing language for creating stemming algorithms'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/snowballstem/pystemmer/archive/refs/tags/v$version.tar.gz")
depends=(python)
makedepends=()
sha256sums=('e00740231deb135855141ef3d568b27c40b34d34e058b775ade6334a5859519f')
group=(dev.python)
uses=()
arch=('x86_64')

cd pystemmer-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}
