#!/usr/bin/env bash
name='spice-protocol'
release='1'
version='0.14.4'
url='https://gitlab.freedesktop.org/spice/spice-protocol'
description='Headers defining the SPICE protocol'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/spice/spice-protocol/-/archive/v${version}/spice-protocol-v${version}.tar.gz")
depends=()
makedepends=()
md5sums=('e4c4651efba3bed061ec2e874aa22f21')
group=(app.emulation)
uses=()
arch=('x86_64')

cd $name-v$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

