#!/usr/bin/env bash
name='kded'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Extensible deamon for providing system level services'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kded-${version}.tar.xz")
depends=(kconfig kservice kcrash kcoreaddons kdbusaddons qt6-base)
makedepends=(extra-cmake-modules)
sha256sums=('292ca941acc69c443f47895ea784493b08fd573afe0f4e99f5f42b8a029954b0')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
	rm -r "$DESTDIR"/usr/lib/systemd
}
