#!/usr/bin/env bash
name='kded'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Extensible deamon for providing system level services'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kded-${version}.tar.xz")
depends=(kconfig kservice kcrash kcoreaddons kdbusaddons qt6-base)
makedepends=(extra-cmake-modules)
sha256sums=('c6243233f2827b27b1a42987a7a3058f13853f7d0e2bf289c055f245d0c5c625')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
	rm -r "$DESTDIR"/usr/lib/systemd
}
