#!/usr/bin/env bash
name='networkmanager-qt'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Qt wrapper for NetworkManager API'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/networkmanager-qt-${version}.tar.xz")
depends=(networkmanager qt6-base )
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('225fc9f44e11d06687ce2ca56be7c7452f0ad2cc850b22f5715c8b701dabb700')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

