#!/usr/bin/env bash
name='networkmanager-qt'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Qt wrapper for NetworkManager API'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/networkmanager-qt-${version}.tar.xz")
depends=(networkmanager qt6-base )
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('563231644587918c950bcbe5fda0bf6a35e97a12f6b0e9bf9eaa4ce3141d3122')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

