#!/usr/bin/env bash
name='py3-pathspec'
release='3'
version='0.12.1'
url='https://github.com/cpburnz/python-path-specification'
description='Utility library for gitignore style pattern matching of file paths'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('MPL-2.0')
source=("https://github.com/cpburnz/python-pathspec/archive/refs/tags/v${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-flit py3-installer py3-wheel)
sha256sums=('dd47a400b58c965c93e1ee6723b8ac562ade44ebfcc12421075ebc8dbe7030a7')
group=(dev.python)
uses=()
arch=('x86_64')

cd "python-pathspec"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

