#!/usr/bin/env bash
name='qt5-quickcontrols'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='Reusable Qt Quick based UI controls to create classic desktop-style user interfaces'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtquickcontrols-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base qt5-declarative)
makedepends=()
sha256sums=('e3d33ab960b77934644e099174be14af1fdc86fd2bcafa3b5228b30809cd0303')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtquickcontrols-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}


