#!/usr/bin/env bash
name='sway'
release='2'
version='1.9'
url='https://github.com/swaywm/sway'
description=='i3-compatible Wayland window manager'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/swaywm/sway/archive/refs/tags/$version.zip"
        "sway.desktop")
depends=(wlroots json-c xorg-xwayland)
makedepends=()
sha256sums=('ee978ecb92d10ea799d746e9e73df7cd1b8138aed5361d55abfc6f59d82587f4'
            'SKIP')
group=(gui.wm)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dwerror=true \
        -Dtray=enabled
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    install -D -m644 ../sway.desktop \
		    -t "$DESTDIR"/usr/share/wayland-sessions/
}

