#!/usr/bin/env bash
name='sway'
release='5'
version='1.10.1'
bg_version='1.2.1'
url='https://github.com/swaywm/sway'
description=='i3-compatible Wayland window manager'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/swaywm/sway/archive/refs/tags/$version.zip"
        "https://github.com/swaywm/swaybg/archive/refs/tags/v${bg_version}.tar.gz"
        "sway.desktop")
depends=(wlroots json-c gdk-pixbuf cairo libevdev libinput pango vulkan-loader xcb-util-renderutil)
makedepends=()
sha256sums=('4f16cb8645eed1475398abadad3bc620a6da399efc7b157b547aa9e867701ec1'
            '45c4a1a3b83c86ddc321a6136402b708f195a022d0ccee4641b23d14c3a3c25e'
            'SKIP')
group=(gui.wm)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dwerror=false \
        -Dtray=enabled
    cd ..
    cd swaybg-${bg_version}
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dgdk-pixbuf=enabled
}

build(){
    ninja -C build
    ninja -C ../swaybg-${bg_version}/build
}

package(){
    ninja -C build install
    ninja -C ../swaybg-${bg_version}/build install
    install -D -m644 ../sway.desktop \
		    -t "$DESTDIR"/usr/share/wayland-sessions/
}

