#!/usr/bin/env bash
name='py3-build'
release='1'
version='0.10.0'
url='https://github.com/pypa/build/'
description='Easily download, build, install, upgrade, and uninstall Python packages'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pypa/build/archive/refs/tags/$version.tar.gz")
depends=(python py3-wheel)
makedepends=( )
md5sums=('1b219467065a5ac8fad9546c93a6332f')
uses=()
group=(dev.python)
arch=('x86_64')

cd build-$version

package(){
    mkdir -p $DESTDIR/usr/lib64/python3/build
    cp -prfv src/build/* $DESTDIR/usr/lib64/python3/build
}

