#!/usr/bin/env bash
name='kjs'
release='3'
version='5.116.0'
url='https://community.kde.org/Frameworks'
description='Support for JS scripting in applications'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/portingAids/kjs-${version}.tar.xz")
depends=(qt5-base pcre)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('9fb4f33e31d5b31eb6449311c1c61acaa968d42419252c0ab9dccb1f5fd9e1b7')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


