#!/usr/bin/env bash
name='kjs'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Support for JS scripting in applications'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/portingAids/kjs-${version}.tar.xz")
depends=(qt5-base pcre)
makedepends=(extra-cmake-modules kdoctools)
md5sums=('f7072f2078bc4c2048ed978c2683f8d6')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


