#!/usr/bin/env bash
name='kxmlrpcclient'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='JXML-RPC client library for KDE'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/portingAids/kxmlrpcclient-${version}.tar.xz")
depends=(kio)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('2b77b3339d21e4aa2b2cb6912de842dc')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=OFF \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
