#!/usr/bin/env bash
name='lxde-icon-theme'
release='2'
version='0.5.2'
url='https://lxde.org'
description='LXDE default icon theme based on nuoveXT2'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL')
source=("https://github.com/lxde/lxde-icon-theme/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=(intltool)
sha256sums=('5b71da247ba25ddcd991a3a184ca5ac92f40b7676766e1e59437067a20f7ecf7')
group=(lxde.base)
uses=()
arch=('x86_64')


export CC=clang

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

