#!/usr/bin/env bash
name='lxde-icon-theme'
release='1'
version='0.5.1'
url='https://lxde.org'
description='LXDE default icon theme based on nuoveXT2'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL')
source=("https://downloads.sourceforge.net/lxde/lxde-icon-theme-$version.tar.xz")
depends=()
makedepends=(intltool)
sha256sums=('e3d0b7399f28a360a3755171c9a08147d68f853f518be5485f5064675037916c')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

