#!/usr/bin/env bash
name='libksysguard'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='KDE system monitor library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/libksysguard-$version.tar.xz")
depends=(kauth kconfig kcoreaddons kdeclarative ki18n kirigami kitemmodels knewstuff kpackage kquickcharts kservice
         libnl libpcap qt6-base qt6-declarative solid zlib lm-sensors)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=('0286a90d0ae1a856efec05cd3a34b695fb2521a3b5b56af2d900c19950228278')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

