#!/usr/bin/env bash
name='libksysguard'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='KDE system monitor library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/libksysguard-$version.tar.xz")
depends=(kauth kconfig kcoreaddons kdeclarative ki18n kirigami kitemmodels knewstuff kpackage kquickcharts kservice
         libnl libpcap qt6-base qt6-declarative solid zlib lm-sensors)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=('c7cf8cd2f0a1e519201dc62889f1135967a850f932c252fd26ea3d88c6564a0f')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

