#!/usr/bin/env bash
name='libsecret'
release='2'
version='0.21.0'
url='https://gitlab.gnome.org/GNOME/libsecret'
description='GObject library for accessing the freedesktop.org Secret Service API'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/libsecret/-/archive/$version/libsecret-$version.tar.gz")
depends=(libgcrypt)
makedepends=()
md5sums=('8caa0c78c6f92b35b712906ba4f2ad0b')
group=(app.crypt)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

