#!/usr/bin/env bash
name='xf86-input-elographics'
release='1'
version='1.4.3'
url='https://gitlab.freedesktop.org/xorg/driver/xf86-input-elographics'
description='Elographics input driver'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/driver/xf86-input-elographics/-/archive/xf86-input-elographics-$version/xf86-input-elographics-xf86-input-elographics-$version.tar.gz")
depends=()
makedepends=()
md5sums=('db0b645df611b18fd338c9e4cb57a175')
group=(x11.drivers)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install
}

