#!/usr/bin/env bash
name='tslib'
release='1'
version='1.22'
url='https://github.com/kergoth/tslib'
description='Touchscreen Access Library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://github.com/libts/tslib/releases/download/${version}/tslib-${version}.tar.xz")
depends=()
makedepends=()
md5sums=('822139e5cc0ee2f0feaa6ce6628b989c')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

