#!/usr/bin/env bash
name='lsl'
release='1'
version='1.0.1'
url='https://sulincix/debian-subsystem'
description='Linux subsystem for linux'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.com/sulincix/debian-subsystem/-/archive/1.0.1/debian-subsystem-$version.tar.gz"
        "lsl.sysconf")
depends=(pam make perl)
makedepends=()
sha256sums=('5ac2d03b363650f50e51bd8232648d401310f67aee8432ffe61b1e3a6f3881a0'
            'SKIP')
group=(app.container)
uses=()
arch=('x86_64')

cd debian-subsystem-$version

build () {
    # parallel job build and install is not supported.
    make
}

package () {
    make install DESTDIR=$DESTDIR DISTRO=debian
    # install sysconf file
    mkdir -p $DESTDIR/etc/sysconf.d/
    install ../lsl.sysconf $DESTDIR/etc/sysconf.d/lsl
}

