#!/usr/bin/env bash
name='lsl'
release='2'
version='1.0.2'
url='https://sulincix/debian-subsystem'
description='Linux subsystem for linux'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.com/sulincix/debian-subsystem/-/archive/1.0.2/debian-subsystem-$version.tar.gz"
        "lsl.sysconf")
depends=(pam make perl)
makedepends=()
sha256sums=('526f8b80b452104a89cbbb42c7cbb655253e621f24c2086a63daab1229c38d89'
            'SKIP')
group=(app.container)
uses=()
arch=('x86_64')

cd debian-subsystem-$version

build () {
    # parallel job build and install is not supported.
    make
}

package () {
    make install DESTDIR=$DESTDIR DISTRO=debian
    # install sysconf file
    mkdir -p $DESTDIR/etc/sysconf.d/ $DESTDIR/etc/xdg/menus/
    install ../lsl.sysconf $DESTDIR/etc/sysconf.d/lsl
}

