#!/usr/bin/env bash
name='lsl'
release='3'
version='1.0.4'
url='https://sulincix/debian-subsystem'
description='Linux subsystem for linux'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.com/sulincix/debian-subsystem/-/archive/$version/debian-subsystem-$version.tar.gz"
        "lsl.sysconf")
depends=(pam make perl)
makedepends=()
sha256sums=('b4244039861c67a982e2f7a32c0ee6602012ee994c6d9cfa6646f44c939a4a0d'
            'SKIP')
group=(app.container)
uses=()
arch=('x86_64')

cd debian-subsystem-$version

build () {
    # parallel job build and install is not supported.
    make
}

package () {
    make install DESTDIR=$DESTDIR DISTRO=debian
    # install sysconf file
    mkdir -p $DESTDIR/etc/sysconf.d/ $DESTDIR/etc/xdg/menus/
    install ../lsl.sysconf $DESTDIR/etc/sysconf.d/lsl
    # suid allow register
    mkdir -p $DESTDIR/etc/suid.d/
    echo "/bin/lsl" > $DESTDIR/etc/suid.d/lsl
}

