#!/usr/bin/env bash
name='directx-headers'
release='3'
version='1.614.0'
url='https://github.com/microsoft/DirectX-Headers'
description='DirectX headers for using D3D12'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/microsoft/DirectX-Headers/archive/refs/tags/v${version}.tar.gz")
depends=()
makedepends=()
sha256sums=('1cd54449799501a4ad129a4c7ccf0c026bbb699f937ba299d92de3aacd29c5be')
group=(dev.util)
uses=()
arch=('x86_64')

cd "DirectX-Headers"-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/ \
		-Dbuild-test=false
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR="$DESTDIR" ninja -C build install $jobs
}

