#!/usr/bin/env bash
name='directx-headers'
release='4'
version='1.614.1'
url='https://github.com/microsoft/DirectX-Headers'
description='DirectX headers for using D3D12'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/microsoft/DirectX-Headers/archive/refs/tags/v${version}.tar.gz")
depends=()
makedepends=()
sha256sums=('344eb454c979ea68d8255d82c818bf7daf01f5109d26ac104f9911d18fae3b21')
group=(dev.util)
uses=()
arch=('x86_64')

cd "DirectX-Headers"-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/ \
		-Dbuild-test=false
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR="$DESTDIR" ninja -C build install $jobs
}

