#!/usr/bin/env bash
name='baloo-widgets'
release='4'
version='24.08.2'
url='https://www.kde.org/'
description='Widgets for Baloo'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/release-service/${version}/src/baloo-widgets-${version}.tar.xz")
depends=(baloo kio)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('b337a20b4681c82e8dd722313f57b58aa737e2d98420acc15124257a4d0263fe')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
    -DBUILD_WITH_QT6=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
