#!/usr/bin/env bash
name='baloo-widgets'
release='2'
version='24.02.2'
url='https://www.kde.org/'
description='Widgets for Baloo'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/release-service/${version}/src/baloo-widgets-${version}.tar.xz")
depends=(baloo kio)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('276b557c363da367d1c6950eb0e1ab2cae389aab7b53daf6a9e2431f87deea15')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
    -DBUILD_WITH_QT6=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
