#!/usr/bin/env bash
name='baloo-widgets'
release='3'
version='24.08.1'
url='https://www.kde.org/'
description='Widgets for Baloo'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/release-service/${version}/src/baloo-widgets-${version}.tar.xz")
depends=(baloo kio)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('979fe83b62a7f47b67377e5288b51d803c0622956f505bed2dbb0919ac4a7965')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
    -DBUILD_WITH_QT6=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
