#!/usr/bin/env bash
name='kpeople'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='A library that provides access to all contacts and the people who hold them'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kpeople-${version}.tar.xz")
depends=(kcontacts kcoreaddons ki18n kwidgetsaddons kitemviews qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools qt6-declarative)
sha256sums=('102cd7ad3260b0d10bd2ec0330c839826ea324c5cd86580163d8364d3370a6c2')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
