#!/usr/bin/env bash
name='py3-distro'
release='2'
version='1.9.0'
url='https://github.com/python-distro/distro'
description="A much more elaborate replacement for removed Python\'s platform.linux_distribution() method "
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/python-distro/distro/archive/refs/tags/v${version}.tar.gz")
depends=(python)
makedepends=()
md5sums=('cec5819e1367f0349b3ef2b3804f1e84')
group=(dev.python)
uses=()
arch=('x86_64')

cd distro-$version


build () {
    python -m build --wheel
    make $jobs
}

package () {
    python -m installer --destdir="${DESTDIR}" dist/*.whl
}

