#!/usr/bin/env bash
name='py3-distro'
release='3'
version='1.9.0'
url='https://github.com/python-distro/distro'
description="A much more elaborate replacement for removed Python\'s platform.linux_distribution() method "
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/python-distro/distro/archive/refs/tags/v${version}.tar.gz")
depends=(python)
makedepends=(py3-sphinx  py3-build py3-installer py3-wheel py3-setuptools)
sha256sums=('6ede051357868ed427ea71d16fc27f4d63cc0d9c8a32788aa11c450ecefcc76f')
group=(dev.python)
uses=()
arch=('x86_64')

cd distro-$version


build () {
    python -m build --wheel
}

package () {
    python -m installer --destdir="${DESTDIR}" dist/*.whl
    mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}

