#!/usr/bin/env bash
name='py3-hotdoc'
release='2'
version='0.17.4'
url='https://pypi.org/project/hotdoc/'
description='A documentation tool micro-framework'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
#source=("https://github.com/hotdoc/hotdoc/archive/refs/tags/$version.tar.gz")
source=(https://files.pythonhosted.org/packages/60/fd/32e24a747181e060ace04cd927698b2b5b3b90f6bf2c014e12df630c183a/hotdoc-0.17.4.tar.gz)

depends=(python json-glib)
makedepends=()
sha256sums=('c4d5dff647f03aa87a1d2d06035d2819edd099b91635e3b2ee390829357ae9fc')
group=(dev.python)
uses=()
arch=('x86_64')

cd hotdoc-$version

build(){
    python setup.py build
}

package(){
    python setup.py install --root="${DESTDIR}" --optimize=1 --skip-build

}

