#!/usr/bin/env bash
name='hotdoc'
release='1'
version='0.14.0'
url='https://pypi.org/project/hotdoc/'
description='A documentation tool micro-framework'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://files.pythonhosted.org/packages/56/ad/c3c7fb2cae9baa369317600d66f41ecbf723867f3e19e5dd56aed09b7ed0/hotdoc-$version.tar.gz")
depends=(python)
makedepends=()
md5sums=('1cd551b2d565877537ffa0854d6ecaee')
group=(dev.python)
uses=()
arch=('x86_64')

cd hotdoc-$version

build(){
    python setup.py build
}

package(){
    python setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build

}

