#!/usr/bin/env bash
name='kactivities'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Core components for the KDE s Activities'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kactivities-${version}.tar.xz")
depends=(boost kconfig kcoreaddons kwindowsystem qt5-declarative)
makedepends=(doxygen extra-cmake-modules qt5-tools)
md5sums=('36869f6c92c2d914d4a48eb80b259934')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


