#!/usr/bin/env bash
name='libkscreen'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='KDE screen management software'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/libkscreen-${version}.tar.xz")
depends=(qt6-base qt6-wayland wayland libxcb)
makedepends=(extra-cmake-modules doxygen qt6-tools plasma-wayland-protocols)
sha256sums=('68d26e27656b450f15a78f44784c50a22034e57c14f96a402019d52bc5b3e2b4')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

