#!/usr/bin/env bash
name='libkscreen'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='KDE screen management software'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/libkscreen-${version}.tar.xz")
depends=(qt5-x11extras kwayland kconfig)
makedepends=(extra-cmake-modules doxygen qt5-tools plasma-wayland-protocols)
md5sums=('5be369e023867db462926ea20dc47d94')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

