#!/usr/bin/env bash
name='poppler'
release='4'
version='24.03.0'
url='https://poppler.freedesktop.org/'
description='PDF rendering library based on xpdf 3.0'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPL')
source=("https://poppler.freedesktop.org/poppler-${version}.tar.xz")
depends=(cairo lcms2 libjpeg-turbo libpng libxml2 nss libtiff zlib)
makedepends=(boost cmake fontconfig gobject-introspection)
sha256sums=('bafbf0db5713dec25b5d16eb2cd87e4a62351cdc40f050c3937cd8dd6882d446')
group=(app.text)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
		-DENABLE_UNSTABLE_API_ABI_HEADERS=ON \
    	-DENABLE_LIBOPENJPEG=none \
		-DBUILD_QT5_TESTS=OFF \
		-DBUILD_QT6_TESTS=OFF \
		-DBUILD_GTK_TESTS=OFF \
		-DBUILD_CPP_TESTS=OFF \
		-DBUILD_MANUAL_TESTS=OFF \
		-DENABLE_QT5=ON \
		-DENABLE_QT6=ON \
		-DENABLE_BOOST=OFF
}

build () {
    cmake --build build
}

package () {
    #DESTDIR="$DESTDIR" cmake --install build

	install -Dm644 build/poppler-qt5.pc -t "$DESTDIR"/usr/lib/pkgconfig/
	install -Dm644 build/poppler-qt6.pc -t "$DESTDIR"/usr/lib/pkgconfig/
	DESTDIR="$DESTDIR" cmake --install build/qt5
	DESTDIR="$DESTDIR" cmake --install build/qt6
}

