#!/usr/bin/env bash
name='poppler'
release='2'
version='23.10.0'
url='https://poppler.freedesktop.org/'
description='PDF rendering library based on xpdf 3.0'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL')
source=("https://poppler.freedesktop.org/poppler-${version}.tar.xz")
depends=(cairo)
makedepends=(boost cmake fontconfig gobject-introspection lcms2 libjpeg-turbo libpng libxml2 nss openjpeg
	libtiff zlib)
md5sums=('3be79099d8725debef73ea07502b771a')
group=(app.text)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=/usr/lib64 \
		-DENABLE_UNSTABLE_API_ABI_HEADERS=ON \
		-DBUILD_QT5_TESTS=OFF \
		-DBUILD_QT6_TESTS=OFF \
		-DBUILD_GTK_TESTS=OFF \
		-DBUILD_CPP_TESTS=OFF \
		-DBUILD_MANUAL_TESTS=OFF \
		-DENABLE_QT5=OFF \
		-DENABLE_QT6=OFF \
		-DENABLE_BOOST=OFF \
		$CMAKE_CROSSOPTS
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

