#!/usr/bin/env bash
name='diffutils'
release='2'
version='3.10'
url='https://ftp.gnu.org/gnu/diffutils/'
description='Utility programs used for creating patch files'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/diffutils/diffutils-$version.tar.xz")
depends=(bash)
makedepends=()
md5sums=('2745c50f6f4e395e7b7d52f902d075bf')
uses=()
group=(sys.apps)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

