#!/usr/bin/env bash
name='diffutils'
release='1'
version='3.8'
url='https://ftp.gnu.org/gnu/diffutils/'
description='Utility programs used for creating patch files'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/diffutils/diffutils-$version.tar.xz")
depends=(bash)
makedepends=()
md5sums=('6a6b0fdc72acfe3f2829aab477876fbc')
uses=()
group=(sys.apps)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

