#!/usr/bin/env bash
name='kwayland'
release='5'
version='6.4.5'
url='https://community.kde.org/Frameworks'
description='Qt-style Client and Server library wrapper for the Wayland libraries'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/plasma/${version}/kwayland-${version}.tar.xz")
#source=("https://download.kde.org/stable/frameworks/${version%.*}/kwayland-${version}.tar.xz")
depends=(qt6-base qt6-wayland wayland)
makedepends=(extra-cmake-modules doxygen qt6-tools wayland-protocols plasma-wayland-protocols)
sha256sums=('0b875d9e7cc5bac4d97d3443ff4311533e0d8dad401af1244d4758a5fa5428f3')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
