#!/usr/bin/env bash
name='kholidays'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='KDE library for regional holiday information'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kholidays-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules qt6-declarative qt6-tools doxygen)
sha256sums=('482f6375fe536a63b67bad45a0ad3880c74d74fc92a3a935ecb78b29830d9b7f')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

