#!/usr/bin/env bash
name='gpgme'
release='3'
version='1.23.1'
url='https://www.gnupg.org/ftp/gcrypt/gpgme'
description='gnupg made easy'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-$version.tar.bz2")
depends=(gnupg)
makedepends=()
md5sums=('6382b05365315fe0494469c3e71e935e')
group=(app.crypt)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

