#!/usr/bin/env bash
name='libnvme'
release='5'
version='1.11.1'
url='https://example.org'
description='C Library for NVM Express on Linux'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/linux-nvme/libnvme/archive/refs/tags/v${version}/libnvme-${version}.tar.gz")
depends=(json-c openssl linux-headers)
makedepends=(dbus	meson python util-linux)
sha256sums=('6d5d8ba2cc4c94a61a994c9f7f25b3b26ef973fb5c0daa37729890903f37a1f1')
group=(sys.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/ \
		-Ddefault_library=both
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR="$DESTDIR" ninja -C build install $jobs
}

