#!/usr/bin/env bash
name='libnvme'
release='2'
version='1.6'
url='https://example.org'
description='C Library for NVM Express on Linux'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/linux-nvme/libnvme/archive/refs/tags/v${version}/libnvme-${version}.tar.gz")
depends=(json-c openssl linux-headers)
makedepends=(dbus	meson python util-linux)
md5sums=('35e840e895bece4d84707695afae3012')
group=(sys.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/ \
		-Ddefault_library=both
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR="$DESTDIR" ninja -C build install $jobs
}

