#!/usr/bin/env bash
name='tk'
release='1'
version='8.6.13'
url='https://tcl.sourceforge.net/'
description='GUI toolkit for the Tcl scripting language'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('TCL')
source=("https://downloads.sourceforge.net/sourceforge/tcl/tk${version}-src.tar.gz")
depends=(tcl libX11 libxss libXft fontconfig)
makedepends=()
md5sums=('95adc33d55a133ee29bc9f81efdf31b2')
group=(dev.lang)
uses=()
arch=('x86_64')

cd $name$version"/unix"

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--mandir=/usr/share/man \
		--enable-threads \
		--disable-rpath \
		--enable-64bit
}

build(){
    make
}

package(){
    make INSTALL_ROOT="${DESTDIR}" install install-private-headers
}

