#!/usr/bin/env bash
name='xkbcomp'
release='1'
version='1.4.6'
url='https://gitlab.freedesktop.org/xorg/app/xkbcomp'
description='XKB keyboard description compiler'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/app/xkbcomp/-/archive/xkbcomp-$version/xkbcomp-xkbcomp-$version.tar.gz")
depends=(libxkbfile libX11)
makedepends=()
md5sums=('f95811772ae9c103d0eed792160254c0')
group=(x11.apps)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

