#!/usr/bin/env bash
name='cinnamon-control-center'
release='3'
version='6.2.0'
url='https://github.com/linuxmint/cinnamon-control-center'
description='The Control Center for Cinnamon'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://github.com/linuxmint/cinnamon-control-center/archive/refs/tags/${version}.tar.gz")
depends=(cinnamon-settings-daemon cinnamon-menus colord libgnomekbd)
makedepends=(meson)
sha256sums=('f3e5caf03c4d629fbaf883caa816fe799685438d650012621e51457583000d07')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
     		--libdir=/usr/lib64/ \
    		-Dmodemmanager=false \
    		-Donlineaccounts=false
}

build () {
    ninja -C build $jobs
}

package () {
     ninja -C build install $jobs
}

