#!/usr/bin/env bash
name='muffin'
release='2'
version='6.0.0'
url='https://github.com/linuxmint/muffin'
description='Cinnamon window manager based on Mutter'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/linuxmint/muffin/archive/refs/tags/${version}.tar.gz")
depends=(cinnamon-desktop gobject-introspection libcanberra libinput
         libSM libxkbcommon startup-notification zenity graphene pipewire
         xorg-xwayland)
makedepends=(meson intltool gobject-introspection wayland-protocols)
md5sums=('884b3aadc288cd2c3c4ce9957e19f0e8')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
