#!/usr/bin/env bash
name='muffin'
release='3'
version='6.2.0'
url='https://github.com/linuxmint/muffin'
description='Cinnamon window manager based on Mutter'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://github.com/linuxmint/muffin/archive/refs/tags/${version}.tar.gz")
depends=(cinnamon-desktop gobject-introspection libcanberra libinput
         libSM libxkbcommon startup-notification zenity graphene pipewire
         xorg-xwayland)
makedepends=(meson intltool gobject-introspection wayland-protocols)
sha256sums=('889200ceb45334899e7568f1735ec2b15e1ae042d176821a0d45c524960bee0a')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
