#!/usr/bin/env bash
name='muffin'
release='4'
version='6.4.1'
url='https://github.com/linuxmint/muffin'
description='Cinnamon window manager based on Mutter'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://github.com/linuxmint/muffin/archive/refs/tags/${version}.tar.gz")
depends=(cinnamon-desktop gobject-introspection libcanberra libinput
         libSM libxkbcommon startup-notification zenity graphene pipewire
         xorg-xwayland)
makedepends=(meson intltool gobject-introspection wayland-protocols)
sha256sums=('3c4ef0139d9bbaf7ac17f39dd06b6397c175614a2eb6c55d463024a457293808')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
