#!/usr/bin/env bash
name='py3-mako'
release='1'
version='1.2.4'
url='https://pypi.org/project/Mako/'
description='A super-fast templating language that borrows the best ideas from the existing templating languages.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://files.pythonhosted.org/packages/05/5f/2ba6e026d33a0e6ddc1dddf9958677f76f5f80c236bd65309d280b166d3e/Mako-${version}.tar.gz")
depends=(python py3-markupsafe)
makedepends=()
md5sums=('651f365616611fcd4f2702a9002e2195')
group=(dev.python)
uses=()
arch=('x86_64')

cd Mako-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

