#!/usr/bin/env bash
name='py3-mako'
release='4'
version='1.3.10'
url='https://pypi.org/project/Mako/'
description='A super-fast templating language that borrows the best ideas from the existing templating languages.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/sqlalchemy/mako/archive/refs/tags/rel_${version//./_}.tar.gz")
depends=(python py3-markupsafe)
makedepends=()
sha256sums=('e8f1334904611d5cb357b6396790fd4375ac21ad901f4314d222d5d5758979b9')
group=(dev.python)
uses=()
arch=('x86_64')

cd mako-rel_${version//./_}

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

