#!/usr/bin/env bash
name='spirv-llvm-translator'
release='2'
version='16.0.0'
url='https://github.com/KhronosGroup/SPIRV-LLVM-Translator'
description='Bi-directional translator between SPIR-V and LLVM IR'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
#source=("https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/v$version/SPIRV-LLVM-Translator-$version.tar.gz")
_commit="322fca5d9c59bfdb80562a52ace51cdbe2a60e92"
source=("https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/${_commit}.zip")
depends=(spirv-tools llvm)
makedepends=()
md5sums=('bd23f9249cea9a33f7ad507bdb3683b3')
group=(dev.util)
uses=()
arch=('x86_64')

cd SPIRV-LLVM-Translator-$version
cd SPIRV-LLVM-Translator-${_commit}

setup(){
    mkdir build && cd build
    cmake .. -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_SHARED_LIBS=True \
        -DLLVM_SPIRV_INCLUDE_TESTS=1 \
        -DLLVM_EXTERNAL_LIT=/usr/bin/lit \
        -DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=/usr/include/spirv

}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

