#!/usr/bin/env bash
name='phonon'
release='1'
version='4.11.1'
url='https://download.kde.org/stable/phonon'
description='Phonon is the multimedia API for KDE. It replaces the old aRts package.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/phonon/$version/phonon-$version.tar.xz")
depends=(qt5-base)
makedepends=(extra-cmake-modules qt5-tools)
md5sums=('d3df5ba646e4b3f11623d998caa40e74')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DPHONON_INSTALL_QT_EXTENSIONS_INTO_SYSTEM_QT=FALSE \
		    -DPHONON_BUILD_PHONON4QT5=ON \
        ..
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

