#!/usr/bin/env bash
name='phonon'
release='2'
version='4.12.0'
url='https://download.kde.org/stable/phonon'
description='Phonon is the multimedia API for KDE. It replaces the old aRts package.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/phonon/$version/phonon-$version.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=('3287ffe0fbcc2d4aa1363f9e15747302d0b080090fe76e5f211d809ecb43f39a')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DPHONON_INSTALL_QT_EXTENSIONS_INTO_SYSTEM_QT=FALSE \
		    -DPHONON_BUILD_QT5=OFF \
        ..
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

