#!/usr/bin/env bash
name='py3-feedgen'
release='1'
version='0.9.0'
url='https://github.com/lkiesow/python-feedgen'
description='feedgen Python 2 and 3 compatibility library '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lkiesow/python-feedgen/archive/refs/tags/v$version.tar.gz")
depends=(python)
makedepends=()
md5sums=('1d5bc899ec8e506391674413911b15dc')
group=(dev.python)
uses=()
arch=('x86_64')

cd python-feedgen-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
