#!/usr/bin/env bash
name='plasma-activities'
release='3'
version='6.5.0'
url='https://download.kde.org/stable/frameworks'
description='A library for accessing the usage data collected by the activities system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/plasma-activities-$version.tar.xz")
depends=(qt6-base)
makedepends=(qt6-tools)
sha256sums=('e0efff427b2155b09784851fa1645511ffb93629e557e887ec5dacff2fe223a0')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DBUILD_TESTING=OFF \
        -DBUILD_QCH=ON
}

build () {
    cmake --build build
}

package () {
    cmake --install build
}

