#!/usr/bin/env bash
name='cairomm'
release='2'
version='1.14.5'
url='https://www.cairographics.org/cairomm/'
description='C++ bindings for Cairo'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL' 'MPL')
source=("https://www.cairographics.org/releases/cairomm-${version}.tar.xz")
depends=(cairo libsigc++)
makedepends=(mm-common)
sha256sums=('70136203540c884e89ce1c9edfb6369b9953937f6cd596d97c78c9758a5d48db')
group=(dev.cpp)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}

