#!/usr/bin/env bash
name='cairomm'
release='1'
version='1.14.4'
url='https://www.cairographics.org/cairomm/'
description='C++ bindings for Cairo'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL' 'MPL')
source=("https://www.cairographics.org/releases/cairomm-${version}.tar.xz")
depends=()
makedepends=()
md5sums=('7c37f213f9f0d7d8a69030c3d18bb8aa')
group=(dev.cpp)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}

