#!/usr/bin/env bash
name='cairomm'
release='2'
version='1.18.0'
url='https://www.cairographics.org/cairomm/'
description='C++ bindings for Cairo'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL' 'MPL')
source=("https://www.cairographics.org/releases/cairomm-${version}.tar.xz")
depends=(cairo libsigc++)
makedepends=()
sha256sums=('b81255394e3ea8e8aa887276d22afa8985fc8daef60692eb2407d23049f03cfb')
group=(dev.cpp)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}

