#!/usr/bin/env bash
name='libclc'
release='3'
version='18.1.8'
url='https://libclc.llvm.org/'
description='Open source implementation of the library requirements of the OpenCL C programming language'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/llvm/llvm-project/releases/download/llvmorg-$version/libclc-$version.src.tar.xz")
depends=(spirv-llvm-translator)
makedepends=()
sha256sums=('905bd59e9f810d6bd0ae6874725a8f8a3c91cb416199c03f2b98b57437cfb32e')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version.src

setup(){
    mkdir build && cd build
    cmake .. -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

