#!/usr/bin/env bash
name='libclc'
release='4'
version='19.1.7'
url='https://libclc.llvm.org/'
description='Open source implementation of the library requirements of the OpenCL C programming language'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/llvm/llvm-project/releases/download/llvmorg-$version/libclc-$version.src.tar.xz")
depends=(spirv-llvm-translator)
makedepends=()
sha256sums=('77e2d71f5cea1d0b1014ba88186299d1a0848eb3dc20948baae649db9e7641cb')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version.src

setup(){
    mkdir build && cd build
    cmake .. -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

