#!/usr/bin/env bash
name='cantarell-fonts'
release='1'
version='0.303.1'
url='https://gitlab.gnome.org/GNOME/cantarell-fonts.git/'
description='Default fontset for GNOME Shell '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.gnome.org/sources/cantarell-fonts/${version:0:5}/cantarell-fonts-${version}.tar.xz")
depends=()
makedepends=()
md5sums=('a9be59ddb29204dcfd3357f201949b8c')
group=(media.fonts)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
	-Duseprebuilt=true
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

