#!/usr/bin/env bash
name='py3-pygments'
release='5'
version='2.17.2'
url='https://pypi.org/project/Pygments'
description='Pygments is a syntax highlighting package written in Python.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pygments/pygments/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=()
md5sums=('33dc62d82b628ba4ce78b4929b851157')
group=(dev.python)
uses=()
arch=('x86_64')

cd pygments-$version

build(){
    python -m build --wheel
}

package(){
	python -m installer --destdir="$DESTDIR" dist/*.whl
}
