#!/usr/bin/env bash
name='py3-pygments'
release='1'
version='2.14.0'
url='https://pypi.org/project/Pygments'
description='Pygments is a syntax highlighting package written in Python.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://files.pythonhosted.org/packages/da/6a/c427c06913204e24de28de5300d3f0e809933f376e0b7df95194b2bb3f71/Pygments-2.14.0.tar.gz')
depends=(python)
makedepends=()
md5sums=('447be4afb076c8325a7dc659aff5b931')
group=(dev.python)
uses=()
arch=('x86_64')

cd Pygments-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
