#!/usr/bin/env bash
name='py3-pygments'
release='2'
version='2.15.1'
url='https://pypi.org/project/Pygments'
description='Pygments is a syntax highlighting package written in Python.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pygments/pygments/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=()
md5sums=('8f3575093e63ffaf2c9b605e35f3286d')
group=(dev.python)
uses=()
arch=('x86_64')

cd pygments-$version

build(){
    python -m build --wheel --no-isolation
}

package(){
	python -m installer --destdir="$DESTDIR" dist/*.whl
}
