#!/bin/bash
name=libtasn1
release=1
version=4.19.0
url='https://gitlab.com/sulinos/devel/ymp'
description='Manage ASN.1 structures'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=('https://ftp.gnu.org/gnu/libtasn1/libtasn1-4.19.0.tar.gz')
md5sums=('f701ab57eb8e7d9c105b2cd5d809b29a') # replace this
arch=(x86_64)
group=(dev.libs)

cd "libtasn1-$version"

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/libtasn1
}
build(){
    make -j`nproc`
}
package(){
    make -j`nproc` install
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/usr/lib64/libtasn1/" > ${DESTDIR}/etc/ld.so.conf.d/libtasn1.conf
    mv ${DESTDIR}/usr/lib64/{$name/pkgconfig,}
}
