#!/usr/bin/env bash
name='xfconf'
release='2'
version='4.18.3'
_version='4.18'
url='https://docs.xfce.org/xfce/xfconf/start'
description='D-Bus-based configuration storage system'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfconf/${_version}/xfconf-${version}.tar.bz2")
depends=( libxfce4util)
makedepends=(gobject-introspection intltool vala)
sha256sums=('c56cc69056f6947b2c60b165ec1e4c2b0acf26a778da5f86c89ffce24d5ebd98')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

