#!/usr/bin/env bash
name='xfconf'
release='1'
version='4.18.1'
_version='4.18'
url='https://docs.xfce.org/xfce/xfconf/start'
description='D-Bus-based configuration storage system'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfconf/${_version}/xfconf-${version}.tar.bz2")
depends=( libxfce4util)
makedepends=(gobject-introspection intltool vala)
md5sums=('60519958af4178d9bf110087a9c4a118')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

