#!/usr/bin/env bash
name='xfconf'
release='3'
version='4.20.0'
_version='4.20'
url='https://docs.xfce.org/xfce/xfconf/start'
description='D-Bus-based configuration storage system'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfconf/${_version}/xfconf-${version}.tar.bz2")
depends=( libxfce4util)
makedepends=(gobject-introspection intltool vala)
sha256sums=('8bc43c60f1716b13cf35fc899e2a36ea9c6cdc3478a8f051220eef0f53567efd')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

