#!/usr/bin/env bash
name='libmm-glib'
release='1'
version='1.20.6'
url='https://www.freedesktop.org/wiki/Software/ModemManager'
description='ModemManager library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
#source=("https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/archive/${version}/ModemManager-${version}.tar.gz" 
source=("https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/archive/1.20.6/ModemManager-1.20.6.tar.gz"
"modemmanager.rules" "modemmanager.initd")
depends=(dbus polkit )
makedepends=(bash-completion elogind gobject-introspection gtk-doc libgudev linux-headers meson)
md5sums=('6bedca29d590d90815b2c9a732fc31f9' 'SKIP' 'SKIP')
group=(net.misc)
uses=()
arch=('x86_64')

cd "ModemManager"-$version

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/ \
		-Db_lto=true \
		-Dsystemdsystemunitdir=no \
		-Ddbus_policy_dir=/usr/share/dbus-1/system.d \
		-Dgtk_doc=true \
		-Dpolkit=permissive \
		-Dsystemd_journal=false \
		-Dsystemd_suspend_resume=true \
		-Dvapi=true \
		-Dmbim=false \
		-Dqmi=false \
		-Dqrtr=false
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
	install -m644 -D "../modemmanager.rules" "$DESTDIR/usr/share/polkit-1/rules.d/01-org.freedesktop.ModemManager.rules"
	install -m755 -D "../modemmanager.initd" "$DESTDIR/etc/init.d/$name"
}

#libmbim 
#libqmi
