#!/usr/bin/env bash
name='libfm'
release='2'
version='1.4.0'
url='https://example.org'
description='Library for file management'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/libfm/archive/refs/tags/$version.tar.gz"
        'libfm-fixes.patch')
depends=(gtk3 pango intltool menu-cache)
makedepends=()
sha256sums=('7d7b616411992389a4b7f35796109d605f30bc2ceab84d4081d1665254ebbf82'
         'SKIP')
group=(x11.libs)
uses=()
uses_extra=(extra-only)
arch=('x86_64')

cd $name-$version

export CC=clang

setup(){
    autoreconf -fvi
	  ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
	      --with-gtk=3 \
	     $(use_opt extra-only --with-extra-only "")
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

