#!/usr/bin/env bash
name='libfm'
release='1'
version='1.3.2'
url='https://example.org'
description='Library for file management'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://github.com/lxde/libfm/archive/refs/tags/1.3.2.tar.gz'
        'libfm-fixes.patch')
depends=(gtk3 pango intltool menu-cache)
makedepends=()
md5sums=('8b2864ba2d21586171ab9616b5610aeb'
         'SKIP')
group=()
uses=()
uses_extra=(extra-only)
arch=('x86_64')

cd $name-$version

prepare(){
    patch -Np1 -i ../libfm-fixes.patch
}

setup(){
    autoreconf -fvi
	  ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
	      --with-gtk=3 \
	     $(use_opt extra-only --with-extra-only "")
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

