#!/usr/bin/env bash
name='libfm'
release='1'
version='1.3.2'
url='https://example.org'
description='Package description missing'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://github.com/lxde/libfm/archive/refs/tags/1.3.2.tar.gz')
depends=(gtk3 pango intltool)
makedepends=()
md5sums=('8b2864ba2d21586171ab9616b5610aeb')
group=()
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    	./autogen.sh
	./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
	--with-gtk=3 \
	--with-extra-only
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

