#!/usr/bin/env bash
name='live-boot'
release='2'
version='1.0'
url='https://gitlab.com/turkman'
description='initramfs tools live hooks'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/live-boot/-/archive/$version/live-boot-$version.tar.gz")
depends=(initramfs-tools)
makedepends=()
md5sums=('069de262fbb125fe931bd0e628046a4b')
group=(sys.kernel)
uses=()
arch=('x86_64')

cd $name-$version

package(){
    make install
}

