#!/usr/bin/env bash
name='live-boot'
release='6'
version='2.2'
url='https://gitlab.com/turkman/devel/sources/live-boot'
description='initramfs tools live hooks'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/live-boot/-/archive/$version/live-boot-$version.tar.gz")
depends=(mkinitrd)
makedepends=()
sha256sums=('45d3b8f64ae9b5a3c0288a313d707694e0f3a42adb0ef9d54f20f63465bb2e66')
group=(sys.kernel)
uses=()
arch=('x86_64')

cd $name-$version

package(){
    make install
}

