#!/usr/bin/env bash
name='font-bitstream-type1'
release='1'
version='1.0.3'
url='https://gitlab.freedesktop.org/xorg/font/bitstream-type1'
description='X.Org Bitstream Type 1 fonts '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/font/bitstream-type1/-/archive/font-bitstream-type1-$version/bitstream-type1-font-bitstream-type1-$version.tar.gz")
depends=(font-util)
makedepends=()
md5sums=('42b0e68c3eb4603cf4f1da89e3d698fc')
group=(media.fonts)
uses=()
arch=('x86_64')

cd bitstream-type1-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

