#!/usr/bin/env bash
name='gnome-terminal'
release='2'
version='3.50.1'
url='https://wiki.gnome.org/Apps/Terminal'
description='GNOME terminal emulator application'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gnome-terminal/-/archive/${version}/gnome-terminal-${version}.tar.gz"
"00-ignore-language-check.patch"
"gnome-terminal-daemon"
"gnome-terminal-daemon.desktop")
depends=(dconf gsettings-desktop-schemas itstool libpcre2 vte3)
makedepends=()
md5sums=('627c0381b3620f7f92662dbc0a9c4099'
         'SKIP'
         'SKIP'
         'SKIP')
group=(x11.terms)
uses=()
arch=('x86_64')

cd $name-$version

prepare (){
    patch -Np1 -i ../00-ignore-language-check.patch
}

setup () {
    meson setup build --prefix=/usr \
		--libdir=/usr/lib64/ \
		-Dnautilus_extension=false \
		-Dsearch_provider=false
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}

