#!/usr/bin/env bash
name='audit'
release='3'
version='4.0'
url='https://people.redhat.com/sgrubb/audit/'
description='Userspace components of the audit framework'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/linux-audit/audit-userspace/archive/refs/tags/v$version.tar.gz"
        "auditd.initd"
        "auditd.confd")
depends=()
makedepends=()
md5sums=('a4a4f9e4a3aa426d5c555184133e447d'
         'SKIP'
         'SKIP')
group=(sys.process)
uses=(libcap_ng)
uses_extra=(python)
python_depends=(python)
libcap_ng_depends=(libcap-ng)
arch=('x86_64')

cd audit-userspace-$version

setup(){
    autoreconf -fv --install
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --libdir=/usr/lib64 \
        --disable-zos-remote \
        --disable-listener \
        --disable-systemd \
        --disable-gssapi-krb5 \
        --enable-shared=audit \
		    --with-arm \
		    --with-aarch64 \
        $(use_opt python --with-python3 --without-python3) \
        $(use_opt python --with-python --without-python) \
        $(use_opt libcap_ng --with-libcap-ng=yes --with-libcap-ng=no)
}

build(){
    make $jobs
}

package(){
    make install $jobs
    install -Dm755 ../auditd.initd "$DESTDIR"/etc/init.d/auditd
    install -Dm755 ../auditd.confd "$DESTDIR"/etc/conf.d/auditd
}

