#!/bin/bash
name='readline'
release='3'
version='8.3'
url='http://www.gnu.org/software/readline/'
description="GNU readline library"
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPL')
arch=(x86_64)
source=("https://ftp.gnu.org/pub/gnu/$name/$name-$version.tar.gz"
       "inputrc")
sha256sums=('fe5383204467828cd495ee8d1d3c037a7eba1389c22bc6a041f627976f9061cc'
         'SKIP')
depends=()
group=(sys.libs)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/lib64
}

build(){
    make SHLIB_LIBS="-L/tools/lib -lncursesw"
}

package(){
    make SHLIB_LIBS="-L/tools/lib -lncursesw" DESTDIR="$DESTDIR" install pkgconfigdir="/lib64/pkgconfig"
    install -Dm644 ../inputrc "$DESTDIR"/etc/inputrc
}
