#!/bin/bash
name='readline'
release='2'
version='8.2'
url='http://www.gnu.org/software/readline/'
description="GNU readline library"
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPL')
arch=(x86_64)
source=("https://ftp.gnu.org/pub/gnu/$name/$name-$version.tar.gz"
       "inputrc")
md5sums=('4aa1b31be779e6b84f9a96cb66bc50f6'
         'SKIP')
depends=()
group=(sys.apps)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/lib64
}

build(){
    make SHLIB_LIBS="-L/tools/lib -lncursesw"
}

package(){
    make SHLIB_LIBS="-L/tools/lib -lncursesw" DESTDIR="$DESTDIR" install pkgconfigdir="/lib64/pkgconfig"
    install -Dm644 ../inputrc "$DESTDIR"/etc/inputrc
}
