#!/usr/bin/env bash
name='labwc'
release='2'
version='0.8.4'
url='https://github.com/labwc/labwc'
description=='A Wayland window-stacking compositor'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/labwc/labwc/archive/$version.tar.gz")
depends=(libpng libsfdo librsvg pango seatd wlroots wayland xorg-xwayland)
makedepends=()
sha256sums=('2d3ded90f78efb5060f7057ea802c78a79dc9b2e82ae7a2ad902af957b8b9797')
group=(gui.wm)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

