#!/usr/bin/env bash
name='labwc'
release='1'
version='0.8.2'
url='https://github.com/labwc/labwc'
description=='A Wayland window-stacking compositor'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/labwc/labwc/archive/$version.tar.gz")
depends=(libpng libsfdo librsvg pango seatd wlroots wayland xorg-xwayland)
makedepends=()
sha256sums=('1adba1c87ec26f2f00409b47a0b79ccfd68bd160e1abc41822fb01f0a76ee947')
group=(gui.wm)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

