#!/usr/bin/env bash
name='ristretto'
release='2'
version='0.13.3'
url='https://docs.xfce.org/apps/ristretto/start'
description='A fast and lightweight picture viewer for Xfce'
email='03teknoloji@gmail.com'
maintainer='mobilturka'
license=('GPLv3')
source=("https://archive.xfce.org/src/apps/$name/0.13/$name-$version.tar.bz2")
depends=(libxfce4ui xfconf tumbler libexif file)
makedepends=()
sha256sums=('5b9172ef704ae192a5338df6bee4e91a59edc65618c375bb4433ffb38e2126cb')
group=(xfce.extra)
uses=()
arch=('x86_64')

build() {
  cd $name-$version

  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-debug
  make
}

package() {
  cd $name-$version
  make DESTDIR="$DESTDIR" install
}

