#!/usr/bin/env bash
name='kmod'
release='2'
version='31'
url='https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git'
description='library and tools for managing linux kernel modules'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kmod/kmod-$version.tar.xz")
depends=(zlib xz-utils)
makedepends=()
md5sums=('6165867e1836d51795a11ea4762ff66a')
group=(sys.apps)
uses=()
arch=('x86_64')

export PATH=$HOME:$PATH

cd $name-$version

prepare(){
    # skip building gtk doc
    touch libkmod/docs/gtk-doc.make
}

setup(){
    ./configure --prefix=/usr \
        --libdir=/lib64/ \
        --bindir=/sbin
   # remove xsltproc dependency
   rm -f man/Makefile
   echo -e "all:\ninstall:" > man/Makefile
}

build(){
    make $jobs
}

package(){
    make install $jobs
    mkdir -p ${DESTDIR}/usr/bin
    for tool in {ins,ls,rm,dep}mod mod{probe,info}; do
        ln -s kmod "${DESTDIR}/sbin/$tool"
  done
}

