#!/usr/bin/env bash
name='kmod'
release='3'
version='34'
url='https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git'
description='library and tools for managing linux kernel modules'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kmod/kmod-$version.tar.xz")
depends=(zlib xz-utils)
makedepends=()
sha256sums=('12e7884484151fbd432b6a520170ea185c159f4393c7a2c2a886ab820313149a')
group=(sys.apps)
uses=()
arch=('x86_64')

export PATH=$HOME:$PATH

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --bindir=/bin \
        --sbindir=/sbin \
        --libdir=/lib64 \
        -Dopenssl=enabled \
        -Dmanpages=false \
        -Dxz=enabled \
        -Dzlib=enabled \
        -Dzstd=disabled
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

