#!/usr/bin/env bash
name='font-cronyx-cyrillic'
release='1'
version='1.0.3'
url='https://gitlab.freedesktop.org/xorg/font/cronyx-cyrillic'
description='X.Org Cronyx cyrillic fonts '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/font/cronyx-cyrillic/-/archive/font-cronyx-cyrillic-$version/cronyx-cyrillic-font-cronyx-cyrillic-$version.tar.gz")
depends=(bdftopcf font-util)
makedepends=()
md5sums=('a49b3550094dba21ef13a546eda65218')
group=(media.fonts)
uses=()
arch=('x86_64')

cd cronyx-cyrillic-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

