#!/bin/bash
name=zlib
release=1
version=1.3
url='https://zlib.net'
description='A compression/decompression library'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('zlib')
source=("https://zlib.net/zlib-$version.tar.gz")
md5sums=('60373b133d630f74f4a1f94c1185a53f')
arch=(x86_64)
group=(app.arch)

cd $name-$version

setup(){
    ./configure --prefix=/usr --libdir=/lib64 --shared
    cd contrib/minizip
    autoreconf -fvi
	./configure --prefix=/usr --libdir=/lib64
}
build(){
    make $jobs
    cd contrib/minizip
    make $jobs
}
package(){
    make install pkgconfigdir="/usr/lib64/pkgconfig"
    cd contrib/minizip
    make install pkgconfigdir="/usr/lib64/pkgconfig"
}
