#!/usr/bin/env bash
name='plasma-activities'
release='3'
version='6.1.5'
url='https://kde.org/plasma-desktop'
description='Core components for KDE Activities'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-activities-${version}.tar.xz")
depends=(kconfig kcoreaddons qt6-base)
makedepends=(extra-cmake-modules qt6-declarative qt6-tools)
sha256sums=('b353fbe7ae30f6a04ef4f81d3e0250654a0f9859a9ef43214c89c78b924e284b')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
