#!/usr/bin/env bash
name='plasma-activities'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description='Core components for KDE Activities'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-activities-${version}.tar.xz")
depends=(kconfig kcoreaddons qt6-base)
makedepends=(extra-cmake-modules qt6-declarative qt6-tools)
sha256sums=('f0bd07bbcd9022c72e564046046029b39f71d1cc5b467b9f50914813043b2795')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
