#!/usr/bin/env bash
name='py3-sphinx'
release='1'
version='7.0.1'
url='https://www.sphinx-doc.org/'
description='Python documentation generator'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://pypi.org/packages/source/S/Sphinx/Sphinx-$version.tar.gz")
depends=(python)
makedepends=()
md5sums=('9b5357daa219d036f1220e44bf1c9512')
group=(dev.python)
uses=()
arch=('x86_64')

echo "adres: $pkgdir"

  cd Sphinx-$version

build() {
	#python --skip-dependency-check --no-isolation
	echo "build"
}


package() {
	#python3 -m installer -d "$pkgdir" dist/sphinx-*.whl
	pip install .
}

