#!/usr/bin/env bash
name='libXdamage'
release='1'
version='1.1.6'
url='https://example.org'
description='Package libXdamage'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXdamage-$version.tar.xz")
depends=(libXfixes libX11)
makedepends=()
md5sums=('ca55d29fa0a8b5c4a89f609a7952ebf8')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

