#!/bin/bash
name=base-files
release=2
version=2
url='https://gitlab.com/turkman/devel/sources/base-files'
description='Base system files'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/base-files/-/archive/$version/base-files-$version.zip"
        "base-files.sysconf"
        "os-release")
md5sums=('913b9fcbea19309e947336007c6e3a21'
         'SKIP'
         'SKIP')
arch=(x86_64)
group=(sys.base)

cd "$name-$version"

package(){
    mkdir -p ${DESTDIR}/etc/sysconf.d
    make install
    install ../base-files.sysconf  ${DESTDIR}/etc/sysconf.d/base-files
    install ../os-release  ${DESTDIR}/etc/
}
