#!/usr/bin/env bash
name='make'
release='1'
version='4.4'
url='https://ftp.gnu.org/gnu/make/'
description='GNU make utility to maintain groups of programs'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/make/make-${version}.tar.gz")
depends=( )
makedepends=( )
md5sums=('d7575a26a94ee8427130e9db23cdaa78')
uses=()
group=(sys.devel)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

