#!/usr/bin/env bash
name='py3-babel'
release='2'
version='2.14.0'
url='http://babel.pocoo.org/'
description='Python3 i18n tool'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('BSD-3-Clause')
source=("https://github.com/python-babel/babel/archive/refs/tags/v${version}.tar.gz")
depends=(python)
makedepends=(py3-tz py3-setuptools)
sha256sums=('ad76eab6905b626d7d4110d2032bc60c69bef225ec94c67d7229425ebe53f659')
group=(dev.python)
uses=()
arch=('x86_64')

cd "babel"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}


