#!/usr/bin/env bash
name='py3-babel'
release='3'
version='2.17.0'
url='http://babel.pocoo.org/'
description='Python3 i18n tool'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('BSD-3-Clause')
source=("https://github.com/python-babel/babel/archive/refs/tags/v${version}.tar.gz")
depends=(python)
makedepends=(py3-tz py3-setuptools)
sha256sums=('a52696499d9da7860726444c170f3481dc7409398392f3500783d01c07221bbf')
group=(dev.python)
uses=()
arch=('x86_64')

cd "babel"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}


