#!/usr/bin/env bash
name='pavucontrol'
release='1'
version='5.0'
url='https://freedesktop.org/software/pulseaudio/pavucontrol/'
description='Pulseaudio Volume Control, GTK based mixer for Pulseaudio'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://freedesktop.org/software/pulseaudio/pavucontrol/pavucontrol-${version}.tar.xz")
depends=(gtkmm3 json-glib libcanberra)
makedepends=()
md5sums=('a4a5dc51dcf4d912443faf3fe8d32b55')
group=(media.sound)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    make $jobs
}

package () {
    make install $jobs
}
