#!/usr/bin/env bash
name='pavucontrol'
release='2'
version='6.1'
url='https://freedesktop.org/software/pulseaudio/pavucontrol/'
description='Pulseaudio Volume Control, GTK based mixer for Pulseaudio'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://freedesktop.org/software/pulseaudio/pavucontrol/pavucontrol-${version}.tar.xz")
depends=(gtkmm3 json-glib libcanberra)
makedepends=()
sha256sums=('0dce61c1088eafa04c270e1fb79eb7aff47e98567f7d28c65a7bee6cd24e415d')
group=(media.sound)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    make $jobs
}

package () {
    make install $jobs
}

