#!/usr/bin/env bash
name='qt5-location'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='Provides access to position, satellite and area monitoring classes'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtlocation-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base qt5-declarative)
makedepends=()
md5sums=('6d7c0a23fe701597815a54cac53c1e62')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtlocation-everywhere-src-"$version

export PATH=/usr/bin/qt5:$PATH

setup () {
		qmake
}

build () {
    make $jobs
}

package () {
    make INSTALL_ROOT="$DESTDIR" install $jobs
}

