#!/usr/bin/env bash
name='kscreenlocker'
release='3'
version='6.1.5'
url='https://kde.org/plasma-desktop'
description='Library and components for secure lock screen architecture'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kscreenlocker-${version}.tar.xz"
"kde.pam"
"kde-np.pam"
"kde-fingerprint.pam")
depends=(kconfig kcoreaddons kcrash kdeclarative kglobalaccel ki18n kidletime kio kirigami knotifications kpackage ksvg
         kwindowsystem kxmlgui layer-shell-qt libkscreen libX11 libxcb libXi pam libplasma qt6-base qt6-declarative wayland
         xcb-util-keysyms)
makedepends=(extra-cmake-modules kdoctools kcmutils)
sha256sums=('a0ea8354122a28e0acc6ec604a7658fee5b00f125cc09ea758c9b91bf3c7f0fc' 'SKIP' 'SKIP' 'SKIP')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build

	install -Dm644 ../kde.pam "$DESTDIR"/etc/pam.d/kde
	install -Dm644 ../kde-np.pam "$DESTDIR"/etc/pam.d/kde-np
	install -Dm644 ../kde-fingerprint.pam "$DESTDIR"/etc/pam.d/kde-fingerprint
}
