#!/usr/bin/env bash
name='qt6-svg'
release='3'
version='6.8.0'
url='https://www.qt.io/'
description='Classes for displaying the contents of SVG files'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtsvg-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(cmake)
sha256sums=('cf7a593d5e520f8177240610d9e55d5b75b0887fe5f385554ff64377f1646199')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtsvg-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH


setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr
}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}