#!/usr/bin/env bash
name='openrc'
release='1'
version='0.46'
url='https://github.com/OpenRC/openrc'
description='The OpenRC init system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/OpenRC/openrc/archive/refs/tags/$version.zip"
    "openrc.sysconf")
depends=()
makedepends=()
md5sums=('8b74d3db544b496f6bb33d2648db5d2f'
    'SKIP')
group=()
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        -Dzsh-completions=true \
		-Dbash-completions=true \
		-Dpam=false \
		-Dpkgconfig=true
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    # disable all services
    rm -f ${DESTDIR}/etc/runlevels/*/*
    rm ${DESTDIR}//etc/init.d/functions.sh
    ln -s ../../lib/rc/sh/functions.sh ${DESTDIR}/etc/init.d/functions.sh
    # install sysconf script
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../openrc.sysconf ${DESTDIR}/etc/sysconf.d/openrc
    mkdir -p ${DESTDIR}/etc/group.d
    mkdir -p ${DESTDIR}/etc/passwd.d
    echo "uucp:x:14:" > ${DESTDIR}/etc/group.d/uucp
    echo "uucp:x:10:14:uucp:/var/spool/uucp:/bin/false" > ${DESTDIR}/etc/passwd.d/uucp
    # symlink init
    ln -s openrc-init ${DESTDIR}/sbin/init
}

