#!/usr/bin/env bash
name='py3-cparser'
release='1'
version='2.21'
url='https://github.com/eliben/pycparser'
description='A super-fast templating language that borrows the best ideas from the existing templating languages.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/eliben/pycparser/archive/refs/tags/release_v$version.tar.gz")
depends=(python)
makedepends=(py3-wheel py3-setuptools)
sha256sums=('3c797eb2eb1ba57772bb99ffa7caed23c3a2c2ae58daef114c9b09d3a6da97e2')
group=(dev.python)
uses=()
arch=('x86_64')

cd pycparser-release_v$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

