#!/usr/bin/env bash
name='desktop-file-utils'
release='2'
version='0.27'
url='https://www.freedesktop.org/wiki/Software/desktop-file-utils'
description='Command line utilities for working with desktop entries'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://www.freedesktop.org/software/desktop-file-utils/releases/desktop-file-utils-$version.tar.xz"
         'desktop-file-utils.sysconf')
depends=(glib)
makedepends=(meson)
md5sums=('fdf9215aea91acb6aebc43f770537f2c'
         'SKIP')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../desktop-file-utils.sysconf ${DESTDIR}/etc/sysconf.d/desktop-file-utils
}
