#!/usr/bin/env bash
name='libxcb'
release='2'
version='1.16'
url='https://xcb.freedesktop.org'
description='X C-language Bindings library'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/lib/libxcb-$version.tar.xz")
depends=(libXau libXdmcp xcb-proto)
makedepends=(xorgproto util-macros python)
md5sums=('c769f93c254263077df62404661b710d')
uses=()
arch=('x86_64')
group=(x11.libs)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
	--enable-shared \
	--enable-static \
	--disable-devel-docs \
	--without-launchd \
	--without-doxygen
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

