#!/usr/bin/env bash
name='mm-common'
release='1'
version='1.0.5'
url='https://www.gtkmm.org'
description='Common build files of the C++ bindings'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.gnome.org/sources/mm-common/${version%.*}/mm-common-${version}.tar.xz")
depends=()
makedepends=()
md5sums=('05d2ca86dfb936c8b2f71b7595ca7ab2')
group=(dev.cpp)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
 --libdir=/usr/lib64/
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR=${DESTDIR} ninja -C build install $jobs
}
