#!/usr/bin/env bash
name='cinnamon-translations'
release='2'
version='6.0.0'
url='https://github.com/linuxmint/cinnamon-translations'
description='Translations for Cinnamon and Nemo'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://github.com/linuxmint/cinnamon-translations/archive/refs/tags/${version}.tar.gz")
depends=()
makedepends=()
md5sums=('c488e3efc6e7aef6cd8d75b3749bc7f2')
group=(cinnamon.extra)
uses=()
arch=('x86_64')

cd $name-$version


build(){
    make $jobs
}

package(){
    cp -r usr/ "${DESTDIR}"
}

