#!/usr/bin/env bash
name='cinnamon-translations'
release='5'
version='6.4.1'
url='https://github.com/linuxmint/cinnamon-translations'
description='Translations for Cinnamon and Nemo'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://github.com/linuxmint/cinnamon-translations/archive/refs/tags/${version}.tar.gz")
depends=()
makedepends=()
sha256sums=('ef2b9e78a4d9bdb0e4374e8d387405f2de16471526dc36aa9b32f9718fa586e3')
group=(cinnamon.extra)
uses=()
arch=('x86_64')

cd $name-$version


build(){
    make $jobs
}

package(){
    cp -r usr/ "${DESTDIR}"
}

