#!/usr/bin/env bash
name='cinnamon-translations'
release='4'
version='6.2.2'
url='https://github.com/linuxmint/cinnamon-translations'
description='Translations for Cinnamon and Nemo'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://github.com/linuxmint/cinnamon-translations/archive/refs/tags/${version}.tar.gz")
depends=()
makedepends=()
sha256sums=('ef0e621492e32155a2e5ac47083c6167280f0b285bc0e4da3259a6d5c5cc366b')
group=(cinnamon.extra)
uses=()
arch=('x86_64')

cd $name-$version


build(){
    make $jobs
}

package(){
    cp -r usr/ "${DESTDIR}"
}

