#!/usr/bin/env bash
name='plasma-pa'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop/'
description='Plasma applet for audio volume management using PulseAudio'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/plasma-pa-$version.tar.xz")
depends=(pipewire plasma-workspace)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('b49abb2bb74401b22cdae1d992101d764b483a18c60087c202f6e695145d022c')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

