#!/usr/bin/env bash
name='plasma-pa'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop/'
description='Plasma applet for audio volume management using PulseAudio'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/plasma-pa-$version.tar.xz")
depends=(pulseaudio-qt pipewire plasma-workspace)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('8a6493177d9d823f747fe917acc3bc859c61c4fe9d3add799ab7f19434d99920')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

