#!/usr/bin/env bash
name='lxrandr'
release='2'
version='0.3.3'
url='https://lxde.org'
description='Monitor configuration tool (part of LXDE)'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/lxde/lxrandr/archive/refs/tags/$version.tar.gz")
depends=(gtk3 xrandr)
makedepends=(intltool)
sha256sums=('24d0abaee830b0b2973ba9d2e46b3c801445342f7d5d3297c021a8a4a471f512')
group=(lxde.base)
uses=()
arch=('x86_64')

export CC=clang

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr --enable-gtk3 --enable-man \
        --libdir=/usr/lib64/
}

build(){
    make DESTDIR=$DESTDIR $jobs
}

package(){
    make DESTDIR=$DESTDIR install $jobs
}

