#!/usr/bin/env bash
name='lxrandr'
release='1'
version='0.3.2'
url='https://lxde.org'
description='Monitor configuration tool (part of LXDE)'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://downloads.sourceforge.net/lxde/lxrandr-$version.tar.xz")
depends=(gtk3 xrandr)
makedepends=(intltool)
sha256sums=('8b5edfc9718061bc161fe51d388697cbaa819d6f8013ed24ba22f438e0dbc312')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr --enable-gtk3 --enable-man \
        --libdir=/usr/lib64/
}

build(){
    make DESTDIR=$DESTDIR $jobs
}

package(){
    make DESTDIR=$DESTDIR install $jobs
}

