#!/usr/bin/env bash
name='libdbusmenu-gtk3'
release='1'
version='16.04.0'
url='https://launchpad.net/libdbusmenu'
description='Library for passing menus over DBus (GTK+ 3 library)'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL3' 'LGPL2.1' 'LGPL3')
source=(https://launchpad.net/libdbusmenu/16.04/${version}/+download/libdbusmenu-${version}.tar.gz{,.asc})
depends=(gtk3 libdbusmenu-glib)
makedepends=(gnome-common gobject-introspection intltool vala valgrind)
md5sums=('3c05d53053b3ea69384b5f93d7a4c7c4' 'SKIP')
group=(dev.libs)
uses=()
arch=('x86_64')

cd "libdbusmenu"-$version

sed -i 's/-Werror//' libdbusmenu-*/Makefile.{am,in}

setup(){
    export HAVE_VALGRIND_TRUE='#'
    export HAVE_VALGRIND_FALSE=''

    (
    ./configure --prefix=/usr \
      --libdir=/usr/lib64/ \
      --sysconfdir=/etc \
      --localstatedir=/var \
      --disable-{dumper,static,tests} \
      --with-gtk=3
    make
    )        
}

build(){
    make -j1 -C libdbusmenu-glib DESTDIR="${DESTDIR}" install $jobs
}

package(){
    pkgdesc+=" (GTK+ 3 library)"
    depends=("libdbusmenu-glib" 'gtk3')

    #make -j1 -C libdbusmenu-glib DESTDIR="${DESTDIR}" install
    #make -j1 -C libdbusmenu-gtk DESTDIR="${DESTDIR}" install
    #make -j1 -C libdbusmenu-glib DESTDIR="${DESTDIR}" uninstall
}

