#!/usr/bin/env bash
name='libXrender'
release='1'
version='0.9.11'
url='https://gitlab.freedesktop.org/xorg/lib/libXrender.git/'
description='X.Org Xrender library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXrender-$version.tar.xz")
depends=()
makedepends=()
md5sums=('ebf7fb3241ec03e8a3b2af72f03b4631')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

