#!/usr/bin/env bash
name='py3-pyproject-hooks'
release='2'
version='1.1.0'
url='https://github.com/pypa/pyproject-hooks'
description='Python project hooks'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pypa/pyproject-hooks/archive/refs/tags/v$version.tar.gz")
depends=(python)
makedepends=(py3-build)
sha256sums=('1cbbabcd93ea1ac50cca7f23e5b640904684ae6c85003c6f7cf02b598c33f28f')
group=(dev.python)
uses=()
arch=('x86_64')

cd pyproject-hooks-$version

export PYTHONPATH=src/pyproject_hooks

build () {
    python -m build --wheel
}

package () {
#    mkdir $DESTDIR/usr/lib64/python3 -p
#    cp -prfv src/* $DESTDIR/usr/lib64/python3
    python -m installer --destdir="$DESTDIR" dist/*.whl
}

