#!/usr/bin/env bash
name='py3-pyproject-hooks'
release='1'
version='1.0.0'
url='https://github.com/pypa/pyproject-hooks'
description='Python project hooks'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://github.com/pypa/pyproject-hooks/archive/refs/tags/v1.0.0.tar.gz')
depends=(python)
makedepends=(py3-build)
md5sums=('03ea6db4dd6f0f06a5732e8d2f4fb39f')
group=(dev.python)
uses=()
arch=('x86_64')

cd pyproject-hooks-$version

export PYTHONPATH=src/pyproject_hooks

build () {
    python -m build --wheel --no-isolation
}

package () {
#    mkdir $DESTDIR/usr/lib64/python3 -p
#    cp -prfv src/* $DESTDIR/usr/lib64/python3
    python -m installer --destdir="$DESTDIR" dist/*.whl
}

