#!/usr/bin/env bash
name='qt5-charts'
release='2'
version='5.15.14'
url='https:/www.qt.io/'
description='The Qt Sensors API provides access to sensor hardware via QML and C++'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtcharts-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=(qt5-declarative)
sha256sums=('4b9659b126bf648a0c035ae1c04e2604941741ea2494f8d8b62ddea26a25d0ab')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtcharts-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}


