#!/usr/bin/env bash
name='xfwm4'
release='1'
version='4.18.0'
_version='4.18'
url='https://docs.xfce.org/xfce/xfwm4/start'
description="Xfce's window manager"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfwm4/${_version}/xfwm4-${version}.tar.bz2")
depends=(libepoxy libwnck3 libxfce4ui xfconf)
makedepends=(intltool)
md5sums=('181415e457c86124fa5f8aa5d715b967')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--enable-startup-notification \
		--enable-randr \
		--enable-compositor \
		--enable-xsync \
		--disable-debug
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

