#!/usr/bin/env bash
name='xfwm4'
release='2'
version='4.20.0'
_version='4.20'
url='https://docs.xfce.org/xfce/xfwm4/start'
description="Xfce's window manager"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfwm4/${_version}/xfwm4-${version}.tar.bz2")
depends=(libepoxy libwnck3 libxfce4ui xfconf)
makedepends=(intltool)
sha256sums=('a58b63e49397aa0d8d1dcf0636be93c8bb5926779aef5165e0852890190dcf06')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--enable-startup-notification \
		--enable-randr \
		--enable-compositor \
		--enable-xsync
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

