#!/usr/bin/env bash
name='thunar'
release='1'
version='4.18.6'
_version='4.18'
url='https://docs.xfce.org/xfce/thunar/start'
description='Modern, fast and easy-to-use file manager for Xfce'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2' 'LGPL2.1')
source=("https://archive.xfce.org/src/xfce/thunar/${_version}/thunar-${version}.tar.bz2")
depends=(exo  libxfce4ui libxfce4util)
makedepends=(gobject-introspection intltool xfce4-panel  hicolor-icon-theme)
md5sums=('dc9ccd48acfd2ca9c9ca46631ee35e35')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--enable-gio-unix \
		--enable-gudev \
		--enable-notifications \
		--enable-exif \
		--disable-debug 
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
	rm -rf $DESTDIR/usr/lib/systemd
}

