#!/usr/bin/env bash
name='thunar'
release='4'
version='4.20.3'
_version='4.20'
url='https://docs.xfce.org/xfce/thunar/start'
description='Modern, fast and easy-to-use file manager for Xfce'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2' 'LGPL2.1')
source=("https://archive.xfce.org/src/xfce/thunar/${_version}/thunar-${version}.tar.bz2")
depends=(exo  libxfce4ui libxfce4util gtk3)
makedepends=(gobject-introspection intltool xfce4-panel  hicolor-icon-theme)
sha256sums=('fe1908b396298e6515a90fa9ddaec0db8b684e4b3d7773118e21561baf8f9639')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --libdir=/usr/lib64/ \
		--enable-gio-unix \
		--enable-gudev \
		--enable-notifications \
		--enable-exif
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
	rm -rf $DESTDIR/usr/lib/systemd
}

