#!/usr/bin/env bash
name='libSM'
release='1'
version='1.2.4'
url='https://gitlab.freedesktop.org/xorg/lib/libSM'
description='libSM X.Org Session Management library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libSM-$version.tar.xz")
depends=(xorgproto libICE)
makedepends=()
md5sums=('ffa434ed96ccae45533b3d653300730e')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

