#!/usr/bin/env bash
name='libSM'
release='1'
version='1.2.4'
url='https://example.org'
description='Package libSM'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://www.x.org/archive/individual/lib/libSM-1.2.4.tar.xz')
depends=(xorgproto libICE)
makedepends=()
md5sums=('ffa434ed96ccae45533b3d653300730e')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

