#!/usr/bin/env bash
name='polkit-qt5'
release='1'
version='0.114.0'
url='https://download.kde.org/stable/polkit-qt-1'
description='Polkit-Qt provides an API to PolicyKit in the Qt environment.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/polkit-qt-1/polkit-qt-1-$version.tar.xz")
depends=(qt5-base polkit)
makedepends=()
md5sums=('2d20b02bd7ad1cd3f6ce235fc6d7de60')
group=()
uses=()
arch=('x86_64')

cd polkit-qt-1-$version

setup () {
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        ..
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

