#!/usr/bin/env bash
name='libxklavier'
release='1'
version='5.4'
url='https://www.freedesktop.org/wiki/Software/LibXklavier/'
description='High-level API for X Keyboard Extension'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://people.freedesktop.org/~svu/libxklavier-${version}.tar.bz2")
depends=(glib iso-codes libxml2)
makedepends=(gobject-introspection intltool)
md5sums=('13af74dcb6011ecedf1e3ed122bd31fa')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--with-xkb-bin-base=/usr/bin \
      	--with-xkb-base=/usr/share/X11/xkb \
		--enable-gtk-doc
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

