#!/usr/bin/env bash
name='qemu'
release='1'
version='8.1.2'
url='https://qemu.org'
description='Quick Emulator'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.qemu.org/qemu-$version.tar.xz")
depends=()
makedepends=()
md5sums=('f7e3443d5b62afa0c10771ad42c5e17a')
group=()
uses=(gtk vnc)
arch=('x86_64')

gtk_depends=(gtk3)


cd $name-$version

setup () {
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --target-list=x86_64-softmmu \
        --disable-zstd \
        $(use_opt gtk --enable-gtk --disable-gtk) \
        $(use_opt vnc --enable-vnc --disable-vnc)
}

build () {
    make $jobs
}

package () {
    make install $jobs
}

