#!/usr/bin/env bash
name='py3-pycups'
release='2'
version='2.0.4'
url='https://github.com/OpenPrinting/pycups'
description='Python bindings for cups'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/OpenPrinting/pycups/archive/refs/tags/v$version.tar.gz")
depends=(python cups)
makedepends=()
sha256sums=('31d9cf62df7884fe430d11970a8c9278282a47a0ff6b1529c58c7d26e8eb4789')
group=(dev.python)
uses=()
arch=('x86_64')

cd pycups-$version

build () {
    python3 setup.py build
}

package () {
    python3 setup.py install --root="${DESTDIR}" --optimize=1
}

