#!/usr/bin/env bash
name='md4c'
release='1'
version='0.4.8'
url='https://github.com/mity/md4c'
description='C Markdown parser'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/mity/md4c/archive/release-${version}/md4c-${version}.tar.gz")
depends=()
makedepends=(cmake)
md5sums=('3a3d87255705dd812a679d329638a92d')
group=(sys.libs)
uses=()
arch=('x86_64')

cd $name-"release"-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr
}

build () {
	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}
