#!/usr/bin/env bash
name='qt6-languageserver'
release='3'
version='6.8.0'
url='https://www.qt.io/'
description='Qt implementation of the Language Server Protocol'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtlanguageserver-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-websockets)
makedepends=(cmake ninja)
sha256sums=('fbf7152c8ca4d1dbdd30205e64a830f378d7ac5ac0b5f02eecab9d7501065cef')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtlanguageserver-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
