#!/usr/bin/env bash
name='libndp'
release='2'
version='1.9'
url='https://github.com/jpirko/libndp'
description='libndp Library for Neighbor Discovery Protocol'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/jpirko/libndp/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
sha256sums=('e564f5914a6b1b799c3afa64c258824a801c1b79a29e2fe6525b682249c65261')
group=(net.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

