#!/usr/bin/env bash
name='wlroots'
release='2'
version='0.17.0'
url='https://gitlab.freedesktop.org/wlroots/wlroots'
description='Pluggable, composable, unopinionated modules for building a Wayland compositor'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/$version/wlroots-$version.tar.gz")
depends=(seatd hwdata eudev libxkbcommon wayland)
makedepends=()
md5sums=('350b9085b67fc8496c4a5228bb992c22')
group=(gui.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dexamples=false
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

