#!/usr/bin/env bash
name='highway'
release='2'
version='1.1.0'
url='https://github.com/google/highway'
description='Performance-portable, length-agnostic SIMD with runtime dispatch'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/google/highway/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('354a8b4539b588e70b98ec70844273e3f2741302c4c377bcc4e81b3d1866f7c9')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    mkdir build
    cd build
    cmake .. \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_TESTING=OFF
}

build(){
    make -C build $jobs
}

package(){
    make -C build install $jobs
}

