#!/usr/bin/env bash
name='xfce4-notifyd'
release='3'
version='0.9.6'
url='https://docs.xfce.org/apps/notifyd/start'
description='Notification daemon for the Xfce desktop'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/apps/xfce4-notifyd/${version%.*}/xfce4-notifyd-${version}.tar.bz2")
depends=(libnotify libxfce4ui)
makedepends=(intltool python xfce4-panel xfce4-dev-tools)
sha256sums=('9e53265cca7d835c31b3c2c0d3ae961704870839ef583dcca3e4cc98ae3d2671')
group=(xfce.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--disable-debug 
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}
