#!/usr/bin/env bash
name='xcb-util-cursor'
release='1'
version='0.1.4'
url='https://xcb.freedesktop.org'
description='X C-language Bindings sample implementations'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/xcb/xcb-util-cursor-${version}.tar.xz")
depends=(libxcb xcb-util-image xcb-util-renderutil)
makedepends=(xorgproto)
md5sums=('0d244518ad54b886413fe782235d6210')
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
	--enable-shared \
	--enable-static \
	--disable-devel-docs \
	--without-doxygen
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}
