#!/usr/bin/env bash
name='libgnomekbd'
release='1'
version='3.28.1'
url='https://example.org'
description='Keyboard management library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://gitlab.gnome.org/GNOME/libgnomekbd/-/archive/${version}/libgnomekbd-${version}.tar.gz")
depends=(libxklavier gtk3 dconf)
makedepends=(gobject-introspection git meson)
md5sums=('3099aaf6a9a3878f3f8e49511bf0fa4e')
group=(gnome.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

