#!/usr/bin/env bash
name='py3-imagesize'
release='1'
version='1.4.1'
url='https://github.com/shibukawa/imagesize_py'
description='Getting image size from png/jpeg/jpeg2000/gif file'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('MIT')
source=("https://github.com/shibukawa/imagesize_py/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer py3-setuptools py3-wheel)
sha256sums=('c353adbba9d9e92fc880ff85279c362a9d4fc580c4783d1949e905200cb8b15b')
group=(dev.python)
uses=()
arch=('x86_64')

cd "imagesize_py"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

