#!/usr/bin/env bash
name='syntax-highlighting'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Syntax highlighting engine for structured text and code'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/syntax-highlighting-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules qt6-declarative qt6-tools doxygen)
sha256sums=('2ef9e6b8aeb8543e64f4a3628afa331c0656fe6c485f3574c407651d7c12a653')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


