#!/usr/bin/env bash
name='syntax-highlighting'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Syntax highlighting engine for structured text and code'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/syntax-highlighting-${version}.tar.xz")
depends=(qt5-base)
makedepends=(extra-cmake-modules qt5-declarative qt5-xmlpatterns qt5-tools doxygen)
md5sums=('87e3e1e86825d0be9f17e3a9af8316d2')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


