#!/usr/bin/env bash
name='knotifyconfig'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Core components for the KDE s Activities'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/knotifyconfig-${version}.tar.xz")
depends=(kconfig kio ki18n libcanberra qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('fb2ad6bffb54e6a05fab4dc871897beaba03a46d42fa290b56ee1fcbb2ee0594')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


