#!/usr/bin/env bash
name='libnsl'
release='1'
version='2.0.0'
url='https://example.org'
description='Public client interface library for NIS(YP)'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('LGPL2.1')
source=('https://github.com/thkukuk/libnsl/releases/download/v2.0.0/libnsl-2.0.0.tar.xz')
depends=(libtirpc)
makedepends=( )
md5sums=('1e8c0615071ea13202452304de1eaab9')
uses=()
group=(net.libs)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/libnsl
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/usr/lib64/libnsl/" > ${DESTDIR}/etc/ld.so.conf.d/libnsl.conf
}

