#!/usr/bin/env bash
name='qt5-imageformats'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='Plugins for additional image formats: TIFF, MNG, TGA, WBMP'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtimageformats-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=()
sha256sums=('768b658231ef7f3e583831713567f5a97640a90c051ac68e7a7e8d5a11882be6')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtimageformats-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

