#!/usr/bin/env bash
name='qt6-virtualkeyboard'
release='4'
version='6.9.1'
url='https://www.qt.io/'
description='Virtual keyboard framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtvirtualkeyboard-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-svg qt6-declarative)
makedepends=(cmake ninja)
sha256sums=('80059a38bdb836f0785292396970edc108f477a68d9a35bed8393750de3d281f')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtvirtualkeyboard-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}