#!/usr/bin/env bash
name='qt6-virtualkeyboard'
release='3'
version='6.8.0'
url='https://www.qt.io/'
description='Virtual keyboard framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtvirtualkeyboard-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-svg qt6-declarative)
makedepends=(cmake ninja)
sha256sums=('8f6502d7f40765fb4960b804927f9d86da39bdf42acc5021353c49527b6d0ce0')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtvirtualkeyboard-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}