#!/usr/bin/env bash
name='expat'
release='2'
version='2.6.0'
url='https://github.com/libexpat/libexpat'
description='An XML parser library'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/libexpat/libexpat/releases/download/R_2_6_0/expat-$version.tar.xz")
depends=( )
makedepends=( )
md5sums=('bd169cb11f4b9bdfddadf9e88a5c4d4b')
uses=()
arch=('x86_64')
group=(dev.libs)

cd $name-$version

setup(){
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib64 \
        -DCMAKE_BUILD_TYPE=None \
        -DEXPAT_BUILD_DOCS=false \
        -W no-dev \
        -B build
}

build(){
    make -C build
}

package(){
    make install -C build
}

