#!/bin/bash
name=libffi
release=1
version=3.4.4
url='https://gitlab.com/sulinos/devel/ymp'
description='A portable foreign-function interface library. '
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=('https://github.com/libffi/libffi/releases/download/v3.4.4/libffi-3.4.4.tar.gz')
md5sums=('0da1a5ed7786ac12dcbaf0d499d8a049') # replace this
arch=(x86_64)
group=(dev.libs)

cd "$name-$version"

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}
build(){
    make $jobs
}
package(){
    make $jobs install
}
