#!/usr/bin/env bash
name='waf'
release='1'
version='2.0.25'
url='http://waf.io/'
description='General-purpose build system modelled after Scons'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.com/ita1024/waf/-/archive/waf-$version/waf-waf-$version.tar.gz")
depends=(python)
makedepends=()
md5sums=('eb4fc0e93547f3088268e22a190290f2')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$name-$version

build(){

   python3 ./waf-light configure build
}

package(){
  install -vDm 755 waf -t "$DESTDIR/usr/bin"
  install -vDm 644 wscript -t "$DESTDIR/usr/share/$name/"

  install -vDm 644 waflib/*.py -t "$DESTDIR/usr/lib64/python3/site-packages/waf/waflib/"
  install -vDm 644 waflib/Tools/*.py -t "$DESTDIR/usr/lib64/python3/site-packages/waf/waflib/Tools/"
  install -vDm 644 waflib/extras/*.py -t "$DESTDIR/usr/lib64/python3site-packages/waf/waflib/extras/"
}
