#!/usr/bin/env bash
name='waf'
release='1'
version='2.0.25'
url='http://waf.io/'
description='General-purpose build system modelled after Scons'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.com/ita1024/waf/-/archive/waf-$version/waf-waf-$version.tar.gz")
depends=(python)
makedepends=()
md5sums=('eb4fc0e93547f3088268e22a190290f2')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$name-$version

build(){

   python3 ./waf-light configure build
}

package(){

 install -vDm 755 waf -t "$pkgdir/usr/bin"
  install -vDm 644 wscript -t "$pkgdir/usr/share/$name/"
  
  install -vDm 644 waflib/*.py -t "$pkgdir/usr/lib64/python3/site-packages/waf/waflib/"
  install -vDm 644 waflib/Tools/*.py -t "$pkgdir/usr/lib64/python3/site-packages/waf/waflib/Tools/"
  install -vDm 644 waflib/extras/*.py -t "$pkgdir/usr/lib64/python3site-packages/waf/waflib/extras/"
  python3 -m compileall -d "/usr/lib64/python3" "$pkgdir/usr/lib64/python3"
  python3 -O -m compileall -d "/usr/lib64/python3" "$pkgdir/usr/lib64/python3/"
  #install -vDm 644 LICENSE -t "$pkgdir/usr/share/licenses/$name/"
#  install -vDm 644 {README,../building-waf}.md -t "$pkgdir/usr/share/doc/$name/"
echo ""
}
