#!/usr/bin/env bash
name='qt5-translations'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='A cross-platform application and UI framework (Translations)'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qttranslations-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-tools)
makedepends=()
md5sums=('f421a46bfd3cbbdf0a3fa701d3ccbedf')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qttranslations-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

