#!/usr/bin/env bash
name='qt5-translations'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='A cross-platform application and UI framework (Translations)'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qttranslations-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-tools)
makedepends=()
sha256sums=('5b94d1a11b566908622fcca2f8b799744d2f8a68da20be4caa5953ed63b10489')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qttranslations-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

