#!/usr/bin/env bash
name='xorg-proto'
release='1'
version='2022.2'
url='https://gitlab.freedesktop.org/xorg/proto/xorgproto'
description='X.Org combined protocol headers'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/proto/xorgproto-${version}.tar.xz")
depends=()
makedepends=()
md5sums=('3fdb11d75f7023db273f7b3e34b58338')
uses=()
arch=('x86_64')
group=(x11.base)

cd xorgproto-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
	--without-xmlto \
	--without-xsltproc
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

