#!/usr/bin/env bash
name='harfbuzz'
release='6'
version='8.3.1'
url='https://github.com/harfbuzz/harfbuzz'
description='HarfBuzz text shaping engine'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/harfbuzz/harfbuzz/archive/refs/tags/$version.tar.gz")
depends=(cairo glib icu)
makedepends=(gobject-introspection)
md5sums=('561a8c81a8ad7cb04c00fbcb671f0527')
group=(media.libs)
uses=(freetype)
freetype_depends=(freetype)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddocs=disabled \
        -Dgobject=enabled \
        -Dfreetype=$(use_opt freetype enabled disabled)
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

