#!/usr/bin/env bash
name='harfbuzz'
release='7'
version='10.2.0'
url='https://github.com/harfbuzz/harfbuzz'
description='HarfBuzz text shaping engine'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/harfbuzz/harfbuzz/archive/refs/tags/$version.tar.gz")
depends=(cairo glib icu)
makedepends=(gobject-introspection)
sha256sums=('11749926914fd488e08e744538f19329332487a6243eec39ef3c63efa154a578')
group=(media.libs)
uses=(freetype)
freetype_depends=(freetype)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddocs=disabled \
        -Dgobject=enabled \
        -Dfreetype=$(use_opt freetype enabled disabled)
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

