#!/usr/bin/env bash
name='libblockdev'
release='1'
version='2.28'
url='https://github.com/storaged-project/libblockdev'
description='A library for manipulating block devices'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/storaged-project/libblockdev/releases/download/$version-1/libblockdev-$version.tar.gz")
depends=(gawk parted kmod libyaml btrfs-progs dosfstools gptfdisk libbytesize ndctl xfsprogs lvm2 volume_key dmraid)
makedepends=()
md5sums=('6476e5967753ee03d8e65f4d7837a4b6')
group=(sys.libs)
uses=()
arch=('x86_64')

cd $name-$version
setup(){
    ./configure --prefix=/usr \
        --sysconfdir=/etc 
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

