#!/usr/bin/env bash
name='libblockdev'
release='3'
version='3.1.1'
url='https://github.com/storaged-project/libblockdev'
description='A library for manipulating block devices'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/storaged-project/libblockdev/releases/download/$version-1/libblockdev-$version.tar.gz")
depends=(gawk parted kmod libyaml btrfs-progs dosfstools gptfdisk
         libbytesize ndctl xfsprogs lvm2 volume_key dmraid libnvme)
makedepends=()
sha256sums=('a5cb33a53ff5969067982704f45399d02555fdb2313ed0c56eac9555397dc2db')
group=(sys.libs)
uses=()
arch=('x86_64')

# ignore warnings. Bad idea but working
export CFLAGS="$CFLAGS -Wno-all"

cd $name-$version
setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --sysconfdir=/etc
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

