#!/usr/bin/env bash
name='jsoncpp'
release='1'
version='1.9.6'
url='https://github.com/open-source-parsers/jsoncpp'
description='A C++ library for interacting with JSON.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/open-source-parsers/jsoncpp/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('f93b6dd7ce796b13d02c108bc9f79812245a82e577581c4c9aabe57075c90ea2')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build \
       --prefix=/usr
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

