#!/usr/bin/env bash
name='phonon-gstreamer'
release='1'
version='4.10.0'
url='https://download.kde.org/stable/phonon/phonon-backend-gstreamer'
description='Phonon GStreamer backend for Qt5'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/phonon/phonon-backend-gstreamer/$version/phonon-backend-gstreamer-$version.tar.xz")
depends=(gst-plugins-base phonon qt5-x11extras)
makedepends=()
md5sums=('60abf634e961160cd1772d486f4a7097')
group=(media.libs)
uses=()
arch=('x86_64')

cd phonon-backend-gstreamer-$version

setup () {
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr \
        ..
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

