#!/usr/bin/env bash
name='mbedtls'
release='2'
version='3.4.0'
url='https://tls.mbed.org/'
description='Portable cryptographic and SSL/TLS library, aka polarssl'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('Apache')
source=("https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v${version}.tar.gz")
depends=(glibc)
makedepends=(cmake python)
md5sums=('3f6c2eadc1243e9895d65c67b46eb890')
group=(net.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
		-DUSE_SHARED_MBEDTLS_LIBRARY=ON
}

build(){
    cmake --build build
}

package(){
    cmake --install build
}

