#!/usr/bin/env bash
name='mbedtls'
release='1'
version='2.28.3'
url='https://tls.mbed.org/'
description='Portable cryptographic and SSL/TLS library, aka polarssl'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('Apache')
source=("https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v${version}.tar.gz")
depends=()
makedepends=(cmake python)
md5sums=('7e1b09243447a0378a78dd5469b68415')
group=(net.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DUSE_SHARED_MBEDTLS_LIBRARY=ON
}

build(){
    cmake --build build
}

package(){
    cmake --install build
}

