#!/bin/bash
name=readline
version=8.1
release=1
source=(https://ftp.gnu.org/pub/gnu/$name/$name-$version.tar.gz
       inputrc
       )
md5sums=(e9557dd5b1409f5d7b37ef717c64518e
         SKIP
        )
depends=(glibc)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/lib64
}

build(){
    make SHLIB_LIBS="-L/tools/lib -lncursesw"
}

package(){
    make SHLIB_LIBS="-L/tools/lib -lncursesw" DESTDIR="$DESTDIR" install
    install -Dm644 ../inputrc "$DESTDIR"/etc/inputrc
}
