#!/usr/bin/env bash
name='kapidox'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Frameworks API Documentation Tools'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kapidox-${version}.tar.xz")
depends=(py3-jinja py3-yaml)
makedepends=(py3-build py3-installer py3-wheel py3-setuptools qt6-base)
sha256sums=('db5f38cb732d6d4bad1348e2cf7892e8c7a9018bab00c85add631507f4b8677f')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

build () {
    python -m build --wheel
}

package () {
    python -m installer --destdir="$DESTDIR" dist/*.whl
}

