#!/usr/bin/env bash
name='kapidox'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Frameworks API Documentation Tools'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kapidox-${version}.tar.xz")
depends=(py3-jinja py3-yaml)
makedepends=(py3-build py3-installer py3-wheel py3-setuptools qt5-base)
md5sums=('b54d1e754dd90caadd728261cde90840')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

build () {
    python -m build --wheel --skip-dependency-check --no-isolation
}

package () {
    python -m installer --destdir="$DESTDIR" dist/*.whl
}

