#!/usr/bin/env bash
name='llvm'
release='1'
version='14.0.3'
url='https://llvm.org'
description='Low Level Virtual Machine'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/llvm/llvm-project/releases/download/llvmorg-$version/llvm-$version.src.tar.xz")
depends=(libffi xz-utils libxml2 zlib)
makedepends=(git)
md5sums=('69b637cfee09e3f5d2ec5cc16681cbe7')
group=(sys.devel)
uses=()
arch=('x86_64')

cd $name-$version.src

export PYTHON=/usr/bin/python3

cmake_args=(
    -G Ninja
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_INSTALL_DOCDIR=share/doc
    -DCMAKE_INSTALL_PREFIX=/usr
    -DCMAKE_INSTALL_LIBDIR=lib64
    -DCMAKE_SKIP_RPATH=ON
    -DLLVM_BINUTILS_INCDIR=/usr/include
    -DLLVM_BUILD_DOCS=OFF
    -DLLVM_BUILD_LLVM_DYLIB=ON
    -DLLVM_BUILD_TESTS=ON
    -DLLVM_ENABLE_BINDINGS=OFF
    -DLLVM_ENABLE_FFI=ON
    -DLLVM_ENABLE_RTTI=ON
    -DLLVM_ENABLE_SPHINX=OFF
    -DLLVM_INCLUDE_BENCHMARKS=OFF
    -DLLVM_INSTALL_UTILS=ON
    -DLLVM_LINK_LLVM_DYLIB=ON
    -DLLVM_USE_PERF=ON
)

setup(){
    mkdir build
    cd build
    cmake .. ${cmake_args[@]}
}

build(){
    cd build
    ninja ${jobs}
}

package(){
    cd build
    ninja install
    mv ${DESTDIR}/usr/lib{,64}
}

