#!/usr/bin/env bash
name='coreutils'
release='3'
version='9.4'
url='https://ftp.gnu.org/gnu/coreutils/'
description='The basic file, shell and text manipulation utilities of the GNU operating system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/coreutils/coreutils-$version.tar.xz")
depends=(acl attr gmp libcap)
makedepends=( )
md5sums=('459e9546074db2834eefe5421f250025')
uses=(openssl)
openssl_depends=(openssl)
arch=('x86_64')
group=(sys.apps)

cd $name-$version

export CFLAGS='-static-libgcc -static-libstdc++ -fPIC'

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --libexecdir=/usr/libexec \
        --enable-largefile \
        --enable-single-binary=symlinks \
        --enable-no-install-program=groups,hostname,kill,uptime \
        $(use_opt openssl --with-openssl --without-openssl)

}

build(){
    make $jobs
}

package(){
    make install $jobs
}

