#!/usr/bin/env bash
name='libzip'
release='1'
version='1.11.2'
url='https://libzip.org'
description='A C library for reading, creating, and modifying zip archives.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://libzip.org/download/libzip-$version.tar.xz")
depends=()
makedepends=()
sha256sums=('5d471308cef4c4752bbcf973d9cd37ba4cb53739116c30349d4764ba1410dfc1')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
      -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

