#!/usr/bin/env bash
name='mpfr'
release='1'
version='4.1.0'
url='https://mpfr.org'
description='multiple precision floating-point computation'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('LGPL-2.1')
source=("https://ftp.gnu.org/gnu/mpfr/mpfr-${version}.tar.xz")
depends=(gmp)
makedepends=( )
md5sums=('bdd3d5efba9c17da8d83a35ec552baef')
arch=('x86_64')
group=(dev.libs)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
	--libdir=/usr/lib64/mpfr \
	--enable-shared \
	--enable-static \
	--disable-maintainer-mode \
	--enable-thread-safe
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
    echo "/usr/lib64/mpfr/" > ${DESTDIR}/etc/ld.so.conf.d/mpfr.conf
}
