#!/usr/bin/env bash
name='mpfr'
release='3'
version='4.2.0'
url='https://mpfr.org'
description='multiple precision floating-point computation'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('LGPL-2.1')
source=("https://ftp.gnu.org/gnu/mpfr/mpfr-${version}.tar.xz")
depends=(gmp)
makedepends=( )
md5sums=('a25091f337f25830c16d2054d74b5af7')
arch=('x86_64')
group=(dev.libs)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
	--libdir=/usr/lib64 \
	--enable-shared \
	--enable-static \
	--disable-maintainer-mode \
	--enable-thread-safe
}

build(){
    make $jobs
}

package(){
    make install $jobs
}
