#!/usr/bin/env bash
name='milou'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='A dedicated search application built on top of Baloo'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/milou-${version}.tar.xz")
depends=(krunner kitemmodels)
makedepends=(extra-cmake-modules kdoctools)
md5sums=('5d192457ae760d75a65adb430c24d65a')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
