#!/usr/bin/env bash
name='milou'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description='A dedicated search application built on top of Baloo'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/milou-${version}.tar.xz")
depends=(kirigami krunner ksvg libplasma qt6-base qt6-declarative)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('c8ea924f7c3915e1deaa5220ba007238526b3df9029b3ac98eca158e5552b34a')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
