#!/usr/bin/env bash
name='milou'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='A dedicated search application built on top of Baloo'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/milou-${version}.tar.xz")
depends=(kirigami krunner ksvg libplasma qt6-base qt6-declarative)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('b1f1b4e13fb40476531b3a63e766a23ef7794de1b8620242b4c51ab445f9b1c5')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
