#!/usr/bin/env bash
name='qt5-webchannel'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='Library for seamless integration of C++ +and QML applications with HTML/JavaScript clients.'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtwebchannel-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base qt5-declarative)
makedepends=()
md5sums=('f9d7d2f9268f90a1f625eb1c500de4a0')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtwebchannel-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

