#!/usr/bin/env bash
name='qt5-serialport'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='Qt5 - QtSerialPort module'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtserialport-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=()
md5sums=('e71cf87487de08867a5bc42287017706')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtserialport-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

