#!/usr/bin/env bash
name='dialog'
release='1'
version='1.3-20230209'
url='https://invisible-island.net'
description='Tool to display dialog boxes from a shell'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://invisible-island.net/archives/dialog/dialog-1.3-20230209.tgz')
depends=(ncurses)
makedepends=()
md5sums=('84cd94a53bfb7ab95286403e7818bbc8')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./configure --prefix=/usr \
         --libdir=/usr/lib64/ \
         --with-ncursesw
    # change default color blue to red
    sed -i "s/COLOR_BLUE/COLOR_RED/g" dlg_colors.h
    sed -i "s/COLOR_CYAN/COLOR_MAGENTA/g" dlg_colors.h
}

build () {
    make $jobs
}

package () {
    make install install-lib $jobs DESTDIR=$DESTDIR
}

