#!/usr/bin/env bash
name='libXau'
release='1'
version='1.0.10'
url='https://www.x.org/wiki/'
description='X.Org X authorization library'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/lib/libXau-${version}.tar.xz")
depends=(xorgproto)
makedepends=()
md5sums=('d32e6e8c70dd957c9c2d654e0f8d0a15')
uses=()
arch=('x86_64')
group=(x11.libs)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --enable-static \
        --enable-shared
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

