#!/bin/bash
name=readline
version=8.1
release=1
url='http://www.gnu.org/software/readline/'
description="GNU readline library"
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPL')
arch=(x86_64)
source=(https://ftp.gnu.org/pub/gnu/$name/$name-$version.tar.gz
       inputrc)
md5sums=('e9557dd5b1409f5d7b37ef717c64518e'
         'SKIP')
depends=(glibc)
group=(system.base)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/lib64/readline
}

build(){
    make SHLIB_LIBS="-L/tools/lib -lncursesw"
}

package(){
    make SHLIB_LIBS="-L/tools/lib -lncursesw" DESTDIR="$DESTDIR" install pkgconfigdir="/usr/lib64/pkgconfig"
    install -Dm644 ../inputrc "$DESTDIR"/etc/inputrc
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/lib64/readline/" > ${DESTDIR}/etc/ld.so.conf.d/readline.conf
}
