#!/usr/bin/env bash
name='cinnamon'
release='1'
version='5.6.8'
url='https://github.com/linuxmint/cinnamon'
description='Linux desktop which provides advanced innovative features and a traditional user experience'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://github.com/linuxmint/cinnamon/archive/refs/tags/$version.tar.gz")
depends=(nm-applet accountsservice cinnamon-control-center cinnamon-menus
        cinnamon-session cinnamon-settings-daemon cjs gnome-backgrounds gsound gstreamer libcroco 
		libgnomekbd libkeybinder3 librsvg muffin nemo polkit-gnome py3-cairo py3-dbus py3-pygobject 
		py3-pam py3-pexpect py3-pillow py3-inotify py3-tz py3-tinycss2 py3-xapp py3-requests 
		timezonemap xapp xdg-desktop-portal-xapp libxkbfile
)
makedepends=(meson gobject-introspection intltool)
md5sums=('f1984b3296868dba9bb481faa3dbaf50')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        --libexecdir=lib/cinnamon
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
    # remove broken symlink
    rm -f $DESTDIR/etc/xdg/menus/cinnamon-applications-merged
}

