#!/usr/bin/env bash
name='elfutils'
release='4'
version='0.191'
url='https://sourceware.org/elfutils/'
description='Libraries/utilities to handle ELF objects (drop in replacement for libelf)'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('GPLv3' 'GPLv2' 'LGPLv3')
source=("https://sourceware.org/elfutils/ftp/${version}/elfutils-${version}.tar.bz2")
depends=()
makedepends=(bzip2 curl gcc libarchive sqlite xz-utils zlib)
sha256sums=('df76db71366d1d708365fc7a6c60ca48398f14367eb2b8954efc8897147ad871')
uses=(bzip2 lzma nls)
uses_extra=(zstd)
arch=('x86_64')
group=(dev.libs)
bzip2_depends=(bzip2)
lzma_depends=(xz-utils)
zstd_depends=(zstd)

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
		--enable-shared \
		--enable-static \
		--disable-debuginfod \
		--disable-libdebuginfod \
		--disable-thread-safety \
		--disable-valgrind \
		$(use_opt nls --enable-nls --disable-nls) \
		--program-prefix="eu-" \
		$(use_opt bzip2 --with-bzlib --without-bzlib) \
		$(use_opt lzma --with-lzma --without-lzma) \
		$(use_opt zstd --with-zstd --without-zstd)
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

