#!/usr/bin/env bash
name='mtdev'
release='2'
version='1.1.7'
url='https://bitmath.org/code/mtdev/'
description='Multitouch Protocol Translation Library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://bitmath.org/code/mtdev/mtdev-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('a55bd02a9af4dd266c0042ec608744fff3a017577614c057da09f1f4566ea32c')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -vfi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

