#!/usr/bin/env bash
name='libXi'
release='1'
version='1.8'
url='https://example.org'
description='Package libXi'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXi-$version.tar.gz")
depends=(libxfixes)
makedepends=()
md5sums=('8367decb1b9c2a1517d11261b6e977e4')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

