#!/usr/bin/env bash
name='zstd'
release='1'
version='1.4.8'
url='https://salsa.debian.org/med-team/libzstd'
description='Zstandard library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://salsa.debian.org/med-team/libzstd/-/archive/debian/1.4.8+dfsg-3/libzstd-debian-1.4.8+dfsg-3.tar.gz')
depends=()
makedepends=()
md5sums=('03109dc77710380a50cb07f201ce8d8b')
group=(app.arch)
uses=(prog)
uses_extra=(lib)
arch=('x86_64')

cd libzstd-debian-1.4.8+dfsg-3
build(){
    make $jobs
}

package(){
    export BINDIR=/usr/bin
    export LIBDIR=/usr/lib64
    export PKGCONFIGDIR=/usr/lib64/pkgconfig/
    export INCLUDEDIR=/usr/include
    make install  $jobs
    rm -rf $DESTDIR/usr/local
    if ! use prog ; then
        rm -rf $DESTDIR/usr/bin
    fi
    if ! use lib ; then
        rm -rf $DESTDIR/usr/lib64 $DESTDIR/usr/include
    fi
}

