#!/usr/bin/env bash
name='binutils'
release='1'
version='2.39'
url='https://ftp.gnu.org/gnu/binutils/'
description='A set of programs to assemble and manipulate binary and object files'
email=' aliriza.keskin@pardus.org.tr'
maintainer=' aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/binutils/binutils-$version.tar.xz")
depends=(zlib)
makedepends=( )
md5sums=('f7e986ae9ff06405cafb2e585ee36d27')
arch=('x86_64')
group=(sys.devel)

unset CFLAGS
unset CXXFLAGS

cd $name-$version

setup(){
    mkdir build
    cd build
    ../configure --prefix=/usr \
        --libdir=/usr/lib64/binutils \
        --disable-nls \
        --disable-werror \
        --enable-cet \
        --enable-default-execstack=no \
        --enable-deterministic-archives \
        --enable-gold \
        --enable-install-libiberty \
        --enable-ld=default \
        --enable-pgo-build=lto \
        --enable-plugins \
        --enable-relro \
        --enable-shared \
        --enable-threads \
        --disable-gdb \
        --disable-gdbserver \
        --disable-libdecnumber \
        --disable-readline \
        --disable-sim \
        --disable-werror \
        --with-pic \
        --with-system-zlib
}

build(){
    cd build
    make
}

package(){
    cd build
    make install -j`nproc`
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/usr/lib64/binutils/" > ${DESTDIR}/etc/ld.so.conf.d/binutils.conf
}

