#!/usr/bin/env bash
name='binutils'
release='8'
version='2.45'
url='https://ftp.gnu.org/gnu/binutils/'
description='A set of programs to assemble and manipulate binary and object files'
email=' aliriza.keskin@pardus.org.tr'
maintainer=' aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/binutils/binutils-$version.tar.xz")
depends=(zlib flex)
makedepends=( )
sha256sums=('c50c0e7f9cb188980e2cc97e4537626b1672441815587f1eab69d2a1bfbef5d2')
arch=('x86_64')
group=(sys.devel)
uses=(multilib)

unset CFLAGS
unset CXXFLAGS

export PATH=$PATH:$HOME

cd $name-$version

prepare(){
    echo "#!/bin/sh" > $HOME/makeinfo
    echo "printf 'makeinfo (GNU texinfo) 5.2\n'" >> $HOME/makeinfo
    chmod +x $HOME/makeinfo
}

setup(){
    mkdir build
    cd build
    set -x
    ../configure --prefix=/usr \
          --libdir=/usr/lib64 \
          --sysconfdir=/etc \
          --enable-cet \
          --enable-default-execstack=no \
          --enable-deterministic-archives \
          --disable-compressed-debug-sections \
          --disable-silent-rules \
          --enable-obsolete \
          --enable-gold \
          --enable-install-libiberty \
          --enable-ld=default \
          --enable-new-dtags \
          --enable-pgo-build=lto \
          --enable-plugins \
          --enable-relro \
          --enable-shared \
          $(use_opt x86_64 --enable-targets=x86_64-linux-gnu,x86_64-linux-gnux32,x86_64-pep ) \
          $(use_opt x86_64 --disable-x86-used-note )\
          --with-gold-ldflags=-static-libstdc++ \
          --enable-threads \
          --disable-gdb \
          --disable-gdbserver \
          --disable-libdecnumber \
          --disable-readline \
          --disable-sim \
          --disable-werror \
          --with-pic \
          --with-system-zlib
}

build(){
    cd build
    make configure-host
    make tooldir=/usr
}

package(){
    cd build
    make tooldir=/usr install $jobs
}

