#!/usr/bin/env bash
name='e2fsprogs'
release='2'
version='1.47.1'
url='https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs'
description='Standard EXT2/EXT3/EXT4 filesystem utilities'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v$version/e2fsprogs-$version.tar.xz")
depends=(util-linux)
makedepends=()
sha256sums=('5a33dc047fd47284bca4bb10c13cfe7896377ae3d01cb81a05d406025d99e0d1')
group=(sys.fs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --enable-elf-shlibs     \
        --disable-libblkid      \
        --disable-libuuid       \
        --disable-uuidd         \
        --disable-fsck
}

build(){
    make $jobs
}

package(){
    make install $jobs
    # this file part of utit-inux
    rm -rf $DESTDIR/usr/share/man/man8/fsck.8
}

