#!/usr/bin/env bash
name='qrencode'
release='1'
version='4.1.1'
url='https://fukuchi.org/works/qrencode/'
description='C library for encoding data in a QR Code symbol'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPL')
source=("https://github.com/fukuchi/libqrencode/archive/refs/tags/v${version}.tar.gz")
depends=(libpng)
makedepends=(libtool)
sha256sums=('5385bc1b8c2f20f3b91d258bf8ccc8cf62023935df2d2676b5b67049f31a049c')
group=(media.gfx)
uses=()
arch=('x86_64')

cd "libqrencode"-$version

setup () {
	autoreconf -fvi
    ./configure --prefix=/usr \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--with-tests
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

