#!/usr/bin/env bash
name='menu-cache'
release='1'
version='1.1.0'
url='https://example.org'
description='Caching mechanism for freedesktop.org compliant menus'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/menu-cache/archive/refs/tags/$version.tar.gz"
        'menu-cache-1.1.0-0001-Support-gcc10-compilation.patch')
depends=(libfm)
makedepends=()
sha256sums=('990857aa61a2894730e3749b6bc0f905967eed0c21aa2b62a7694007bdccbe8d'
         'SKIP')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    patch -Np1 -i ../menu-cache-1.1.0-0001-Support-gcc10-compilation.patch
}

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

