#!/usr/bin/env bash
name='sddm'
release='1'
version='0.20.0'
url='https://github.com/sddm/sddm'
description='Simple Desktop Display Manager'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL')
source=("https://github.com/sddm/sddm/archive/v${version}/sddm-v${version}.tar.gz"
	"sddm.initd"
	"sddm.confd")
depends=(qt5-declarative xauth xorg-server)
makedepends=(extra-cmake-modules py3-docutils qt5-tools)
md5sums=('7af67d5fb767639861d35c80eb4e1191' 'SKIP' 'SKIP')
group=(x11.misc)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	CXXFLAGS="$CXXFLAGS -flto=auto" \
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=None \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_MAN_PAGES=ON \
		-DBUILD_WITH_QT6=OFF \
		-DENABLE_JOURNALD=OFF \
		-DNO_SYSTEMD=ON \
		-DUSE_ELOGIND=ON \
		-DUID_MIN=500 \
		-DUID_MAX=65000 \
		-DDBUS_CONFIG_DIR=/usr/share/dbus-1/system.d
}

build () {
	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
    install -Dm755 ../sddm.initd "$DESTDIR"/etc/init.d/sddm
	install -Dm644 ../sddm.confd "$DESTDIR"/etc/conf.d/sddm
}