#!/usr/bin/env bash
name='nemo-extensions'
release='1'
version='6.2.0'
url='https://example.org'
description='Embedded terminal window for Nemo'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://github.com/linuxmint/nemo-extensions/archive/refs/tags/${version}.tar.gz")
depends=(nemo clutter cinnamon-desktop py3-pygobject)
makedepends=(intltool gobject-introspection meson ninja)
sha256sums=('b1c7e3d269ed05f472c80c16cf3f12827cbb48cb05406b276be14060225dbbc3')
group=(cinnamon.extra)
uses=(terminal share python compare emblems fileroller repairer)
arch=('x86_64')

cd "nemo-extensions"-$version


setup(){
    for _dir in ${uses[@]}; do
        cd nemo-${_dir}
        if [[ -f meson.build ]] ; then
            meson setup build --prefix=/usr \
                --libdir=/usr/lib64
        fi
        cd ..
    done
}

build(){
    for _dir in ${uses[@]}; do
        cd nemo-${_dir}
        if [[ -f meson.build ]] ; then
            ninja -C build
        else
            python3 setup.py build
        fi
        cd ..
    done
}

package(){
    for _dir in ${uses[@]}; do
        cd nemo-${_dir}
        if [[ -f meson.build ]] ; then
            ninja -C build install
        else
            python3 setup.py install --root="${DESTDIR}" \
                --prefix=/usr --install-lib=/usr/lib64/python3 \
                --optimize=1 --skip-build
        fi
        cd ..
    done
}
