#!/usr/bin/env bash
name='py3-pam'
release='2'
version='2.0.2'
url='https://github.com/FirefighterBlu3/python-pam'
description='A Python interface to the PAM library'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('MIT')
source=("https://github.com/FirefighterBlu3/python-pam/archive/refs/tags/v${version}.tar.gz")
depends=(python py3-six)
makedepends=(py3-build py3-installer py3-setuptools py3-wheel)
sha256sums=('23f5fd680b43d9dc8c96061c2c855f7c4758ee29c5d9f3cc469b558a0afd558b')
group=(dev.python)
uses=()
arch=('x86_64')

cd "python-pam"-$version

build(){
    python -m build --wheel
}

package(){
	python -m installer --destdir="${DESTDIR}" dist/*.whl
	install -Dm644 LICENSE "${DESTDIR}/usr/share/licenses/${name}/LICENSE"
  mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}


