#!/usr/bin/env bash
name='kstatusnotifieritem'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Implementation of Status Notifier Items'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kstatusnotifieritem-${version}.tar.xz")
depends=(kwindowsystem qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('d78aa20e1858f700478eecedb49714160d5e04b4a0d177bca4355aa1a0f7d730')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_PYTHON_BINDINGS=OFF \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

