#!/usr/bin/env bash
name='kstatusnotifieritem'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Implementation of Status Notifier Items'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kstatusnotifieritem-${version}.tar.xz")
depends=(kwindowsystem qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('80eae2693cdb5da669b4ed6a8228bddc39816aca0fde928f231e4894827d1de0')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

