#!/usr/bin/env bash
name='kstatusnotifieritem'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Implementation of Status Notifier Items'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kstatusnotifieritem-${version}.tar.xz")
depends=(kwindowsystem qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('5def5e1a862d85d0f325c4f1973967bcf8fa97353fe1d361a1cafb0670198403')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

