#!/usr/bin/env bash
name='libpciaccess'
release='1'
version='0.17'
url='https://example.org'
description='Package libpciaccess'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libpciaccess-$version.tar.xz")
depends=()
makedepends=()
md5sums=('1466cf950c914ad2db1dbb76c9a724db')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

