#!/usr/bin/env bash
name='libpciaccess'
release='2'
version='0.18'
url='https://gitlab.freedesktop.org/xorg/lib/libpciaccess'
description='Library providing generic access to the PCI bus and devices'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libpciaccess-$version.tar.xz")
depends=()
makedepends=()
md5sums=('54f48367e37666f9e0f12571d1ee3620')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddefault_library=both
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

