#!/usr/bin/env bash
name='kitemmodels'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Models for Qt Model/View system'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kitemmodels-${version}.tar.xz")
depends=(qt6-base)
makedepends=(doxygen extra-cmake-modules qt6-tools qt6-declarative)
sha256sums=('887653b1571ad0afd4b836ad2451a42b07657d0eede1a2628e9c69102ce23de1')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DBUILD_TESTING=OFF \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

