#!/usr/bin/env bash
name='plasma5support'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='Support components for porting from KF5/Qt5 to KF6/Qt6'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma5support-${version}.tar.xz")
depends=(kconfig kcoreaddons ki18n qt6-base qt6-declarative)
makedepends=(extra-cmake-modules plasma-wayland-protocols qt6-tools)
sha256sums=('46eb4f5d94077c46c24b494bbae2e5749b5b5f7cc1db6ef2923b8112ae6ae58d')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=ON \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}