#!/usr/bin/env bash
name='fakeroot'
release='4'
version='1.36'
url='https://salsa.debian.org/clint/fakeroot/-/tags'
description='A fake root environment by means of LD_PRELOAD and SysV IPC (or TCP) trickery'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_$version.orig.tar.gz")
depends=(sed util-linux bash)
makedepends=()
sha256sums=('7fe3cf3daf95ee93b47e568e85f4d341a1f9ae91766b4f9a9cdc29737dea4988')
uses=()
group=(sys.apps)
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --with-ipc=sysv
}

build(){
    make
    #cd doc
    #po4a -k 0 --rm-backups --variable 'srcdir=../doc/' po4a/po4a.cfg
}

package(){
    make install

}

