#!/usr/bin/env bash
name='font-adobe-utopia-type1'
release='1'
version='1.0.4'
url='https://gitlab.freedesktop.org/xorg/font/adobe-utopia-type1'
description='X.Org Adobe Utopia Type 1 fonts '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/font/adobe-utopia-type1/-/archive/font-adobe-utopia-type1-$version/adobe-utopia-type1-font-adobe-utopia-type1-$version.tar.gz")
depends=(font-util)
makedepends=()
md5sums=('5a26fd465b35de00f4626380f066761e')
group=(media.fonts)
uses=()
arch=('x86_64')

cd adobe-utopia-type1-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

