#!/usr/bin/env bash
name='kiconthemes'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Support for icon themes'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kiconthemes-${version}.tar.xz")
depends=(qt6-base qt6-svg kconfigwidgets kcolorscheme karchive kwidgetsaddons)
makedepends=(extra-cmake-modules doxygen qt6-tools breeze-icons)
sha256sums=('b971460949fafc98e7ae293f35635c2fd6101a6fc46b2f4fce64bb21440ece04')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

