#!/usr/bin/env bash
name='kiconthemes'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description='Support for icon themes'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kiconthemes-${version}.tar.xz")
depends=(qt5-svg kconfigwidgets karchive)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('f997425dce56c003c6350e2595d81069')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

