#!/usr/bin/env bash
name='kiconthemes'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Support for icon themes'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kiconthemes-${version}.tar.xz")
depends=(qt6-base qt6-svg kconfigwidgets kcolorscheme karchive kwidgetsaddons)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('cdc4c5788e0b3f88f25aa474d51d43496e4c742777f88025ef2fa606f2721331')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

