#!/usr/bin/env bash
name='py3-editables'
release='2'
version='0.5'
url='https://github.com/pfmoore/editables'
description='library for creating editable wheels'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/pfmoore/editables/archive/refs/tags/${version}.tar.gz")
depends=()
makedepends=()
md5sums=('e738f27bdde55318832ea8d3cd2ffb10')
group=(dev.python)
uses=()
arch=('x86_64')

cd "editables"-$version

build(){
    #python3 setup.py build
	python -m build --wheel --no-isolation
}

package(){
    #python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
	python -m installer --destdir="$DESTDIR" dist/*.whl
}


