#!/usr/bin/env bash
name='py3-editables'
release='2'
version='0.5'
url='https://github.com/pfmoore/editables'
description='library for creating editable wheels'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('MIT')
source=("https://github.com/pfmoore/editables/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-flit py3-installer)
sha256sums=('1ff2663aa1669eb89115a38e2d4067c21bb847e7006f72bf979a1a91b8bc2304')
group=(dev.python)
uses=()
arch=('x86_64')

cd "editables"-$version

build(){
	python -m build --wheel --no-isolation
}

package(){
	python -m installer --destdir="$DESTDIR" dist/*.whl
  mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}


