#!/usr/bin/env bash
name='brotli'
release='2'
version='1.1.0'
url='https://github.com/google/brotli'
description='Generic-purpose lossless compression algorithm'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/google/brotli/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
md5sums=('3a6a3dba82a3604792d3cb0bd41bca60')
group=(app.arch)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    mkdir build
    cd build
    cmake .. \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_SHARED_LIBS=True
}

build(){
    make -C build $jobs
}

package(){
    make -C build install $jobs
}

