#!/usr/bin/env bash
name='py3-psutil'
release='3'
version='7.0.0'
url='https://github.com/giampaolo/psutil'
description='Cross-platform lib for process and system monitoring in Python'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/giampaolo/psutil/archive/refs/tags/release-$version.tar.gz")
depends=(python)
makedepends=()
sha256sums=('a3c736187215d1f94ebe18ee6b14202d1b89c165c2eaad159f55cdfb494f7a1c')
group=(dev.python)
uses=()
arch=('x86_64')

cd psutil-release-$version


build () {
    python3 setup.py build
}

package () {
    python3 setup.py install --skip-build --root="$DESTDIR"
}

