#!/usr/bin/env bash
name='py3-psutil'
release='2'
version='6.0.0'
url='https://github.com/giampaolo/psutil'
description='Cross-platform lib for process and system monitoring in Python'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/giampaolo/psutil/archive/refs/tags/release-$version.tar.gz")
depends=(python)
makedepends=()
sha256sums=('187588c10ff4804b91e0c947d6b1a4006dbb633261c0f869865de518603c5d5e')
group=(dev.python)
uses=()
arch=('x86_64')

cd psutil-release-$version


build () {
    python3 setup.py build
}

package () {
    python3 setup.py install --skip-build --root="$DESTDIR"
    rm -r "$DESTDIR"/usr/lib/python3*/site-packages/psutil/tests/
}

