#!/usr/bin/env bash
name='doxygen'
release='1'
version='1.9.7'
url='http://www.doxygen.nl/'
description='Documentation system for C++, C, Java, IDL and PHP'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/doxygen/doxygen/archive/refs/tags/Release_${version//./_}.tar.gz")
depends=()
makedepends=(cmake)
md5sums=('c273eeeecaff4902007bd66169c249ca')
group=(app.doc)
uses=()
arch=('x86_64')

cd $name-Release_${version//./_}

setup () {
	cmake -B build -G Ninja \
			-DGIT_EXECUTABLE=/bin/false \
			-DCMAKE_INSTALL_PREFIX=/usr \
			-DCMAKE_BUILD_TYPE=MinSizeRel \
			-Dbuild_xmlparser=ON
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

