#!/usr/bin/env bash
name='doxygen'
release='1'
version='1.9.7'
url='http://www.doxygen.nl/'
description='Documentation system for C++, C, Java, IDL and PHP'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://doxygen.nl/files/doxygen-${version}.src.tar.gz")
depends=(cmake)
makedepends=()
md5sums=('95008edf2d84aeefb7c65a6a4857dc2c')
group=(app.doc)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	cmake -B build -G Ninja \
			-DGIT_EXECUTABLE=/bin/false \
			-DCMAKE_INSTALL_PREFIX=/usr \
			-DCMAKE_BUILD_TYPE=MinSizeRel \
			-Dbuild_xmlparser=ON
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

