#!/usr/bin/env bash
name='polkit'
release='2'
version='123'
url='https://gitlab.freedesktop.org/polkit/polkit'
description='Application development toolkit for controlling system-wide privileges'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/polkit/polkit/-/archive/$version/polkit-$version.tar.gz"
        "polkit.groups"
        "polkit.initd"
        "polkit.passwd"
        "polkit.sysconf")
depends=(duktape expat glib pam elogind)
makedepends=(gobject-introspection gtk-doc meson)
md5sums=('36540b837c588e1e77145523bb39f511'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP')
group=(sys.auth)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dsession_tracking="libelogind" \
        -Dsystemdsystemunitdir=/garbage
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
    rm -rf $DESTDIR/garbage
    install -d $DESTDIR/etc/{passwd,group,sysconf,init}.d
    install ../polkit.sysconf $DESTDIR/etc/sysconf.d/polkit
    install ../polkit.groups $DESTDIR/etc/group.d/polkit
    install ../polkit.passwd $DESTDIR/etc/passwd.d/polkit
    install ../polkit.initd $DESTDIR/etc/init.d/polkit
}

