#!/usr/bin/env bash
name='polkit'
release='3'
version='125'
url='https://gitlab.freedesktop.org/polkit/polkit'
description='Application development toolkit for controlling system-wide privileges'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/polkit-org/polkit/archive/refs/tags/$version.tar.gz"
        "polkit.initd"
        "polkit.sysconf")
depends=(duktape expat glib pam elogind)
makedepends=(gobject-introspection gtk-doc meson)
sha256sums=('ea5cd6e6e2afa6bad938ee770bf0c2cd9317910f37956faeba2869adcf3747d1'
         'SKIP'
         'SKIP')
group=(sys.auth)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dsession_tracking="elogind" \
        -D os_type=redhat \
        -D polkitd_uid=102 \
        -D polkitd_user=polkitd \
        -Dsystemdsystemunitdir=/garbage
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
    rm -rf $DESTDIR/garbage
    install -d $DESTDIR/etc/{passwd,group,sysconf,init}.d
    install ../polkit.sysconf $DESTDIR/etc/sysconf.d/polkit
    install ../polkit.initd $DESTDIR/etc/init.d/polkit
    # GID: polkitd 102
    echo "polkitd:x:102:polkitd" > $DESTDIR/etc/group.d/polkitd
    echo "polkitd:x:102:102:User for polkitd:/var/empty:/sbin/nologin" > $DESTDIR/etc/passwd.d/polkitd
}

