#!/usr/bin/env bash
name='py3-pillow'
release='2'
version='10.0.0'
url='https://python-pillow.org/'
description='Python Imaging Library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://github.com/python-pillow/Pillow/archive/refs/tags/${version}.tar.gz")
depends=(python freetype lcms2  libtiff  libxcb)
makedepends=(git py3-build py3-installer py3-wheel py3-setuptools libwebp)
md5sums=('03b2729023f76331138eb123cc3a5264')
group=()
uses=()
arch=('x86_64')

cd "Pillow"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}