#!/usr/bin/env bash
name='py3-pillow'
release='5'
version='10.3.0'
url='https://python-pillow.org/'
description='Python Imaging Library'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('BSD')
source=("https://github.com/python-pillow/Pillow/archive/refs/tags/${version}.tar.gz")
depends=(python freetype lcms2  libtiff  libxcb)
makedepends=(git py3-build py3-installer py3-wheel py3-setuptools libwebp)
sha256sums=('5a2f1a812237bf9bd57f283422f46ca97a1c3d43d5f67b9bf8a0d499c4b97c85')
group=(dev.python)
uses=()
arch=('x86_64')

cd "Pillow"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}