#!/usr/bin/env bash
name='attr'
release='1'
version='2.5.1'
url='https://mirror.rabisu.com/savannah-nongnu/attr/'
description='The attr package contains utilities to administer the extended attributes on filesystem objects. '
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://mirror.rabisu.com/savannah-nongnu/attr/attr-${version}.tar.gz")
depends=( )
makedepends=( )
md5sums=('ac1c5a7a084f0f83b8cace34211f64d8')
group=(sys.apps)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/attr
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
    echo "/usr/lib64/attr/" > ${DESTDIR}/etc/ld.so.conf.d/attr.conf
}

