#!/usr/bin/env bash
name='xrdb'
release='1'
version='1.2.1'
url='https://gitlab.freedesktop.org/xorg/app/xrdb'
description='X resource database utility'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/app/xrdb/-/archive/xrdb-$version/xrdb-xrdb-$version.tar.gz")
depends=(libX11)
makedepends=()
md5sums=('e82849ca3db670c59df4420e19cd7582')
group=(x11.apps)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

