#!/usr/bin/env bash
name='linux'
release='3'
version='6.6.4'
url='https://cdn.kernel.org/pub/linux/kernel/'
description='Linux kernel'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv2')
source=()
depends=( )
makedepends=(mklinux)
md5sums=('3de364bdbacd2115950cc3dd94157ab6')
uses=()
arch=('x86_64')
group=(sys.kernel)
# Kernel module strip make garbage it.
dontstrip="31"

package(){
    # install kernel (archlinux kernel config used)
    # https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/linux/trunk/config
    ALLOWROOT=1 bash mklinux -i -o "$DESTDIR" -t linux \
     -c "https://gitlab.com/turkman/devel/assets/linux-config/-/raw/main/config"  \
     -v $version -y 1
    # remove headers (for fix conflict with linux-headers)
    rm -rf ${DESTDIR}/usr/include
    # remove broken symlink if exists
    rm -rf ${DESTDIR}/lib/modules/$version/build/linux-$version || true
}

