#!/usr/bin/env bash
name='linux'
release='10'
version='6.17.4'
url='https://cdn.kernel.org/pub/linux/kernel/'
description='Linux kernel'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv2')
source=()
depends=( )
makedepends=(mklinux)
sha256sums=()
uses=()
arch=('x86_64')
group=(sys.kernel)
# Kernel module strip make garbage it.
dontstrip="31"

package(){
    # install kernel (archlinux kernel config used)
    ALLOWROOT=1 bash mklinux -i -o "$DESTDIR" -t linux \
     -c "https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/raw/main/config"  \
     -v $version -y 1
    # remove headers (for fix conflict with linux-headers)
    rm -rf ${DESTDIR}/usr/include
    # remove broken symlink if exists
    rm -rf ${DESTDIR}/lib/modules/$version/build/linux-$version || true
    # decompress kernel modules (if gzipped)
    find ${DESTDIR}/lib/modules -iname "*.ko.gz" -exec gzip -d {} \;
    # decompress kernel modules (if xzed)
    find ${DESTDIR}/lib/modules -iname "*.ko.xz" -exec xz -d {} \;
}

