#!/usr/bin/env bash
name='xorg-macros'
release='1'
version='1.19.3'
url='https://www.x.org/wiki/'
description='X.Org autotools utility macros'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/util/macros/-/archive/util-macros-$version/macros-util-macros-$version.tar.gz")
depends=()
makedepends=()
md5sums=('1fa010576c7c8814195232660553f6f7')
group=(x11.misc)
uses=()
arch=('x86_64')

cd macros-util-macros-$version

setup(){
    	./autogen.sh
	./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install
}

