#!/usr/bin/env bash
name='qt6-quick3d'
release='3'
version='6.8.0'
url='https://www.qt.io/developers'
description='Qt module and API for defining 3D content in Qt Quick'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=(GPLv3)
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtquick3d-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative qt6-quicktimeline qt6-shadertools zlib)
makedepends=(cmake ninja)
sha256sums=('3e95044ee2da33db1a6fa3f834b09e71b2491c4899bac3a3bdf0c10b06f0223f')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtquick3d-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr

}

build () {
	ninja -C build clean
	ninja -C build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
