#!/usr/bin/env bash
name='font-cursor-misc'
release='1'
version='1.0.3'
url='https://gitlab.freedesktop.org/xorg/font/cursor-misc'
description='X.Org cursor font '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/font/cursor-misc/-/archive/font-cursor-misc-$version/cursor-misc-font-cursor-misc-$version.tar.gz")
depends=(font-util)
makedepends=()
md5sums=('5599c23c9116da55363950b724e328b3')
group=(media.fonts)
uses=()
arch=('x86_64')

cd cursor-misc-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

