#!/usr/bin/env bash
name='mklinux'
release='3'
version='20240815'
url='https://gitlab.com/turkman/devel/sources/mklinux'
description='kernel builder'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/mklinux/-/archive/$version/mklinux-$version.zip")
depends=(bc findutils file tar elfutils gcc binutils bison flex make kmod rsync)
makedepends=()
sha256sums=('5dace58267445a79af8b45d4c544f9c594911d9e783eaf2e4db7b5c63a87eea0')
group=(sys.kernel)
uses=()
arch=('x86_64')

cd $name-$version

package(){
    bash mklinux.sh -g -o $DESTDIR
    install mkfw.sh $DESTDIR/usr/bin/mkfw
}

