#!/usr/bin/env bash
name='mklinux'
release='1'
version='20230127'
url='https://gitlab.com/turkman/devel/sources/mklinux'
description='kernel builder'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/mklinux/-/archive/$version/mklinux-$version.zip")
depends=(bc findutils file tar elfutils gcc binutils bison flex make kmod rsync)
makedepends=()
md5sums=('9d409e3763ccf535ebde917f5535ecc0')
group=(sys.kernel)
uses=()
arch=('x86_64')

cd $name-$version

package(){
    bash mklinux.sh -g -o $DESTDIR
}

