#!/usr/bin/env bash
name='gawk'
release='2'
version='5.3.0'
url='https://savannah.gnu.org/projects/gawk'
description='GNU awk pattern-matching language'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/gawk/gawk-$version.tar.xz")
depends=(mpfr readline)
makedepends=()
md5sums=('97c5a7d83f91a7e1b2035ebbe6ac7abd')
uses=()
group=(sys.apps)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --without-libsigsegv
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

