#!/usr/bin/env bash
name='kcalendarcore'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='The KDE calendar access library'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcalendarcore-${version}.tar.xz")
depends=(libical qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('4d2330af35d56c59ee69f08f3845babee9896d00012bccfbb143bdc571bc58e7')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

