#!/usr/bin/env bash
name='libtracefs'
release='3'
version='1.8.0'
url='https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/'
description='Linux kernel trace file system library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/snapshot/libtracefs-$version.tar.gz")
depends=(libtraceevent)
makedepends=()
md5sums=('9421a747292616a29b41f17b7dfa17d9')
group=(net.libs)
uses=()
arch=('x86_64')

cd $name-$version

build(){
    make libdir_relative=lib64 prefix=/usr $jobs
}

package(){
    make libdir_relative=lib64 prefix=/usr install $jobs
}

