#!/usr/bin/env bash
name='libtracefs'
release='2'
version='1.7.0'
url='https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/'
description='Linux kernel trace file system library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://git.kernel.org/pub/scm/libs/libtrace/libtracefs.git/snapshot/libtracefs-$version.tar.gz")
depends=(libtraceevent)
makedepends=()
md5sums=('f425ce100c05de04aa1c72b487507214')
group=(net.libs)
uses=()
arch=('x86_64')

cd $name-$version

build(){
    make libdir_relative=lib64 prefix=/usr $jobs
}

package(){
    make libdir_relative=lib64 prefix=/usr install $jobs
}

