#!/usr/bin/env bash
name='py3-lxml'
release='2'
version='5.4.0'
url='https://pypi.org/project/lxml/'
description='Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxml/lxml/archive/refs/tags/lxml-$version.tar.gz")
depends=(python libxml2 libxslt py3-cython)
makedepends=()
sha256sums=('12ed971a99bd07977e236bf59314cfd53fbf5d59f39d4a13caad901c7fceb0a2')
group=(dev.python)
uses=()
arch=('x86_64')


cd lxml-lxml-$version

unset CFLAGS
unset CXXFLAGS
unset LDFLAGS

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}

