#!/usr/bin/env bash
name='prison'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='A barcode API to produce QRCode barcodes and DataMatrix barcodes'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/prison-${version}.tar.xz")
depends=(qt6-base libdmtx qrencode qt6-multimedia)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('6ff5fbc6fc38581072ee45904e022d5bf2e7b3b1f49ac9d1d0c6024d7ca3ec5a')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	cmake -B build \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON
}

build () {
    cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

