#!/usr/bin/env bash
name='prison'
release='1'
version='5.112.0'
url='https://community.kde.org/Frameworks'
description='A barcode API to produce QRCode barcodes and DataMatrix barcodes'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/5.112/prison-$version.tar.xz")
depends=(qt5-base)
makedepends=()
md5sums=('7829a393955af2d58f9a27cfb06f18ad')
group=(kde.framework)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
         -DBUILD_TESTING=OFF \
         -DBUILD_QCH=ON
}

build () {
    cmake --build build
}

package () {
    cmake --install build
}

