#!/usr/bin/env bash
name='prison'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='A barcode API to produce QRCode barcodes and DataMatrix barcodes'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/prison-${version}.tar.xz")
depends=(qt6-base libdmtx qrencode qt6-multimedia zxing-cpp)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('38a4f154b39b4d2e4b86d16f84846039d27bd70cb26ecd488b591f612dd4141e')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	cmake -B build \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON
}

build () {
    cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

