#!/usr/bin/env bash
name='py3-snowballstemmer'
release='2'
version='3.0.1'
url='https://snowballstem.org/'
description='Snowball stemming library collection for Python3'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
#source=("https://github.com/snowballstem/snowball/archive/refs/tags/v${version}.tar.gz")
source=("https://pypi.python.org/packages/source/s/snowballstemmer/snowballstemmer-${version}.tar.gz")
depends=(python)
makedepends=()
sha256sums=('6d5eeeec8e9f84d4d56b847692bacf79bc2c8e90c7f80ca4444ff8b6f2e52895')
group=(dev.python)
uses=()
arch=('x86_64')

cd "snowballstemmer"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
