#!/bin/bash
name=make-ca
release=1
version=1.10
url='https://github.com/lfs-book/make-ca'
description='Ssl certificates'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/lfs-book/make-ca/releases/download/v1.10/make-ca-${version}.tar.xz
        make-ca.sysconf")
md5sums=('74f1ad16d7a086ac76e0424fd4dfe67b'
         'SKIP')
depends=(p11-kit)
arch=(x86_64)
group=(app.misc)

cd "$name-$version"

build(){
    sed -i "s|/usr/bin/cut|/bin/cut|g" make-ca
    sed -i "s|/usr/bin/md5sum|/bin/md5sum|g" make-ca
    make
}

package(){
    make install SBINDIR="/sbin/"
    mkdir -p "$DESTDIR"/etc/sysconf.d
    install ../make-ca.sysconf "$DESTDIR"/etc/sysconf.d/make-ca
}
