#!/usr/bin/env bash
name='hello'
release='1'
version='2.12'
url='https://example.org'
description='Hello world Package'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/hello/hello-2.12.tar.gz")
depends=( )
makedepends=( )
md5sums=('SKIP')
arch=(x86_64)
group=(system.devel)
dontstrip="1"

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make
}

package(){
    make install
}
