#!/usr/bin/env bash
name='acl'
release='1'
version='2.3.1'
url='https://mirror.rabisu.com/savannah-nongnu/acl'
description='The acl package contains utilities to administer Access Control Lists'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('LGPL')
source=("https://download.savannah.nongnu.org/releases/acl/acl-$version.tar.xz")
depends=(attr)
makedepends=( )
md5sums=('95ce715fe09acca7c12d3306d0f076b2')
group=(sys.apps)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/acl
}
https://gitlab.com/sulix/packages/binary-repo
build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/usr/lib64/acl/" > ${DESTDIR}/etc/ld.so.conf.d/acl.conf
    mv ${DESTDIR}/usr/lib64/{$name/pkgconfig,}
}
