#!/usr/bin/env bash
name='acl'
release='2'
version='2.3.2'
url='https://mirror.rabisu.com/savannah-nongnu/acl'
description='The acl package contains utilities to administer Access Control Lists'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('LGPL')
source=("https://download.savannah.nongnu.org/releases/acl/acl-$version.tar.xz")
depends=(attr)
makedepends=( )
md5sums=('590765dee95907dbc3c856f7255bd669')
group=(sys.apps)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}
build(){
    make $jobs
}

package(){
    make install $jobs
}
