#!/usr/bin/env bash
name='gst-plugins-base'
release='3'
version='1.22.7'
url='https://gitlab.freedesktop.org/gstreamer'
description='GStreamer plugins and helper libraries'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-${version}.tar.xz")
#source=("https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/archive/$version/gst-plugins-base-$version.tar.gz")
depends=(gstreamer orc)
makedepends=()
md5sums=('156e377fb065b9ba5d38d30385f15608')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}
