#!/usr/bin/env bash
name='gst-plugins-base'
release='4'
version='1.24.7'
url='https://gitlab.freedesktop.org/gstreamer'
description='GStreamer plugins and helper libraries'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-${version}.tar.xz")
#source=("https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/archive/$version/gst-plugins-base-$version.tar.gz")
depends=(gstreamer orc)
makedepends=()
sha256sums=('1528d1746a393299f5ac17ebf13a32a660202f1e29d0a852a2250f6a059a2fda')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}
