#!/usr/bin/env bash
name='gst-plugins-base'
release='1'
version='1.18.6'
url='https://gitlab.freedesktop.org/gstreamer'
description='GStreamer plugins and helper libraries'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/archive/$version/gst-plugins-base-$version.tar.gz")
depends=(gstreamer)
makedepends=()
md5sums=('848c60f921e07464538f0aff82c0bc7d')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}
