#!/usr/bin/env bash
name='knotifications'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Abstraction for system notifications'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/knotifications-${version}.tar.xz")
depends=(qt6-base libcanberra kconfig)
makedepends=(extra-cmake-modules qt6-tools doxygen qt6-declarative)
sha256sums=('593cb00c9e04018477ba146031f6d46f4079c637c6a46630566712d842b9f3a8')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_PYTHON_BINDINGS=OFF \
		-DBUILD_QCH=ON \
		-DWITH_X11=$(usex X)
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

