#!/usr/bin/env bash
name='knotifications'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Abstraction for system notifications'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/knotifications-${version}.tar.xz")
depends=(qt6-base libcanberra kconfig)
makedepends=(extra-cmake-modules qt6-tools doxygen qt6-declarative)
sha256sums=('9e972f015d9b31b3283bf842a32d270096224d127c13a6e79450f4f0452de5e7')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON \
		-DWITH_X11=$(usex X)
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

