#!/usr/bin/env bash
name='xmodmap'
release='1'
version='1.0.11'
url='https://gitlab.freedesktop.org/xorg/app/xmodmap'
description='utility for modifying keymaps and pointer button mappings in X'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://xorg.freedesktop.org/archive/individual/app/xmodmap-$version.tar.gz")
depends=(libX11)
makedepends=()
md5sums=('b9ffdd93021e279f5c4f6c49b6bd00b9')
group=(x11.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
   	./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

