#!/usr/bin/env bash
name='flac'
release='1'
version='1.4.2'
url='https://xiph.org/flac/'
description=' Free lossless audio encoder and decoder '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/xiph/flac/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
md5sums=('1b7e335a4a2a43bea1ac5796be57f2b0')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
  ./autogen.sh	
   ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

