#!/usr/bin/env bash
name='libsass'
release='1'
version='3.6.5'
url='https://sass-lang.com/libsass'
description='C/C++ implementation of a Sass compiler'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/sass/libsass/archive/${version}.tar.gz")
depends=()
makedepends=()
md5sums=('c49765b9b3824dcd4a7423225ca28bad')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

