#!/usr/bin/env bash
name='kauth'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description='Abstraction to system policy and authentication features'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kauth-${version}.tar.xz")
depends=(qt5-base kcoreaddons)
makedepends=(extra-cmake-modules graphviz qt5-tools doxygen)
md5sums=('763be13bb190f61d2ceaec14ea8d8887')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


