#!/usr/bin/env bash
name='kpty'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Pty abstraction'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kpty-${version}.tar.xz")
depends=(kcoreaddons)
makedepends=(doxygen extra-cmake-modules qt6-tools ki18n)
sha256sums=('3f800638fcc0dbea0810930a1f2decfa6b894bb00732ff8646182c7dfd2ac76d')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

