#!/usr/bin/env bash
name='kpty'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Pty abstraction'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kpty-${version}.tar.xz")
depends=(kcoreaddons)
makedepends=(doxygen extra-cmake-modules qt6-tools ki18n)
sha256sums=('42cc1b1f70ee0bdacd26812857d31047d218e1f585ac35fe9165908501a9946a')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

