#!/usr/bin/env bash
name='xfce4-battery-plugin'
release='2'
version='1.2.0'
url='https://docs.xfce.org/panel-plugins/xfce4-battery-plugin'
description='A battery monitor plugin for the Xfce panel'
email='03teknoloji@gmail.com'
maintainer='mobilturka'
license=('GPL2')
source=("https://archive.xfce.org/src/panel-plugins/$name/${version%.*}/$name-$version.tar.xz")
depends=(xfce4-panel)
makedepends=(intltool)
sha256sums=('1dba8f470d2b12517e7b86d83cd2ebf13eb57ff1a01a4f2d2d156cf5194d97b6')
group=(xfce.extra)
uses=()
arch=('x86_64')


cd $name-$version

setup() {
     meson setup build \
      --prefix=/usr \
      --sysconfdir=/etc \
      --localstatedir=/var
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

