#!/usr/bin/env bash
name='qt5-websockets'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='Provides WebSocket communication compliant with RFC 6455'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtwebsockets-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base qt5-declarative qt5-websockets)
makedepends=()
md5sums=('edcc0916088caf3aed27b3d4b01036ba')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtwebsockets-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

