#!/usr/bin/env bash
name='qt5-websockets'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='Provides WebSocket communication compliant with RFC 6455'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtwebsockets-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base qt5-declarative)
makedepends=()
sha256sums=('4bf4c0b699852111fcbea96c122f0cee3a04df9e4da60c5324ad1e18223a78c5')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtwebsockets-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

