#!/usr/bin/env bash
name='libICE'
release='1'
version='1.1.1'
url='https://example.org'
description='Package libICE'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://www.x.org/archive/individual/lib/libICE-1.1.1.tar.xz')
depends=(xorgproto)
makedepends=()
md5sums=('b444a0e4c2163d1bbc7b046c3653eb8d')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

