#!/usr/bin/env bash
name='xfce4-power-manager'
release='2'
version='4.18.1'
_version='4.18'
url='https://docs.xfce.org/xfce/xfce4-power-manager/start'
description='Power Manager for Xfce'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfce4-power-manager/${_version}/xfce4-power-manager-${version}.tar.bz2")
depends=(libnotify  libxfce4ui upower)
makedepends=(xfce4-panel intltool)
sha256sums=('6b08b10c4cb7516377dbd32c6cc2296a9faf47022c555f11e75b38fde14aff03')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--localstatedir=/var \
		--disable-network-manager \
		--enable-polkit \
		--disable-debug
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

