#!/usr/bin/env bash
name='xfce4-power-manager'
release='3'
version='4.20.0'
_version='4.20'
url='https://docs.xfce.org/xfce/xfce4-power-manager/start'
description='Power Manager for Xfce'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfce4-power-manager/${_version}/xfce4-power-manager-${version}.tar.bz2")
depends=(libnotify  libxfce4ui upower)
makedepends=(xfce4-panel intltool)
sha256sums=('971391cef63352833bdd92df28957392e17e1f2b3d486c0f57294fd204d6ed29')
group=(xfce.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--localstatedir=/var \
		--disable-network-manager \
		--enable-polkit
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

