#!/usr/bin/env bash
name='lightdm-pardus-greeter'
release='5'
version='0.3.0'
url='https://github.com/pardus/pardus-lightdm-greeter'
description='Lightdm greeter for Pardus'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pardus/pardus-lightdm-greeter/archive/refs/tags/debian/$version.tar.gz")
depends=(lightdm py3-pygobject py3-cairo)
makedepends=()
sha256sums=('b610ec9ab4e11512faf155a978bbefbcd05af49973b8c9b272f50776d170386f')
group=(x11.misc)
uses=()
arch=('x86_64')

cd pardus-lightdm-greeter-debian-$version

build(){
    make $jobs
}

package(){
    make install $jobs
}

