#!/usr/bin/env bash
name='lightdm-pardus-greeter'
release='7'
version='0.4.7'
url='https://github.com/pardus/pardus-lightdm-greeter'
description='Lightdm greeter for Pardus'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pardus/pardus-lightdm-greeter/archive/refs/tags/debian/$version.tar.gz")
depends=(lightdm py3-pygobject py3-cairo )
makedepends=()
sha256sums=('e1df960442bf0ff4d0f40feed4d994c8b5573529de6dea969ba774d6ef92be5c')
group=(x11.misc)
uses=()
arch=('x86_64')

cd pardus-lightdm-greeter-debian-$version

setup(){
    meson setup build \
        --prefix=/usr
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

