#!/usr/bin/env bash
name='initramfs-tools'
release='2'
version='0.143'
url='https://salsa.debian.org/kernel-team/initramfs-tools'
description='Initial ramdisk system from debian'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://salsa.debian.org/kernel-team/initramfs-tools/-/archive/v$version/initramfs-tools-v$version.tar.gz"
        "patches/remove-zstd.patch"
        "patches/non-debian.patch"
        "patches/no-dracut.patch"
        "patches/remove-logsave.patch"
        "initramfs-tools.sysconf")
depends=(eudev findutils coreutils)
makedepends=()
sha256sums=('5d3091b0393c4246bcdae499cfd5ba490c78194d7eede01d951f4124ff2f9895'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP')
uses=()
group=(sys.kernel)
arch=('x86_64')

cd $name-v$version

prepare(){
    patch -Np1 -i ../remove-zstd.patch
    patch -Np1 -i ../remove-logsave.patch
    patch -Np1 -i ../non-debian.patch
    patch -Np1 -i ../no-dracut.patch
    # hidepid=2 default
    sed -i "s/ proc \/proc/,hidepid=2,gid=31&/g" init
    # replace linux-version command
    sed -i "s/linux-version/false/g" hook-functions
    sed -i "s/linux-version list/ls \/lib\/modules\//g" update-initramfs
    sed -i "s/linux-version sort --reverse/cat/g" update-initramfs
}

package(){
    cat debian/*.install | sed "s/\t/ /g" | tr -s " " | while read line ; do
        file=$(echo $line | cut -f1 -d" ")
        target=$(echo $line | cut -f2 -d" ")
        mkdir -p ${DESTDIR}/$target
        cp -prvf $file ${DESTDIR}/$target/
    done
    # install mkinitramfs
    cp -pvf mkinitramfs ${DESTDIR}/usr/sbin/mkinitramfs
    sed -i "s/@BUSYBOX_PACKAGES@/busybox/g" ${DESTDIR}/usr/sbin/mkinitramfs
    sed -i "s/@BUSYBOX_MIN_VERSION@/1.22.0/g" ${DESTDIR}/usr/sbin/mkinitramfs
    # Remove debian stuff
    rm -rvf ${DESTDIR}/etc/kernel
    # install sysconf
    mkdir -p ${DESTDIR}/etc/sysconf.d
    install ../initramfs-tools.sysconf ${DESTDIR}/etc/sysconf.d/initramfs-tools
}

