#!/usr/bin/env bash
name='garcon'
release='3'
version='4.20.0'
_version='4.20'
url='https://docs.xfce.org/xfce/garcon/start'
description='Freedesktop.org compliant menu library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2' 'LGPL')
source=("https://archive.xfce.org/src/xfce/garcon/${_version}/garcon-${version}.tar.bz2")
depends=(libxfce4ui)
makedepends=(intltool)
sha256sums=('7fb8517c12309ca4ddf8b42c34bc0c315e38ea077b5442bfcc4509415feada8f')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}
