#!/usr/bin/env bash
name='garcon'
release='2'
version='4.18.2'
_version='4.18'
url='https://docs.xfce.org/xfce/garcon/start'
description='Freedesktop.org compliant menu library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2' 'LGPL')
source=("https://archive.xfce.org/src/xfce/garcon/${_version}/garcon-${version}.tar.bz2")
depends=(libxfce4ui)
makedepends=(intltool)
sha256sums=('1b8c9292e131968fbfc8987bbc62c5ba47186dd45ef4e47c5d8c5088bb2d434d')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug 
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}
