#!/usr/bin/env bash
name='xcb-util-renderutil'
release='1'
version='0.3.10'
url='https://xcb.freedesktop.org'
description='X C-language Bindings sample implementations'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/xcb/xcb-util-renderutil-${version}.tar.xz")
depends=(libxcb)
makedepends=(util-macros xorgproto)
md5sums=('193b890e2a89a53c31e2ece3afcbd55f')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
	--enable-shared \
	--enable-static \
	--disable-devel-docs \
	--without-doxygen
}

build(){
    make $jobs
}

package(){
    make install $jobs
}
