#!/usr/bin/env bash
name='py3-setproctitle'
release='3'
version='1.3.6'
url='https://github.com/dvarrazzo/py-setproctitle'
description='A Python module to customize the process title'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD-3-Clause')
source=("https://github.com/dvarrazzo/py-setproctitle/archive/refs/tags/version-${version}.tar.gz")
depends=(python)
makedepends=()
sha256sums=('be91b6f4e476bf3c6412db08df79f95cd54f8e1bb52b35452fb38066997a9cce')
group=(dev.python)
uses=()
arch=('x86_64')

cd "py-setproctitle-version"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}


