#!/usr/bin/env bash
name='py3-setproctitle'
release='2'
version='1.3.3'
url='https://github.com/dvarrazzo/py-setproctitle'
description='A Python module to customize the process title'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD-3-Clause')
source=("https://github.com/dvarrazzo/py-setproctitle/archive/refs/tags/version-${version}.tar.gz")
depends=(python)
makedepends=()
sha256sums=('c4ff32c5482f7b434bd3b3a29d11a4cbac05e5f3b88eeba24c8ba7d2e405af9d')
group=(dev.python)
uses=()
arch=('x86_64')

cd "py-setproctitle-version"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}


