#!/usr/bin/env bash
name='py3-cython'
release='3'
version='3.1.2'
url='https://cython.org/'
description='A Python to C compiler.'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/cython/cython/archive/refs/tags/$version.tar.gz")
depends=(python libxml2 libxslt)
makedepends=(py3-build py3-installer py3-wheel py3-setuptools)
sha256sums=('da72f94262c8948e04784c3e6b2d14417643703af6b7bd27d6c96ae7f02835f1')
group=(dev.python)
uses=()
arch=('x86_64')

unset CFLAGS
unset CXXFLAGS
unset LDFLAGS


cd cython-$version

build(){
    python3 setup.py build
}

package(){
  python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}

