#!/usr/bin/env bash
name='py3-cython'
release='2'
version='3.0.10'
url='https://cython.org/'
description='A Python to C compiler.'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/cython/cython/archive/refs/tags/$version.tar.gz")
depends=(python3.11 libxml2 libxslt)
makedepends=(py3-build py3-installer py3-wheel py3-setuptools)
sha256sums=('00f97476cef9fcd9a89f9d2a49be3b518e1a74b91f377fe08c97fcb44bc0f7d7')
group=(dev.python)
uses=()
arch=('x86_64')

  cd cython-$version

build(){
    python3 setup.py build
}

package(){
  python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

