#!/usr/bin/env bash
name='pipewire'
release='2'
version='1.0.0'
url='https://pipewire.org/'
description='Multimedia processing graphs '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/$version/pipewire-$version.tar.gz"
        "pipewire.desktop"
        "pipewire-launcher.sh")
depends=(lilv libpulse alsa-lib dbus)
makedepends=()
md5sums=('0452405de47b4a619766f18fbda4bfa1'
         'SKIP'
         'SKIP')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
   #./autogen.sh 
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64 \
    -D session-managers=[]
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/usr/libexec ${DESTDIR}/etc/xdg/autostart/
    # pipewire launcher from alpine linux
    install ../pipewire-launcher.sh ${DESTDIR}/usr/libexec/pipewire-launcher
    install ../pipewire.desktop ${DESTDIR}/etc/xdg/autostart/
    
}
