#!/usr/bin/env bash
name='dkms'
release='2'
version='3.2.1'
url='https://github.com/dell/dkms'
description='Dynamic Kernel Module Support'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/dell/dkms/archive/refs/tags/v$version.tar.gz")
depends=(bash coreutils gcc mklinux sed patch linux-headers)
makedepends=()
sha256sums=('15941af7312af595ced516955aad33df82452c3ec9649ee48ababf8564682e03')
group=(sys.kernel)
uses=()
arch=('x86_64')

cd $name-$version


package () {
    make KCONF=/../trash \
        install $jobs
}

