#!/usr/bin/env bash
name='dkms'
release='1'
version='3.0.13'
url='https://github.com/dell/dkms'
description='Dynamic Kernel Module Support'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/dell/dkms/archive/refs/tags/v$version.tar.gz")
depends=(bash coreutils gcc mklinux sed patch linux-headers)
makedepends=()
sha256sums=('ceb5bbb89ece7310ee96952a56c926faa51c4486f7e5e43c8589585056e45bb5')
group=(sys.kernel)
uses=()
arch=('x86_64')

cd $name-$version


package () {
    make KCONF=/../trash \
        install $jobs
}

