#!/usr/bin/env bash
name='libsoup2'
release='1'
version='2.74.3'
url='https://gitlab.gnome.org/GNOME/libsoup.git/'
description='HTTP client/server library for GNOME'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.gnome.org/sources/libsoup/2.74/libsoup-2.74.3.tar.xz")
depends=(smartypants glib-networking brotli)
makedepends=()
md5sums=('8f657fd301a213629204b3320c35d75a')
group=(net.libs)
uses=()
arch=('x86_64')

cd libsoup-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dsysprof=disabled
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

