#!/usr/bin/env bash
name='cinnamon-desktop'
release='2'
version='6.0.0'
url='https://github.com/linuxmint/cinnamon-desktop'
description='Library with common API for various Cinnamon modules'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/linuxmint/cinnamon-desktop/archive/$version/cinnamon-desktop-$version.tar.gz")
depends=()
makedepends=(libXinerama libxkbfile)
md5sums=('265b69d5f57e9600c673c6be79ec20e0')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

