#!/usr/bin/env bash
name='cinnamon-desktop'
release='1'
version='5.6.1'
url='https://github.com/linuxmint/cinnamon-desktop'
description='Library with common API for various Cinnamon modules'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/linuxmint/cinnamon-desktop/archive/$version/cinnamon-desktop-$version.tar.gz")
depends=()
makedepends=(libXinerama libxkbfile)
md5sums=('d584d51f1896e75479807503f7e9c0d6')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ 
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

