#!/usr/bin/env bash
name='cinnamon-desktop'
release='2'
version='5.8.0'
url='https://github.com/linuxmint/cinnamon-desktop'
description='Library with common API for various Cinnamon modules'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/linuxmint/cinnamon-desktop/archive/$version/cinnamon-desktop-$version.tar.gz")
depends=()
makedepends=(libXinerama libxkbfile)
md5sums=('cde124596a427145f001b33a9d77f183')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

