#!/usr/bin/env bash
name='libtirpc'
release='1'
version='1.3.3'
url='https://example.org'
description='Transport Independent RPC library (SunRPC replacement)'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.3.tar.bz2')
depends=( )
makedepends=( )
md5sums=('bacdad5c27dcf6e2830b3e26a1c8ed3f')
uses=()
group=(net.libs)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/libtirpc \
        --disable-gssapi
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/usr/lib64/libtirpc/" > ${DESTDIR}/etc/ld.so.conf.d/libtirpc.conf
}

