#!/usr/bin/env bash
name='kpackage'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Framework that lets applications manage user installable packages of non-binary assets'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kpackage-${version}.tar.xz")
depends=(qt6-base karchive ki18n kcoreaddons)
makedepends=(doxygen extra-cmake-modules qt6-tools kdoctools)
sha256sums=('d2aec3df0dffb71e93acc03c46f2d4ca59c58263a9989df75107bf5223e9d1b7')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

