#!/usr/bin/env bash
name='kpackage'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Framework that lets applications manage user installable packages of non-binary assets'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kpackage-${version}.tar.xz")
depends=(karchive ki18n kcoreaddons)
makedepends=(doxygen extra-cmake-modules qt5-tools)
md5sums=('5e8011e0dcd69e4c3b12f75b2820af34')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

