#!/usr/bin/env bash
name='py3-tz'
release='2'
version='2024.1'
url='https://pypi.python.org/pypi/pytz'
description='Python3 definitions of world timezone'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://pypi.python.org/packages/source/p/pytz/pytz-${version}.tar.gz")
depends=(python)
makedepends=()
sha256sums=('2a29735ea9c18baf14b448846bde5a48030ed267578472d8955cd0e7443a9812')
group=(dev.python)
uses=()
arch=('x86_64')

cd "pytz"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

