#!/usr/bin/env bash
name='py3-tz'
release='1'
version='2023.3'
url='https://pypi.python.org/pypi/pytz'
description='Python3 definitions of world timezone'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://pypi.python.org/packages/source/p/pytz/pytz-${version}.tar.gz")
depends=(python)
makedepends=()
md5sums=('fe54c8f8a1544b4e78b523b264ab071b')
group=(dev.python)
uses=()
arch=('x86_64')

cd "pytz"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

