#!/usr/bin/env bash
name='py3-tz'
release='3'
version='2025.2'
url='https://pypi.python.org/pypi/pytz'
description='Python3 definitions of world timezone'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://pypi.python.org/packages/source/p/pytz/pytz-${version}.tar.gz")
depends=(python)
makedepends=()
sha256sums=('360b9e3dbb49a209c21ad61809c7fb453643e048b38924c765813546746e81c3')
group=(dev.python)
uses=()
arch=('x86_64')

cd "pytz"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

