#!/usr/bin/env bash
name='meson'
release='2'
version='1.2.0'
url='https://github.com/mesonbuild/meson'
description='High productivity build system'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/mesonbuild/meson/releases/download/$version/meson-$version.tar.gz")
depends=(python py3-setuptools)
makedepends=( )
md5sums=('677616183f2c5e03e2139b06280129a0')
uses=()
group=(dev.util)
arch=('x86_64')

cd $name-$version

build(){
    python3 -m build
}

package(){
    python -m installer --destdir="$DESTDIR" dist/*.whl
    # move to version independent
    mkdir -p "${DESTDIR}/usr/lib64/python3"
    mv ${DESTDIR}/usr/lib/python*/site-packages/* "${DESTDIR}/usr/lib64/python3"
    rm -rf "${DESTDIR}/usr/lib"
    install -d "${DESTDIR}/usr/share/vim/vimfiles"
    cp -rt "${DESTDIR}/usr/share/vim/vimfiles" data/syntax-highlighting/vim/*/

    install -Dt "${DESTDIR}/usr/share/bash-completion/completions" -m644 data/shell-completions/bash/*
    install -Dt "${DESTDIR}/usr/share/zsh/site-functions" -m644 data/shell-completions/zsh/*
    # fix hardcoded interpreter location
    sed -i "1s|.*|#!/usr/bin/python3|g" "${DESTDIR}/usr/bin/meson"
}

