#!/usr/bin/env bash
name='cogl'
release='1'
version='1.22.8'
url='https://gitlab.gnome.org/Archive/cogl'
description='An object oriented GL/GLES Abstraction/Utility Layer'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://download.gnome.org/sources/cogl/1.22/cogl-$version.tar.xz")
depends=(mesa libdrm libXext libXdamage libXcomposite gdk-pixbuf pango libXrandr)
makedepends=(gobject-introspection git gtk-doc)
md5sums=('7dd8b2e24171ef7399f851cea144b569')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
#	autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--localstatedir=/var \
		--disable-debug \
		--enable-gles2 \
		--enable-gl \
		--enable-gdk-pixbuf \
		--enable-introspection \
		--enable-cairo \
		--enable-gtk-doc=no \
		--enable-gtk-doc-html=no \
		--enable-gtk-doc-pdf=no \
		--enable-wayland-egl-platform \
		--enable-wayland-egl-server \
		--disable-dependency-tracking
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

