#!/usr/bin/env bash
name='nemo'
release='5'
version='6.4.3'
url='https://github.com/linuxmint/nemo'
description='File manager for the Cinnamon desktop environment'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://github.com/linuxmint/nemo/archive/refs/tags/${version}.tar.gz")
depends=(cinnamon-desktop dconf gvfs libexif libgsf libnotify libxml2 python xapp)
makedepends=(meson intltool gobject-introspection)
sha256sums=('dc4b2ed52fd69551a53fd95a008a738fc9c904fc79d41c8e39ec49bfd739094e')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
 		--libdir=/usr/lib64/ \
		-Dxmp=false \
		-Dselinux=false
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR="$DESTDIR" ninja -C build install $jobs
}
