#!/usr/bin/env bash
name='jansson'
release='1'
version='2.14'
url='https://github.com/akheron/jansson'
description='C library for encoding, decoding and manipulating JSON data'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/akheron/jansson/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
md5sums=('bc78f39c7cd7fab1dd5fc4a2c3be1661')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

