#!/usr/bin/env bash
name='mesa'
release='8'
version='24.3.4'
url='https://gitlab.freedesktop.org/mesa/mesa'
description='An open-source implementation of the OpenGL specification'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/mesa/mesa/-/archive/mesa-$version/mesa-mesa-$version.tar.gz")
depends=(libva libvdpau libdrm llvm glslang elfutils libclc py3-mako libglvnd eudev)
makedepends=(git directx-headers py3-ply py3-yaml)
sha256sums=('966b515c83e6d52f34a151194abd0464b1a7af87158eba4036801a600216288e')
group=(media.libs)
uses=(wayland x11)
wayland_depends=(wayland wayland-protocols)
x11_depends=(libxshmfence libXxf86vm libXrandr)
arch=('x86_64')

cd $name-$name-$version

export CFLAGS="-O3 -s"
export CXXFLAGS="-O3 -s"

setup(){
    meson setup build --prefix=/usr \
        -D b_ndebug=true \
        -D b_lto=false \
        -D platforms=$(use_opt x11 x11 ""),$(use_opt wayland wayland "") \
        -D gallium-drivers=r300,r600,radeonsi,nouveau,virgl,svga,llvmpipe,softpipe,swrast,i915,iris,crocus,zink,d3d12 \
        -D vulkan-drivers=amd,intel,intel_hasvk,swrast,virtio \
        -D vulkan-layers=device-select,intel-nullhw,overlay \
        -D platforms=x11,wayland \
        -D llvm=enabled \
        -D shared-llvm=enabled \
        -D shared-glapi=enabled \
        -D gbm=enabled \
        -D glx=dri \
        -D opengl=true \
        -D osmesa=true \
        -D gles1=enabled \
        -D gles2=enabled \
        -D egl=enabled \
        -D gallium-extra-hud=true \
        -D gallium-nine=true \
        -D gallium-rusticl=false \
        -D gallium-va=enabled \
        -D gallium-vdpau=enabled \
        -D gallium-xa=enabled \
        -D rust_std=2021 \
        -D video-codecs=all \
        -D lmsensors=disabled \
        -D zstd=false

}

build(){
    ninja -C build ${jobs}
}

package(){
    ninja -C build install
}

