#!/usr/bin/env bash
name='font-util'
release='1'
version='1.3.3'
url='https://gitlab.freedesktop.org/xorg/font/util'
description='X.Org font utilities'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/font/util/-/archive/font-util-$version/util-font-util-$version.tar.gz")
depends=()
makedepends=()
md5sums=('60dfc824f9b5b38e5935268ffe6d0fb4')
group=(media.fonts)
uses=()
arch=('x86_64')

cd util-$name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

