#!/usr/bin/env bash
name='font-util'
release='2'
version='1.4.1'
url='https://gitlab.freedesktop.org/xorg/font/util'
description='X.Org font utilities'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/font/util/-/archive/font-util-$version/util-font-util-$version.tar.gz")
depends=()
makedepends=()
sha256sums=('f0129159515c13ebe53ba2a6a94755e98c266470e844ee0aacc6196fd62b44f0')
group=(media.fonts)
uses=()
arch=('x86_64')

cd util-$name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

