#!/usr/bin/env bash
name='flatpak-builder'
release='2'
version='1.4.0'
url='https://salsa.debian.org/debian/flatpak-builder'
description='Sandboxed app framework - developer tools'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/flatpak/flatpak-builder/releases/download/$version/flatpak-builder-$version.tar.xz")
depends=(flatpak elfutils git patch dconf)
makedepends=()
md5sums=('9cc2c9156ba828c2e7810c20e66cacfb')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build \
        --prefix=/usr \
        --sysconfdir=/etc \
        --libdir=/usr/lib64/ \
       -Dfuse=3

}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

