#!/usr/bin/env bash
name='flatpak-builder'
release='1'
version='1.3.3'
url='https://salsa.debian.org/debian/flatpak-builder'
description='Sandboxed app framework - developer tools'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://salsa.debian.org/debian/flatpak-builder/-/archive/upstream/1.3.3/flatpak-builder-upstream-1.3.3.tar.gz')
depends=(flatpak elfutils git patch)
makedepends=()
md5sums=('2905c9f70b28815d7c0faad7d928e8b6')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-upstream-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

