#!/usr/bin/env bash
name='perl-libwww'
release='2'
version='6.72'
url='https://metacpan.org/release/libwww-perl'
description='The World-Wide Web library for Perl'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('PerlArtistic' 'GPL')
source=("https://cpan.metacpan.org/authors/id/O/OA/OALDERS/libwww-perl-$version.tar.gz")
depends=(perl )
makedepends=()
md5sums=('ea683625d1c875c583ae8859602bac66')
group=(dev.perl)
uses=()
arch=('x86_64')

cd "libwww-perl"-$version

setup(){
    perl Makefile.PL --aliases INSTALLDIRS=vendor
        PREFIX=/usr \
        LIBDIR=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make DESTDIR=$DESTDIR install $jobs
}

