#!/usr/bin/env bash
name='hyprwayland-scanner'
release='2'
version='0.4.4'
url='https://github.com/hyprwm/hyprlang'
description='A Hyprland implementation of wayland-scanner, in and for C++.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/hyprwayland-scanner/archive/refs/tags/v$version.tar.gz")
depends=(hyprutils glib pugixml)
makedepends=()
sha256sums=('ac73f626019f8d819ff79a5fca06ce4768ce8a3bded6f48c404445f3afaa25ac')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

