#!/usr/bin/env bash
name='libtraceevent'
release='1'
version='1.7.2'
url='https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/'
description='Linux kernel trace event library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/snapshot/libtraceevent-$version.tar.gz")
depends=()
makedepends=()
md5sums=('5a8cd771ab709e7a7eb793555c7e570f')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version
setup(){
	#./configure --prefix=/usr \
       #--libdir=/usr/lib64/
       echo ""
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

