#!/usr/bin/env bash
name='libtraceevent'
release='2'
version='1.8.1'
url='https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/'
description='Linux kernel trace event library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://git.kernel.org/pub/scm/libs/libtrace/libtraceevent.git/snapshot/libtraceevent-$version.tar.gz")
depends=()
makedepends=()
md5sums=('4ab55447c9ccfbfb12ba5e9b7ae412e7')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

build(){
    make libdir_relative=lib64 prefix=/usr $jobs
}

package(){
    make libdir_relative=lib64 prefix=/usr install $jobs
}

