#!/usr/bin/env bash
name='qt5-declarative'
release='2'
version='5.15.14'
url='https://www.qt.io/developers/'
description='Qt5 - QtDeclarative component'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtdeclarative-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=(python vulkan-headers)
sha256sums=('25d9ae3e27efb814f3ca933b6f5acdc754fdefbc714a297040932f133ad1e652')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtdeclarative-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}


