#!/usr/bin/env bash
name='kwayland-integration'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='KWayland integration'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kwayland-integration-${version}.tar.xz")
depends=(kwindowsystem kwayland)
makedepends=(extra-cmake-modules wayland-protocols kidletime)
sha256sums=('6ae7ba5ec5f065f36603c0612341ddbd0d9445b72fc6fba6b62cbedcd4fa9ff0')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}