#!/usr/bin/env bash
name='kwayland-integration'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description='KWayland integration'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kwayland-integration-${version}.tar.xz")
depends=(kwindowsystem kwayland)
makedepends=(extra-cmake-modules wayland-protocols kidletime)
sha256sums=('04e2cbc45ea3c4b6f18aba16610fd2c7fa20b263ca606290b1b27546650101e9')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}