#!/usr/bin/env bash
name='libXxf86vm'
release='1'
version='1.1.5'
url='https://example.org'
description='Package libXxf86vm'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXxf86vm-$version.tar.xz")
depends=()
makedepends=()
md5sums=('5b913dac587f2de17a02e17f9a44a75f')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

