#!/usr/bin/env bash
name='qt6-serialport'
release='4'
version='6.9.1'
url='https://www.qt.io/'
description='Provides access to hardware and virtual serial ports'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtserialport-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(cmake ninja)
sha256sums=('808fed52380c74ae89268306ce4d04b00f8f6b81f8c442489c390006d93eff10')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtserialport-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
