#!/usr/bin/env bash
name='xeyes'
release='1'
version='1.2.0'
url='X.Org xeyes application '
description='X.Org xeyes application'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://gitlab.freedesktop.org/xorg/app/xeyes/-/archive/xeyes-1.2.0/xeyes-xeyes-1.2.0.tar.gz')
depends=(libICE libSM libXau libXau libXext libXi libXmu libXrender libXt libxcb)
makedepends=()
md5sums=('fa718fa72c9fcb07da1934debf880cdf')
group=(x11.apps)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

