#!/usr/bin/env bash
name='json-c'
release='3'
version='0.18'
_date="20240915"
url='https://github.com/json-c/json-c'
description='A JSON implementation in C'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/json-c/json-c/archive/refs/tags/json-c-$version-${_date}.tar.gz")
depends=()
makedepends=()
sha256sums=('3112c1f25d39eca661fe3fc663431e130cc6e2f900c081738317fba49d29e298')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$name-$version-${_date}

setup(){
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    make -C build
}

package(){
    make install -C build
}

