#!/usr/bin/env bash
name='py3-setuptools-scm'
release='2'
version='8.3.1'
url='https://github.com/pypa/setuptools_scm'
description='Handles managing your python package versions in scm metadata'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('MIT')
source=("https://github.com/pypa/setuptools_scm/archive/refs/tags/v${version}.tar.gz")
depends=(python py3-packaging py3-setuptools)
makedepends=(py3-build py3-installer py3-wheel)
sha256sums=('b37ede42f184324a408a256cce7f2e3b94c87e158d839e9737126e0d720244c9')
uses=()
group=(dev.python)
arch=('x86_64')


cd setuptools-scm-$version

build(){
    python3 -m build --wheel
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
    mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}

