#!/usr/bin/env bash
name='libjxl'
release='4'
version='0.11.1'
url='https://github.com/libjxl/libjxl'
description='JPEG XL image format reference implementation'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/libjxl/libjxl/archive/refs/tags/v$version.tar.gz")
depends=(brotli libjpeg-turbo highway libpng lcms2)
makedepends=()
sha256sums=('1492dfef8dd6c3036446ac3b340005d92ab92f7d48ee3271b5dac1d36945d3d9')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version


setup(){
    mkdir build
    cd build
    cmake .. \
        -DCMAKE_INSTALL_PREFIX:PATH='/usr' \
        -DBUILD_TESTING=OFF \
        -DJPEGXL_ENABLE_MANPAGES=OFF \
        -DJPEGXL_ENABLE_DOXYGEN=OFF \
        -DJPEGXL_ENABLE_BENCHMARK=OFF \
		    -DJPEGXL_ENABLE_COVERAGE=OFF \
		    -DJPEGXL_ENABLE_EXAMPLES=OFF \
		    -DJPEGXL_ENABLE_FUZZERS=OFF \
		    -DJPEGXL_ENABLE_SJPEG=OFF \
		    -DJPEGXL_ENABLE_SKCMS=OFF \
		    -DJPEGXL_ENABLE_VIEWERS=OFF \
        -DJPEGXL_FORCE_SYSTEM_GTEST=ON \
		    -DJPEGXL_FORCE_SYSTEM_BROTLI=ON \
		    -DJPEGXL_FORCE_SYSTEM_HWY=ON
}
build(){
    make -C build $jobs
}

package(){
    make -C build install $jobs
}

