#!/usr/bin/env bash
name='libjxl'
release='2'
version='0.9.2'
url='https://github.com/libjxl/libjxl'
description='JPEG XL image format reference implementation'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/libjxl/libjxl/archive/refs/tags/v$version.tar.gz")
depends=(brotli libjpeg-turbo highway libpng lcms2)
makedepends=()
md5sums=('11ecf6dbf3a9afdf907becb016bf8e0c')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
	./deps.sh
}

setup(){
    mkdir build
    cd build
    cmake .. \
        -DCMAKE_INSTALL_PREFIX:PATH='/usr' \
        -DBUILD_TESTING=OFF \
        -DJPEGXL_ENABLE_MANPAGES=OFF \
        -DJPEGXL_ENABLE_DOXYGEN=OFF \
        -DJPEGXL_ENABLE_BENCHMARK=OFF \
		    -DJPEGXL_ENABLE_COVERAGE=OFF \
		    -DJPEGXL_ENABLE_EXAMPLES=OFF \
		    -DJPEGXL_ENABLE_FUZZERS=OFF \
		    -DJPEGXL_ENABLE_SJPEG=OFF \
		    -DJPEGXL_ENABLE_SKCMS=OFF \
		    -DJPEGXL_ENABLE_VIEWERS=OFF
}

build(){
    make -C build $jobs
}

package(){
    make -C build install $jobs
}

