#!/usr/bin/env bash
name='libxml2'
release='1'
version='2.10.3'
url='https://gitlab.gnome.org/GNOME/libxml2'
description='XML parser and toolkit'
email=' aliriza.keskin@pardus.org.tr'
maintainer=' aliriza'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/libxml2/-/archive/v2.10.3/libxml2-v${version}.tar.gz")
depends=(zlib xz-utils)
makedepends=()
md5sums=('4a8bc66943dd13f7ff2ee8816b808969')
uses=()
uses_extra=(python)
python_depends=(python)
arch=('x86_64')
group=(dev.libs)

cd $name-v$version

setup(){
    set -ex
    ./autogen.sh
    ./configure --prefix=/usr \
    --with-history \
    --libdir=/usr/lib64 \
    $(use_opt python --with-python --without-python)
}

build(){
    make $jobs
}

package(){
    make install $jobs
    if [ -d ${DESTDIR}/usr/lib ] ; then
        mv ${DESTDIR}/usr/lib/* ${DESTDIR}/usr/lib64/
        rmdir ${DESTDIR}/usr/lib/
    fi
}

