#!/usr/bin/env bash
name='libxml2'
release='2'
version='2.11.4'
url='https://gitlab.gnome.org/GNOME/libxml2'
description='XML parser and toolkit'
email=' aliriza.keskin@pardus.org.tr'
maintainer=' aliriza'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/libxml2/-/archive/v${version}/libxml2-v${version}.tar.gz")
depends=(zlib xz-utils)
makedepends=()
md5sums=('8510dc032833bb3aebb304dcf530b4bc')
uses=(python)
uses_extra=()
python_depends=(python)
arch=('x86_64')
group=(dev.libs)

cd $name-v$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
    --sysconfdir=/etc \
    --with-history \
    --libdir=/usr/lib64 \
    $(use_opt python --with-python --without-python)
}

build(){
    make $jobs
}

package(){
    make install $jobs
    if [ -d ${DESTDIR}/usr/lib ] ; then
        mv ${DESTDIR}/usr/lib/* ${DESTDIR}/usr/lib64/
        rmdir ${DESTDIR}/usr/lib/
    fi
    mkdir -p ${DESTDIR}/usr/lib64/python3/
    mv ${DESTDIR}/usr/lib64/python*/site-packages/* ${DESTDIR}/usr/lib64/python3/
}

