#!/usr/bin/env bash
name='abseil-cpp'
release='2'
version='20230802.1'
url='https://abseil.io/'
description='Abseil Common Libraries (C++), LTS Branch '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/abseil/abseil-cpp/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
md5sums=('84665b6daa5dda7c9082b1a00057457a')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    cmake .
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

