#!/usr/bin/env bash
name='bluedevil'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='Integrate the Bluetooth technology within KDE workspace and applications'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/bluedevil-${version}.tar.xz")
depends=(bluez-qt kdeclarative)
makedepends=(extra-cmake-modules plasma-framework kdoctools kcmutils)
md5sums=('4fca7af9df4e4a39e9b3b7e18e6e8836')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


