#!/usr/bin/env bash
name='polkit-kde-agent'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop/'
description='Daemon providing a polkit authentication UI for KDE'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/polkit-kde-agent-1-$version.tar.xz")
depends=(polkit kiconthemes kdbusaddons kcrash)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('2ccfc41a83cfef8c9b3311fe1f93ab52d062f63b0f6e5a63b08240ed1153aa4e')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-1-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}
build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

