#!/usr/bin/env bash
name='polkit-kde-agent'
release='4'
version='6.4.5'
url='https://kde.org/plasma-desktop/'
description='Daemon providing a polkit authentication UI for KDE'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/polkit-kde-agent-1-$version.tar.xz")
depends=(polkit kiconthemes kdbusaddons kcrash)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('5b5d771660f5209295a65afdcb3e117c1cc9cd7c1893d0c9b68ad0c531308301')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-1-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}
build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

