#!/usr/bin/env bash
name='bluez-qt'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Qt wrapper for Bluez 5 DBus API'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/bluez-qt-${version}.tar.xz")
depends=(qt6-base bluez)
makedepends=(extra-cmake-modules doxygen qt6-tools qt6-declarative)
sha256sums=('f0234766fc1af9410708d0886eef304175b09a5b99c48c0eb877a80fec6aa65e')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
