#!/usr/bin/env bash
name='pciutils'
release='2'
version='3.14.0'
url='https://git.kernel.org/pub/scm/utils/pciutils/pciutils.git'
description='PCI bus configuration space access library and tools'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://git.kernel.org/pub/scm/utils/pciutils/pciutils.git/snapshot/pciutils-$version.tar.gz")
depends=(hwdata kmod)
makedepends=(git)
sha256sums=('9f99bb89876510435fbfc47bbc8653bc57e736a21915ec0404e0610460756cb8')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

build(){
    make OPT="$CFLAGS -fPIC -flto=auto" ZLIB=no \
		SHARED=yes \
		PREFIX=/usr \
		SHAREDIR=/usr/share/hwdata \
		all
}

package(){
	make SHARED=yes PREFIX=/usr SBINDIR=/usr/bin SHAREDIR=/usr/share/hwdata MANDIR=/usr/share/man DESTDIR="${DESTDIR}" install install-lib

	# this is now supplied by the hwids package
	rm -rf "$DESTDIR"/usr/share/hwdata
}
