#!/usr/bin/env bash
name='py3-cffi'
release='4'
version='1.17.1'
url='https://pypi.org/project/cffi/'
description='Foreign Function Interface for Python calling C code.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/python-cffi/cffi/archive/refs/tags/v${version}.tar.gz")
#source=("https://files.pythonhosted.org/packages/2b/a8/050ab4f0c3d4c1b8aaa805f70e26e84d0e27004907c5b8ecc1d31815f92a/cffi-1.15.1.tar.gz")
depends=(python py3-cparser libffi)
makedepends=(py3-build py3-installer py3-wheel py3-setuptools)
sha256sums=('5aff2444731a1fc55c67080ded66d27cc4a0151e0bd37a7d02ca2a0c0edd895d')
group=(dev.python)
uses=()
arch=('x86_64')

cd cffi-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --optimize=1 --skip-build
}

