#!/usr/bin/env bash
name='kidletime'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Monitoring user activity'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kidletime-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools qt6-wayland libxss plasma-wayland-protocols wayland-protocols)
sha256sums=('60a6c70387b63e61147029ce57f170237271411630a3372a0e8d7240b8006aaf')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

