#!/usr/bin/env bash
name='kidletime'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Monitoring user activity'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kidletime-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools qt6-wayland libxss plasma-wayland-protocols wayland-protocols)
sha256sums=('b6dc7d6eadb642248000f165155a72d2dfab6c1a93e0130f8f83394a7628eaf6')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

