#!/usr/bin/env bash
name='kidletime'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Monitoring user activity'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kidletime-${version}.tar.xz")
depends=(qt5-x11extras libxss)
makedepends=(extra-cmake-modules doxygen qt5-tools plasma-wayland-protocols wayland-protocols)
md5sums=('8f4d1fa08be91f126b0af6ff00cb2e4c')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

