#!/usr/bin/env bash
name='lxde-common'
release='1'
version='0.99.2'
url='https://github.com/lxde/lxde-common'
description='LXDE Session default configuration files and nuoveXT2 iconset '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxde-common/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
md5sums=('35ee87e007b15e80d334cb68b1355124')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

