#!/usr/bin/env bash
name='lxde-common'
release='2'
version='0.99.3'
url='https://github.com/lxde/lxde-common'
description='LXDE Session default configuration files and nuoveXT2 iconset '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxde-common/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('e55ac4b4406f7538ed5994677c6488c6a0dd9a4b34a0969402aaa4f04b52b26f')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

export CC=clang

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

