#!/usr/bin/env bash
name='lxde-common'
release='1'
version='0.99.2'
url='https://github.com/lxde/lxde-common'
description='LXDE Session default configuration files and nuoveXT2 iconset '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxde-common/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('f62a0a02bfa0837a91916f66336228520d54040674590d4b6dd5ad2efc4e92fd')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

