#!/usr/bin/env bash
name='gst-plugins-ugly'
release='3'
version='1.24.7'
url='https://gitlab.freedesktop.org/gstreamer'
description='Ugly GStreamer plugins'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-${version}.tar.xz")
#source=("https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly/-/archive/$version/gst-plugins-ugly-$version.tar.gz")
depends=(gst-plugins-base)
makedepends=()
sha256sums=('3dc954fc53fe18883670322a1c215e3c6529036e0a69b30f64781cd40c268593')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
   #./autogen.sh 
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}
