#!/usr/bin/env bash
name='gst-plugins-ugly'
release='1'
version='1.18.6'
url='https://gitlab.freedesktop.org/gstreamer'
description='Ugly GStreamer plugins'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly/-/archive/$version/gst-plugins-ugly-$version.tar.gz")
depends=()
makedepends=()
md5sums=('7957c8b34be7abba8fc80d72da6259ef')
group=(media.video)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
   #./autogen.sh 
	 meson setup build --prefix=/usr \
    --libdir=/usr/lib64
}
build(){
   ninja -C build
}

package(){
    ninja -C build install
}
