#!/usr/bin/env bash
name='hsakmt'
release='1'
version='1.0.0'
url='https://www.x.org/archive/individual/lib/'
description='Package hsakt'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/hsakmt-$version.tar.gz")
depends=()
makedepends=()
md5sums=('9beb20104e505300daf541266c4c3c3d')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

