#!/usr/bin/env bash
name='plasma-workspace'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='Kde Plasma Workspace'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/plasma-workspace-$version.tar.xz")
depends=(accountsservice kactivitymanagerd kded  kio
         kquickcharts kwin milou pipewire phonon
         plasma-integration qt6-base xdotool qcoro-qt6
         plasma5support plasma-activities-stats)
makedepends=(qt6-tools)
sha256sums=('2d4268cbae757631be57d69d34fc02c8d0204762515370c9679ecb2aa2afdf33')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

export LANG="C.UTF-8"
export LC_ALL=$LANG

prepare(){
    # Remove bloats from cmakelist.txt
    ## Main
    sed -i "/.*KUserFeedback.*/d" CMakeLists.txt
    sed -i "s/ Wallet / /g" CMakeLists.txt
    sed -i "/.*KSysGuard.*/d" CMakeLists.txt
    sed -i "/.*libqalculate.*/d" CMakeLists.txt
    sed -i "/.*systemmonitor.*/d" CMakeLists.txt
    sed -i "/.*soliduiserver.*/d" CMakeLists.txt
    ## subdir : dataengines
    sed -i "/.*systemmonitor.*/d" dataengines/CMakeLists.txt
    sed -i "/.*devicenotifications.*/d" dataengines/CMakeLists.txt
    ## subdir: kcms
    sed -i "/.*users.*/d" kcms/CMakeLists.txt
    ## subdir : applets
    sed -i "/.*systemmonitor.*/d" applets/CMakeLists.txt
    sed -i "/.*devicenotifier.*/d" applets/CMakeLists.txt
    ## subdir : runners
    sed -i "/.*kill.*/d" runners/CMakeLists.txt

}

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DGLIBC_LOCALE_GEN=OFF \
        -DBUILD_TESTING=OFF
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
    # fix symlinks
    rm -f $DESTDIR//usr/bin/lookandfeeltool
    ln -s plasma-apply-lookandfeel $DESTDIR//usr/bin/lookandfeeltool
}

