#!/usr/bin/env bash
name='plasma-workspace'
release='3'
version='6.1.5'
url='https://kde.org/plasma-desktop'
description='Kde Plasma Workspace'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/plasma-workspace-$version.tar.xz")
depends=(accountsservice kactivitymanagerd kded  kio
         kquickcharts kwin milou pipewire phonon
         plasma-integration qt6-base xdotool qcoro-qt6)
makedepends=(qt6-tools)
sha256sums=('c29e15a3ed42446f997b7e1695864f85ebff084e2ece581c914a0d8a8e265ae7')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

export LANG="C.UTF-8"
export LC_ALL=$LANG

prepare(){
    # Remove bloats from cmakelist.txt
    ## Main
    sed -i "/.*KUserFeedback.*/d" CMakeLists.txt
    sed -i "s/ Wallet / /g" CMakeLists.txt
    sed -i "/.*KSysGuard.*/d" CMakeLists.txt
    sed -i "/.*libqalculate.*/d" CMakeLists.txt
    sed -i "/.*systemmonitor.*/d" CMakeLists.txt
    sed -i "/.*soliduiserver.*/d" CMakeLists.txt
    ## subdir : dataengines
    sed -i "/.*systemmonitor.*/d" dataengines/CMakeLists.txt
    sed -i "/.*devicenotifications.*/d" dataengines/CMakeLists.txt
    ## subdir: kcms
    sed -i "/.*users.*/d" kcms/CMakeLists.txt
    ## subdir : applets
    sed -i "/.*systemmonitor.*/d" applets/CMakeLists.txt
    sed -i "/.*devicenotifier.*/d" applets/CMakeLists.txt
    ## subdir : runners
    sed -i "/.*kill.*/d" runners/CMakeLists.txt

}

setup () {
    mkdir build
    cd build
    cmake .. -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
    # fix symlinks
    rm -f $DESTDIR//usr/bin/lookandfeeltool
    ln -s plasma-apply-lookandfeel $DESTDIR//usr/bin/lookandfeeltool
}

