#!/usr/bin/env bash
name='lxmenu-data'
release='1'
version='0.1.5'
url='https://github.com/lxde/lxmenu-data'
description='Provides files needed for LXDE application menus '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxmenu-data/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('e2417923d16ac1dfce27ec7416d88fbafff5023eeb1f47fa481062cb1d93c855')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --sysconfdir=/etc
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

