#!/usr/bin/env bash
name='lxmenu-data'
release='1'
version='0.1.5'
url='https://github.com/lxde/lxmenu-data'
description='Provides files needed for LXDE application menus '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxmenu-data/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
md5sums=('48b214030360e9ae0e3a04566eed305c')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --sysconfdir=/etc
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

