#!/usr/bin/env bash
name='lxmenu-data'
release='2'
version='0.1.6'
url='https://github.com/lxde/lxmenu-data'
description='Provides files needed for LXDE application menus '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxmenu-data/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('b237e732609fb2a521a942e08bb825ac7973ee478db7567d3606665a3793b2e8')
group=(lxde.base)
uses=()
arch=('x86_64')

export CC=clang

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --sysconfdir=/etc
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

