#!/usr/bin/env bash
name='libdmtx'
release='1'
version='0.7.7'
url='https://libdmtx.sourceforge.net/'
description='A software for reading and writing Data Matrix 2D barcodes'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPL2')
source=("https://github.com/dmtx/libdmtx/archive/v${version}/libdmtx-${version}.tar.gz")
depends=()
makedepends=()
sha256sums=('7aa62adcefdd6e24bdabeb82b3ce41a8d35f4a0c95ab0c4438206aecafd6e1a1')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

