#!/usr/bin/env bash
name='gnutls'
release='2'
version='3.8.0'
_version='3.8'
url='https://www.gnupg.org/ftp/gcrypt/gnutls'
description='The GnuTLS Transport Layer Security Library'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GplV2')
source=("https://www.gnupg.org/ftp/gcrypt/gnutls/v${_version}/gnutls-${version}.tar.xz")
depends=(nettle p11-kit)
makedepends=( )
md5sums=('20a662caf20112b6b9ad1f4a64db3a97')
arch=('x86_64')
group=(net.libs)

uses_extra=(zstd brotli libidn2)

brotli_depends=(brotli)
zstd_depends=(zstd)
libidn2_depends=(libind2)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
    --libdir=/usr/lib64 \
    --disable-guile \
    --enable-ssl3-support \
    --enable-openssl-compatibility \
    --with-included-unistring \
    --with-included-libtasn1 \
    $(use_opt zstd --with-zstd --without-zstd) \
    $(use_opt brotli --with-brotli --without-brotli) \
    $(use_opt libidn2 --with-libidn2 --without-libidn2)
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

