#!/usr/bin/env bash
name='speech-dispatcher'
release='1'
version='0.11.5'
url='https://github.com/brailcom/speechd'
description='Speech synthesis interface'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/brailcom/speechd/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
md5sums=('e9f03959ced56a6fff8e933e8fe89cc0')
group=(app.accessibility)
uses=()
arch=('x86_64')

cd speechd-$version

prepare(){
    # fake makeinfo command
    > $HOME/makeinfo
    chmod +x $HOME/makeinfo
}

setup () {
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --with-ibmtts=no \
        --with-kali=no \
        --with-baratinoo=no \
        --with-voxin=no \
        --without-flite
}

build () {
    make $jobs
}

package () {
    make install $jobs
}

