#!/usr/bin/env bash
name='libXcomposite'
release='1'
version='0.4.6'
url='https://example.org'
description='Package libXcomposite'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXcomposite-$version.tar.xz")
depends=(xorgproto libX11 libXfixes)
makedepends=()
md5sums=('af0a5f0abb5b55f8411cd738cf0e5259')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

