#!/usr/bin/env bash
name='libXcomposite'
release='1'
version='0.4.6'
url='https://gitlab.freedesktop.org/xorg/lib/libXcomposite'
description='X.Org Xcomposite library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/lib/libxcomposite/-/archive/libXcomposite-$version/libxcomposite-libXcomposite-$version.tar.gz")
depends=()
makedepends=()
md5sums=('931241d380a00b43c0ae6a0dbbd5eb30')
group=(x11.libs)
uses=()
arch=('x86_64')

cd libxcomposite-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

