#!/usr/bin/env bash
name='py3-libxdo'
release='1'
version='0.1.2a1'
url='https://pypi.org/project/python-libxdo/'
description='ibxdo is the library behind xdotool, a tool to “fake keyboard/mouse input, window management, and more”.'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://github.com/rshk/python-libxdo/archive/refs/tags/v${version}.tar.gz")
depends=(python)
makedepends=()
sha256sums=('d1767b433006df30b5ca048c675f1daf239757714acf615c80f861b650f2f90e')
group=(dev.python)
uses=()
arch=('x86_64')

cd "python-libxdo"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}


