#!/usr/bin/env bash
name='kirigami'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='A QtQuick based components set'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kirigami-${version}.tar.xz")
depends=(qt6-base qt6-svg qt6-declarative)
makedepends=(extra-cmake-modules qt6-tools doxygen qt6-shadertools)
sha256sums=('4d645a0374d33b9465e79e3e17170882e2cbda1526f45bc5b6b176dadda77d76')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

