#!/usr/bin/env bash
name='kirigami'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='A QtQuick based components set'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kirigami-${version}.tar.xz")
depends=(qt6-base qt6-svg qt6-declarative)
makedepends=(extra-cmake-modules qt6-tools doxygen qt6-shadertools)
sha256sums=('ed0f56c89249fb92a9af99a94fd13542abbae4a8f1613aaaa2bfab87914b601a')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

