#!/usr/bin/env bash
name='kirigami'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='A QtQuick based components set'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kirigami-${version}.tar.xz")
depends=(qt6-base qt6-svg qt6-declarative)
makedepends=(extra-cmake-modules qt6-tools doxygen qt6-shadertools)
sha256sums=('43a73b161e1c85da3eadc63e7cc6c1b3c686aa56951b0d0e2df4a2cc1334759c')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

