#!/usr/bin/env bash
name='kwin'
release='4'
version='6.1.5'
url='https://kde.org/plasma-desktop'
description='An easy to use, but flexible, composited Window Manager'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kwin-${version}.tar.xz")
depends=(kscreenlocker xcb-util-cursor kcmutils breeze libqaccessibilityclient pipewire lcms2 libxcvt qt6-tools  qt6-5compat
         qt6-base qt6-declarative qt6-multimedia qt6-sensors qt6-wayland xorg-xwayland libinput libdisplay-info kglobalacceld
         kwayland)
makedepends=(extra-cmake-modules kdoctools krunner libdisplay-info wayland-protocols plasma-wayland-protocols)
sha256sums=('ba0aace323195b58adbfde14ec74cdd4c28c211d78a567c44af70f336dcab3f7')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
