#!/usr/bin/env bash
name=libssh
version=0.10.4
release=1
url='https://libssh.org'
description='C library implenting the SSHv2 protocol on client and server side'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
depends=()
source=("https://www.libssh.org/files/0.10/libssh-${version}.tar.xz")
md5sums=('cb2e47ac2de59eefa31a57ae53b44363')
license=('LGPL-2.1' 'BSD')
group=(net.libs)

depends=(openssl)
uses=(server sftp zlib)
zlib_depends=(zlib)

setup() {
    cmake -S $name-$version -B build \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=/usr/lib64/libssh \
	-DWITH_EXAMPLES=NO \
	-DBUILD_SHARED_LIBS=YES \
	-DBUILD_STATIC_LIB=YES \
	-DWITH_NACL=OFF \
	-DWITH_GCRYPT=OFF \
	-DWITH_MBEDTLS=OFF \
	-DWITH_GSSAPI=OFF \
	-DWITH_PCAP=OFF \
	-DWITH_SERVER=$(use_opt server ON OFF) \
	-DWITH_SFTP=$(use_opt sftp ON OFF) \
	-DWITH_ZLIB=$(use_opt zlib ON OFF)
}
build() {
    make -C build -j$(nproc)
}
package() {
    make -C build install
    install build/src/libssh.a ${DESTDIR}/usr/lib64/libssh/
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/usr/lib64/libssh/" > ${DESTDIR}/etc/ld.so.conf.d/libssh.conf
}
