#!/usr/bin/env bash
name='kdav'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='A DAV protocol implemention with KJobs'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kdav-${version}.tar.xz")
depends=(ki18n kcoreaddons kio qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('b3c81f5e312b3eeed2c8b7db218f64b90f67e1b2d0ce37a44ff273b5232843e9')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON \
		-DDocBookXSL_DIR=/usr/share/xml/docbook/xsl-stylesheets-1.79.2-nons
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
