#!/usr/bin/env bash
name='v4l-utils'
release='2'
version='1.26.0'
url='https://linuxtv.org/'
description='Userspace tools and conversion library for Video 4 Linux'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
				
source=("https://www.linuxtv.org/downloads/v4l-utils/v4l-utils-${version}.tar.xz")
depends=(hicolor-icon-theme libjpeg-turbo sysfsutils)
makedepends=(alsa-lib)
md5sums=('0ccb2a18e1d3a3b2986591753a2b3a7f')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddefault_library=both \
        -Dqv4l2=disabled \
        -Dqvidcap=disabled
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}
