#!/usr/bin/env bash
name='fribidi'
release='1'
version='1.0.12'
url='https://github.com/fribidi/fribidi'
description='A free implementation of the unicode bidirectional algorithm'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/fribidi/fribidi/releases/download/v$version/fribidi-$version.tar.xz")
depends=()
makedepends=()
md5sums=('21185b398635a7fc0d3ff0a7578c4791')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

