#!/usr/bin/env bash
name='screen'
release='2'
version='5.0.0'
url='https://ftp.gnu.org/gnu/screen/'
description='Full-screen window manager that multiplexes a physical terminal'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/screen/screen-$version.tar.gz")
depends=(ncurses pam libxcrypt)
makedepends=()
sha256sums=('f04a39d00a0e5c7c86a55338808903082ad5df4d73df1a2fd3425976aed94971')
group=(app.misc)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./autogen.sh
    ./configure --prefix=/usr \
       --libdir=/usr/lib64/ \
       --enable-colors256 \
       --enable-pam \
       --enable-rxvt_osc \
       --enable-telnet \
       --with-sys-screenrc=/etc/screenrc
}

build () {
    make $jobs
}

package () {
    make install DESTDIR=$DESTDIR $jobs
    install -Dm644 etc/etcscreenrc "${DESTDIR}"/etc/screenrc
}

