#!/usr/bin/env bash
name='libsoxr'
release='1'
version='0.1.3'
url='https://sourceforge.net/p/soxr/wiki/Home/'
description='SoX Resampler library '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://downloads.sourceforge.net/project/soxr/soxr-$version-Source.tar.xz")
depends=()
makedepends=()
md5sums=('3f16f4dcb35b471682d4321eda6f6c08')
group=(media.libs)
uses=()
arch=('x86_64')

cd soxr-$version-Source

setup(){
cmake -S . -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_EXAMPLES=OFF \
    -DBUILD_SHARED_LIBS=ON \
    -DWITH_AVFFT=ON \
    -DWITH_LSR_BINDINGS=ON \
    -DWITH_OPENMP=ON \
    -DWITH_PFFFT=ON
}

build(){
    #make -j`nproc`
        cmake --build build
}

package(){
    #make install -j`nproc`
    cmake --install build
}

