#!/usr/bin/env bash
name='libsoxr'
release='1'
version='0.1.3'
url='https://sourceforge.net/p/soxr/wiki/Home/'
description='The SoX Resampler library that aims to give fast and high quality results for any constant resampling ratio'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL')
source=("https://downloads.sourceforge.net/project/soxr/soxr-${version}-Source.tar.xz")
depends=()
makedepends=(cmake ninja)
md5sums=('3f16f4dcb35b471682d4321eda6f6c08')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    cmake -S soxr-${version}-Source -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_EXAMPLES=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DWITH_AVFFT=ON \
        -DWITH_LSR_BINDINGS=ON \
        -DWITH_OPENMP=ON \
        -DWITH_PFFFT=ON
}

build(){
    cmake --build build
}

package(){
    cmake --install build
    rm -rf "${DESTDIR}"/usr/share/doc
    install -Dm 644 soxr-${version}-Source/LICENCE -t "${DESTDIR}"/usr/share/licenses/libsoxr/
}

