#!/usr/bin/env bash
name='qt5-webglplugin'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='QPA plugin for running an application via a browser using streamed WebGL commands'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtwebglplugin-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base qt5-declarative qt5-websockets)
makedepends=()
sha256sums=('8727541d54c5663c290eaa1f341a271398aeda3c841627c53b6c4cf7899c55b3')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtwebglplugin-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}
