#!/usr/bin/env bash
name='qt5-x11extras'
release='2'
version='5.15.14'
url='https://download.qt.io/archive/qt'
description='Provides platform-specific APIs for X11'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/5.15/$version/submodules/qtx11extras-everywhere-opensource-src-$version.tar.xz")
depends=(qt5-base)
makedepends=()
sha256sums=('ad3c47c835fd87b375069402e21a6e0d6cb98c89ece4949f5076df0472c0847f')
group=(dev.qt)
uses=()
arch=('x86_64')

cd qtx11extras-everywhere-src-$version
export PATH=$PATH:/usr/bin/qt5

setup () {
    qmake
}

build () {
    make $jobs
}

package () {
    make INSTALL_ROOT=$DESTDIR install $jobs
}

