#!/usr/bin/env bash
name='xcb-proto'
release='1'
version='1.14'
url='https://xcb.freedesktop.org/'
description='X C-language Bindings protocol headers'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://xorg.freedesktop.org/archive/individual/proto/xcb-proto-${version}.tar.xz")
depends=( )
makedepends=( )
md5sums=('4a053ca2456007a343024a0452dbf13b')
uses=()
arch=('x86_64')
group=(x11.base)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}
