#!/usr/bin/env bash
name='lxpanel'
release='1'
version='0.10.1'
url='https://wiki.lxde.org/en/LXPanel'
description='Lightweight X11 desktop panel for LXDE '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://salsa.debian.org/lxde-team/lxpanel/-/archive/debian/$version-1/lxpanel-debian-$version-1.tar.gz")
depends=(libwnck3 wireless-tools)
makedepends=()
sha256sums=('e4c6a8c9901f4226160af79c409236fe4e5d1b1ec3aefdb1c43e416698f27811')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-debian-$version-1

prepare(){
    # Disable pager plugin as it breaks panel layout with GTK+ 3
    # https://sourceforge.net/p/lxde/bugs/773/
    sed -i '/pager.c/d' plugins/Makefile.am
    sed -i '/STATIC_PAGER/d' src/private.h
    sed -i 's/libwnck-3.0//' configure.ac
    sed -i 's/background=1/background=0/' data/default/panels/panel.in
}

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --enable-gtk3 \
        --disable-silent-rules \
        --with-plugins=all,-cpufreq
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

