#!/usr/bin/env bash
name='kglobalaccel'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description='Add support for global workspace shortcuts'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kglobalaccel-${version}.tar.xz")
depends=(kdbusaddons kconfig kcrash kcoreaddons kwindowsystem qt5-declarative qt5-x11extras)
makedepends=(extra-cmake-modules doxygen qt5-tools xcb-util-keysyms)
md5sums=('d4b9194beb2d0f67a150354636a7d778')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

