#!/usr/bin/env bash
name='font-bh-100dpi'
release='1'
version='1.0.3'
url='https://gitlab.freedesktop.org/xorg/font/bh-100dpi'
description='X.Org Bigelow & Holmes bitmap fonts'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/font/bh-100dpi/-/archive/font-bh-100dpi-$version/bh-100dpi-font-bh-100dpi-$version.tar.gz")
depends=(bdftopcf font-util)
makedepends=()
md5sums=('61149e221915e1b88ae5c3f9fbde2850')
group=(media.fonts)
uses=()
arch=('x86_64')

cd bh-100dpi-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

