#!/usr/bin/env bash
name='attica'
release='4'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Qt library that implements the Open Collaboration Services API'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/attica-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('6ce80618dc52a7a2c48a425617161ec46b7126d05ecb23076e655fde1d6010e6')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
		-DBUILD_QCH=ON

}

build () {
    cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

