#!/usr/bin/env bash
name='py3-pexpect'
release='3'
version='4.9'
url='http://pexpect.readthedocs.org/en/stable'
description='Make Python a better tool for controlling and automating other programs'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('MIT')
source=("https://github.com/pexpect/pexpect/archive/refs/tags/${version}.tar.gz")
depends=(python py3-ptyprocess)
makedepends=(py3-setuptools)
sha256sums=('13756b834dba0adf7603be77d943cc427011983ecd7c58b59b9bf122a1063e40')
group=(dev.python)
uses=()
arch=('x86_64')

cd "pexpect"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

