#!/usr/bin/env bash
name='efivar'
release='2'
version='39'
url='https://github.com/rhboot/efivar'
description='Tools and libraries to work with EFI variables'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://github.com/rhboot/efivar/archive/refs/tags/39.tar.gz')
depends=()
makedepends=()
md5sums=('a8fc3e79336cd6e738ab44f9bc96a5aa')
group=(sys.libs)
uses=()
arch=('x86_64')

cd $name-$version

export ERRORS=''
export PATH=$PATH:$HOME

prepare(){
    # fake mandoc for ignore extra dependency
    echo "exit 0" > $HOME/mandoc
    chmod +x $HOME/mandoc
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

