#!/usr/bin/env bash
name='grep'
release='2'
version='3.11'
url='https://ftp.gnu.org/gnu/grep/'
description='GNU regular expression matcher'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/grep/grep-$version.tar.xz")
depends=(libpcre2)
makedepends=()
md5sums=('7c9bbd74492131245f7cdb291fa142c0')
uses=()
group=(sys.apps)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

