#!/usr/bin/env bash
name='libidn2'
release='1'
version='2.3.4'
url='https://example.org'
description='Libidn2 is a free software implementation of IDNA2008, Punycode and Unicode TR46'
email=' parduscix@yandex.ru'
maintainer=' sulincix'
license=('GPLv3')
source=('https://ftp.gnu.org/gnu/libidn/libidn2-2.3.4.tar.gz')
depends=(libunistring)
makedepends=( )
md5sums=('a12109804fc9c5d7fb31f068c66655b8')
arch=('x86_64')
group=(net.dns)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/libidn2
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/usr/lib64/libidn2/" > ${DESTDIR}/etc/ld.so.conf.d/libidn2.conf
    mv ${DESTDIR}/usr/lib64/{$name/pkgconfig,}
}

