#!/bin/bash
name=build-base
release=1
version=1
url='https://gitlab.com/turkman/'
description='Build tools meta'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=()
md5sums=()
arch=(x86_64)
group=(sys.meta)
depends=(gcc make bison flex binutils file tar clang llvm git
         python autoconf automake findutils fakeroot gettext m4
         patch coreutils meson cmake linux-headers gtk-doc
         pkgconf bc diffutils libtool mklinux)
