#!/usr/bin/env bash
name='setxkbmap'
release='1'
version='1.3.3'
url='https://gitlab.freedesktop.org/xorg/app/setxkbmap'
description='Controls the keyboard layout of a running X server'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/app/setxkbmap/-/archive/setxkbmap-$version/setxkbmap-setxkbmap-$version.tar.gz")
depends=(libX11 libXau libXdmcp libXext libXrandr libXrender libxcb libxkbfile)
makedepends=()
md5sums=('03f8f4729d71a2bad78da4b7abcebfcf')
group=(x11.apps)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

