#!/usr/bin/env bash
name='gptfdisk'
release='1'
version='1.0.9'
url='https://salsa.debian.org/debian/gdisk'
description='GPT partition table manipulator for Linux'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://salsa.debian.org/debian/gdisk/-/archive/debian/$version-2.1/gdisk-debian-$version-2.1.tar.gz"
        "gptfdisk-1.0.9-convenience-1.patch")
depends=(popt)
makedepends=()
md5sums=('c01c07ce8570ec39129fa1682174f711'
         'SKIP')
group=(sys.apps)
uses=()
arch=('x86_64')

cd gdisk-debian-$version-2.1

# tinfo is not symlink of ncurses for turkman
export LDFLAGS="$LDFLAGS -ltinfo"

prepare(){
    patch -Np1 -i ../gptfdisk-1.0.9-convenience-1.patch
    sed -i 's|ncursesw/||' gptcurses.cc &&
    sed -i 's|sbin|usr/sbin|' Makefile &&
    sed -i '/UUID_H/s/^.*$/#if defined (_UUID_UUID_H) || defined (_UL_LIBUUID_UUID_H)/' guid.cc &&
    sed -i "/device =/s/= \(.*\);/= strdup(\1);/" gptcl.cc
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

