#!/usr/bin/env bash
name='libxmlb'
release='2'
version='0.3.14'
url='https://github.com/hughsie/libxmlb'
description='Library to help create and query binary XML blobs'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
_ver="e64c60d993cd463edf0441a221fae263f9a6663e"
source=("https://github.com/hughsie/libxmlb/archive/${_ver}.zip")
depends=()
makedepends=()
md5sums=('1ae671b08f5b4b0e163179fbb040389f')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-${_ver}

prepare(){
    sed -i "s|dependency('libzstd'|&,required: false|g" meson.build
}

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
		    -Dgtkdoc=false \
		    -Dtests=true \
		    -Dstemmer=false \
		    -Dintrospection=true \
        -Dzstd=false
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

