#!/usr/bin/env bash
name='libxkbcommon'
release='2'
version='1.6.0'
url='https://github.com/xkbcommon/libxkbcommon'
description='keymap handling library for toolkits and window systems'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/xkbcommon/libxkbcommon/archive/refs/tags/xkbcommon-$version.tar.gz")
depends=(libxml2 libxcb xkeyboard-config)
makedepends=()
md5sums=('34ee8ede1374fc2eb6bd03d27c1b2e5d')
group=(x11.libs)
uses=(wayland)
wayland_depends=(wayland-protocols wayland)
arch=('x86_64')

cd libxkbcommon-xkbcommon-$version

setup(){
    meson setup build \
        --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Denable-docs=false \
        -Denable-wayland=$(use_opt wayland true false)
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

