#!/usr/bin/env bash
name=libarchive
version=3.6.1
release=1
url='https://www.libarchive.org'
description='Multi-format archive and compression library'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
source=("https://www.libarchive.org/downloads/libarchive-${version}.tar.xz"
        'fix-mount-h-conflict.patch')
md5sums=('9465f7995649c9ea84854a7fd8c76f30'
         'SKIP')
license=('BSD')
group=(app.arch)

uses=(bzip2 lzma iconv acl lz4 lzo)
uses_extra=(blake2 libxml2 nettle zstd expat )
depends=(openssl zlib)
bzip2_depends=(bzip2)
lzma_depends=(xz-utils)
acl_depends=(acl)
blake2_depends=(libb2)
libxml2_depends=(libxml2)
lz4_depends=(lz4)
lzo_depends=(lzo)
nettle_depends=(nettle)
zstd_depends=(zstd)
arch=(x86_64)

cd $name-$version

unset CFLAGS
unset CXXFLAGS

prepare(){
    patch -Np1 -i ../fix-mount-h-conflict.patch
}

setup() {
    ./configure --prefix=/usr \
	--libdir=/usr/lib64 \
	--enable-static \
	--enable-shared \
	--enable-xattr \
	$(use_opt iconv --with-iconv --without-iconv) \
	$(use_opt bzip2 --with-bz2lib --without-bz2lib) \
	$(use_opt lzma --with-lzma --without-lzma) \
	$(use_opt acl --enable-acl --disable-acl) \
	$(use_opt nettle --with-nettle --without-nettle) \
	$(use_opt libxml2 --with-xml2 --without-xml2) \
	$(use_opt expat --with-expat --without-expat) \
	$(use_opt zstd --with-zstd --without-zstd) \
	$(use_opt lz4 --with-lz4 --without-lz4) \
	$(use_opt blake2 --with-libb2 --without-libb2) \
	--without-cng
}
build() {
    make $jobs
}
package() {
    make $jobs install
}
