#!/usr/bin/env bash
name='libhandy'
release='2'
version='1.8.3'
url='https://gitlab.gnome.org/GNOME/libhandy'
description='Building blocks for modern adaptive GNOME apps'
email='me@osmancoskun.com'
maintainer='mergin'
license=('LGPLv2.1')
source=("https://gitlab.gnome.org/GNOME/libhandy/-/archive/$version/libhandy-$version.tar.gz")
depends=(gtk3)
makedepends=()
sha256sums=('7e7670f5d0a6d0adc24b888da44dab938a6f52472b8944d6dd4e31b6d3569a5f')
group=(gui.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
		meson setup build --prefix=/usr \
				--libdir=/usr/lib64/
}

build(){
		ninja -C build $jobs
}

package(){
		ninja -C build install $jobs
}

