#!/usr/bin/env bash
name='flex'
release='1'
version='2.6.4'
url='https://github.com/westes/flex'
description='A tool for generating text-scanning programs'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/westes/flex/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
md5sums=('96828d1e36d18545b71a027caa6478dd')
uses=()
group=(sys.devel)
arch=('x86_64')

cd $name-$version

export PATH=$PATH:$HOME

prepare(){
    # create fake makeinfo
    echo "#!/bin/sh" > $HOME/makeinfo
    echo "printf 'makeinfo (GNU texinfo) 5.2\n'" >> $HOME/makeinfo
    chmod +x $HOME/makeinfo
}

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
    # remove document build
    rm -rf doc && mkdir doc
    echo "all install:" > doc/Makefile
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

