#!/usr/bin/env bash
name='flex'
release='1'
version='2.6.4'
url='https://github.com/westes/flex'
description='A tool for generating text-scanning programs'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/westes/flex/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
md5sums=('96828d1e36d18545b71a027caa6478dd')
uses=()
group=(sys.devel)
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

