#!/usr/bin/env bash
name='py3-typogrify'
release='2'
version='2.0.7'
url='https://github.com/mintchaos/typogrify'
description='A set of Django template filters to make caring about typography on the web a bit easier.'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/mintchaos/typogrify/archive/refs/tags/$version.tar.gz")
depends=(python)
makedepends=()
sha256sums=('d5081966c1c1423157e240d5cfe7435b56ca30be57ff8c7fe6f90f6cc42295ee')
group=(dev.python)
uses=()
arch=('x86_64')

cd typogrify-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

