#!/usr/bin/env bash
name='pixman'
release='1'
version='0.42.2'
url='https://gitlab.freedesktop.org/pixman/pixman.git/'
description='Low-level pixel manipulation routines'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/pixman-$version.tar.gz")
depends=()
makedepends=()
md5sums=('a0f6ab8a1d8e0e2cd80e935525e2a864')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

