#!/usr/bin/env bash
name='pixman'
release='2'
version='0.43.2'
url='https://gitlab.freedesktop.org/pixman/pixman.git/'
description='Low-level pixel manipulation routines'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/pixman-$version.tar.gz")
depends=()
makedepends=()
md5sums=('b5ad6407cd8c7abf8c1669273a2fb162')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddefault_library=both
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

