#!/usr/bin/env bash
name='py3-xapp'
release='2'
version='2.4.2'
url='https://github.com/linuxmint/python3-xapp'
description='Python Xapp Library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://github.com/linuxmint/python3-xapp/archive/refs/tags/${version}.tar.gz")
depends=(python py3-psutil)
makedepends=(meson)
sha256sums=('39e4c3f06732e9d197b9aed31444653da2976c1d66dded870b52cc9782f2237d')
group=(dev.python)
uses=()
arch=('x86_64')

#cd "python3-xapp"-$version

setup(){
    meson build "python3-xapp"-$version \
        --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    meson compile -C build
}

package(){
    meson install -C build --destdir=${DESTDIR}
    python -m compileall -d / "$DESTDIR"/usr/lib
    python -O -m compileall -d / "$DESTDIR"/usr/lib
}

