#!/usr/bin/env bash
name='neofetch'
release='1'
version='7.1.0'
url='https://github.com/dylanaraps/neofetch'
description='neofetch'
email='03teknoloji@gmail.com'
maintainer='mobilturka'
license=('GPLv3')
source=("https://github.com/dylanaraps/neofetch/archive/refs/tags/$version.tar.gz")
depends=()
makedepends=()
sha256sums=('58a95e6b714e41efc804eca389a223309169b2def35e57fa934482a6b47c27e7')
group=(app.misc)
uses=()
arch=('x86_64')


package() {
    cd "$name-$version"

    install -Dm 00755 $name "$DESTDIR/usr/bin/$name"
    install -Dm 00644 $name.1 "$DESTDIR/usr/share/man/man1/$name.1"
}
