#!/usr/bin/env bash
name='libasyncns'
release='1'
version='0.8'
url='http://0pointer.de/lennart/projects/libasyncns/'
description='C library for executing name service queries asynchronously '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("http://0pointer.de/lennart/projects/libasyncns/libasyncns-$version.tar.gz")
depends=()
makedepends=()
md5sums=('1f553d6ce1ad255bc83b3d8e9384f515')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	autoreconf -fvi
  ./configure --prefix=/usr \
      --libdir=/usr/lib64/

}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

