#!/usr/bin/env bash
name='kwrited'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='KDE daemon listening for wall and write messages'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kwrited-${version}.tar.xz")
depends=(kcoreaddons kpty knotifications kdbusaddons qt6-base)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('434b83b115a480f542c97d519c27f2eb5dd4d333cfbdda28ed994813892a00d1')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

