#!/usr/bin/env bash
name='kwrited'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='KDE daemon listening for wall and write messages'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kwrited-${version}.tar.xz")
depends=(kpty knotifications kdbusaddons oxygen-sounds)
makedepends=(extra-cmake-modules kdoctools)
md5sums=('17446a45250972265dd4a09609e96cc9')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

