#!/usr/bin/env bash
name='kwrited'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description='KDE daemon listening for wall and write messages'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kwrited-${version}.tar.xz")
depends=(kcoreaddons kpty knotifications kdbusaddons qt6-base)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('f641c003df091c4f3796c4c6f3151d5627a8a385310084e2e7f4fcacf4f74a62')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

