#!/usr/bin/env bash
name='libavif'
release='1'
version='1.0.1'
url='https://aomediacodec.github.io/av1-avif/'
description='Library for encoding and decoding .avif files'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://github.com/AOMediaCodec/libavif/archive/v${version}/libavif-v${version}.tar.gz")
depends=(aom dav1d libjpeg-turbo)
makedepends=(cmake gdk-pixbuf)
md5sums=('d7b2a7da1fb652b40936b09ffb006b24')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DAVIF_BUILD_APPS=ON \
		-DAVIF_BUILD_GDK_PIXBUF=ON \
		-DAVIF_BUILD_TESTS=ON \
		-DAVIF_CODEC_AOM=ON \
		-DAVIF_CODEC_DAV1D=ON

}

build () {
    	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

