#!/usr/bin/env bash
name='libavif'
release='2'
version='1.2.1'
url='https://aomediacodec.github.io/av1-avif/'
description='Library for encoding and decoding .avif files'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://github.com/AOMediaCodec/libavif/archive/v${version}/libavif-v${version}.tar.gz")
depends=(libaom dav1d libjpeg-turbo)
makedepends=(cmake gdk-pixbuf)
sha256sums=('9c859c7c12ccb0f407511bfe303e6a7247f5f6738f54852662c6df8048daddf4')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DAVIF_BUILD_APPS=ON \
    -DAVIF_LIBYUV=OFF \
		-DAVIF_BUILD_GDK_PIXBUF=ON \
		-DAVIF_BUILD_TESTS=OFF \
		-DAVIF_CODEC_AOM=ON \
		-DAVIF_CODEC_DAV1D=ON

}

build () {
    	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}

