#!/usr/bin/env bash
name='baloo'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='A framework for searching and managing metadata'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/baloo-${version}.tar.xz")
depends=(kconfig kcoreaddons kcrash kdbusaddons kfilemetadata ki18n kidletime kio lmdb qt6-base solid)
makedepends=(extra-cmake-modules kdoctools doxygen qt6-tools)
sha256sums=('ea21e88d1fe252d2dc95e0b7ae8891594822ccdd898e7aa56d46ed9ecd626a41')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
    # remove autostart file (it is bloat)
    rm -f $DESTDIR/etc/xdg/autostart/baloo_file.desktop
    # remove systemd stuff
    rm -r "$DESTDIR"/usr/lib/systemd
}
