#!/usr/bin/env bash
name='font-bh-type1'
release='1'
version='1.0.3'
url='https://gitlab.freedesktop.org/xorg/font/bh-type1'
description='X.Org Bigelow & Holmes Type 1 fonts'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/font/bh-type1/-/archive/font-bh-type1-$version/bh-type1-font-bh-type1-$version.tar.gz")
depends=(font-util)
makedepends=()
md5sums=('ad5a14b484099fd5bc186c32d8accd30')
group=(media.fonts)
uses=()
arch=('x86_64')

cd bh-type1-$name-$version

setup(){
    	autoreconf -fvi
	./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

