#!/usr/bin/env bash
name='asciidoc'
release='1'
version='10.2.0'
url='https://github.com/asciidoc-py/asciidoc-py/'
description='A plain text human readable/writable document format '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/asciidoc-py/asciidoc-py/archive/refs/tags/$version.tar.gz")
depends=(python)
makedepends=()
md5sums=('dce6bfe35fd2fe4fc71e1ca8c8ead683')
group=(dev.python)
uses=()
arch=('x86_64')

cd $name-py-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
