#!/usr/bin/env bash
name='libayatana-indicator'
release='2'
version='0.9.4'
url='https://github.com/AyatanaIndicators/libayatana-indicator'
description='Ayatana Application Indicators'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/AyatanaIndicators/libayatana-indicator/archive/refs/tags/$version.tar.gz")
depends=(libayatana-ido)
makedepends=()
sha256sums=('a18d3c682e29afd77db24366f8475b26bda22b0e16ff569a2ec71cd6eb4eac95')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    cmake -G Ninja -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib64
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

