#!/usr/bin/env bash
name='libogg'
release='1'
version='1.3.5'
url='https://xiph.org/downloads/'
description='Ogg bitstream and framing library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=('https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.xz')
depends=()
makedepends=()
md5sums=('3178c98341559657a15b185bf5d700a5')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

