#!/usr/bin/env bash
name='libogg'
release='1'
version='1.3.5'
url='https://xiph.org/ogg/'
description='The Ogg media file format library '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://downloads.xiph.org/releases/ogg/libogg-$version.tar.gz")
depends=()
makedepends=()
md5sums=('3267127fe8d7ba77d3e00cb9d7ad578d')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
  autoreconf -fiv
   ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

