#!/usr/bin/env bash
name='libcap-ng'
release='2'
version='0.8.5'
url='https://github.com/stevegrubb/libcap-ng/releases'
description='A library for Linux that makes using posix capabilities easy'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('LGPL2.1')
source=("https://github.com/stevegrubb/libcap-ng/archive/refs/tags/v${version}.zip")
depends=()
makedepends=(python)
sha256sums=('3490fe6bf50614f27a9120cd664dbcebc5483d138124df86c1aee922c8e34abc')
group=(sys.libs)
uses=(python)
uses_extra=()
arch=('x86_64')

cd $name-$version

setup(){
    bash autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        $(use_opt python --with-python --without-python) \
        $(use_opt python --with-python3 --without-python3)
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

