#!/usr/bin/env bash
name='qt6-connectivity'
release='4'
version='6.9.1'
url='https://www.qt.io/'
description='Provides access to Bluetooth hardware'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtconnectivity-everywhere-src-${version}.tar.xz")
depends=(qt6-base bluez pcsc-lite)
makedepends=(cmake ninja)
sha256sums=('4988e50112104d5ad85e5b3cef66036ca445f18c22cf375d3dac9dcca95e0a17')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtconnectivity-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
