#!/usr/bin/env bash
name='qt6-remoteobjects'
release='2'
version='6.7.0'
url='https://www.qt.io/'
description='Inter-process communication (IPC) module developed for Qt'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtremoteobjects-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(cmake ninja)
sha256sums=('a0ba60d625c9713fc8396b8db1e283df863bfaa06664d46496bd16fab5e4c695')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtremoteobjects-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
