#!/usr/bin/env bash
name='xfce4-panel'
release='1'
version='4.18.3'
_version='4.18'
url='https://docs.xfce.org/xfce/xfce4-panel/start'
description='Panel for the Xfce desktop environment'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfce4-panel/${_version}/xfce4-panel-${version}.tar.bz2")
depends=(exo garcon  libxfce4ui xfconf libwnck3 cairo libdbusmenu)
makedepends=(gobject-introspection intltool vala)
md5sums=('9673827a083036f54f013a4b249efec6')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug 
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

