#!/usr/bin/env bash
name='xfce4-panel'
release='2'
version='4.18.6'
_version='4.18'
url='https://docs.xfce.org/xfce/xfce4-panel/start'
description='Panel for the Xfce desktop environment'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfce4-panel/${_version}/xfce4-panel-${version}.tar.bz2")
depends=(exo garcon  libxfce4ui xfconf libwnck3 cairo libdbusmenu)
makedepends=(gobject-introspection intltool vala)
sha256sums=('21337161f58bb9b6e42760cb6883bc79beea27882aa6272b61f0e09d750d7c62')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug 
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

