#!/usr/bin/env bash
name='xfce4-panel'
release='3'
version='4.20.0'
_version='4.20'
url='https://docs.xfce.org/xfce/xfce4-panel/start'
description='Panel for the Xfce desktop environment'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfce4-panel/${_version}/xfce4-panel-${version}.tar.bz2")
depends=(exo garcon  libxfce4ui xfconf libwnck3 cairo libdbusmenu)
makedepends=(gobject-introspection intltool vala)
sha256sums=('ff33cd5f5d16c2193fe305f4878d82cd8d2feea92f2594bcd27b2b5c392d43b8')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

