#!/usr/bin/env bash
name='layer-shell-qt'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='Qt component to allow applications to make use of the Wayland wl-layer-shell protocol'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/layer-shell-qt-${version}.tar.xz")
depends=(qt6-base qt6-wayland wayland)
makedepends=(extra-cmake-modules wayland-protocols)
sha256sums=('5390d178e7f6516d691edaa85fce9cbccfe060cea573abc650bb4066878eb2fe')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DENABLE_TESTING=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
