#!/usr/bin/env bash
name='layer-shell-qt'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='Qt component to allow applications to make use of the Wayland wl-layer-shell protocol'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/layer-shell-qt-${version}.tar.xz")
depends=(qt6-base qt6-wayland wayland)
makedepends=(extra-cmake-modules wayland-protocols)
sha256sums=('ef6baae22114f038af89029f3f0075ee29c3b91fd49100828c4c3a32e1496e95')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DENABLE_TESTING=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
