#!/usr/bin/env bash
name='ndctl'
release='2'
version='78'
url='https://github.com/pmem/ndctl'
description='Helper tools and libraries for managing non-volatile memory on Linux'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/pmem/ndctl/archive/refs/tags/v$version.tar.gz")
depends=(json-c kmod libtraceevent libtracefs keyutils iniparser)
makedepends=()
md5sums=('e9508933924acacb006e1f4003c47bbc')
group=(sys.block)
uses=()
arch=('x86_64')

cd $name-$version
setup(){
	meson setup build --prefix=/usr \
            --libdir=/usr/lib64/ \
            -Ddocs=disabled \
            -Dsystemd=disabled \
            -Dtest=disabled
}

build(){
    ninja -C build
}

package(){
   ninja -C build install
}

