#!/usr/bin/env bash
name='ymp'
release='3'
version='1.2'
url='https://gitlab.com/turkman/devel/sources/ymp'
description='Yerli ve Milli Package manager'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/ymp/-/archive/${version}/ymp-${version}.tar.gz")
depends=(glib readline ncurses)
makedepends=(vala)
sha256sums=('664624366937e47ce5bd78b7a638580f9a980cbf97ec0e4bb9b1c6505b37e729')
uses=(curl libarchive)
curl_depends=(curl)
libarchive_depends=(libarchive)
group=(sys.apps)
arch=('x86_64')

cd $name-$version

unset CFLAGS
unset CXXFLAGS

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64 \
        $(use_opt curl  -Dlibcurl=true -Dlibcurl=false) \
        $(use_opt libarchive -Dlibarchive=true -Dlibarchive=false) \
        -Ddebug=true -Dscripts=true -Dlibbrotli=false
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

