#!/usr/bin/env bash
name='ymp'
release='1'
version='1.0'
url='https://gitlab.com/sulix/devel/sources/ymp'
description='Yerli ve Milli Package manager'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=('https://gitlab.com/sulix/devel/sources/ymp/-/archive/1.0/ymp-1.0.tar.gz')
depends=(glib)
makedepends=()
md5sums=('241db615b0887b7255bb656170c657ed')
uses=(curl libarchive)
curl_depends=(curl)
libarchive_depends=(libarchive)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/lib64 \
        --bindir=/bin \
        -Dshared=true \
        -Dstatic=false \
        $(use_opt curl  -Dlibcurl=true -Dlibcurl=false) \
        $(use_opt libarchive -Dlibarchive=true -Dlibarchive=false) \
        -Dlibbrotli=false \
        -Dscripts=true
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

