#!/usr/bin/env bash
name='ymp'
release='1'
version='1.0'
url='https://gitlab.com/turkman/devel/sources/ymp'
description='Yerli ve Milli Package manager'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.com/turkman/devel/sources/ymp/-/archive/${version}/ymp-${version}.tar.gz")
depends=(glib readline ncurses)
makedepends=(vala)
md5sums=('4d3a74ec5107b75bae167badf9654de5')
uses=(curl libarchive)
curl_depends=(curl)
libarchive_depends=(libarchive)
group=(sys.apps)
arch=('x86_64')

cd $name-$version
setup(){
    meson setup build --prefix=/usr \
        --libdir=/lib64 \
        --bindir=/bin \
        -Dshared=true -Dstatic=false \
        $(use_opt curl  -Dlibcurl=true -Dlibcurl=false) \
        $(use_opt libarchive -Dlibarchive=true -Dlibarchive=false) \
        -Dlibbrotli=false \
        -Dscripts=true
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

