#!/usr/bin/env bash
name='py3-inotify'
release='1'
version='0.9.6'
url='https://pypi.org/project/pyinotify'
description='Linux filesystem events monitoring'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('MIT')
source=("https://github.com/seb-m/pyinotify/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-setuptools)
sha256sums=('7943f198c5cef2bdc121d847937fbe565daaa7d4daaf1b8de8ef5689812f481c')
group=(dev.python)
uses=()
arch=('x86_64')

cd "pyinotify"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}


