#!/usr/bin/env bash
name='breeze-icons'
release='3'
version='6.5.0'
url='Breeze icon themes'
description='Addons to QtCore'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/breeze-icons-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules qt6-base)
sha256sums=('ca6e8faef84891750ebc240d0b99f42414e5f643678d5b1ae94bcbad551ab0c4')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBINARY_ICONS_RESOURCE=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
	  #rm $DESTDIR/usr/share/icons/breeze/actions/24/fingerprint-symbolic.svg
}

