#!/usr/bin/env bash
name='extra-cmake-modules'
release='2'
version='5.112.0'
url='https://community.kde.org/Frameworks'
description='Extra modules and scripts for CMake'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/extra-cmake-modules-${version}.tar.xz")
depends=(cmake)
makedepends=()
md5sums=('40fa6d3c54ce18dccec1dac4ee23d7d6')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    #mkdir build && cd build
    cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DSphinx_BUILD_EXECUTABLE=/usr/bin/sphinx-build \
        -DBUILD_HTML_DOCS=OFF \
        -DBUILD_MAN_DOCS=OFF \
        -DBUILD_QTHELP_DOCS=OFF
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}


