#!/usr/bin/env bash
name='extra-cmake-modules'
release='6'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Extra modules and scripts for CMake'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/extra-cmake-modules-${version}.tar.xz")
depends=(cmake qt5-tools qt6-tools)
makedepends=(py3-sphinx)
sha256sums=('8f3c2ca1e502990629f3b68507189fc0f912f3cab279b500dac91ee7031a49cf')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    #mkdir build && cd build
    cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DSphinx_BUILD_EXECUTABLE=/usr/bin/sphinx-build \
        -DBUILD_HTML_DOCS=OFF \
        -DBUILD_MAN_DOCS=OFF \
        -DBUILD_QTHELP_DOCS=OFF
}

build () {
    cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}


