#!/usr/bin/env bash
name='qt6-webchannel'
release='2'
version='6.7.0'
url='https://www.qt.io/'
description='Library for seamless integration of C++ +and QML applications with HTML/JavaScript clients.'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtwebchannel-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(cmake)
sha256sums=('26bfbd404e0c82bfbeeaef81796eb7a7cf931c5c1a5e942a315ca7126322efff')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtwebchannel-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}