#!/usr/bin/env bash
name='oxygen-icons'
release='3'
version='5.116.0'
url='https://community.kde.org/Frameworks'
description='Oxygen icon theme'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/oxygen-icons-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules qt5-base)
sha256sums=('fc83cac9567b54072cd1b99bd5ab1e555f555076b9c5f503e30e280580b79db5')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}