#!/usr/bin/env bash
name='oxygen-icons'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description='Oxygen icon theme'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/oxygen-icons-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules qt5-base)
md5sums=('eaa06cbd28343f48d776cd6103529105')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}