#!/usr/bin/env bash
name='krunner'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Framework for providing different actions given a string query'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/krunner-${version}.tar.xz")
depends=( kconfig kcoreaddons ki18n kitemmodels qt6-base)
makedepends=(extra-cmake-modules kdoctools doxygen qt6-tools)
sha256sums=('22d33fd27567a350ae4edae4fe5662b748e8fabd539863441794558e68f3313d')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
