#!/usr/bin/env bash
name='libglvnd'
release='1'
version='1.6.0'
url='https://gitlab.freedesktop.org/glvnd/libglvnd'
description='The GL Vendor-Neutral Dispatch library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v$version/libglvnd-v$version.tar.gz")
depends=(libXext)
makedepends=()
md5sums=('239b1799a2fb82ffe0902b6b7afd469b')
group=()
uses=()
arch=('x86_64')

cd $name-v$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

