#!/usr/bin/env bash
name='libglvnd'
release='2'
version='1.7.0'
url='https://gitlab.freedesktop.org/glvnd/libglvnd'
description='The GL Vendor-Neutral Dispatch library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/glvnd/libglvnd/-/archive/v$version/libglvnd-v$version.tar.gz")
depends=(libXext)
makedepends=()
md5sums=('6055d0ef8676601eb78a233a9285502c')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-v$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

