#!/usr/bin/env bash
name='sonnet'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Spelling framework for Qt5'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/sonnet-${version}.tar.xz")
depends=(qt6-base hunspell)
makedepends=(extra-cmake-modules qt6-declarative qt6-tools doxygen)
sha256sums=('2d94c957a3c5f2232653ad782b291e2b959eea6dca83cc09cae621bc9834ab25')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

