#!/usr/bin/env bash
name='sonnet'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Spelling framework for Qt5'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/sonnet-${version}.tar.xz")
depends=(qt6-base)
makedepends=(extra-cmake-modules qt6-declarative qt6-tools doxygen)
sha256sums=('2f970d490effd668e64dd93ffef344a80db7e63130bb23df4fa0d6b14150e588')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

