#!/usr/bin/env bash
name='sonnet'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description='Spelling framework for Qt5'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/sonnet-${version}.tar.xz")
depends=(qt5-base)
makedepends=(extra-cmake-modules qt5-tools doxygen)
md5sums=('57b2211d1c7ed7b6fce10912791399db')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


