#!/usr/bin/env bash
name='fontconfig'
release='4'
version='2.17.1'
url='https://www.freedesktop.org/software/fontconfig/'
description='Fontconfig is a library for configuring and customizing font access.'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/$version/fontconfig-$version.tar.gz"
        "fontconfig.sysconf"
        "19-enhanced-defaults.conf")
depends=(freetype expat)
makedepends=()
sha256sums=('82e73b26adad651b236e5f5d4b3074daf8ff0910188808496326bd3449e5261d'
         'SKIP'
         'SKIP')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddefault-hinting=full \
        -Ddefault-sub-pixel-rendering=rgb
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    # fix symlinks
    for link in $(ls ${DESTDIR}/etc/fonts/conf.d/) ; do
        if [[ -L ${DESTDIR}/etc/fonts/conf.d/$link ]] ; then
            rm -f ${DESTDIR}/etc/fonts/conf.d/$link
            ln -s ../../../usr/share/fontconfig/conf.avail/$link ${DESTDIR}/etc/fonts/conf.d/$link
        fi
    done
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../fontconfig.sysconf ${DESTDIR}/etc/sysconf.d/fontconfig
    #install ../19-enhanced-defaults.conf ${DESTDIR}/etc/fonts/conf.d/19-enhanced-defaults.conf
}

