#!/usr/bin/env bash
name='xf86-input-libinput'
release='3'
version='1.4.0'
url='https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput'
description='X.org input driver based on libinput'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput/-/archive/xf86-input-libinput-$version/xf86-input-libinput-xf86-input-libinput-$version.tar.gz")
depends=(libinput)
makedepends=()
md5sums=('d220f5ab49b52b57c695a4ec04de8fc4')
group=(x11.drivers)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install
}

