#!/usr/bin/env bash
name='xf86-input-libinput'
release='2'
version='1.3.0'
url='https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput'
description='X.org input driver based on libinput'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/driver/xf86-input-libinput/-/archive/xf86-input-libinput-$version/xf86-input-libinput-xf86-input-libinput-$version.tar.gz")
depends=(libinput)
makedepends=()
md5sums=('0d328c4771099c7f8aafdae04292b63b')
group=(x11.drivers)
uses=()
arch=('x86_64')

cd $name-$name-$version

setup(){
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make
}

package(){
    make install
}

