#!/usr/bin/env bash
name='hyprutils'
release='2'
version='0.8.1'
url='https://github.com/hyprwm/hyprutils'
description='Hyprland utilities library used across the ecosystem'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/hyprutils/archive/refs/tags/v$version.zip")
depends=(pixman)
makedepends=()
sha256sums=('374df06d53d01b2c682fb016c0109f9b5b0cdba739cf6f8a603115018a3f7b74')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

