#!/usr/bin/env bash
name='libusb'
release='1'
version='1.0.26'
url='https://github.com/libusb/libusb'
description='Userspace access to USB devices '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/libusb/libusb/archive/refs/tags/v$version.tar.gz")
depends=(eudev)
makedepends=()
md5sums=('dceb7af39f34844bcc78d526d8b6469a')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

