#!/usr/bin/env bash
name='util-macros'
release='2'
version='1.20.1'
url='https://gitlab.freedesktop.org/xorg/util/macros'
description='X.Org autotools utility macros'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('MIT')
source=("https://www.x.org/releases/individual/util/util-macros-${version}.tar.gz")
depends=()
makedepends=()
sha256sums=('b373f72887b1394ce2193180a60cb0d1fb8b17bc96ddd770cfd7a808cb489a15')
arch=('x86_64')
group=(x11.misc)

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

