#!/usr/bin/env bash
name='py3-pluggy'
release='4'
version='1.6.0'
url='https://github.com/pytest-dev/pluggy/tags'
description='Plugin management and hook calling for Python'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/pytest-dev/pluggy/archive/refs/tags/$version.tar.gz")
depends=(py3-pdm-pep517)
makedepends=(py3-setuptools)
sha256sums=('d35ec78be56dae9fd736e1378a2c3c176fd2aefd9daefc209abeab569c2732ee')
group=(dev.python)
uses=()
arch=('x86_64')

cd "pluggy"-$version


export SETUPTOOLS_SCM_PRETEND_VERSION=$version

build(){
    python3 -m build
}

package(){
    python3 -m installer --destdir ${DESTDIR} dist/*.whl
    mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}


