#!/usr/bin/env bash
name='opus'
release='2'
version='1.4'
url='https://opus-codec.org/'
description='Open codec for interactive speech and music transmission over the Internet'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/xiph/opus/archive/refs/tags/v$version.tar.gz")
depends=()
makedepends=()
md5sums=('4383274c187f9f9a32e88bbb69e170d7')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	autoreconf -fvi
  ./configure --prefix=/usr \
      --libdir=/usr/lib64/

}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

