#!/usr/bin/env bash
name='libnghttp2'
release='1'
version='1.51.0'
url='https://github.com/nghttp2/nghttp2'
description='HTTP/2 C Library'
email=' aliriza.keskin@pardus.org.tr'
maintainer=' aliriza'
license=('MIT')
source=("https://github.com/nghttp2/nghttp2/releases/download/v1.51.0/nghttp2-${version}.tar.gz")
depends=( )
makedepends=( )
md5sums=('d8c534bbdd84297afa4f6576896a3d76')
arch=('x86_64')
group=(net.libs)
uses=(libxml2)
libxml2_depends=(libxml2)

cd nghttp2-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --without-neverbleed \
        --without-jemalloc \
        --disable-examples \
        --enable-static \
        --enable-lib-only\
        $(use_opt libxml2 --with-libxml2 --without-libxml2)
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

