#!/usr/bin/env bash
name='kio'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Resource and network access abstraction'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kio-${version}.tar.xz")
depends=(karchive kbookmarks kcompletion kconfig kconfigwidgets kcoreaddons kcrash kauth
	kdbusaddons ki18n kiconthemes kitemviews kjobwidgets kservice kwidgetsaddons kwindowsystem solid qt6-base qt6-5compat)
makedepends=(doxygen extra-cmake-modules libxml2 libxslt qt6-tools)
sha256sums=('4951adf043299e463803cc63ed33d5261b81bff969eb189dc13350f495cb4b42')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version


setup () {
  cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

