#!/usr/bin/env bash
name='kio'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description='Resource and network access abstraction'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kio-${version}.tar.xz")
depends=(karchive kbookmarks kcompletion kconfig kconfigwidgets kcoreaddons kcrash
	kdbusaddons ki18n kiconthemes kitemviews kjobwidgets kservice kwidgetsaddons kwindowsystem solid)
makedepends=(doxygen extra-cmake-modules libxml2 libxslt qt5-tools)
md5sums=('476559f2314a7e7cf6e0bc870c4334fe')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    # remove kwallet dependency
    sed -i "/add_subdirectory(kpasswdserver)/d" src/CMakeLists.txt
}

setup () {
  cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

