#!/usr/bin/env bash
name='networkmanager-qt5'
release='1'
version='5.112.0'
url='https://community.kde.org/Frameworks'
description='Qt wrapper for NetworkManager API'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/frameworks/${version%.*}/networkmanager-qt-${version}.tar.xz")
depends=(networkmanager qt5-base)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('4b5901b5a65a1f33c17214d8b8d4334e')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd "networkmanager-qt"-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
