#!/usr/bin/env bash
name='lightdm'
release='1'
version='1.32.0'
url='https://github.com/canonical/lightdm'
description='A lightweight display manager'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://salsa.debian.org/xfce-extras-team/lightdm/-/archive/debian/$version-1/lightdm-debian-$version-1.tar.gz"
        "lightdm-session.sh"
        "lightdm.initd")
depends=(libX11 pam libxklavier xorg-server libxcb glib libgcrypt libXdmcp xmodmap xrdb libXi)
makedepends=(gobject-introspection vala intltool yelp-tools)
sha256sums=('10eec5e47c9546f934f568591140204db2ea2241f345685bb8eeb35da05c83e5'
         'SKIP'
         'SKIP')
group=(x11.misc)
uses=()
arch=('x86_64')

#cd $name-$version-1
cd lightdm-debian-$version-1
setup(){
   	./autogen.sh
	./configure --prefix=/usr \
            --sysconfdir=/etc \
            --libdir=/usr/lib64/ \
            --localstatedir=/var \
            --disable-tests \
            --disable-gtk-doc \
            --enable-yelp-tools \
            --disable-qt5-base \
            --with-greeter-user=lightdm \
            --with-greeter-session=lightdm-gtk-greeter
}

build(){
    make $jobs
}

package(){
    make install $jobs
    # create user and group
    mkdir -p $DESTDIR/etc/group.d
    mkdir -p $DESTDIR/etc/passwd.d
    # GID: lightdm 118
    echo "lightdm:x:118:118:Lightdm Display Manager:/var/lib/lightdm-data/:/bin/sh" > $DESTDIR/etc/passwd.d/lightdm
    echo "lightdm:x:118:" > $DESTDIR/etc/group.d/lightdm
    # install service
    mkdir -p $DESTDIR/etc/init.d
    install ../lightdm.initd $DESTDIR/etc/init.d/lightdm
    # generate lightdm-session file
    install ../lightdm-session.sh $DESTDIR/usr/bin/lightdm-session
    # fix pam config
    sed -i "s/systemd/elogind/g" $DESTDIR/etc/pam.d/*
}

