#!/usr/bin/env bash
name='vidstab'
dizin='vid.stab'
release='1'
version='1.1.1'
url='http://public.hronopik.de/vid.stab/'
description='Video stabilization library'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/georgmartius/vid.stab/archive/v${version}/vid.stab-v${version}.tar.gz")
depends=(glibc)
makedepends=(cmake)
md5sums=('3fb59a96f6e49e2719fd8c551eb3617a')
group=(media.libs)
uses=()
arch=('x86_64')

cd $dizin-$version

setup(){
    cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build(){
    cmake --build build
}

package(){
    cmake --install build
}

