#!/usr/bin/env bash
name='libpsl'
release='2'
version='0.21.2'
url='https://github.com/rockdaboot/libpsl'
description='C library for the Public Suffix List'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/rockdaboot/libpsl/releases/download/$version/libpsl-$version.tar.gz")
depends=(libidn2)
makedepends=(python)
md5sums=('2864d3eb744b378d68f5c4da25603459')
arch=('x86_64')
group=(net.libs)

cd $name-$version

prepare(){
    # meson build missing .la file
    # autotools missing static library
    cp -prf ../$name-$version ../$name-autotools
}

setup(){
    cd ../$name-autotools
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
       --enable-ld-version-script \
       --enable-runtime=libidn2 \
       --enable-builtin
    cd ../$name-$version
    meson setup build --prefix=/usr \
        --default-library=both \
        --libdir=/usr/lib64 \
        -Druntime=libidn2 \
			  -Dbuiltin=true
}

build(){
    cd ../$name-autotools
    make $jobs
    cd ../$name-$version
    ninja -C build $jobs
}

package(){
    cd ../$name-autotools
    make install $jobs
    cd ../$name-$version
    ninja -C build install $jobs
}

