#!/usr/bin/env bash
name='libpsl'
release='1'
version='0.21.1'
url='https://github.com/rockdaboot/libpsl'
description='C library for the Public Suffix List'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=('https://github.com/rockdaboot/libpsl/releases/download/0.21.1/libpsl-0.21.1.tar.gz')
depends=(libidn2)
makedepends=( )
md5sums=('ad40b970dcb5117d559b62a1e0d8d827')
arch=('x86_64')
group=(net.libs)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/libpsl
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
    mkdir -p ${DESTDIR}/etc/ld.so.conf.d/
    echo "/usr/lib64/libpsl/" > ${DESTDIR}/etc/ld.so.conf.d/libpsl.conf
}

