#!/usr/bin/env bash
name='solid'
release='2'
version='5.114.0'
url='https://community.kde.org/Frameworks'
description=' Hardware integration and detection'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/solid-${version}.tar.xz")
depends=(bison 	eudev flex qt5-tools udisks2 upower)
makedepends=(doxygen extra-cmake-modules)
md5sums=('bfe60502c09abb3b91f5bf949d454e77')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DBUILD_TESTING=OFF \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}
