#!/usr/bin/env bash
name='solid'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Hardware integration and detection'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/solid-${version}.tar.xz")
depends=(qt6-base udisks2 upower)
makedepends=(qt6-tools qt6-declarative doxygen extra-cmake-modules)
sha256sums=('e8237c6c9617bef4bf5fc74461bb7417ca57afe15d4f54878cfe8c806e706a5c')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DBUILD_TESTING=OFF \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}
