#!/usr/bin/env bash
name='kcolorscheme'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Classes to read and interact with KColorScheme'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcolorscheme-${version}.tar.xz")
depends=(qt6-base kconfig kguiaddons ki18n)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=('1b4c6e84f1dd96b2ee62be755f60da60d61ba80d6709eeb3186d8882e72e2130')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
