#!/usr/bin/env bash
name='kcolorscheme'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Classes to read and interact with KColorScheme'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcolorscheme-${version}.tar.xz")
depends=(qt6-base kconfig kguiaddons ki18n)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=('14e99e74cc636640ac8d705f2878d72d0379fff671e75c0f138302489898d651')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
