#!/usr/bin/env bash
name='libayatana-appindicator'
release='2'
version='0.5.94'
url='https://github.com/AyatanaIndicators'
description='Ayatana Application Indicators Shared Library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/AyatanaIndicators/libayatana-appindicator/archive/refs/tags/$version.tar.gz")
depends=(gtk3 libayatana-indicator libdbusmenu)
makedepends=()
sha256sums=('884a6bc77994c0b58c961613ca4c4b974dc91aa0f804e70e92f38a542d0d0f90')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib64 \
        -DENABLE_BINDINGS_MONO=OFF
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

