#!/usr/bin/env bash
name='xfce4-whiskermenu-plugin'
release='3'
version='2.8.3'
url='https://gottcode.org/xfce4-whiskermenu-plugin/'
description='Menu for Xfce4'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://github.com/gottcode/xfce4-whiskermenu-plugin/archive/refs/tags/v${version}.tar.gz")
depends=(garcon xfce4-panel accountsservice)
makedepends=(cmake ninja)
sha256sums=('bf1fa1c6563b3354bb196d99010d013ddaa227398e70d4ac79a4798b8d92fece')
group=(xfce.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	cmake -B build -S . \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DENABLE_GTK_LAYER_SHELL=OFF
}

build(){
    cmake --build build
}

package(){
     DESTDIR="${DESTDIR}" cmake --install build
}

