#!/usr/bin/env bash
name='xfce4-whiskermenu-plugin'
release='4'
version='2.10.0'
url='https://gottcode.org/xfce4-whiskermenu-plugin/'
description='Menu for Xfce4'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://github.com/gottcode/xfce4-whiskermenu-plugin/archive/refs/tags/v${version}.tar.gz")
depends=(garcon xfce4-panel accountsservice)
makedepends=(cmake ninja)
sha256sums=('07b8f30ce8a54bab6d8f880da25f650b1b306b6825ee40cf9a0bfb2af60da902')
group=(xfce.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	cmake -B build -S . \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DENABLE_GTK_LAYER_SHELL=OFF
}

build(){
    cmake --build build
}

package(){
     DESTDIR="${DESTDIR}" cmake --install build
}

