#!/usr/bin/env bash
name='xfce4-whiskermenu-plugin'
release='1'
version='2.7.3'
url='https://gottcode.org/xfce4-whiskermenu-plugin/'
description='Menu for Xfce4'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://github.com/gottcode/xfce4-whiskermenu-plugin/archive/refs/tags/v${version}.tar.gz")
depends=(garcon xfce4-panel)
makedepends=(cmake ninja)
md5sums=('0f4ef8695e9f3f5491379088322ff919')
group=(xfce.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	cmake -B build -S . \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-GNinja
}

build(){
    ninja -C build
}

package(){
    DESTDIR="$DESTDIR" ninja -C build install
}

