#!/usr/bin/env bash
name='texinfo'
release='1'
version='7.1'
url='https://www.gnu.org/software/texinfo/'
description='Utilities to work with and produce manuals, ASCII text, and on-line documentation from a single source file'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/texinfo/texinfo-${version}.tar.xz" "fix-build-without-NLS.patch")
depends=(perl gzip)
makedepends=(ncurses help2man)
sha256sums=('deeec9f19f159e046fdf8ad22231981806dac332cc372f1c763504ad82b30953' 'SKIP')
group=(sys.apps)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
	export LC_CTYPE=tr_TR.UTF-8
	export LC_ALL=tr_TR.UTF-8
	patch -Np1 -i ../fix-build-without-NLS.patch 
}

setup () {
	autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--disable-man
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

