#!/usr/bin/env bash
name='ca-certificates'
release='2'
version='20240705'
url='https://salsa.debian.org/debian/ca-certificates'
description='Common CA certificates'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.alpinelinux.org/alpine/ca-certificates/-/archive/$version/ca-certificates-$version.tar.gz"
        "ca-certificates.sysconf")
depends=()
makedepends=()
sha256sums=('125ad77f66dbac3dfedefa2368a907f90b449baf5c826396714a4055c582bce6'
         'SKIP')
group=(app.misc)
uses=()
arch=('x86_64')

cd $name-$version

build(){
    make $jobs
}

package(){
    make install $jobs
    # openssl conflict fix
    rm -f ${DESTDIR}/usr/bin/c_rehash
    # install sysconf file
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../ca-certificates.sysconf ${DESTDIR}/etc/sysconf.d/ca-certificates
}

