#!/usr/bin/env bash
name='pardus-power-manager'
release='1'
version='3.0.0'
url='https://pardus.org.tr'
description='pardus-power-manager'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/pardus/pardus-power-manager/archive/refs/tags/debian/$version.tar.gz")
depends=(python gtk3)
makedepends=()
sha256sums=('13a6bc79dc33579ff8ddcf5ace2e3f5a87d4d73a169ad4e93fb14a16b8849e81')
group=(app.misc)
uses=()
arch=('x86_64')

cd $name-debian-$version

setup () {
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Dservice=openrc
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}
