#!/usr/bin/env bash
name='kdecoration'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='Plugin based library to create window decorations'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kdecoration-${version}.tar.xz")
depends=(ki18n qt6-base)
makedepends=(extra-cmake-modules)
sha256sums=('f9d3ec4256cf7125a3b0bc08c7737af715235d5c22b69ba29797bb06c5ef4a4c')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
