#!/usr/bin/env bash
name='kdecoration'
release='3'
version='6.1.5'
url='https://kde.org/plasma-desktop'
description='Plugin based library to create window decorations'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kdecoration-${version}.tar.xz")
depends=(ki18n qt6-base)
makedepends=(extra-cmake-modules)
sha256sums=('3ce16cea659d863f78eb93d567bf952b3f66440becd424b06d2041ff0679def7')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
