#!/usr/bin/env bash
name='qt5-scxml'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='Static and runtime integration of SCXML models into Qt code'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtscxml-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=(qt5-declarative)
sha256sums=('a1c77176eb1b27b9a4a4b9cc324493c55282f81880770e9f0411fa9ee5e705bd')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtscxml-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

