#!/usr/bin/env bash
name='qt5-scxml'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='Static and runtime integration of SCXML models into Qt code'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtscxml-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base)
makedepends=(qt5-declarative)
md5sums=('fbf72ea0d2c96fc8f4a953cb74caff17')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtscxml-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

