#!/usr/bin/env bash
name='qt6-speech'
release='3'
version='6.8.0'
url='https://www.qt.io/'
description='Qt module to make text to speech and speech recognition easy'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtspeech-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-multimedia)
makedepends=(speech-dispatcher qt6-declarative cmake)
sha256sums=('75230a12bc37b8535f3858c11247bf68a502e2559265243eb3b44fc917166565')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtspeech-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH


setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}

