#!/usr/bin/env bash
name='libXpresent'
release='1'
version='1.0.1'
url='https://example.org'
description='Package libXpresent'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXpresent-$version.tar.xz")
depends=(libX11 xorgproto libXext libXfixes libXrandr)
makedepends=()
md5sums=('bdd3ec17c6181fd7b26f6775886c730d')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

