#!/usr/bin/env bash
name='qt6-quicktimeline'
release='4'
version='6.9.1'
url='https://www.qt.io/developers'
description='Qt module for keyframe-based timeline construction'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtquicktimeline-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(cmake ninja)
sha256sums=('78bfdbe7ca8178e4e0931372e07a3076dec503b6a55ff07e41b594d781897294')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtquicktimeline-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
export CFLAGS="$CFLAGS -g1 -flto=auto"
export CXXFLAGS="$CXXFLAGS -g1 -flto=auto"

	cmake -B build  -G Ninja \
			-DCMAKE_INSTALL_PREFIX=/usr

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}