#!/usr/bin/env bash
name='qt6-quicktimeline'
release='2'
version='6.7.0'
url='https://www.qt.io/developers'
description='Qt module for keyframe-based timeline construction'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtquicktimeline-everywhere-src-${version}.tar.xz")
depends=(qt6-base qt6-declarative)
makedepends=(cmake)
sha256sums=('eb45657c6c6b5d57775473d4d69e7d964a17778695ffb2ff50a75aa1b63489bd')
group=(dev.qt)
uses=()
arch=('x86_64')

# HATALI PAKET

cd "qtquicktimeline-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
export CFLAGS="$CFLAGS -g1 -flto=auto"
export CXXFLAGS="$CXXFLAGS -g1 -flto=auto"

	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=Release \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}