#!/usr/bin/env bash
name='libdmx'
release='1'
version='1.1.4'
url='https://gitlab.freedesktop.org/xorg/lib/libdmx'
description='X.Org dmx library'
email='bayramkk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libdmx-$version.tar.gz")
depends=()
makedepends=()
md5sums=('bf40bddfe658d224a5574ea249583f9e')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

