#!/usr/bin/env bash
name='docbook-xsl'
release='1'
version='1.79.2'
url='https://docbook.org/'
description='XML stylesheets for Docbook-xml transformations'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('custom')
source=(https://github.com/docbook/xslt10-stylesheets/releases/download/release/$version/docbook-xsl-$version.zip
        '765567_non-recursive_string_subst.patch'
        'docbook-xsl.sysconf')
depends=(docbook-xml libxml2 libxslt)
makedepends=()
md5sums=('39c12481817d5a57501d27621eeba9a8'
         'SKIP'
         'SKIP')
group=(app.text)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
	patch -Np2 -i ../765567_non-recursive_string_subst.patch
}

package(){
	local _dest dir f
	_dest="$DESTDIR"/usr/share/xml/docbook/xsl-stylesheets-$version

	install -dm755 "$_dest"
	install -m644 VERSION VERSION.xsl "$_dest"/
	ln -s xsl-stylesheets-$version "${_dest%/*}/xsl-stylesheets"
	ln -s xsl-stylesheets-$version "${_dest%/*}/xsl-stylesheets-current"

	for dir in assembly common eclipse epub epub3 fo highlighting html \
		htmlhelp javahelp lib manpages params profiling roundtrip \
		template website xhtml xhtml-1_1 xhtml5; do

		install -dm755 $_dest/$dir
		for f in $dir/*.xml $dir/*.xsl $dir/*.dtd $dir/*.ent; do
			[ -e "$f" ] || continue
			install -m644 $f $_dest/$dir
		done
	done

	install -dm755 "$DESTDIR"/etc/xml

	install -m644 -D COPYING \
		"$DESTDIR"/usr/share/licenses/$name/COPYING

        install -dm755 "$DESTDIR"/etc/sysconf.d/
        install $HOME/docbook-xsl.sysconf "$DESTDIR"/etc/sysconf.d/docbook-xsl
}

