#!/usr/bin/env bash
name='docbook-xsl'
release='1'
version='1.79.2'
url='https://docbook.org/'
description='XML stylesheets for Docbook-xml transformations'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('custom')
source=(https://github.com/docbook/xslt10-stylesheets/releases/download/release/$version/docbook-xsl{,-nons}-$version.zip '765567_non-recursive_string_subst.patch')
depends=(docbook-xml libxml2 libxslt)
makedepends=()
md5sums=('39c12481817d5a57501d27621eeba9a8' 'df397633036d576f04431f1b00047910' 'd41d8cd98f00b204e9800998ecf8427e')
group=(app.text)
uses=()
arch=('x86_64')

install=$name.install
cd $name-$version


build(){

	patch -Np2 -i ../765567_non-recursive_string_subst.patch
	cd ../$name-nons-$version
	patch -Np2 -i ../765567_non-recursive_string_subst.patch
}

package(){

	local pkgroot ns dir
	for ns in -nons ''; do
	pkgroot="$DESTDIR/usr/share/xml/docbook/xsl-stylesheets-$version$ns"
	dir="../"$name$ns-$version

	install -Dt "$pkgroot" -m644 $dir/VERSION{,.xsl}

	(
	  shopt -s nullglob  # ignore missing files
	  for fn in assembly common eclipse epub epub3 fo highlighting html \
		htmlhelp javahelp lib manpages params profiling roundtrip template \
		website xhtml xhtml-1_1 xhtml5
	  do
		install -Dt "$pkgroot/$fn" -m644 $dir/$fn/*.{xml,xsl,dtd,ent}
	  done
	)
	done
    install -v -m644 -D README /usr/share/doc/docbook-xsl-nons-1.79.2/README.txt
    install -v -m644    RELEASE-NOTES* NEWS* /usr/share/doc/docbook-xsl-nons-1.79.2
	install -d "$DESTDIR/etc/xml"
	install -Dt "$DESTDIR/usr/share/licenses/$name" -m644 $dir/COPYING
}

