#!/usr/bin/env bash
name=bzip2
version=1.0.8
release=1
url='https://sourceware.org/bzip2'
description='lzma compression utilities and library'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
source=("https://sourceware.org/pub/bzip2/bzip2-${version}.tar.gz"
        'bzip2.pc.in')
md5sums=('67e051268d0c475ea773822f7500d0e5'
         'SKIP')
group=(app.arch)
arch=(x86_64)
cd $name-$version

setup(){
	# Generate relative symlinks
	sed -i \
		-e 's:\$(PREFIX)/man:\$(PREFIX)/share/man:g' \
		-e 's:ln -s -f $(PREFIX)/bin/:ln -s :' \
		Makefile

	# fixup broken version stuff
	sed -i \
		-e "s:1\.0\.4:$version:" \
		bzip2.1 bzip2.txt Makefile-libbz2_so manual.*
}
build(){
    make -f Makefile-libbz2_so all
	make all
}
package(){
    make PREFIX="$DESTDIR"/usr install
	install -D libbz2.so.$version "$DESTDIR"/usr/lib/libbz2.so.$version
	ln -s libbz2.so.$version "$DESTDIR"/usr/lib/libbz2.so
	ln -s libbz2.so.$version "$DESTDIR"/usr/lib/libbz2.so.${version%%.*}
	mkdir -p "$DESTDIR"/usr/lib/pkgconfig/
    sed "s|@VERSION@|$version|" ../bzip2.pc.in \
		> "$DESTDIR"/usr/lib/pkgconfig/bzip2.pc
}
