#!/usr/bin/env bash
name='libdrm'
release='3'
version='2.4.123'
url='https://gitlab.freedesktop.org/mesa/drm'
description='X.Org libdrm library'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://dri.freedesktop.org/libdrm/libdrm-$version.tar.xz")
depends=(libpciaccess)
makedepends=()
sha256sums=('a2b98567a149a74b0f50e91e825f9c0315d86e7be9b74394dae8b298caadb79e')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        -D default_library=both \
        -D udev=false \
        -D etnaviv=disabled \
        -D freedreno=disabled \
        -D vc4=disabled \
        -D valgrind=disabled \
        -D install-test-programs=true
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

