#!/usr/bin/env bash
name='libdrm'
release='2'
version='2.4.120'
url='https://gitlab.freedesktop.org/mesa/drm'
description='X.Org libdrm library'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://dri.freedesktop.org/libdrm/libdrm-$version.tar.xz")
depends=(libpciaccess)
makedepends=()
md5sums=('f8521de37ccbd15987b843a83fabd567')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        -D default_library=both \
        -D udev=false \
        -D etnaviv=disabled \
        -D freedreno=disabled \
        -D vc4=disabled \
        -D valgrind=disabled \
        -D install-test-programs=true
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

