#!/usr/bin/env bash
name='aquamarine'
release='2'
version='0.8.0'
url='https://github.com/hyprwm/aquamarine'
description='Aquamarine is a very light linux rendering backend library'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/aquamarine/archive/refs/tags/v$version.tar.gz")
depends=(hyprwayland-scanner libglvnd libglvnd libinput mesa seatd wayland)
makedepends=()
sha256sums=('1c3570de268fff008c6dd76472d783710b7f62c545f76091580c9edd13ad23d5')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
      -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

