#!/usr/bin/env bash
name='bc'
release='1'
version='1.07'
url='https://ftp.gnu.org/gnu/bc/'
description='Handy console-based calculator utility'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://salsa.debian.org/debian/bc/-/archive/debian/$version.1-3/bc-debian-$version.1-3.tar.gz"
        "https://gitweb.gentoo.org/repo/gentoo.git/plain/sys-devel/bc/files/bc-1.07.1-no-ed-its-sed.patch")
depends=(readline)
makedepends=()
md5sums=('88f3760aeddf374a849ca4518540960b'
         'a7bdd642f30ae47ee5bcbcf3f65e061b')
group=(sys.devel)
uses=()
uses_extra=(static)
arch=('x86_64')

cd $name-debian-$version.1-3

if use static ; then
    export CFLAGS="-static"
fi

export PATH=$PATH:$HOME

prepare(){
    echo "#!/bin/sh" > $HOME/makeinfo
    echo "printf 'makeinfo (GNU texinfo) 5.2\n'" >> $HOME/makeinfo
    chmod +x $HOME/makeinfo
    patch -Np1 -i ../bc-1.07.1-no-ed-its-sed.patch
    for file in debian/patches/*.diff ; do
        patch -Np1 -i $file
    done
}

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --with-readline
}

build(){
    make
}

package(){
    make install -j`nproc`
}

