#!/usr/bin/env bash
name='nano'
release='3'
version='8.0'
url='https://www.nano-editor.org/download.php'
description='Pico editor clone with enhancements'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
_commit="ff189e2baa8d89f44b5f58ea7da7aac04ee4ad8b"
source=("https://www.nano-editor.org/dist/v8/nano-$version.tar.xz"
        "https://github.com/galenguyer/nano-syntax-highlighting/archive/${_commit}.zip"
        "nanorc"
        "nano.desktop"
        "icon.svg")
depends=(file zlib ncurses bzip2)
makedepends=()
sha256sums=('c17f43fc0e37336b33ee50a209c701d5beb808adc2d9f089ca831b40539c9ac4'
            '9e836760f61473a7a6ae28ac5e10b8d5b26f0415d1bd0c85d56d9b09e27a9fe1'
            'SKIP'
            'SKIP'
            'SKIP'
)
uses=(nanorc)
arch=('x86_64')
group=(app.editor)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --libdir=/usr/lib64/ \
        $(use_arg nanorc --enable-color --disable-color )\
        $(use_arg nanorc --enable-nanorc --disable-nanorc )\
        --enable-multibuffer
}

build(){
    make $jobs
}

package(){
    make install $jobs
    mkdir -p ${DESTDIR}/etc
    install ../nanorc ${DESTDIR}/etc/nanorc
    # install extra nanorc files
    cd ../nano-syntax-highlighting-${_commit}
    for file in ./*.nanorc ; do
        if [[ ! -f ${DESTDIR}/usr/share/nano/$file ]] ; then
            # black color is buggy with dark themes so replace with green
            sed -i "s/color black/ color green/g" $file
            sed -i "s/color brightblack/ color brightgreen/g" $file
            install $file ${DESTDIR}/usr/share/nano/
        fi
    done
    # install application launcher for desktop environments
    mkdir -p ${DESTDIR}/usr/share/applications/
    mkdir -p ${DESTDIR}/usr/share/icons/hicolor/scalable/apps/
    install ../nano.desktop ${DESTDIR}/usr/share/applications
    install ../icon.svg ${DESTDIR}/usr/share/icons/hicolor/scalable/apps/nano.svg

}

