#!/usr/bin/env bash
name='freetype'
release='2'
version='2.13.1'
url='https://download.savannah.gnu.org/releases/freetype/'
description='Package freetype'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.savannah.gnu.org/releases/freetype/freetype-$version.tar.gz")
depends=(zlib bzip2 glib libpng brotli)
makedepends=()
md5sums=('ea70022407b00debe025681f974835ad')
group=(media.libs)
uses=(harfbuzz)
harfbuzz_depends=(harfbuzz)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
    --with-harfbuzz=$(use_opt harfbuzz yes no)
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

