#!/usr/bin/env bash
name='freetype'
release='1'
version='2.9.1'
url='https://download.savannah.gnu.org/releases/freetype/'
description='Package freetype'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://download.savannah.gnu.org/releases/freetype/freetype-$version.tar.gz")
depends=(zlib bzip2 glib libpng)
makedepends=()
md5sums=('3adb0e35d3c100c456357345ccfa8056')
group=(media.libs)
uses=(harfbuzz)
harfbuzz_depends=(harfbuzz)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
    --with-harfbuzz=$(use_opt harfbuzz yes no)
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

