#!/usr/bin/env bash
name='findutils'
release='2'
version='4.10.0'
url='https://ftp.gnu.org/gnu/findutils/'
description='GNU utilities for finding files'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/findutils/findutils-$version.tar.xz")
depends=()
makedepends=()
sha256sums=('1387e0b67ff247d2abde998f90dfbf70c1491391a59ddfecb8ae698789f0a4f5')
uses=()
group=(sys.apps)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

