#!/usr/bin/env bash
name='btrfs-progs'
release='6'
version='6.11'
url='https://github.com/storaged-project/libblockdev'
description='A library for manipulating block devices'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/kdave/btrfs-progs/archive/refs/tags/v${version}.tar.gz")
depends=(e2fsprogs zlib libgcrypt eudev)
makedepends=()
sha256sums=('ba1b8017b82e22f874fb3b09805ac4f45e3265888dc56eaf4449f38f896f6fc4')
group=(sys.fs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	./autogen.sh
	./configure --prefix=/usr \
            --libdir=/usr/lib64/\
            --with-crypto=libgcrypt \
            --disable-zstd \
            --disable-documentation
}

build(){
    make $jobs
}

package(){
  make DESTDIR="$DESTDIR" install install_python
  # install bash completion (FS#44618)
  install -Dm644 btrfs-completion "$DESTDIR/usr/share/bash-completion/completions/btrfs"
}

