#!/usr/bin/env bash
name='py3-parsing'
release='3'
version='3.2.3'
url='https://pypi.org/project/pyparsing/'
description='Python library for creating PEG parsers'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/pyparsing/pyparsing/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer py3-flit)
sha256sums=('3ad3397385c3f68c89d313529af4cafc9a9117845bc0cb6b38f02e621d151d38')
group=(dev.python)
uses=()
arch=('x86_64')

cd pyparsing-$version

package(){
    mkdir -p ${DESTDIR}/usr/lib64/python3
    cp -prfv pyparsing ${DESTDIR}/usr/lib64/python3
}

