#!/usr/bin/env bash
name='py3-parsing'
release='2'
version='3.1.2'
url='https://pypi.org/project/pyparsing/'
description='Python library for creating PEG parsers'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/pyparsing/pyparsing/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer py3-flit)
sha256sums=('a8a6b7db8b837566884b6c5d8d24bf627f85b72c8abce1338e4d7ffe1a88473e')
group=(dev.python)
uses=()
arch=('x86_64')

cd pyparsing-$version

package(){
    mkdir -p ${DESTDIR}/usr/lib64/python3
    cp -prfv pyparsing ${DESTDIR}/usr/lib64/python3
}

