#!/usr/bin/env bash
name='mousepad'
release='2'
version='0.6.1'
_version='0.6'
url='https://docs.xfce.org/apps/mousepad/start'
description='Simple text editor for Xfce'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
#source=("https://gitlab.xfce.org/apps/mousepad/-/archive/mousepad-${version}/mousepad-mousepad-${version}.tar.gz")
source="https://archive.xfce.org/src/apps/mousepad/${_version}/mousepad-${version}.tar.bz2"
depends=(desktop-file-utils gtksourceview4)
makedepends=(intltool)
md5sums=('9f1b5565cbb8975f85ed5cc0ff6a876b')
group=(app.editors)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-debug
}

build(){
    make $jobs
}

package(){
    make DESTDIR=$DESTDIR install $jobs
}