#!/usr/bin/env bash
name='kcoreaddons'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Addons to QtCore'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcoreaddons-${version}.tar.xz")
depends=(qt5-base)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('9fcee2fb381bcee57e42f7fb91275024')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
