#!/usr/bin/env bash
name='libX11'
release='1'
version='1.8'
url='https://www.x.org/archive/individual/lib/'
description='X.Org X11 library'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libX11-$version.tar.xz")
depends=(libxcb libXau libXdmcp xtrans)
makedepends=()
md5sums=('26758ed669a643b090dfe97b61922627')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}
