#!/usr/bin/env bash
name='waybar'
release='1'
version='0.11.0'
url='https:///github.com/Alexays/Waybar'
description='Highly customizable Wayland bar for Sway and Wlroots based compositors.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/Alexays/Waybar/archive/refs/tags/0.11.0.tar.gz"
        "fix-systray.patch"
)
depends=(fmt gtk-layer-shell gtkmm3 jack2 jsoncpp libdbusmenu libinput
         libnl libxkbcommon pipewire spdlog upower wireplumber)
makedepends=()
sha256sums=('6a0e9f0f7f2eff503951958cbb16dc39041c0b67e86c35154e8507677c61be9d'
            'SKIP')
group=(gui.apps)
uses=()
arch=('x86_64')

cd Waybar-$version

prepare(){
    patch -Np1 -i ../fix-systray.patch
}

setup () {
    meson setup build \
       --prefix=/usr \
       -Dcpp_std=c++20 \
       -Dexperimental=true \
       -Dcava=disabled \
       -Dpulseaudio=disabled \
       -Dsndio=disabled



}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

