#!/usr/bin/env bash
name='libXvMC'
release='1'
version='1.0.13'
url='https://gitlab.freedesktop.org/xorg/lib/libXvMC.git/'
description='X.Org XvMC library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXvMC-$version.tar.xz")
depends=(libX11 libXext libXv xorgproto )
makedepends=()
md5sums=('11a358e7229fa28dc9801c1e64fe2e18')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

