#!/usr/bin/env bash
name='py3-tomli'
release='2'
version='2.2.1'
url='https://github.com/hukkin/tomli'
description="Lil' TOML parser"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/hukkin/tomli/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-flit)
sha256sums=('3af7c4b571d1ccddaba020c558da0ce5b5e24edc830e478a903d82dc2d9013ae')
group=(dev.python)
uses=()
arch=('x86_64')

cd "tomli"-$version

build(){
    python -m build -wn --skip-dependency-check
}

package(){
    python3 -m installer -d "$DESTDIR" dist/*.whl
    mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}

