#!/usr/bin/env bash
name='gdbm'
release='3'
version='1.26'
url='https://www.gnu.org.ua/software/gdbm/download.html'
description=' Standard GNU database libraries'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/gdbm/gdbm-${version}.tar.gz")
depends=( )
makedepends=( )
sha256sums=('695e9827fdf763513f133910bc7e6cfdb9187943a4fec943e57449723d2b8dbf')
uses=()
group=(sys.libs)
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --enable-libgdbm-compat
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

