#!/usr/bin/env bash
name='gdbm'
release='3'
version='1.26'
url='https://www.gnu.org.ua/software/gdbm/download.html'
description=' Standard GNU database libraries'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/gdbm/gdbm-${version}.tar.gz")
depends=( )
makedepends=( )
sha256sums=('6a24504a14de4a744103dcb936be976df6fbe88ccff26065e54c1c47946f4a5e')
uses=()
group=(sys.libs)
arch=('x86_64')

cd $name-$version

prepare(){
    # dummy makeinfo command
    echo "#!/bin/sh" > ~/makeinfo
    chmod 755 ~/makeinfo
}

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --enable-libgdbm-compat
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

