#!/usr/bin/env bash
name='asciidoc'
release='3'
version='10.2.1'
url='https://github.com/asciidoc-py/asciidoc-py/'
description='A plain text human readable/writable document format '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/asciidoc-py/asciidoc-py/archive/refs/tags/$version.tar.gz")
depends=(docbook-xsl libxslt python)
makedepends=(py3-build py3-installer py3-wheel)
sha256sums=('8e1fb9691952cc4f13357e1ef58172e566c5f88e3c44222d4a8693585f884507')
group=(dev.python)
uses=()
arch=('x86_64')

cd $name-py-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}
