#!/usr/bin/env bash
name='kdeplasma-addons'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description=''
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/kdeplasma-addons-$version.tar.xz")
depends=(plasma-workspace)
makedepends=()
sha256sums=('4bdbdc2892bbf6211c3be6c02177f7ffdce10ab1546d811a4b59024192b77bce')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

