#!/usr/bin/env bash
name='kdeplasma-addons'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description=''
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/kdeplasma-addons-$version.tar.xz")
depends=(plasma-workspace kunitconversion)
makedepends=()
sha256sums=('bd0d590664464c886fe14447be38c161a927b70fb6c9ce28a7090f9090260cf7')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

