#!/usr/bin/env bash
name='kdeplasma-addons'
release='3'
version='6.1.5'
url='https://kde.org/plasma-desktop'
description=''
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/kdeplasma-addons-$version.tar.xz")
depends=(plasma-workspace kunitconversion)
makedepends=()
sha256sums=('36b6f9e1c03e52ea4e5d0409a0786117c8247166169f2d0a221f20f1aeab8863')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    ninja -C build $jobs
}

package () {
    ninja -C build install $jobs
}

