#!/usr/bin/env bash
name='cryptsetup'
release='2'
version='2.7.0'
url='https://gitlab.com/cryptsetup/'
description='Tool to setup encrypted devices with dm-crypt'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.com/cryptsetup/cryptsetup/-/archive/v$version/cryptsetup-v$version.tar.gz")
depends=(lvm2 json-c)
makedepends=()
md5sums=('b564e09e74d29c38611c12ce9bed3a26')
group=(sys.fs)
uses=()
arch=('x86_64')

cd $name-v$version
setup(){
	autoreconf -fvi
	./configure --prefix=/usr \
       --libdir=/usr/lib64/ \
       --disable-asciidoc
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

