#!/usr/bin/env bash
name='cryptsetup'
release='1'
version='2.6.1'
url='https://gitlab.com/cryptsetup/'
description='Tool to setup encrypted devices with dm-crypt'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.com/cryptsetup/cryptsetup/-/archive/v$version/cryptsetup-v$version.tar.gz")
depends=(lvm2)
makedepends=()
md5sums=('62dca8beccc359ada07cd932d5556eb6')
group=(sys.fs)
uses=()
arch=('x86_64')

cd $name-v$version
setup(){
	autoreconf -fvi
	./configure --prefix=/usr \
       --libdir=/usr/lib64/ \
       --disable-asciidoc
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

