#!/usr/bin/env bash
name='py3-tinycss2'
release='2'
version='1.3.0'
url='https://pypi.python.org/pypi/tinycss2'
description='Low-level CSS parser for Python'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://github.com/Kozea/tinycss2/archive/refs/tags/v${version}.tar.gz")
depends=(py3-webencodings)
makedepends=()
sha256sums=('e085126b6223786cb56dc711d460f7d8a9e425ad93d01bd6d5ecc08ede6bc846')
group=(dev.python)
uses=()
arch=('x86_64')

cd "tinycss2"-$version


build(){
    python -m build -nw
}

package(){
    python -m installer -d "$DESTDIR" dist/*.whl
	install -Dm644 LICENSE -t "$DESTDIR"/usr/share/licenses/$name/
}

