#!/usr/bin/env bash
name='py3-tinycss2'
release='3'
version='1.4.0'
url='https://pypi.python.org/pypi/tinycss2'
description='Low-level CSS parser for Python'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('BSD')
source=("https://github.com/Kozea/tinycss2/archive/refs/tags/v${version}.tar.gz")
depends=(py3-webencodings)
makedepends=()
sha256sums=('c8f0ea1b2bf55ceb5db60a5b4d7c151b584aade43353d2a44e8e55459ea735f4')
group=(dev.python)
uses=()
arch=('x86_64')

cd "tinycss2"-$version


build(){
    python -m build -nw
}

package(){
    python -m installer -d "$DESTDIR" dist/*.whl
	  install -Dm644 LICENSE -t "$DESTDIR"/usr/share/licenses/$name/
	  mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}

