#!/usr/bin/env bash
name='plasma-activities-stats'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description='Qt Platform Theme integration plugins for the Plasma workspaces'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-activities-stats-${version}.tar.xz")
depends=(plasma-activities kconfig qt6-base)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=('5e6ab0fe5f3c5db0de2ebe6adcd79c26170b92addc056cf35f0484fb45007d2e')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}