#!/usr/bin/env bash
name='plasma-activities-stats'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='Qt Platform Theme integration plugins for the Plasma workspaces'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-activities-stats-${version}.tar.xz")
depends=(plasma-activities kconfig qt6-base)
makedepends=(extra-cmake-modules qt6-tools)
sha256sums=('35c64f724c0550f99677f6134849decf76be47971210ca9418582ea38b480c30')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}