#!/bin/bash
name=base-files
release=1
version=1
url='https://gitlab.com/sulix/devel/sources/base-files'
description='Base system files'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.com/sulix/devel/sources/base-files/-/archive/$version/base-files-$version.zip"
        "base-files.sysconf")
md5sums=('cd0c378da701d2eb8f6ee5e2b59d55e4'
         'SKIP')
arch=(x86_64)
group=(system.base)

cd "$name-$version"

package(){
    mkdir -p ${DESTDIR}/etc/sysconf.d
    make install
    install ../base-files.sysconf  ${DESTDIR}/etc/sysconf.d/base-files
}
