#!/bin/bash
name=base-files
release=1
version=1
url='https://gitlab.com/sulix/devel/sources/base-files'
description='Base system files'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://gitlab.com/sulix/devel/sources/base-files/-/archive/$version/base-files-$version.zip")
md5sums=('3f58695b0babbca2691a8bbcadd2d131')
arch=(x86_64)
group=(system.base)

if [[ -d "$name-$version" ]] ; then
    cd "$name-$version"
fi

package(){
    make install
}
