#!/usr/bin/env bash
name='qt5-speech'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='Qt module to make text to speech and speech recognition easy'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtspeech-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base qt5-multimedia speech-dispatcher)
makedepends=()
sha256sums=('73b5ff6273a7a99d0b6b1886439488d9c8c410c0265b1dcc41974e6352643248')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtspeech-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}


