#!/usr/bin/env bash
name='libppd'
release='1'
version='2.0.0'
url='https://github.com/OpenPrinting/libppd'
description='OpenPrinting - the legacy support library for PPD files'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('Apache')
source=("https://github.com/OpenPrinting/libppd/releases/download/${version}/libppd-${version}.tar.xz")
depends=(cups cups-filters)
makedepends=(ghostscript)
md5sums=('ab889cbcdaa23689d9a425769f208da9')
group=(net.print)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--localstatedir=/var \
		--disable-mutool

}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

