#!/usr/bin/env bash
name='py3-wheel'
release='3'
version='0.42.0'
url='https://pypi.org/project/wheel/'
description='A built-package format for Python'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/pypa/wheel/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-installer py3-flit)
md5sums=('1e40a8426110603dd90377b9c330d3c3')
group=(dev.python)
uses=()
arch=('x86_64')

cd wheel-$version

prepare(){
: #  rm -r src/wheel/vendored
}

build(){
    python3 -m build
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
}

