#!/usr/bin/env bash
name='py3-wheel'
release='4'
version='0.43.0'
url='https://pypi.org/project/wheel/'
description='A built-package format for Python'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://github.com/pypa/wheel/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=(py3-installer py3-flit)
sha256sums=('23060d7cc8afafc2930554624b4bae7d58031830672048622c926675ab91e3b0')
group=(dev.python)
uses=()
arch=('x86_64')

cd wheel-$version

prepare(){
: #  rm -r src/wheel/vendored
}

build(){
    python3 -m build
}

package(){
    python3 -m installer --destdir="$DESTDIR" dist/*.whl
}

