#!/usr/bin/env bash
name='py3-wheel'
release='1'
version='0.38.4'
url='https://pypi.org/project/wheel/'
description='A built-package format for Python'
email='parduscix@yandex.ru'
maintainer='sulincix'
license=('GPLv3')
source=("https://files.pythonhosted.org/packages/a2/b8/6a06ff0f13a00fc3c3e7d222a995526cbca26c1ad107691b6b1badbbabf1/wheel-$version.tar.gz")
depends=(python)
makedepends=()
md5sums=('83bb4e7bd4d687d398733f341a64ab91')
group=(dev.python)
uses=()
arch=('x86_64')

cd wheel-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}

