#!/usr/bin/env bash
name='qt5-quickcontrols2'
release='2'
version='5.15.14'
url='https://www.qt.io/'
description='Next generation user interface controls based on Qt Quick'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtquickcontrols2-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base qt5-declarative qt5-graphicaleffects)
makedepends=()
sha256sums=('25ee6bffabb63d9612e7f544e5e1cab5d1776fa49c47aa3c9a02eb56573ec982')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtquickcontrols2-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}
