#!/usr/bin/env bash
name='libxfce4util'
release='3'
version='4.20.0'
_version='4.20'
url='https://www.xfce.org/'
description='Basic utility non-GUI functions for Xfce'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/libxfce4util/${_version}/libxfce4util-${version}.tar.bz2")
depends=(glib)
makedepends=(gobject-introspection intltool vala)
sha256sums=('21493f9c9995a282823db93839f6b9f06ae31edb094191ba9acf04d932a2b592')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

