#!/usr/bin/env bash
name='libxfce4util'
release='4'
version='4.20.1'
_version='4.20'
url='https://www.xfce.org/'
description='Basic utility non-GUI functions for Xfce'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/libxfce4util/${_version}/libxfce4util-${version}.tar.bz2")
depends=(glib)
makedepends=(gobject-introspection intltool vala)
sha256sums=('84bfc4daab9e466193540c3665eee42b2cf4d24e3f38fc3e8d1e0a2bebe3b8f1')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sysconfdir=/etc \
        --sbindir=/usr/bin \
        --localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

