#!/usr/bin/env bash
name='flatpak-kcm'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='Flatpak Permissions Management KCM'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/plasma/${version}/flatpak-kcm-${version}.tar.xz")
depends=(flatpak)
makedepends=(extra-cmake-modules)
sha256sums=('2a203e7292571ef1373785c2449c503be15408dbdf0a7a59d7e99d8e9def1a81')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
