#!/usr/bin/env bash
name='flatpak-kcm'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='Flatpak Permissions Management KCM'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/plasma/${version}/flatpak-kcm-${version}.tar.xz")
depends=(flatpak kitemmodels kcmutils)
makedepends=(extra-cmake-modules)
sha256sums=('3f1858707124305bc23186f334bbaf63c5a2bc2d8975eaff1274d402e611b8b1')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
