#!/usr/bin/env bash
name='flatpak-kcm'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description='Flatpak Permissions Management KCM'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/plasma/${version}/flatpak-kcm-${version}.tar.xz")
depends=(flatpak)
makedepends=(extra-cmake-modules)
sha256sums=('deee5c35cc531c092e4898e6bc95089c33b3279cf598f93446363c6d80fb7121')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
