#!/usr/bin/env bash
name='lxterminal'
release='1'
version='0.4.0-2'
url='https://wiki.lxde.org/en/LXTerminal'
description='Lightweight vte-based tabbed terminal emulator for LXDE '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://salsa.debian.org/lxde-team/lxterminal/-/archive/debian/0.4.0-2/lxterminal-debian-0.4.0-2.tar.gz")
depends=(vte3 gtk3)
makedepends=()
md5sums=('9bd60448006d310575b083b3fa0e8559')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-debian-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ --enable-gtk3 
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

