#!/usr/bin/env bash
name='lxterminal'
release='2'
version='0.4.1'
url='https://wiki.lxde.org/en/LXTerminal'
description='Lightweight vte-based tabbed terminal emulator for LXDE '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxterminal/archive/refs/tags/$version.tar.gz")
depends=(vte3 gtk3 dejavu)
makedepends=()
sha256sums=('d5da0646e20ad2be44ef69a9d620be5f1ec43b156dc585ebe203dd7b05c31d88')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

export CC="clang"
export CXX="clang++"


setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ --enable-gtk3
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

