#!/usr/bin/env bash
name='xproto'
release='1'
version='7.0.31'
url='https://example.org'
description='Package description missing'
email='bayramk@gmail.com'
maintainer='bayramkarahan'
license=('GPLv3')
source=("https://www.x.org/archive/individual/proto/xproto-$version.tar.gz")
depends=()
makedepends=()
md5sums=('04b925bf9e472c80f9212615cd684f1e')
group=(x11.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

