#!/usr/bin/env bash
name='kunitconversion'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Support for unit conversion'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kunitconversion-${version}.tar.xz")
depends=(ki18n qt6-base)
makedepends=(doxygen extra-cmake-modules qt6-tools)
sha256sums=('c88494ac8971c25dc6bc9a1119ea44c0f8eda44e9d2883ade9aca651e9968d5e')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

