#!/usr/bin/env bash
name='kunitconversion'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Support for unit conversion'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kunitconversion-${version}.tar.xz")
depends=(ki18n qt6-base)
makedepends=(doxygen extra-cmake-modules qt6-tools)
sha256sums=('c7d521423c7443d305803e2f606e8dff58fa9e1c7c73b09bce8dd3862e992fe4')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

