#!/usr/bin/env bash
name='kunitconversion'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Support for unit conversion'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kunitconversion-${version}.tar.xz")
depends=(qt5-base)
makedepends=(doxygen extra-cmake-modules qt5-tools ki18n)
md5sums=('c620b57ca8c18a4135c4b8aee02327b4')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

