#!/usr/bin/env bash
name='plasma-nm'
release='3'
version='6.1.5'
url='https://kde.org/plasma-desktop/'
description='Plasma applet written in QML for managing network connections'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://download.kde.org/stable/plasma/$version/plasma-nm-$version.tar.xz"
        'no-kwallet.patch')
depends=(kcmutils kcolorscheme kcompletion kconfig kcoreaddons kdbusaddons kdeclarative ki18n kio kirigami knotifications kquickcharts
         ksvg kwidgetsaddons kwindowsystem libplasma modemmanager-qt networkmanager-qt prison qca qcoro-qt6 qt6-base qt6-declarative solid)
makedepends=(extra-cmake-modules)
sha256sums=('cb04ddaf00d728ea0b4b5d108b3389d462ce5078726f8b655f38de330eeb21f5' 'SKIP')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

