#!/usr/bin/env bash
name='frameworkintegration'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Framework providing components to allow applications to integrate with a KDE Workspace'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/frameworkintegration-${version}.tar.xz")
depends=(appstream kconfig kconfigwidgets ki18n kiconthemes knewstuff 	knotifications kpackage kwidgetsaddons qt5-base)
makedepends=(extra-cmake-modules)
md5sums=('536b44079250ad3f785ac1d00c1d9d81')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
