#!/usr/bin/env bash
name='frameworkintegration'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Framework providing components to allow applications to integrate with a KDE Workspace'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/frameworkintegration-${version}.tar.xz")
depends=(appstream ki18n kiconthemes knewstuff knotifications kwidgetsaddons qt6-base)
makedepends=(extra-cmake-modules)
sha256sums=('890101854bbbb3937d321f2ac35b2a0a8f3ce833422297ddda59bda8c8cac69d')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
