#!/usr/bin/env bash
name='linux-headers'
release='1'
version='6.1.4'
url='https://cdn.kernel.org/pub/linux/kernel/'
description='Linux kernel headers'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv2')
source=()
depends=( )
makedepends=(mklinux)
md5sums=('3de364bdbacd2115950cc3dd94157ab6')
uses=()
arch=('x86_64')
group=(sys.kernel)

package(){
    # install headers (archlinux kerhel config used)
    ALLOWROOT=1 mklinux -f -o $DESTDIR -v $version -y 1 --no-build \
        -c "https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/linux/trunk/config"
}

