#!/usr/bin/env bash
name='linux-headers'
release='9'
version='6.15'
url='https://cdn.kernel.org/pub/linux/kernel/'
description='Linux kernel headers'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv2')
source=()
depends=( )
makedepends=(mklinux)
md5sums=('3de364bdbacd2115950cc3dd94157ab6')
uses=()
arch=('x86_64')
group=(sys.kernel)

package(){
    # install kernel (archlinux kernel config used)
    ALLOWROOT=1 mklinux -f -o $DESTDIR -t linux -v $version -y 1 --no-build \
       -c "https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/raw/main/config"
    # symlink for musl
    mkdir -p $DESTDIR/usr/include/musl
    for name in $(ls $DESTDIR/usr/include/ | grep -v musl) ; do
        ln -s ../$name $DESTDIR/usr/include/musl/$name
    done
}

