#!/usr/bin/env bash
name='cinnamon-settings-daemon'
release='1'
version='5.8.1'
url='https://github.com/linuxmint/cinnamon-settings-daemon'
description='The Cinnamon Settings daemon'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/linuxmint/cinnamon-settings-daemon/archive/refs/tags/${version}.tar.gz")
depends=(cinnamon-desktop colord dbus-glib libcanberra cups libgnomekbd libgudev libnotify librsvg libwacom nss polkit upower)
makedepends=(meson ninja xf86-input-wacom)
md5sums=('bb03d40c4c83297c3dcfe563ebdf9bd5')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

