#!/usr/bin/env bash
name='cinnamon-settings-daemon'
release='3'
version='6.2.0'
url='https://github.com/linuxmint/cinnamon-settings-daemon'
description='The Cinnamon Settings daemon'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://github.com/linuxmint/cinnamon-settings-daemon/archive/refs/tags/${version}.tar.gz")
depends=(cinnamon-desktop colord dbus-glib libcanberra cups libgnomekbd libgudev libnotify librsvg libwacom nss polkit upower)
makedepends=(meson ninja xf86-input-wacom)
sha256sums=('ecb360017284cdf8a5776a64175ac69f730790d3031f1f4cabc5f8c52660a498')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

