#!/usr/bin/env bash
name='libnl'
release='2'
version='3.8.0'
_version='3_8_0'
url='https://github.com/thom311'
description='Netlink Library Suite '
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/thom311/libnl/releases/download/libnl${_version}/libnl-${version}.tar.gz")
depends=()
makedepends=()
md5sums=('86a4245274aae0a1cfdbd85ce88eede9')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --sysconfdir=/etc \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
    # fix terminal cursor issue
    echo -e "\033[?25h"
}

