#!/usr/bin/env bash
name='libgpg-error'
release='1'
version='1.46'
url='https://www.gnupg.org/'
description='Support library for libgcrypt'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=(https://www.gnupg.org/ftp/gcrypt/libgpg-error/${name}-${version}.tar.bz2{,.sig})
depends=()
makedepends=()
md5sums=('db41efe5aba3baad6cf266fea720095d' 'SKIP')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -vfi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make DESTDIR=$DESTDIR install $jobs
}

