#!/usr/bin/env bash
name='libgpg-error'
release='3'
version='1.51'
url='https://www.gnupg.org/'
description='Support library for libgcrypt'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=(https://www.gnupg.org/ftp/gcrypt/libgpg-error/${name}-${version}.tar.bz2)
depends=(glibc )
makedepends=()
sha256sums=('be0f1b2db6b93eed55369cdf79f19f72750c8c7c39fc20b577e724545427e6b2')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -vfi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make DESTDIR=$DESTDIR install $jobs
}

