#!/usr/bin/env bash
name='cinnamon-screensaver'
release='2'
version='6.0.0'
url='https://github.com/linuxmint/cinnamon-screensaver'
description='Screensaver designed to integrate well with the Cinnamon desktop.'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/linuxmint/cinnamon-screensaver/archive/refs/tags/${version}.tar.gz")
depends=(accountsservice cinnamon-desktop libgnomekbd py3-cairo py3-pygobject py3-setproctitle py3-xapp xapp)
makedepends=(gobject-introspection meson)
md5sums=('5ed5b247b59c5400b073b7fbed811e82')
group=(cinnamon.base)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    meson setup build --prefix=/usr \
    	--libdir=/usr/lib64/ \
    	-Ddefault_library=both 
		#-Dlocking=false #$name-$version
}

build () {
    ninja -C build $jobs
}

package () {
    DESTDIR="${DESTDIR}" ninja -C build install $jobs
    
    rm -f ${DESTDIR}/usr/bin/cinnamon-screensaver-command
    rm -f ${DESTDIR}/usr/bin/cinnamon-screensaver

    ln -s ../../usr/share/cinnamon-screensaver/cinnamon-screensaver-command.py ${DESTDIR}/usr/bin/cinnamon-screensaver-command
    ln -s ../../usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py ${DESTDIR}/usr/bin/cinnamon-screensaver
}
