#!/usr/bin/env bash
name='lxhotkey'
release='2'
version='0.1.2'
url='https://github.com/lxde/lxhotkey/'
description='LXDE hotkey'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxhotkey/archive/refs/tags/$version.tar.gz")
depends=(libfm libexif)
makedepends=()
sha256sums=('f32686d298d86ae1e97c9e3d27ba1f01b6a0f17dbbbbd67dfbf82e7c0080c592')
group=(lxde.base)
uses=()
arch=('x86_64')

export CC=clang

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --with-gtk=3
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

