#!/usr/bin/env bash
name='lxhotkey'
release='1'
version='0.1.1'
url='https://github.com/lxde/lxhotkey/'
description='LXDE hotkey'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxhotkey/archive/refs/tags/$version.tar.gz")
depends=(libfm)
makedepends=()
sha256sums=('c5a9fa01960c1d0d92b1fb6392bc73db7793c7f889ca716c41a46a434bcfff57')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --with-gtk=3
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

