#!/usr/bin/env bash
name='lxhotkey'
release='1'
version='0.1.1'
url='https://github.com/lxde/lxhotkey/'
description='LXDE hotkey'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxhotkey/archive/refs/tags/0.1.1.tar.gz")
depends=(libfm)
makedepends=()
md5sums=('2e21ba7d8d318652000b083b49d8de5f')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --with-gtk=3
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

