#!/usr/bin/env bash
name='iniparser'
release='1'
version='4.1'
url='https://github.com/ndevilla/iniparser'
description='A free stand-alone ini file parsing library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/ndevilla/iniparser/archive/refs/tags/v$version.tar.gz")
depends=(chrpath)
makedepends=()
md5sums=('e43b722c71b399ab17c329c04dbdf1d7')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

build(){
    make $jobs
}

package(){
  install -Dm0644 src/iniparser.h "${DESTDIR}"/usr/include/iniparser.h
  install -Dm0644 src/dictionary.h "${DESTDIR}"/usr/include/dictionary.h
  install -Dm0644 libiniparser.so.1 "$DESTDIR"/usr/lib/libiniparser.so.1
  install -Dm0644 LICENSE "${DESTDIR}"/usr/share/licenses/iniparser/LICENSE
  ln -sf libiniparser.so.1 "${DESTDIR}"/usr/lib/libiniparser.so
  chrpath -d "${DESTDIR}"/usr/lib/libiniparser.so

}

