#!/usr/bin/env bash
name='font-bh-lucidatypewriter-75dpi'
release='1'
version='1.0.3'
url='https://gitlab.freedesktop.org/xorg/font/bh-lucidatypewriter-75dpi'
description='X.Org Bigelow & Holmes Lucida bitmap fonts '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xorg/font/bh-lucidatypewriter-75dpi/-/archive/font-bh-lucidatypewriter-75dpi-$version/bh-lucidatypewriter-75dpi-font-bh-lucidatypewriter-75dpi-$version.tar.gz")
depends=(font-util)
makedepends=()
md5sums=('90d47411a152573572b8e5082fa73cf8')
group=(media.fonts)
uses=()
arch=('x86_64')

cd bh-lucidatypewriter-75dpi-$name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

