#!/bin/bash
name=bash
version=5.1
release=1
depends=(readline ncurses)
source=(https://ftp.gnu.org/gnu/$name/$name-$version.tar.gz)
md5sums=(bb91a17fd6c9032c26d0b2b78b50aff5)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/lib64 \
        --bindir=/bin \
  	    --with-curses \
        --enable-readline \
        --without-bash-malloc
}
build(){
    make -j$(nproc)
}

package(){
    make DESTDIR=${DESTDIR} install
}
