#!/usr/bin/env bash
name='kirigami-addons'
release='4'
version='1.10.0'
url='https://invent.kde.org/libraries/kirigami-addons'
description='Add-ons for the Kirigami framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/kirigami-addons/kirigami-addons-$version.tar.xz")
depends=(kirigami qt6-multimedia)
makedepends=(extra-cmake-modules ki18n)
sha256sums=('c98f92bf7c452e12f6dc403404215413db3959fe904ad830ead0db6bb09b3d11')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

