#!/usr/bin/env bash
name='lxinput'
release='2'
version='0.3.6'
url='https://github.com/lxde/lxinput'
description='LXDE keyboard and mouse configuration tool '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxinput/archive/refs/tags/$version.tar.gz")
depends=(gtk3)
makedepends=()
sha256sums=('2f15c2a17f970afb152cbd024503da26c1e15135e76e9f516e0ca97e909d6c37')
group=(lxde.base)
uses=()
arch=('x86_64')

export CC=clang

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ --enable-gtk3
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

