#!/usr/bin/env bash
name='lxinput'
release='1'
version='0.3.5'
url='https://github.com/lxde/lxinput'
description='LXDE keyboard and mouse configuration tool '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://salsa.debian.org/lxde-team/lxinput/-/archive/debian/$version-1/lxinput-debian-$version-1.tar.gz")
depends=(gtk3)
makedepends=()
sha256sums=('b78baa9af84ca671b1e2b16387f4d6e452860a1803203fa844f35b93ec97c054')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-debian-$version-1

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ --enable-gtk3 
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

