#!/usr/bin/env bash
name='modemmanager-qt'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Qt wrapper for modemmanager API'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/modemmanager-qt-${version}.tar.xz")
depends=(modemmanager qt6-base )
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('fc45dcd8ada243baf7900099062f312b677bf694f88f36746d534afe907bf8f3')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

