#!/usr/bin/env bash
name='modemmanager-qt'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Qt wrapper for modemmanager API'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/modemmanager-qt-${version}.tar.xz")
depends=(modemmanager qt5-base )
makedepends=(extra-cmake-modules qt5-tools doxygen)
md5sums=('9319b8873ab28ca425182a1fe0c9afc5')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

