#!/usr/bin/env bash
name='gnome-backgrounds'
release='2'
version='45.0'
url='https://gitlab.gnome.org/GNOME/gnome-backgrounds'
description='Default wallpaper set for GNOME'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL-2.0-or-later' 'CC-BY-2.0' 'CC-BY-SA-2.0' 'CC-BY-SA-3.0')
source=("https://download.gnome.org/sources/gnome-backgrounds/${version%.*}/gnome-backgrounds-${version}.tar.xz")
depends=()
makedepends=()
md5sums=('79a429a1aaa46aa94fecd1923e9be0b1')
group=(x11.themes)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
    	--libdir=/usr/lib64/ \
    	-Ddefault_library=both
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}


