#!/usr/bin/env bash
name='gnome-backgrounds'
release='1'
version='44.0'
url='https://gitlab.gnome.org/GNOME/gnome-backgrounds'
description='Default wallpaper set for GNOME'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL-2.0-or-later' 'CC-BY-2.0' 'CC-BY-SA-2.0' 'CC-BY-SA-3.0')
source=("https://download.gnome.org/sources/gnome-backgrounds/${version%.*}/gnome-backgrounds-${version}.tar.xz")
depends=()
makedepends=()
md5sums=('3364a0479babd85f333c1e8a635330b2')
group=(x11.themes)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr
	#meson compile -C build
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}


