#!/usr/bin/env bash
name='seatd'
release='2'
version='0.8.0'
url='https://sr.ht/~kennylevinsen/seatd'
description='Minimal seat management daemon and universal library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/kennylevinsen/seatd/archive/refs/tags/$version.tar.gz"
        "seatd.initd")
depends=()
makedepends=()
md5sums=('7c687ded0fa4db2352a8c9a6b41abca7'
         'SKIP')
group=(sys.auth)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    install -m755 -D ../seatd.initd "$DESTDIR"/etc/init.d/seatd
}

