#!/usr/bin/env bash
name='kglobalacceld'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='Daemon providing Global Keyboard Shortcut (Accelerator) functionality'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kglobalacceld-${version}.tar.xz")
depends=(kconfig kcoreaddons kcrash kdbusaddons kglobalaccel kio kjobwidgets kservice kwindowsystem libX11
         libxcb qt6-base xcb-util-keysyms)
makedepends=(extra-cmake-modules)
sha256sums=('a712d1f7a86960292feb6979fe2c92f2e7d5cfbcd107f4efe3979e1a4c32cd73')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
