#!/usr/bin/env bash
name='kcompletion'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Text completion helpers and widgets'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcompletion-${version}.tar.xz")
depends=(kconfig kcodecs kwidgetsaddons qt6-base)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('6d06881ff2ece4c29df5c3cbe3700cb5e3425064686a667e84f06f2a5732a1c5')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


