#!/usr/bin/env bash
name='kcompletion'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Text completion helpers and widgets'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcompletion-${version}.tar.xz")
depends=(kconfig kcodecs kwidgetsaddons qt6-base)
makedepends=(extra-cmake-modules qt6-tools doxygen)
sha256sums=('778af80e5015f49ce1e1dde6180bf51167a1f5dfb12d07c73216b5fa804eedf9')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


