#!/usr/bin/env bash
name='libbsd'
release='1'
version='0.11.7'
url='https://libbsd.freedesktop.org/wiki/'
description='Library to provide useful functions commonly found on BSD systems'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://libbsd.freedesktop.org/releases/libbsd-$version.tar.xz")
depends=()
makedepends=()
md5sums=('2c5e63b5bb7771bbe4f572c7788e0bb8')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make
}

package(){
    make install
}

