#!/usr/bin/env bash
name='libbsd'
release='2'
version='0.12.2'
url='https://libbsd.freedesktop.org/wiki/'
description='Library to provide useful functions commonly found on BSD systems'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://libbsd.freedesktop.org/releases/libbsd-$version.tar.xz")
depends=()
makedepends=()
sha256sums=('b88cc9163d0c652aaf39a99991d974ddba1c3a9711db8f1b5838af2a14731014')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make
}

package(){
    make install
}

