#!/usr/bin/env bash
name='konsole'
release='4'
version='24.08.2'
url='https://kde.org/applications/system/konsole'
description="KDE's terminal emulator"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL' 'GPL' 'FDL')
source=("https://download.kde.org/stable/release-service/${version}/src/konsole-${version}.tar.xz")
depends=(kpty kparts knewstuff knotifyconfig)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('ae72ca4e2d9123b9bada99d2d3b01398ff5082b549b38579cf9aa94c2bffd719')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DENABLE_PLUGIN_SSHMANAGER=ON \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

