#!/usr/bin/env bash
name='konsole'
release='2'
version='24.02.2'
url='https://kde.org/applications/system/konsole'
description="KDE's terminal emulator"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL' 'GPL' 'FDL')
source=("https://download.kde.org/stable/release-service/${version}/src/konsole-${version}.tar.xz")
depends=(kpty kparts knewstuff knotifyconfig)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=('66467e336536d7df5c12bcad31a3ef0a2150c40351d87677047a40eae440ee2f')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DENABLE_PLUGIN_SSHMANAGER=ON \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

