#!/usr/bin/env bash
name='kactivitymanagerd'
release='2'
version='6.0.0'
url='https://kde.org/plasma-desktop'
description="System service to manage user's activities and track the usage patterns"
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/kactivitymanagerd-${version}.tar.xz")
depends=(kconfig kcoreaddons kcrash kglobalaccel ki18n kio kservice kwindowsystem kxmlgui qt6-base)
makedepends=(extra-cmake-modules boost)
sha256sums=('9210b391c329018e45ac65c6e3a77f64532f3e0176c589bcd76460c2030102fc')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
