#!/usr/bin/env bash
name='ksvg'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Components for handling SVGs'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/ksvg-${version}.tar.xz")
depends=(kconfig kcoreaddons kguiaddons qt6-base qt6-svg)
makedepends=(extra-cmake-modules kirigami qt6-declarative qt6-tools)
sha256sums=('bbdf7c786c959707cd9c67c04a67e51a15dbcdd6eff7ab52b03c09544e66f184')
group=(kde.framework)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
