#!/usr/bin/env bash
name='ksvg'
release='3'
version='6.5.0'
url='https://community.kde.org/Frameworks'
description='Components for handling SVGs'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/ksvg-${version}.tar.xz")
depends=(kconfig kcoreaddons kguiaddons qt6-base qt6-svg)
makedepends=(extra-cmake-modules kirigami qt6-declarative qt6-tools)
sha256sums=('ae2024bd4d7e6950c92b5924deced5d55b6101749d635799b24fedac60cb26cd')
group=(kde.framework)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
