#!/usr/bin/env bash
name='ksvg'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Components for handling SVGs'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('GPLv3')
source=("https://download.kde.org/stable/frameworks/${version%.*}/ksvg-${version}.tar.xz")
depends=(kconfig kcoreaddons kguiaddons qt6-base qt6-svg)
makedepends=(extra-cmake-modules kirigami qt6-declarative qt6-tools)
sha256sums=('0eab2ba532906b612afee2fbfa802a88d7f4570d4c322972cb6debd320075c10')
group=(kde.framework)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
