#!/usr/bin/env bash
name='libunistring'
release='2'
version='1.3'
url='https://www.gnu.org/software/libunistring/'
description='Library for manipulating Unicode strings and C strings'
email=' parduscix@yandex.ru'
maintainer=' sulincix'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/libunistring/libunistring-$version.tar.xz")
depends=( )
makedepends=(gperf)
sha256sums=('f245786c831d25150f3dfb4317cda1acc5e3f79a5da4ad073ddca58886569527')
arch=('x86_64')
group=(dev.libs)

cd $name-$version

prepare(){
    # dummy makeinfo
    > $HOME/makeinfo
    chmod 755 $HOME/makeinfo
}

setup(){
    autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64
}

build(){
    make $jobs
}

package(){
    make install $jobs
    ln -s libunistring.so ${DESTDIR}/usr/lib64/libunistring.so.2
    ln -s libunistring.so ${DESTDIR}/usr/lib64/libunistring.so.2.2.0
}

