#!/usr/bin/env bash
name='libxkbfile'
release='1'
version='1.1.2'
url='https://example.org'
description='Package libxkbfile'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libxkbfile-$version.tar.gz")
depends=(libX11 xorgproto)
makedepends=()
md5sums=('17b29e91233a7d5220c2d80961c903b4')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

