#!/usr/bin/env bash
name='libva'
release='5'
version='2.22.0'
url='https://github.com/intel/libva'
description='An implementation for VA-API (Video Acceleration API)'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/intel/libva/archive/$version.tar.gz")
depends=(libdrm)
makedepends=()
sha256sums=('467c418c2640a178c6baad5be2e00d569842123763b80507721ab87eb7af8735')
group=(media.libs)
uses=(wayland x11)
arch=('x86_64')
x11_depends=(libX11 libXext libXfixes)
wayland_depends=(wayland)

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddefault_library=both \
        -Db_lto=true \
        -Dwith_glx=no \
        -Dwith_x11=$(use_opt x11 yes no) \
        -Dwith_wayland=$(use_opt wayland yes no)
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/etc/
    echo "LIBVA_MESSAGING_LEVEL=1" > ${DESTDIR}/etc/libva.conf
}

