#!/usr/bin/env bash
name='libva'
release='1'
version='2.17.0'
url='https://github.com/intel/libva'
description='An implementation for VA-API (Video Acceleration API)'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/intel/libva/archive/$version.tar.gz")
depends=(libdrm)
makedepends=()
md5sums=('0ac769fc61c2f7c1dd0916f12794549d')
group=(media.libs)
uses=(wayland x11)
arch=('x86_64')
x11_depends=(libXext libXfixes)

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Db_lto=true \
        -Dwith_glx=no \
        -Dwith_x11=$(use_opt x11 yes no) \
        -Dwith_wayland=$(use_opt wayland yes no)
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    echo "LIBVA_MESSAGING_LEVEL=1" > ${DESTDIR}/etc/libva.conf
}

