#!/usr/bin/env bash
name='ark'
release='2'
version='24.02.2'
url='https://kde.org/applications/utilities/org.kde.ark'
description='Graphical file compression/decompression utility with support for multiple formats'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.kde.org/stable/release-service/${version}/src/ark-${version}.tar.xz")
depends=(kio libarchive kparts)
makedepends=()
sha256sums=('06374f5c7c2aee7a93c04bfd7b6b3baaeab3962e8277c9087fea54ba9805bdce')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64

}

build () {
    	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}
