#!/usr/bin/env bash
name='ark'
release='5'
version='25.08.1'
url='https://kde.org/applications/utilities/org.kde.ark'
description='Graphical file compression/decompression utility with support for multiple formats'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.kde.org/stable/release-service/${version}/src/ark-${version}.tar.xz")
depends=(kio libarchive kparts kfilemetadata kpty)
makedepends=()
sha256sums=('2febbab11881e3d32f44c4107041d53b1d5353c8c95c4d6536ab57de0958f96f')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64

}

build () {
    	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}
