#!/usr/bin/env bash
name='ark'
release='1'
version='23.08.2'
url='https://kde.org/applications/utilities/org.kde.ark'
description='Graphical file compression/decompression utility with support for multiple formats'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.kde.org/stable/release-service/${version}/src/ark-${version}.tar.xz")
depends=(kio libarchive kparts)
makedepends=()
md5sums=('aac8020d47081acbbf5178f5d13eb85c')
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=MinSizeRel \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib

}

build () {
    	cmake --build build
}

package () {
    DESTDIR="$DESTDIR" cmake --install build
}
