#!/usr/bin/env bash
name='xfce4-terminal'
release='3'
version='1.1.3'
url='https://docs.xfce.org/apps/terminal/start'
description='A modern terminal emulator primarily for the Xfce desktop environment'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/apps/xfce4-terminal/${version%.*}/xfce4-terminal-${version}.tar.bz2")
depends=(libxfce4ui vte3)
makedepends=(intltool)
sha256sums=('214dd588d441b69f816009682a3bb4652cc19bed7ea64b612a12f097417b3d45')
group=(xfce.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
      --libdir=/usr/lib64/ \
      --sysconfdir=/etc \
    	--libexecdir=/usr/libexec \
		  --localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

