#!/usr/bin/env bash
name='libxfce4ui'
release='3'
version='4.20.0'
_version='4.20'
url='https://www.xfce.org/'
description='Widgets library for the Xfce desktop environment'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/libxfce4ui/${_version}/libxfce4ui-${version}.tar.bz2")
depends=(gtk3 xfconf libxfce4util)
makedepends=(gobject-introspection intltool vala)
sha256sums=('75e8996984f20375aadecd5c16f5147c211ed0bd26d7861ab0257561eb76eaee')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--localstatedir=/var
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}

