#!/usr/bin/env bash
name='kirigami-addons'
release='1'
version='1.1.0'
url='https://invent.kde.org/libraries/kirigami-addons'
description='Add-ons for the Kirigami framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/kirigami-addons/kirigami-addons-$version.tar.xz")
depends=(kirigami qt6-multimedia)
makedepends=(extra-cmake-modules ki18n)
sha256sums=('8ef352499139616b3142a6d7a92ab23749c568403ece8d854f064a941d085536')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

