#!/usr/bin/env bash
name='kirigami-addons'
release='3'
version='1.5.0'
url='https://invent.kde.org/libraries/kirigami-addons'
description='Add-ons for the Kirigami framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/kirigami-addons/kirigami-addons-$version.tar.xz")
depends=(kirigami qt6-multimedia)
makedepends=(extra-cmake-modules ki18n)
sha256sums=('f9dfd191022b633ea3348f84730d7158a159dfe49668dba0a9e9bd678ac44e54')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

