#!/usr/bin/env bash
name='kirigami-addons'
release='2'
version='1.4.0'
url='https://invent.kde.org/libraries/kirigami-addons'
description='Add-ons for the Kirigami framework'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/kirigami-addons/kirigami-addons-$version.tar.xz")
depends=(kirigami qt6-multimedia)
makedepends=(extra-cmake-modules ki18n)
sha256sums=('56e3ceb52055b5603320ea08b27d3673d32a391a8d58646d998227d8b51f0a93')
group=(kde.plasma)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

