#!/usr/bin/env bash
name='py3-requests'
release='1'
version='2.31.0'
url='https://requests.readthedocs.io/'
description='Python HTTP for Humans'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('Apache')
source=("https://github.com/psf/requests/archive/refs/tags/v${version}.tar.gz")
depends=()
makedepends=(py3-build py3-wheel py3-setuptools)
md5sums=('fb734df6b273e30f68f9346dbf72aa34')
group=(dev.python)
uses=()
arch=('x86_64')

cd "requests"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}


