#!/usr/bin/env bash
name='libgudev'
release='2'
version='238'
url='https://example.org'
description='GObject bindings for libudev'
email='bk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/libgudev/-/archive/$version/libgudev-$version.tar.gz")
depends=(glib eudev)
makedepends=()
md5sums=('c85736d109526690bf6e2845616f6809')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

