#!/usr/bin/env bash
name='oxygen-sounds'
release='2'
version='5.27.11'
url='https://kde.org/plasma-desktop'
description='The Oxygen Sound Theme'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/oxygen-sounds-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules)
sha256sums=('6fa249c55a51941e023b982e20279e594279e216c53e065a928de6b4089df1de')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
