#!/usr/bin/env bash
name='oxygen-sounds'
release='1'
version='5.27.9'
url='https://kde.org/plasma-desktop'
description='The Oxygen Sound Theme'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/oxygen-sounds-${version}.tar.xz")
depends=()
makedepends=(extra-cmake-modules)
md5sums=('f6c770e3433516628c2f805ae5d32bbd')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}
