#!/usr/bin/env bash
name='libopenmpt'
release='1'
version='0.6.9'
url='https://lib.openmpt.org/libopenmpt/'
description='Library to decode tracked music files (modules) '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-$version+release.autotools.tar.gz")
depends=(mpg123 libpulse libsndfile libogg libvorbis portaudio flac)
makedepends=()
md5sums=('cad469bef72baeefc43a651dbe9b225c')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version+release.autotools

setup(){
  autoreconf -fiv	
   ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

