#!/usr/bin/env bash
name='libopenmpt'
release='2'
version='0.7.1'
url='https://lib.openmpt.org/libopenmpt/'
description='Library to decode tracked music files (modules) '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://lib.openmpt.org/files/libopenmpt/src/libopenmpt-$version+release.autotools.tar.gz")
depends=(mpg123 libpulse libsndfile libogg libvorbis portaudio flac)
makedepends=()
md5sums=('82268ef9f79a6b99c7229f7486054ad2')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version+release.autotools

setup(){
  autoreconf -fiv	
   ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

