#!/usr/bin/env bash
name='shared-mime-info'
release='2'
version='2.4'
url='https://gitlab.freedesktop.org/xdg/shared-mime-info'
description='The Shared MIME-info Database specification'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/${version}/shared-mime-info-${version}.tar.gz"
        shared-mime-info.sysconf)
depends=(libxml2)
makedepends=()
md5sums=('aac56db912b7b12a04fb0018e28f2f36'
         'SKIP')
group=(x11.misc)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    mkdir -p ${DESTDIR}/etc/sysconf.d/
    install ../shared-mime-info.sysconf ${DESTDIR}/etc/sysconf.d/shared-mime-info
}

