#!/usr/bin/env bash
name='shared-mime-info'
release='1'
version='2.2'
url='https://gitlab.freedesktop.org/xdg/shared-mime-info'
description='The Shared MIME-info Database specification'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.2/shared-mime-info-$version.tar.gz")
depends=()
makedepends=()
md5sums=('06cb9e92e4211dc53fd52b7bfd586c78')
group=(x11.misc)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

