#!/usr/bin/env bash
name='libXxf86dga'
release='1'
version='1.1.6'
url='https://gitlab.freedesktop.org/xorg/lib/libXxf86dga.git/'
description='X.Org Xxf86dga library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXxf86dga-$version.tar.gz")
depends=()
makedepends=()
md5sums=('f88c63c9be40f3a51d9c22159858c2d5')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

