#!/usr/bin/env bash
name='lxtask'
release='1'
version='0.1.10'
url='https://wiki.lxde.org/en/LXTask'
description='LXDE Task manager'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxtask/archive/refs/tags/$version.tar.gz")
depends=(gtk3)
makedepends=()
sha256sums=('a3ea7f983396d816d8057eea8974e3cc12a870e658f71e15dec41c863e50f5d9')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ --enable-gtk3
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

