#!/usr/bin/env bash
name='lxtask'
release='1'
version='0.1.10'
url='https://wiki.lxde.org/en/LXTask'
description='LXDE Task manager'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxtask/archive/refs/tags/0.1.10.tar.gz")
depends=()
makedepends=()
md5sums=('9dae6bb75181e3b6f1421cd7325d494d')
group=(lxde.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ --enable-gtk3
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

