#!/usr/bin/env bash
name='lxtask'
release='2'
version='0.1.12'
url='https://wiki.lxde.org/en/LXTask'
description='LXDE Task manager'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://github.com/lxde/lxtask/archive/refs/tags/$version.tar.gz")
depends=(gtk3)
makedepends=()
sha256sums=('f9d97ebdd8402fe7d9533b6173d0f553d5f9987f5c2885f7d2ee070e80300ab3')
group=(lxde.base)
uses=()
arch=('x86_64')

export CC=clang

cd $name-$version

setup(){
	autoreconf -fvi
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ --enable-gtk3
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

