#!/usr/bin/env bash
name='qt6-networkauth'
release='2'
version='6.7.0'
url='https://www.qt.io/'
description='Network authentication module'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtnetworkauth-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(cmake ninja)
sha256sums=('993105616ff0223d3d826e2a497440035721c6e1acdae232935fae3bcfa74a45')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtnetworkauth-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_INSTALL_PREFIX=/usr 

}


build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}
