#!/usr/bin/env bash
name='plasma-disks'
release='4'
version='6.2.0'
url='https://kde.org/plasma-desktop'
description='Monitors S.M.A.R.T. capable devices for imminent failure'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-disks-${version}.tar.xz")
depends=(smartmontools kinfocenter)
makedepends=(extra-cmake-modules)
sha256sums=('581fba7b97397853442e9203e02cc5fe6007a1f6d6020bd3383751d7a70d2ba1')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

