#!/usr/bin/env bash
name='plasma-disks'
release='5'
version='6.4.5'
url='https://kde.org/plasma-desktop'
description='Monitors S.M.A.R.T. capable devices for imminent failure'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-disks-${version}.tar.xz")
depends=(smartmontools kinfocenter)
makedepends=(extra-cmake-modules)
sha256sums=('8017c749fbc850a13d11d5b35343f85194ad4276a01cc05311dd69828f51fef3')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

