#!/usr/bin/env bash
name='plasma-disks'
release='3'
version='6.1.5'
url='https://kde.org/plasma-desktop'
description='Monitors S.M.A.R.T. capable devices for imminent failure'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://download.kde.org/stable/plasma/${version}/plasma-disks-${version}.tar.xz")
depends=(smartmontools kinfocenter)
makedepends=(extra-cmake-modules)
sha256sums=('5d7669c019e8be668b985d73d7f0fdb315984a90ac7b0cf1e3989b80946e6c4a')
group=(kde.extra)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

