#!/usr/bin/env bash
name='libXcursor'
release='1'
version='1.2.1'
url='https://gitlab.freedesktop.org/xorg/lib/libXcursor'
description='X.Org Xcursor library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXcursor-$version.tar.xz")
depends=(libXrender libXfixes libX11)
makedepends=()
md5sums=('4cdd1886fe5cce6f68554296edb46db8')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

