#!/usr/bin/env bash
name='py3-hatchling'
release='3'
version='1.24.2'
url='https://github.com/pypa/hatch'
description=' 	Modern, extensible Python build backend'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('MIT')
source=("https://github.com/pypa/hatch/archive/refs/tags/hatchling-v${version}.tar.gz")
depends=(python)
makedepends=(py3-build py3-installer)
sha256sums=('b8e6974a780dc2c5b43676c352f20e19c61a33b7a4e1cb47b05c364ae22f0a8c')
group=(dev.python)
uses=()
arch=('x86_64')

cd "hatch-hatchling-v"$version

build(){
    python -m build --wheel backend
}

package(){
  python -m installer --destdir="$DESTDIR" backend/dist/*.whl
  install -Dm644 README.md "${DESTDIR}/usr/share/doc/${name}/README.md"
  install -Dm644 backend/LICENSE.txt "${DESTDIR}/usr/share/licenses/${name}/LICENSE.txt"

}


