#!/usr/bin/env bash
name='py3-hatchling'
release='2'
version='1.21.0'
url='https://github.com/pypa/hatch'
description=' 	Modern, extensible Python build backend'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/pypa/hatch/archive/refs/tags/hatchling-v${version}.tar.gz")
depends=(python)
makedepends=(py3-pathspec py3-editables py3-trove-classifiers py3-pluggy)
md5sums=('6f0aaa799c8490cc3ab7a67e65b75b97')
group=(dev.python)
uses=()
arch=('x86_64')

cd "hatch-hatchling-v"$version

build(){
    python -m build --wheel backend
}

package(){
  python -m installer --destdir="$DESTDIR" backend/dist/*.whl
  install -Dm644 README.md "${DESTDIR}/usr/share/doc/${name}/README.md"
  install -Dm644 backend/LICENSE.txt "${DESTDIR}/usr/share/licenses/${name}/LICENSE.txt"

}


