#!/usr/bin/env bash
name='qt6-sensors'
release='4'
version='6.9.1'
url='https://www.qt.io/'
description='The Qt Sensors API provides access to sensor hardware via QML and C++'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtsensors-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(qt6-declarative)
sha256sums=('f04b131acacfd42dfe056bd5861ff1e12e2ab57b3e20332becefa3644a409c6c')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtsensors-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}