#!/usr/bin/env bash
name='qt6-sensors'
release='3'
version='6.8.0'
url='https://www.qt.io/'
description='The Qt Sensors API provides access to sensor hardware via QML and C++'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('FDL' 'GPL3' 'LGPL3' 'custom')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtsensors-everywhere-src-${version}.tar.xz")
depends=(qt6-base)
makedepends=(qt6-declarative)
sha256sums=('723544c5fa05fab75d53d66186a7ce83fb2f6f9a770ce796306992e983dde679')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtsensors-everywhere-src-"${version}
export PATH=/usr/bin/qt6:$PATH

setup() {
	cmake -B build -G Ninja \
			-DCMAKE_BUILD_TYPE=RelWithDebInfo \
			-DCMAKE_INSTALL_PREFIX=/usr 

}

build () {
	cmake --build build
}

package () {
   DESTDIR="$DESTDIR" cmake --install build
}