#!/usr/bin/env bash
name='cairo'
release='1'
version='1.17.6'
url='https://gitlab.freedesktop.org/cairo/cairo.git/'
description='A vector graphics library with cross-device output support'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/cairo/cairo/-/archive/$version/cairo-$version.tar.gz")
depends=(pixman libpng glib libpcre2)
makedepends=()
md5sums=('bbea11bcc63e465e58aa054b56350b04')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

