#!/usr/bin/env bash
name='libXinerama'
release='1'
version='1.1.5'
url='https://gitlab.freedesktop.org/xorg/lib/libXinerama.git/'
description='X.Org Xinerama library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXinerama-$version.tar.xz")
depends=()
makedepends=()
md5sums=('228c877558c265d2f63c56a03f7d3f21')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

