#!/usr/bin/env bash
name='libxshmfence'
release='1'
version='1.3.2'
url='https://gitlab.freedesktop.org/xorg/lib/libxshmfence.git/'
description='Shared memory fences using futexes'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libxshmfence-$version.tar.xz")
depends=(xorgproto)
makedepends=()
md5sums=('faa74f7483074ce7d4349e6bdc237497')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

