#!/usr/bin/env bash
name='kcontacts'
release='2'
version='6.0.0'
url='https://community.kde.org/Frameworks'
description='Address book API for KDE'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcontacts-${version}.tar.xz")
depends=(qt6-base kcoreaddons kconfig ki18n kcodecs)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('179c6748e555c5c028b02a4b9b165ede13a09cf5eaf0ea012366c9727d230ec4')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

