#!/usr/bin/env bash
name='kcontacts'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Address book API for KDE'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcontacts-${version}.tar.xz")
depends=(kcoreaddons kconfig ki18n kcodecs)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('8c21f7cea752f575f05e629bab71fd1f')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

