#!/usr/bin/env bash
name='kcontacts'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Address book API for KDE'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kcontacts-${version}.tar.xz")
depends=(qt6-base kcoreaddons kconfig ki18n kcodecs)
makedepends=(extra-cmake-modules doxygen qt6-tools)
sha256sums=('292f8104f9f31d62c59289a3a821766d1ec540f4fc513ffc3b6f7197602d42c5')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

