#!/usr/bin/env bash
name='libXv'
release='1'
version='1.0.12'
url='https://gitlab.freedesktop.org/xorg/lib/libXv.git/'
description='X.Org Xv library'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXv-$version.tar.xz")
depends=()
makedepends=()
md5sums=('70bfdd14ca1a563c218794413f0c1f42')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

