#!/usr/bin/env bash
name='libaio'
release='1'
version='0.3.113'
url='https://pagure.io/libaio'
description='Asynchronous input/output library that uses the kernels native interface'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://pagure.io/libaio/archive/libaio-$version/libaio-libaio-$version.tar.gz")
depends=()
makedepends=()
md5sums=('4422d9f1655f358d74ff48af2a3b9f49')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$name-$version
setup(){
	#./autogen.sh
	#./configure --prefix=/usr \
        #--libdir=/usr/lib64/ \
        #--enable-compat-symlinks
        echo ""
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

