#!/usr/bin/env bash
name='gnome-common'
release='1'
version='3.18.0'
url='https://gitlab.gnome.org/GNOME/gnome-common.git/'
description='Common files for development of Gnome packages '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gnome-common/-/archive/3.18.0/gnome-common-3.18.0.tar.gz")
depends=()
makedepends=()
md5sums=('a6d83f1e9a04673ac9704c9919ea80af')
group=(gnome.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	./autogen.sh
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

