#!/usr/bin/env bash
name='libmtp'
release='1'
version='1.1.21'
url='http://libmtp.sourceforge.net/'
description='Library implementation of the Media Transfer Protocol'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.sourceforge.net/libmtp/libmtp-${version}.tar.gz" "https://download.sourceforge.net/libmtp/libmtp-${version}.tar.gz.asc")				 
depends=(libusb)
makedepends=()
md5sums=('532b445b22d01cc5c4b0683dd5ed894e' 'SKIP')
group=(media.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--with-udev=/usr/lib/udev
}

build(){
    make $jobs
}

package(){
    make DESTDIR="$DESTDIR" install $jobs
}

