#!/usr/bin/env bash
name='gtksourceview4'
dizin='gtksourceview'
release='1'
version='4.8.4'
_version='4.8'
url='https://wiki.gnome.org/Projects/GtkSourceView'
description='A text widget adding syntax highlighting and more to GNOME'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.gnome.org/sources/gtksourceview/${_version}/gtksourceview-${version}.tar.xz")
depends=(gtk3 libxml2)
makedepends=(gobject-introspection)
md5sums=('2bf056caaae27654ec3a5930dd5597d3')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $dizin-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/ \
        -Ddefault_library=both
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
}

