#!/usr/bin/env bash
name='kwallet'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Secure and unified container for user passwords'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kwallet-${version}.tar.xz")
depends=(kservice kconfigwidgets gpgme)
makedepends=(extra-cmake-modules doxygen qt5-tools)
md5sums=('caf9835950039b305064a2826bcdf0c2')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

#HATA : Could not find a package configuration file provided by "KF5Notifications"  (requested version 5.110.0) with any of the following names:
#   KF5NotificationsConfig.cmake kf5notifications-config.cmake

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

