#!/usr/bin/env bash
name='kwallet'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Secure and unified container for user passwords'
email='brkt8khn@gmailmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kwallet-${version}.tar.xz")
depends=(gpgme kcolorscheme kconfig kcoreaddons kdbusaddons ki18n knotifications kwidgetsaddons
         kwindowsystem libgcrypt qt6-base libsecret)
makedepends=(extra-cmake-modules doxygen kservice qt6-tools)
sha256sums=('c8630e1b280b9aee44f3367302fce381370a611557f1941908b9286e3891d163')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=OFF \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

