#!/usr/bin/env bash
name='wayland'
release='2'
version='1.22.0'
url='https://gitlab.freedesktop.org/wayland'
description='Core Wayland window system code and protocol'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wayland/wayland/-/archive/$version/wayland-$version.tar.gz")
depends=(zlib expat libffi xz-utils libxml2 mesa)
makedepends=()
md5sums=('0093c2b9cacd102e21cc25dfc9f88f36')
group=(dev.libs)
uses=()
uses_extra=(doc)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64 \
        -Ddefault_library=both \
        -Ddocumentation=$(use_opt doc true false)
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

