#!/usr/bin/env bash
name='wayland'
release='3'
version='1.23.0'
url='https://gitlab.freedesktop.org/wayland'
description='Core Wayland window system code and protocol'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wayland/wayland/-/archive/$version/wayland-$version.tar.gz")
depends=(zlib expat libffi xz-utils libxml2 mesa)
makedepends=()
sha256sums=('7c5c28fa73f22d1c5021e17e1148f29ab17bf8b776a406f1c4489d3e2992ec3a')
group=(dev.libs)
uses=()
uses_extra=(doc)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64 \
        -Ddefault_library=both \
        -Ddocumentation=$(use_opt doc true false)
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

