#!/usr/bin/env bash
name='wayland'
release='4'
version='1.23.1'
url='https://gitlab.freedesktop.org/wayland'
description='Core Wayland window system code and protocol'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/wayland/wayland/-/archive/$version/wayland-$version.tar.gz")
depends=(zlib expat libffi xz-utils libxml2 mesa)
makedepends=()
sha256sums=('158ec49af498f2558c7fbf7e8b070d010d4e270cc6076003a18a6c813f87e244')
group=(dev.libs)
uses=()
uses_extra=(doc)
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64 \
        -Ddefault_library=both \
        -Ddocumentation=$(use_opt doc true false)
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

