#!/usr/bin/env bash
name='libFS'
release='1'
version='1.0.9'
url='https://example.org'
description='Package libFS'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://www.x.org/archive/individual/lib/libFS-1.0.9.tar.xz')
depends=(xorgproto)
makedepends=()
md5sums=('742863a552ecd53cdb957b7b276213cc')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

