#!/usr/bin/env bash
name='xkeyboard-config'
release='4'
version='2.40'
url='https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config'
description='X keyboard configuration database'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/archive/xkeyboard-config-$version/xkeyboard-config-xkeyboard-config-$version.tar.gz")
depends=()
makedepends=()
md5sums=('1100dcdf310c64634cffbcf603f5a828')
group=(x11.misc)
uses=()
arch=('x86_64')
cd $name-$name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
}

