#!/usr/bin/env bash
name='purpose'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Framework for providing abstractions to get the developer s purposes fulfilled'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/purpose-${version}.tar.xz")
depends=(kconfig kcoreaddons kcmutils ki18n kio kirigami knotifications kservice qt6-base qt6-declarative)
makedepends=(intltool extra-cmake-modules)
sha256sums=('4f8bbf19022c70df1dc345a4abd81677a505a2e8fef643311287fe8e9212d56a')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_TESTING=ON
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

