#!/usr/bin/env bash
name='purpose'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Framework for providing abstractions to get the developer s purposes fulfilled'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/purpose-${version}.tar.xz")
depends=(kconfig kcoreaddons ki18n kio kirigami2 knotifications kservice qt5-base qt5-declarative)
makedepends=(intltool extra-cmake-modules)
md5sums=('a007abef9234eebe7d32910951190d13')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}