#!/usr/bin/env bash
name='hyprlang'
release='1'
version='0.5.3'
url='https://github.com/hyprwm/hyprlang'
description='The official implementation library for the hypr config language.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/hyprlang/archive/refs/tags/v$version.tar.gz")
depends=(hyprutils glib)
makedepends=()
sha256sums=('9715311d6b31c18f1e83da999269c71a61c0862645795d2666fa1d7b20d5d0f6')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

