#!/usr/bin/env bash
name='hyprlang'
release='2'
version='0.6.3'
url='https://github.com/hyprwm/hyprlang'
description='The official implementation library for the hypr config language.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/hyprlang/archive/refs/tags/v$version.tar.gz")
depends=(hyprutils glib)
makedepends=()
sha256sums=('f5effe017edc7a0036c20c7ecbea4edc2bfdacbc0f791b283bd21ec202384251')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

