#!/usr/bin/env bash
name='hyprcursor'
release='2'
version='0.1.12'
url='https://github.com/hyprwm/hyprcursor'
description='The hyprland cursor format, library and utilities.'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://github.com/hyprwm/hyprcursor/archive/refs/tags/v$version.zip")
depends=(librsvg libzip tomlplusplus hyprlang)
makedepends=()
sha256sums=('667f5bbfec649b85e844e85e9e8dccb92a97144b891b587eb956b48bda6625ad')
group=(hyprland.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr
}

build () {
    make -C build $jobs
}

package () {
    make -C build install $jobs
}

