#!/usr/bin/env bash
name='libXpm'
release='1'
version='3.5.14'
url='https://example.org'
description='Package dlibXpm'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=('https://www.x.org/archive/individual/lib/libXpm-3.5.14.tar.xz')
depends=(libX11)
makedepends=()
md5sums=('8001c7e6d2727609da2a78d8e08a2977')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

