#!/usr/bin/env bash
name='qt5-graphicaleffects'
release='1'
version='5.15.10'
url='https://www.qt.io/'
description='Graphical effects for use with Qt Quick 2'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://download.qt.io/archive/qt/${version%.*}/${version}/submodules/qtgraphicaleffects-everywhere-opensource-src-${version}.tar.xz")
depends=(qt5-base qt5-declarative)
makedepends=()
md5sums=('4419cc31af8b693dea99387a2ea826a5')
group=(dev.qt)
uses=()
arch=('x86_64')

cd "qtgraphicaleffects-everywhere-src-"${version}
export PATH=/usr/bin/qt5:$PATH


setup() {
	qmake 
}


build () {
    make
}

package () {
    make INSTALL_ROOT="$DESTDIR" install
}

