#!/usr/bin/env bash
name='bluez'
release='5'
version='5.79'
url='https://www.bluez.org'
description='Daemons for the bluetooth protocol stack'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://www.kernel.org/pub/linux/bluetooth/bluez-${version}.tar.xz"
        "bluetooth.initd")
depends=(glib)
makedepends=(dbus libical json-c alsa-lib ell)
sha256sums=('4164a5303a9f71c70f48c03ff60be34231b568d93a9ad5e79928d34e6aa0ea8a'
         'SKIP')
group=(net.wireless)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sysconfdir=/etc     \
        --localstatedir=/var  \
        --enable-library      \
        --disable-manpages    \
        --disable-systemd \
		    --enable-deprecated \
        --enable-hid2hci \
        --enable-mesh \
        --enable-sixaxis
}

build(){
    make $jobs
}

package (){
    make install $jobs
    install -v -dm755 $DESTDIR/usr/sbin
    install -v -dm755 $DESTDIR/etc/init.d
    ln -svf ../libexec/bluetooth/bluetoothd $DESTDIR/usr/sbin/bluetoothd
    install -v -dm755 $DESTDIR/etc/bluetooth
    install -v -m644 src/main.conf $DESTDIR/etc/bluetooth/main.conf
    install -v -dm755 $DESTDIR/usr/share/doc/
    install -v -dm755 $DESTDIR/usr/share/doc/bluez-5.66
    install -v -m644 doc/*.txt $DESTDIR/usr/share/doc/bluez-5.66
    install ../bluetooth.initd $DESTDIR/etc/init.d/bluetooth
}
