#!/usr/bin/env bash
name='bluez'
#pkgname=('bluez' 'bluez-utils' 'bluez-libs' 'bluez-cups' 'bluez-hid2hci' 'bluez-plugins')
release='2'
version='5.68'
url='https://www.bluez.org'
description='Daemons for the bluetooth protocol stack'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://www.kernel.org/pub/linux/bluetooth/bluez-${version}.tar.xz"
        "bluez-obexd_without_systemd-1.patch"
        "bluetooth.initd")
depends=(glib)
makedepends=(dbus libical json-c alsa-lib ell)
md5sums=('00a72fed12e706b2d8bb40786154d3aa'
         'SKIP'
         'SKIP')
group=(net.wireless)
uses=()
arch=('x86_64')

cd $name-$version

prepare(){
    patch -Np1 -i ../bluez-obexd_without_systemd-1.patch
}

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
        --sysconfdir=/etc     \
        --localstatedir=/var  \
        --enable-library      \
        --disable-manpages    \
        --disable-systemd
}

build(){
    make $jobs
}

package (){
    make install $jobs
    install -v -dm755 $DESTDIR/usr/sbin
    install -v -dm755 $DESTDIR/etc/init.d
    ln -svf ../libexec/bluetooth/bluetoothd $DESTDIR/usr/sbin/bluetoothd
    install -v -dm755 $DESTDIR/etc/bluetooth
    install -v -m644 src/main.conf $DESTDIR/etc/bluetooth/main.conf
    install -v -dm755 $DESTDIR/usr/share/doc/
    install -v -dm755 $DESTDIR/usr/share/doc/bluez-5.66
    install -v -m644 doc/*.txt $DESTDIR/usr/share/doc/bluez-5.66
    install ../bluetooth.initd $DESTDIR/etc/init.d/bluetooth
}
