#!/usr/bin/env bash
name='gi-docgen'
release='3'
version='2024.1'
url='https://gitlab.gnome.org/GNOME/gi-docgen'
description=' A documentation generator for GObject-based libraries '
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/gi-docgen/-/archive/$version/gi-docgen-$version.tar.gz")
depends=(py3-pygments py3-markdown py3-jinja py3-typogrify)
makedepends=()
sha256sums=('c2f49f0bdea0366d04b6ab6f34071f324ef70016bc3650371cc08d3c6f2764da')
group=(dev.util)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    ninja -C build
}

package(){
    ninja -C build install
    # move to generic site-packages
    mv $DESTDIR/usr/lib/python3.*/site-packages $DESTDIR/usr/lib/python3/
    rmdir $DESTDIR/usr/lib/python3.*
}

