#!/usr/bin/env bash
name='cups-filters'
release='2'
version='2.0.0'
url='https://wiki.linuxfoundation.org/openprinting/cups-filters'
description='OpenPrinting CUPS filters and backends'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv3')
source=("https://github.com/OpenPrinting/cups-filters/archive/refs/tags/${version}.tar.gz")
#source=("https://www.openprinting.org/download/cups-filters/cups-filters-${version}.tar.xz")
depends=(cups poppler ghostscript libppd)
makedepends=()
md5sums=('64ec28ce5e05623048c55b9007b0455b')
group=(net.print)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
	CXXFLAGS="$CXXFLAGS -flto=auto -std=c++17" \
	autoreconf -fvi
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--disable-avahi \
		--disable-mutool \
		--sysconfdir=/etc \
		--mandir=/usr/share/man \
		--infodir=/usr/share/info \
		--localstatedir=/var \
		--with-shell=/bin/sh \
		--without-rcdir \
		--without-rclevels \
		--with-test-font-path=/usr/share/fonts/dejavu/DejaVuSans.ttf
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

