#!/usr/bin/env bash
name='libXfixes'
release='1'
version='6.0.0'
url='https://example.org'
description='Package libXfixes'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXfixes-$version.tar.gz")
depends=()
makedepends=()
md5sums=('efe99ef5c971d0ad12cdc9e0c78e5f38')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

