#!/usr/bin/env bash
name='xfce4-settings'
release='4'
version='4.20.2'
_version='4.20'
url='https://docs.xfce.org/xfce/xfce4-settings/start'
description="Xfce's Configuration System"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfce4-settings/${_version}/xfce4-settings-${version}.tar.bz2")
depends=(exo garcon hicolor-icon-theme libnotify gnome-themes-standard libxklavier)
makedepends=(intltool)
sha256sums=('6e11776e640798a1ac4168d53877f105bb3e8cf93b443c160841e3acdab63939')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--localstatedir=/var \
		--enable-xrandr \
		--enable-xcursor \
		--enable-libnotify \
		--enable-libxklavier \
		--enable-pluggable-dialogs \
		--enable-sound-settings
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}
