#!/usr/bin/env bash
name='xfce4-settings'
release='2'
version='4.18.6'
_version='4.18'
url='https://docs.xfce.org/xfce/xfce4-settings/start'
description="Xfce's Configuration System"
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPLv2')
source=("https://archive.xfce.org/src/xfce/xfce4-settings/${_version}/xfce4-settings-${version}.tar.bz2")
depends=(exo garcon hicolor-icon-theme libnotify gnome-themes-standard libxklavier)
makedepends=(intltool)
sha256sums=('d9a9051b6026edd6766c64bb403b51e9167e4d31e7f1c7f843d3aed19f667bfe')
group=(xfce.base)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/ \
		--sysconfdir=/etc \
		--sbindir=/usr/bin \
		--localstatedir=/var \
		--enable-xrandr \
		--enable-xcursor \
		--enable-libnotify \
		--enable-libxklavier \
		--enable-pluggable-dialogs \
		--enable-sound-settings \
		--disable-debug
}

build(){
    make $jobs
}

package(){
    make install DESTDIR=$DESTDIR $jobs
}
