#!/usr/bin/env bash
name='nghttp2'
release='1'
version='1.51.0'
url='https://github.com/nghttp2/nghttp2'
description='Package description missing'
email=' aliriza.keskin@pardus.org.tr'
maintainer=' aliriza'
license=('MIT')
source=("https://github.com/nghttp2/nghttp2/releases/download/v1.51.0/nghttp2-${version}.tar.gz")
depends=( )
makedepends=( )
md5sums=('d8c534bbdd84297afa4f6576896a3d76')
arch=('x86_64')
group=(system.extra)

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64 \
        --without-libxml2 \
		--without-neverbleed \
		--without-jemalloc \
		--disable-python-bindings \
		--disable-examples \
		--enable-static \
		--enable-app
}

build(){
    make -j`nproc`
}

package(){
    make install -j`nproc`
}

