#!/usr/bin/env bash
name='py3-trove-classifiers'
release='4'
version='2024.1.31'
url='https://github.com/pypa/trove-classifiers'
description='Canonical source for classifiers on PyPI'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('Apache-2.0')
source=("https://github.com/pypa/trove-classifiers/archive/refs/tags/${version}.tar.gz")
depends=()
makedepends=()
md5sums=('8129d786e5a7e587995ef0b9fe9774e9')
group=(dev.python)
uses=()
arch=('x86_64')

cd "trove-classifiers"-$version

build(){
    python3 setup.py build
}

package(){
    python3 setup.py install --root="${DESTDIR}" --install-lib=/usr/lib64/python3 --optimize=1 --skip-build
}


