#!/usr/bin/env bash
name='py3-trove-classifiers'
release='5'
version='2024.10.21.16'
url='https://github.com/pypa/trove-classifiers'
description='Canonical source for classifiers on PyPI'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('Apache-2.0')
source=("https://github.com/pypa/trove-classifiers/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=()
sha256sums=('4c86dbaacda8ca2bee6891dcf24bc1bab2b58a1d5bc36db6d6910bc3488eacf2')
group=(dev.python)
uses=()
arch=('x86_64')

cd "trove-classifiers"-$version

build(){
    python3 -m build
}

package(){
    python3 -m installer --destdir "${DESTDIR}" dist/*.whl
}


