#!/usr/bin/env bash
name='py3-trove-classifiers'
release='6'
version='2025.5.9.12'
url='https://github.com/pypa/trove-classifiers'
description='Canonical source for classifiers on PyPI'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('Apache-2.0')
source=("https://github.com/pypa/trove-classifiers/archive/refs/tags/${version}.tar.gz")
depends=(python)
makedepends=()
sha256sums=('e2073313aeed13ca9c305ad6cacc2bed0c42a1170ef843f67e1e27c3d98c39c1')
group=(dev.python)
uses=()
arch=('x86_64')

cd "trove-classifiers"-$version

build(){
    python3 -m build
}

package(){
    python3 -m installer --destdir "${DESTDIR}" dist/*.whl
    mv ${DESTDIR}/usr/lib/python3.*/site-packages ${DESTDIR}/usr/lib/python3
}


