#!/usr/bin/env bash
name='kservice'
release='4'
version='6.7.0'
url='Advanced plugin and service introspection'
description='Support for unit conversion'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kservice-${version}.tar.xz")
depends=(ki18n kconfig kcoreaddons qt6-base)
makedepends=(extra-cmake-modules doxygen kdoctools qt6-tools)
sha256sums=('39d2542e38fb3434c5405c92d5b45e0d5ba650d265309adf93c787a741d57fa1')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

