#!/usr/bin/env bash
name='kservice'
release='3'
version='6.5.0'
url='Advanced plugin and service introspection'
description='Support for unit conversion'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kservice-${version}.tar.xz")
depends=(ki18n kconfig kcoreaddons qt6-base)
makedepends=(extra-cmake-modules doxygen kdoctools qt6-tools)
sha256sums=('48cdd204bc9fb9282c37b6bcc2364f7dbc124057547ddb6b1471988b464cf8bd')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_QCH=ON 
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}


