#!/usr/bin/env bash
name='gettext'
release='2'
version='0.22'
url='https://gnu.org/software/gettext'
description='GNU locale utilities'
email='kurth4cker@tutanota.com'
maintainer='kurth4cker'
license=('GPLv3')
source=("https://ftp.gnu.org/gnu/gettext/gettext-${version}.tar.xz")
depends=(libunistring)
makedepends=( )
md5sums=('db2f3daf34fd5b85ab1a56f9033e42d1')
group=(sys.devel)
uses=(bzip2 lzma)
bzip2_depends=(bzip2)
lzma_depends=(xz-utils)
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/lib64 \
        --enable-shared \
        --enable-static \
        --disable-java \
        --without-emacs \
        --without-cvs \
        --without-included-regex \
        --without-included-libxml \
        --without-git \
        $(use_opt bzip2 --with-bzip2 --without-bzip2) \
        $(use_opt lzma --with-xz --without-xz)
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

