#!/usr/bin/env bash
name='libXrandr'
release='1'
version='1.5.3'
url='https://example.org'
description='Package libXrandr'
email='bayramk@gmail.com'
maintainer='bk'
license=('GPLv3')
source=("https://www.x.org/archive/individual/lib/libXrandr-$version.tar.xz")
depends=(libXrender)
makedepends=()
md5sums=('850cbc7c921c9d5d0135734b114ff6ac')
group=(x11.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    ./configure --prefix=/usr \
        --libdir=/usr/lib64/
}

build(){
    make $jobs
}

package(){
    make install $jobs
}

