#!/usr/bin/env bash
name='kcalc'
release='3'
version='24.08.1'
url='https://kde.org/applications/utilities/org.kde.kcalc'
description='Scientific Calculator'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('GPL' 'LGPL' 'FDL')
source=(https://download.kde.org/stable/release-service/${version}/src/${name}-${version}.tar.xz)
depends=(mpfr kxmlgui knotifications)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=("86ebb9b36b5f4d620904884206985cecc0ffd253666f27313ec7bae99b10a96e")
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
	cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64 \
		-DBUILD_TESTING=OFF
}

build () {
	cmake --build build
}

package () {

    DESTDIR="$DESTDIR" cmake --install build
	  rm -f $DESTDIR/usr/share/kglobalaccel/org.kde.kcalc.desktop
	  ln -s ../applications/org.kde.kcalc.desktop $DESTDIR/usr/share/kglobalaccel/org.kde.kcalc.desktop
}
