#!/usr/bin/env bash
name='caribou'
release='1'
version='0.4.21'
url='https://wiki.gnome.org/Projects/Caribou'
description='A text entry and UI navigation application (on-screen keyboard)'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.gnome.org/sources/caribou/${version%.*}/caribou-${version}.tar.xz")
depends=(at-spi2-core py3-pygobject gtk3 libxklavier libgee dconf)
makedepends=(intltool docbook-xsl gobject-introspection vala git gnome-common)
md5sums=('16b76cd7453b99e2871e8d4da88bf976')
group=(app.accessibility)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    ./configure --prefix=/usr \
		--libdir=/usr/lib64/ \
		--build=$CBUILD \
		--host=$CHOST \
		--sysconfdir=/etc \
		--localstatedir=/var \
		--disable-gtk2-module
}

build () {
    make $jobs
}

package () {
    make DESTDIR="$DESTDIR" install $jobs
}

