#!/usr/bin/env bash
name='dolphin'
release='4'
version='24.08.2'
url='https://apps.kde.org/dolphin/'
description='KDE File Manager'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/release-service/${version}/src/dolphin-${version}.tar.xz")
depends=(baloo-widgets knewstuff kcmutils kparts phonon)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=("551516270762b71a53502e42cae22106642e1253e22720632a805250434145b1")
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
	rm -r "$DESTDIR"/usr/lib/systemd

	rm -f $DESTDIR/usr/share/kglobalaccel/org.kde.dolphin.desktop
	ln -s ../applications/org.kde.dolphin.desktop $DESTDIR/usr/share/kglobalaccel/org.kde.dolphin.desktop

}

