#!/usr/bin/env bash
name='dolphin'
release='3'
version='24.08.1'
url='https://apps.kde.org/dolphin/'
description='KDE File Manager'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/release-service/${version}/src/dolphin-${version}.tar.xz")
depends=(baloo-widgets knewstuff kcmutils kparts phonon)
makedepends=(extra-cmake-modules kdoctools)
sha256sums=("1dba9afb6617080c1b4937a88ec012fba77184327acc8573d9e351feed537668")
group=(kde.apps)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib64
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
	rm -r "$DESTDIR"/usr/lib/systemd

	rm -f $DESTDIR/usr/share/kglobalaccel/org.kde.dolphin.desktop
	ln -s ../applications/org.kde.dolphin.desktop $DESTDIR/usr/share/kglobalaccel/org.kde.dolphin.desktop

}

