#!/usr/bin/env bash
name='libwacom'
release='3'
version='2.9.0'
url='https://github.com/linuxwacom/libwacom/wiki'
description='Library to help implement Wacom tablet settings'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('MIT')
source=("https://github.com/linuxwacom/libwacom/releases/download/libwacom-${version}/libwacom-${version}.tar.xz")
depends=(eudev)
makedepends=(meson)
md5sums=('2f4de3d56ae20702cbd4174e10a99aa8')
group=(dev.libs)
uses=()
arch=('x86_64')

cd $name-$version

setup(){
    meson setup build  \
      --prefix=/usr   \
      --buildtype=release \
      -Dtests=disabled
}

build(){
    ninja -C build $jobs
}

package(){
    ninja -C build install $jobs
	install -D -m644 COPYING "${DESTDIR}/usr/share/licenses/${name}/LICENSE"
}
