#!/usr/bin/env bash
name='nm-applet'
release='1'
version='1.32.0'
url='https://gitlab.gnome.org/GNOME/network-manager-applet'
description='Network manager applet'
email='aliriza.keskin@pardus.org.tr'
maintainer='aliriza'
license=('GPLv3')
source=("https://gitlab.gnome.org/GNOME/network-manager-applet/-/archive/$version/network-manager-applet-$version.tar.gz")
depends=(libsecret gtk3 networkmanager)
makedepends=()
md5sums=('cf18a8da802218479a958c50e2a33b9c')
group=(gnome.extra)
uses=()
arch=('x86_64')

cd network-manager-applet-$version

setup(){
    meson setup build --prefix=/usr \
        -Dselinux=false \
        --libdir=/usr/lib64/
}

build(){
    make -C build $jobs
}

package(){
    make -C build install $jobs
}

