#!/usr/bin/env bash
name='kwidgetsaddons'
release='4'
version='6.7.0'
url='https://community.kde.org/Frameworks'
description='Addons to QtWidgets'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kwidgetsaddons-${version}.tar.xz")
depends=(qt6-base)
makedepends=(clang doxygen extra-cmake-modules qt6-tools)
sha256sums=('bd36342893863e6110c5f1245f8ae0b3a338275f4eaf124b15585d2fe492329a')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

