#!/usr/bin/env bash
name='kwidgetsaddons'
release='5'
version='6.18.0'
url='https://community.kde.org/Frameworks'
description='Addons to QtWidgets'
email='brkt8khn@gmail.com'
maintainer='brkt8khn'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kwidgetsaddons-${version}.tar.xz")
depends=(qt6-base)
makedepends=(clang doxygen extra-cmake-modules qt6-tools)
sha256sums=('0c2fb00744ffd9ecb7531ee5a79c1db4b406753f250565122f3add93cf200afb')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
    cmake -B build -G Ninja \
      -DBUILD_PYTHON_BINDINGS=OFF
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

