#!/usr/bin/env bash
name='kwidgetsaddons'
release='1'
version='5.110.0'
url='https://community.kde.org/Frameworks'
description='Addons to QtWidgets'
email='akarsu@protonmail.com'
maintainer='akarsu'
license=('LGPL')
source=("https://download.kde.org/stable/frameworks/${version%.*}/kwidgetsaddons-${version}.tar.xz")
depends=(qt5-base)
makedepends=(clang doxygen extra-cmake-modules qt5-tools)
md5sums=('7a341a44caf89aa586a902ae67677910')
group=(kde.frameworks)
uses=()
arch=('x86_64')

cd $name-$version

setup () {
cmake -B build -G Ninja \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib
}

build () {
	cmake --build build
}

package () {
    INSTALL_ROOT="$DESTDIR" cmake --install build
}

